### ISSUE TITLE
Dark theme reverts to light theme everytime Wire is closed and reopened

### ISSUE THREAD

**Issue by angelospanag** [wireapp/wire-android#1026]
## The problem

Dark theme reverts to light theme everytime Wire is closed and reopened

## Environment

* Wire version that exhibits the issue: 2.37.349
* Last Wire version that did not exhibit the issue (if applicable): 2.36.343
* Android OS version used to run Wire: 6.0.1
* Is this a custom firmware or a stock one: stock
* Mobile phone model/manufacturer: Nexus 5 (Hammerhead 2013)

## Details

1. Given that Wire is currently NOT using a dark theme
2. Profile -> Settings -> Options -> By popular demand -> Dark theme (should be disabled)
3. Enable Dark theme
4. Go to a discussion and notice that the theme is applied
5. Close the app, remove it from running in the background
6. Open app, go to a discussion, the theme is reverted to light
7. Go to the menu described on step 2. The slider shows that the dark theme is still enabled when it's not

## Link to Debug logs
https://gist.github.com/angelospanag/8b646704072a8b7a49ab53d057a8a159

**Comment by red-avtovo** [comment]
Hey, @angelospanag! Thank you for your report. Could you also try to reproduce that on latest 2.37.349 build?

**Comment by angelospanag** [comment]
The above issue is happening using the latest build (2.37.349)

![screenshot_20170719-225755](https://user-images.githubusercontent.com/1130363/28391469-1857415a-6cd6-11e7-9052-6acf6d90db67.png)

**Comment by red-avtovo** [comment]
Thank you. Wi will investigate that issue

**Comment by rebasar** [comment]
I am experiencing the same issue on Wire 2.37.349, Motorola XT1580 (Moto X Force) on Android 6.0.1

The behavior also seems to be a bit more inconsistent, as the colors can change just by exiting the app and getting back, without manually removing it from the background.

**Comment by phoenixeliot** [comment]
Additional details:
Toggling the Dark Theme option off and on again does not restore the dark theme. Instead, I must turn off the dark theme, press the android home button, reopen Wire, and turn the dark theme back on. Only then does it use the dark theme.

Version 2.37.349
Android 7.1.2
Google Pixel

**Comment by red-avtovo** [comment]
No worries. The fix is coming

**Comment by revpp** [comment]
It's happening to me as well. It became an issue with new update 2.37.349.

**Comment by AyelGoth** [comment]
I confirm the error, the same thing happens to me.

**Comment by mhham** [comment]
Same thing goes for me

**Comment by red-avtovo** [comment]
Guys, it will happen with everyone, who uses dark theme. Thanks to all of you, but there is no need re confirm that issue. I can say only, that you will have a surprise quit soon

**Comment by Strit** [comment]
Color me intriuged @red-avtovo 
Any hints? Whole new UI?

**Comment by qazip** [comment]
I would laugh if the "surprise quite soon" which he referes is having the bugs they introduced this last version fixed.

**Comment by wmengli** [comment]
Thanks for your input 😉! A fix for it is out with the release today.

**Comment by Strit** [comment]
Haven't experienced this bug, since the latest update!
