### ISSUE TITLE
Unable to turn off notification vibration

### ISSUE THREAD

**Issue by bytegeist** [wireapp/wire-android#1037]
Wire Version: 2.37.349
OS: Android 7.0

What steps will reproduce the problem?
- Turn off vibration for alerts in options.
- Exit Wire.
- Receive message + notification

What is the expected result?
- Just the notification sound.

What happens instead?
- Notification sound + vibration

**Comment by alien2003** [comment]
The same on Android 6.0

**Comment by JexPY** [comment]
Same problem Android 7.0
latest wire version that's on play store now

**Comment by someoneEsle** [comment]
Hi guys, we have been looking into this issue recently and we're planning on releasing a fix soon!

**Comment by someoneEsle** [comment]
Hey guys, we just pushed a new version (2.40.357) to the Play store that fixes this issue. Let us know if you still experience it on the new update!
