### ISSUE TITLE
[Feature Request] Message bubbles

### ISSUE THREAD

**Issue by bytegeist** [wireapp/wire-android#1038]
[Message bubbles](https://previews.123rf.com/images/artinspiring/artinspiring1608/artinspiring160800492/63285569-Smartphone-text-messaging-Template-blank-text-bubbles-Social-network-conversation--Stock-Vector.jpg) are an important interface element that I am sure many users are missing from this messenger.

It might not seem important to the devs as the functionality gain to implementation effort ratio is low, but this might be one of bigger perceived downsides that causes users to opt for a competitor, e.g. Signal - even though it is less feature rich.

**Comment by someoneEsle** [comment]
This has been requested several other times. See #192 for an official reply
