### ISSUE TITLE
Contacts shared with multi account

### ISSUE THREAD

**Issue by benediktrauch** [wireapp/wire-android#1040]
I just added a second account and it looks like that contacts witch phone number in my address book are shared between my both accounts. 
It's a bug if that's just the case that they appear locally, but critical it it's a shared account (eg. from an organisation) and everyone can see them.

**Comment by red-avtovo** [comment]
Hey, @benediktrauch! Is your second account - team account?
Did you add your phone number to your second account?

**Comment by benediktrauch** [comment]
Second account is a normal account. I created it with a mail address.

**Comment by red-avtovo** [comment]
But did you give permissions to contacts after login to second account?

**Comment by benediktrauch** [comment]
I think it was enabled on first account, but did not ask for second (enabled by default?)

**Comment by makingthematrix** [comment]
As we no longer import contacts from the address book, I think I can safely close this issue.
