### ISSUE TITLE
Switching between accounts opens last conversation

### ISSUE THREAD

**Issue by benediktrauch** [wireapp/wire-android#1041]
When switching between accounts the first conversation opens. Don't think that's a feature, because if that happens I'm not sure if I switched accounts or just opened a conversation from the current account.
Would prefer to see the full list.
EDIT:
Opening the app
Switching accounts
Shows list of conversations.

After I opened a conversation and then switching accounts described behaviour appers.

Quickly changing accounts (before it can open a conversation) fixes that behaviour temporarily.

**Comment by red-avtovo** [comment]
Hey @benediktrauch! Thank you for your report!
Fortunately, this issue is known and we are working on fix.

**Comment by someoneEsle** [comment]
Hi, this should be fixed in the latest version :)
