### ISSUE TITLE
No "Send" button when in landscape

### ISSUE THREAD

**Issue by qazip** [wireapp/wire-android#1046]
## The problem

Up until the latest version, I was able to send messages in wire while I was using/writing in landscape mode (I use an app to activate landscape mode). With the latest version, there's no send button when I'm in landscape. In order to send a message now, I write in landscape and then have to switch to portrait in order to send.

It's so infuriating that I stopped using Wire on android all-together. 

## Environment

* Wire version that exhibits the issue:
2.37.349
* Last Wire version that did not exhibit the issue (if applicable):
Previous one.
* Android OS version used to run Wire:
Android 5.
* Is this a custom firmware or a stock one:
Stock.

**Comment by someoneEsle** [comment]
Hi, at this point we have limited resources and cannot support landscape mode officially. Please understand that we are just a small team and that at this moment there are other more pressing priorities. The app you use to activate landscape mode may also play a role in this.
I am not sure if this will work, but maybe you can try playing with the "send button" setting in Settings>Options.
I have to close this issue for now, but you can upvote #455 to show your interest in the feature.

**Comment by qazip** [comment]
That brought it back to the way it was before. That option must have reset to the default value when I upgraded to the latest version.
