### ISSUE TITLE
Problems in notification with multiple accounts

### ISSUE THREAD

**Issue by daviortega** [wireapp/wire-android#1047]
## The problem
I have wire-android running on my phone and I have two accounts. Notifications only come if they are from the "in focus" account and not the other.

## Environment

* Wire version that exhibits the issue:  2.38.352
* Last Wire version that did not exhibit the issue (if applicable): NA
* Android OS version used to run Wire: 7.0
* Is this a custom firmware or a stock one: No
* Mobile phone model/manufacturer: Motorola Z play
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/Wi-fi

## Details

two accounts, notifications only showing for the one which I am currently using it.

## Link to Debug logs
NA
## How to send detailed debug report from Wire:
NA
## Screenshots
NA

**Comment by red-avtovo** [comment]
Hey @daviortega, thank you for your report! 
It is a current known limitation. We are working on solution

**Comment by Gardosen** [comment]
this issue has been solved some time ago. this ticket will be closed now as solved

Kind regards
Marco from the Android Team
