### ISSUE TITLE
Running wire in background? Also no notifications?

### ISSUE THREAD

**Issue by ganego** [wireapp/wire-android#1050]
Using wire on a Xiaomi Redmi Note 4 (Based on Android 6.0.1), with Google Apps installed - device was in WiFi for testing.
I'm new to smartphones so this might be a stupid question but I cannot find anything via Google.
Is it not possible to run Wire as a background task/service? When I click on the button on my phone that lets me see all running apps and I close Wire from there, the whole app is gone and I will not receive any more messages. But I know other apps can run fine in the background without showing up on that screen all the time. Is that not possible with wire, or do I do something wrong?

In addition to that - despite having all sounds and even vibration enabled in wire - I get no notification of new messages or pings, neither when the app is open an in view, nor in the notification bar.

**Comment by jakejoh** [comment]
Are you using MIUI? It has pretty heavy restrictions for apps running in background. Did you try to disable battery optimisations for Wire as well as removing all restrictions in permissions manager?

**Comment by ganego** [comment]
Yes I'm using MIUI. I found the problem and it was totally on my side. I had netguard (firewall) blocking the google play services. Sorry to have bothered you.

**Comment by someoneEsle** [comment]
Sorry for the late reply, I just saw this issue. Good that you were able to solve it 👍
