### ISSUE TITLE
Download Pictures option is turned around

### ISSUE THREAD

**Issue by pkolmann** [wireapp/wire-android#1051]
Wire Android: some options are wrongly connected:

On Android if I go into the options and set 'Download Pictures' to 'always' the pictures are only downloaded when connected to wifi. If I set this option to 'WIFI-only', pictures are also downloaded via mobile data.

Other options also may be affected.

If needed I can add more info.

Version: 2.38.352
Android: 7.1.1 (Stock Sony Xperia Z5 Compact)

**Comment by someoneEsle** [comment]
Hi, thank you for your report. It's a known bug and we are looking into it, it should be fixed soon!

**Comment by someoneEsle** [comment]
This has been fixed :)
