### ISSUE TITLE
Question: Is it possible to write a desktop client based on the Android backend libraries?

### ISSUE THREAD

**Issue by MrCustomizer** [wireapp/wire-android#1064]
This is not exactly an issue with the Android client rather than a question concerning a possible Java-based alternative desktop client based on the Android libraries. If this is the wrong place for this kind of question, please feel free to close my issue. Preferably with a hint as to where my question would be better placed ;).

I'm thinking about writing an alternative cross-platform desktop client for Wire. I really am not planning to reinvent the wheel, I'm mostly aiming for an alternative user experience without any Electron and/or JavaScript Code, as I'm personally not a fan of script languages in desktop applications.

So my idea was to reuse the libraries of the Android client, which handle the communication with the Wire server and put a new Java desktop GUI in front of it. That way, I would be able to spent most of my time programming the GUI, while leaving the development of the messaging protocol implementation to the Wire team. At least theoretically.

My question is, if this would be possible without too much of a hassle. If I recall correctly, the basic libraries are written in Rust and Scala. I'm a pretty experienced Java developer, but haven't done anything in Scala yet. I would be willing to learn Scala, though, if the API of the underlying communications layer is better accessed by an application written in Scala than in Java.

As I don't have any experience with Gradle and Maven, my first experiments of trying to integrate the zmessaging-android library in a new IntelliJ project failed miserably. I just don't know yet, what I'm doing. I don't even know, if the zmessaging-android library is the correct starting point.
If you think this project could work, I would be glad about some advice where and how to get started.

Please don't misunderstand this post as an announcement for a new desktop client. As of now it's just an idea and I don't know if it will come to life, yet. It's even pretty much possible, that I start this project and it will never reach a usable state.

**Comment by someoneEsle** [comment]
A while ago one of our developers actually started a project that kind of goes in this direction. Here (https://github.com/wireapp/scala-utils) you can find an implementation of the sync engine (basically the app without the UI) that contains almost all the features. If you want you can add a UI on top of it.
However, keep in mind that you are on your own if you decide to start developing this. If you have questions we are always happy to answer, but we cannot actively help you with the development --  otherwise we would be developing it ourselves, and at the moment we have other priorities :)

**Comment by MrCustomizer** [comment]
Hey, that's interesting news. I will take a look at this project, thanks a lot for the information.
And yes, it was fully my intention to develop this project on my own. I'm aware that you have other priorities. Btw. I'm really looking forward to the completion of the open sourcing of the server and the federation feature, you are thinking about.
If I'm pulling this off, I will be open to help from the community, though. If someone is interested: I will be posting a link to the project in this issue as soon as I have laid out some of the groundwork and implemented the most important parts of the GUI.

**Comment by MrCustomizer** [comment]
I'm closing this issue as the scala-utils project seems to be a good starting point for my project. If new questions come up, I will probably open issues on the github page of that project. Thanks a lot for the fast answer.

**Comment by MrCustomizer** [comment]
I've discontinued this project as I've lost my trust in Wire's source. For a more complete explanation, see the last post in this issue:
https://github.com/wireapp/scala-utils/issues/1
