### ISSUE TITLE
(General:) New Features prioritized over Reliable Behavior

### ISSUE THREAD

**Issue by Awerick** [wireapp/wire-android#1065]
### My "General Issue"
I'm a passionate Wire user however I have a (rather "general") issue:

Since I am using Wire (~1 year), several lovely new features have been introduced (like _Timed Messages_, _Bot API_, _Linux Client_, _Search Menu_, most recently: _Teams_).
But its behavior has remained highly unreliable for me/my contacts since then. Some issues even made Wire _literally_ unusable!
 >  _(e.g.  "not opening": #769; "_ silently _not receiving media": #213 / [#744-desktop](https://github.com/wireapp/wire-desktop/issues/744)/detailed mail-exchange with support I had ~5 months ago; "messages not being sent": #1014; and more … )_

=> It seems like new features are higher prioritized than the reliable performance of the existing system.

### (Helpful?) Feedback
This issue report is not supposed to be a rant but (hopefully) helpful feedback:

Wire has a long list of impressing features – it _is already_ beloved and attractive for new users. (I am also excited for future improvements :heart:)
But in any case: An unreliable / unusable performance is _more_ important than new features, as it drives even existing users away (see comments for "high power usage" bug #853)! (I want to keep Wire despite problems, but my friends and family don't have this attitude and demand to switch the messenger…)

Best of luck for the future!
Awerick

(**Addendum:** While writing this, my Desktop-Wire would not let me log in and Android-Wire did not notify me about a message… This is still not supposed to be a rant :wink: but it nicely illustrates the problem.)

**Comment by teller** [comment]
Hi, first of all, thanks for all the support and getting your friends-family on Wire. I'm very sorry for the troubles and sincere apologies from the whole team.

We're very aware how important basic performance and stability is to a product such as Wire - something people use and rely on on a daily basis. We've definitely had some issues which we've mapped out for all platform teams and that they are tackling one-by-one.

We're a small team and finding the right balance between building new features and focus on maintenance is always a hard one. User feedback like yours helps to keep us always checking our sights, so thanks again!

**Comment by IronJunkie** [comment]
Start a beta channel for guys like me & OP who don't mind bugs etc before you lose too many normal users and get a bad rep! My sister doesn't want to use it anymore as buggy.

**Comment by Awerick** [comment]
Thanks for your answer, I appreciate it!

I don't intent to keep this general issue/feedback open over months, so I would close it in the next ~10 days or so – if there is nothing more to discuss…

For reference: Issue #1087 dicusses plans about a Beta program.
(Maybe it was already planned but anyways: Thanks @IronJunkie for bringing this up.)
