### ISSUE TITLE
Disappearing Messages retaining word length information is a security leak

### ISSUE THREAD

**Issue by phoenixeliot** [wireapp/wire-android#1077]
## The problem

Disappearing messages used to completely disappear after the timer expired.
Now the disappearing messages leave behind blue squiggles after the message expires — with the squiggles matching the length of the words in the original message, with spaces in between.

By retaining information about the number of messages sent, their length, and the length of each word, a lot of information is retained.

When I write a disappearing message, I do so because I do not want any record of the message to exist, not even on my phone. I do not even want proof that any messages were sent, nevermind any information about their contents. I don't want this information on my phone in case my phone is stolen and accessed.

There should at the very least be an option to turn this behavior off.

Note: This information doesn't seem to stay on the receiver's end, but I object even to the fact that it's stored anywhere at all after expiring.

For me, this strongly reduces my trust in the ongoing security of the app if this kind of security compromise is made for the sake of a "cool feature". It especially does not help that this change occurred without me being told about it — I was caught by surprise by this behavior.

## Environment

* Wire version that exhibits the issue: 2.38.352
* Last Wire version that did not exhibit the issue (if applicable): Not sure.
* Android OS version used to run Wire: 7.1.2
* Is this a custom firmware or a stock one: Stock 
* Mobile phone model/manufacturer: Google Pixel
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Any

## Details

- Send an expiring message (I tried 5 minutes or less)
- note the length of the words in the message (for example, send "a aa aaa aaaa aaaaa aaaaaa")
- when the message expires, see that the squiggles match up with the original text perfectly.

## Screenshots

I don't think Wire allows screenshots to be taken.

**Comment by someoneEsle** [comment]
Hi,
I think you misunderstand the behavior of the app, so let me explain it a little better.

When you send a message that has a timeout of 30 seconds, the following happens:
- 30 seconds after you have sent it, the message turns into squiggles
- when the other user reads the message, a 30 second countdown starts on their device
- when the countdown reaches 0, the squiggles go away from your phone and the message disappears on the receiver's end

As you can see the squiggles are only a temporary thing: they are not staying forever. If you want to be extra safe you can delete the timed message after you send it (delete "only for me").

p.s.: Wire does not allow screenshots to be taken if there are ephemeral messages visible in your current conversation :)

**Comment by phoenixeliot** [comment]
Hm. That doesn't seem to match the behavior I see. All of the messages I sent a couple days ago with very short timers still have squiggles remaining in my chat log. The person I sent them to confirms that the message has disappeared from their history.

Deleting the messages is an okay workaround, except for this issue which makes it easy to delete the wrong one (which happened to me while trying to delete the squiggles): https://github.com/wireapp/wire-android/issues/1078

**Comment by someoneEsle** [comment]
Hmm, sounds like you ran into a bug then. Sorry about that. What
device/OS/wire version is your friend on?
(I will probably follow up tomorrow when I go back to the office)

**Comment by phoenixeliot** [comment]
See my initial comment :)

**Comment by someoneEsle** [comment]
Sorry I only see your phone/os there. What about your friend's?

**Comment by phoenixeliot** [comment]
Ah! Sorry, missed that word.

OS: Android 7.0 (stock)
Model: Motorola Droid Turbo 2
Wire version: 2.38.352

**Comment by someoneEsle** [comment]
Hi again.
I checked today and it looks like the bug you reported (squiggles never
going away) is probably related to another bug that we just fixed. Sometime
today you should get an update to version 2.39.356. It would be really
useful if both you and your friend could update to that version, and see if
you can reproduce the issue. The squiggles should go away as designed now.
If they don't, please set the timer to 5 seconds, send/receive some
messages, and then send us the logs from both phones. Hopefully though you
won't have to do that :)

**Comment by BobbyWibowo** [comment]
So is this reply https://github.com/wireapp/wire-desktop/issues/1081#issuecomment-357208792 the conclusion for this issue?

**Comment by makingthematrix** [comment]
Ok, I think I can close this issue now. Please reopen if anything is unclear.
