### ISSUE TITLE
Allow Wire messenger to be rotated

### ISSUE THREAD

**Issue by KopfKrieg** [wireapp/wire-android#1088]
## The problem

The wire messenger can only be rotated 0°, 90° or 270°. Please add the option to rotate the wire messenger 180°. Nearly every other app on my phone can be rotated 180°.

## Environment

* Wire version that exhibits the issue: 2.39.356
* Android OS version used to run Wire: 7.1.2
* Is this a custom firmware or a stock one: Lineage OS from August, 24th
* Mobile phone model/manufacturer: One Plus 2
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi

**Comment by KopfKrieg** [comment]
Update: I did a factory reset of my phone (by mistake), and wire now can't be rotated in any direction. Is this intended behaviour? Am I forced to use wire (as the only exception of all the other apps on my phone) in portrait mode, not even able to rotate 180° (because of the location of the usb port/audio jack it would be nice rotate at least 180°).

**Comment by someoneEsle** [comment]
I am surprised you were able to rotate wire in the first place -- we only support portrait mode. Maybe you were using some app that enforces rotation on other apps? Just guessing.

**Comment by KopfKrieg** [comment]
I'm surprised too. Currently I'm not sure if I was really able to use wire in landscape mode (btw., I don't use any apps to force rotation).

Do you know if there's a reason to only support portrait mode (even on tablets?), or is there maybe an open discussion about this I could join? Because using wire in landscape mode (and upside down/rotated 180°) is something I really would appreciate, and I'm can't think of a good reason why this shouldn't be implemented (well, "implemented" is maybe the wrong wording. I found a few hits in the wire source code if I search for "portrait", but the screen orientation of the app should, if I remember that correctly, be set through the screenOrientation property in the app's manifest).

**Comment by someoneEsle** [comment]
Hi, currently we only support portrait mode due to a lack of resources -- we are just a small team. However, you can use landscape on tablet.

**Comment by Awerick** [comment]
@KopfKrieg: Issue #455 is probably what you are looking for.
It also references the old (and closed) issue #78 that explains why this is currently not supported.

**Comment by KopfKrieg** [comment]
Ah, okay. Thank you for your input and the links. I hope it's okay to close this issue then.
