### ISSUE TITLE
No audio output over bluetooth

### ISSUE THREAD

**Issue by SIRSteiner** [wireapp/wire-android#111]
If connected with a bluetooth device, audio always sent to speaker not to the device.

**Comment by david-wire** [comment]
Thanks for the feedback.
Could you tell us a bit more about this issue? What is the Bluetooth device you are using (model)? 
Also, if you could send us a debug report when this happens, that would be good: 
Within Wire > Settings > Advanced > Submit Debug report.
Many thanks.

**Comment by SIRSteiner** [comment]
I did it including a catlog file

**Comment by Gregory-K** [comment]
Same here with a Jabra bluetooth hands-free connected.
It works for standard calls and other apps (like Skype) but not with Wire.
I have to use the phone earpiece/mic.

**Comment by GabMar** [comment]
Same here with Levin-998 Bluetooth Headphones.

**Comment by jdiercks** [comment]
+1... Wire doesn't seem to recognize my headset either

Bluetooth headset support is pretty important if Wire is hoping to gain widespread adoption for voice/video calling.

**Comment by Transisto** [comment]
This is pretty basic is Wire want to replace Signal which is trying to replace regular phone calls, I don't know any app that doesn't send the sound to my bluetooth headphones 
MDR-1000X

**Comment by marcoconti83** [comment]
@jspittka do you know wether this is this still an issue on Android+bluetooth, or has it been fixed since?

**Comment by Transisto** [comment]
No but thinking of it, when getting a call on while listening to ie. a
podcast the sound just stop, doesn't ring (Bluetooth)

**Comment by makingthematrix** [comment]
https://wearezeta.atlassian.net/browse/AN-6605

**Comment by Gardosen** [comment]
this issue should have been resolved, 
i checked this with different bluetooth headphones, and there was no unexpected behaviour.

Closed as fixed
