### ISSUE TITLE
Search contact is our first step !!!

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#1110]
I've just moved all my teams from Signal to Wire. It's to long to search though the list of contacts, and that's how we got used to using Signal with many contacts.

**Comment by someoneEsle** [comment]
Hi, I'm sorry but I'm not sure I understand your problem. Is the app taking too long to bring up results when you search for a contact?

**Comment by Transisto** [comment]
I figured that we can tap the small + sign at the bottom left to search contacts.

Signal on android allow for that too but ALSO has a search at the very top right that doesn't load another page to start typing, which I think is more faster and more obvious.
![image](https://user-images.githubusercontent.com/388716/30287905-c3b0dd0c-96f4-11e7-989d-4a469368dc6f.png)

**Comment by Transisto** [comment]
![image](https://user-images.githubusercontent.com/388716/30525487-5517e904-9bd5-11e7-973b-89ee246bf5b8.png)

**Comment by someoneEsle** [comment]
Hi, we have filed this with the other feature requests we get. Thanks!
