### ISSUE TITLE
Saving multiple images is bugged

### ISSUE THREAD

**Issue by KopfKrieg** [wireapp/wire-android#1116]
## The problem

Steps to reproduce:
 - Receive a couple of images via wire
 - Tap on an image
 - Save image via download button
 - Swipe to next image
 - Save image
 - Swipe to next image
 - Save image
 - Et cetera

Result: Only the first image opened is saved, but multiple times. None of the other images are saved.

Expected: Every image is saved, not only the first one multiple times.

## Environment

* Wire version that exhibits the issue: 2.40.357
* Android OS version used to run Wire: Android 7.1.2
* Is this a custom firmware or a stock one: LineageOS
* Mobile phone model/manufacturer: OnePlus 2
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi

**Comment by makingthematrix** [comment]
This functionality was rewritten. I followed the steps (thanks for the detailed explanation, @KopfKrieg ) and the bug seems to be fixed. I'll close the ticket - please reopen if it happens again.
