### ISSUE TITLE
Time tags are 30 minutes late

### ISSUE THREAD

**Issue by victor987** [wireapp/wire-android#1118]
## The problem

The time tags are 30 minutes late.

![This message was sent at 18:11, the displayed time is 17:41](https://user-images.githubusercontent.com/7703181/30299388-73211dce-971d-11e7-9f35-4f200764ae3e.jpg)

###### Wire:
time of log: 2017-09-11T22:19:28.957Z
package: com.wire
app version: 357
zms version: 107.0.394
device: LGE bullhead | Nexus 5X | google | NJH47F
version: 7.1.2 | REL

## Details

I am on the Venezuela time zone (-04:00) which has changed from -04:30 a few months ago, maybe it is related to the issue.
The Linux and web versions display the correct 18:11 time for the same message.

**Comment by someoneEsle** [comment]
Hi, what do your phone's settings for date and time look like? Are they set automatically or manually?

**Comment by victor987** [comment]
"Date & time" is on Automatic.
The issue is present with Automatic time zone.
The issue is present with Manual time zone set to "Caracas GMT-04:00".
The issue **not** is present with Manual time zone set to "Manaus GMT-04:00".

_Note: "GMT-04:00" is incorrect for [time zone designation](https://en.wikipedia.org/wiki/Time_zone) and should be "UTC-04:00". I am copying them as they appear on my phone._

The time zone change for Venezuela from UTC-04:30 to UTC-04:00 occurred on 2016-05-01 and was previously announced.
I guess you are using an outdated time zone library instead of using the device's local time.

**Comment by someoneEsle** [comment]
Thanks for your help! It looks like you are right. We'll update our library and hopefully the problem will go away. Sorry about that :)

**Comment by victor987** [comment]
FYI there are [IANA time zone database](https://www.iana.org/time-zones) updates (not DST changes) many times per year (10 in 2016), so you may want to make that automatic for each release, or rely on the devices' settings/local time.

I guess there are situations where having a wrong message time can cause lots of trouble to people. For instance: "meet there in an hour".

**Comment by victor987** [comment]
The issue is still present.
