### ISSUE TITLE
Conversation sometimes blank or jump to the top

### ISSUE THREAD

**Issue by SIRSteiner** [wireapp/wire-android#112]
Sometimes if clicking on a new notification to open the conversation you see nothing, after reopening the conversation all items are visible. 
And sometimes when opening the conversation it jumps to the top. A reopen does not help, you have to scroll down manually. 

Maybe these are 2 problems without any relation. Thanks

**Comment by someoneEsle** [comment]
If you want to avoid having to scroll down manually, you can:
- open the keyboard
- hit any keystroke
and it will automatically scroll all the way down.
I think this issues are being worked/fixed on in the branch message_stream, so hopefully we'll get a fix soon.

**Comment by hakonbo** [comment]
Hi, and thanks for posting. We are aware of some issue with the conversation view and are working on making this better. Will be out in a few weeks if everything goes to plan.

**Comment by someoneEsle** [comment]
Actually I just had this bug again today, Nexus 5X Android 7.1
