### ISSUE TITLE
No notification for missed phone calls while offline.

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#1137]
Called a friend 3 times, he did not see any notification that I tried to call him once he got Wire back online.

**Comment by someoneEsle** [comment]
Hi,
when you create a new issue on github you are prompted to fill out a form that provides us with some basic information. Without it, we will be unable to help you. I just tried to reproduce and it worked well for me.

**Comment by Transisto** [comment]
We had the same issue with android devices.

I tested with iOS and the notification worked.

**Comment by hub-ch** [comment]
https://github.com/wireapp/wire-android/issues/777#issuecomment-466763316

**Comment by marcoconti83** [comment]
Hi all,
there are a lot of duplicated issues covering this same problem (or a very similar one), let's unify all conversations and keep it going here: #777 . Closing this one and continuing there.
