### ISSUE TITLE
Problem changing email address

### ISSUE THREAD

**Issue by j-a-n** [wireapp/wire-android#1144]
## Unable to change email address in profile settings

Go to profile settings.
Tap on email address.
Type new email address in dialog
Ok button has no effect, dialog stays open.

## Environment

* Wire version that exhibits the issue: 2.40.357
* Android OS version used to run Wire: 7.0
* Is this a custom firmware or a stock one: stock
* Mobile phone model/manufacturer: SM-G935F/Samsung
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): any

**Comment by someoneEsle** [comment]
Hi, thanks for reporting. We will release an update today that fixes this issue :)

**Comment by j-a-n** [comment]
Thank you for the quick fix!
