### ISSUE TITLE
Severe error in deleting chat

### ISSUE THREAD

**Issue by AyelGoth** [wireapp/wire-android#1148]
When I tried to delete a chat I used to archive it. Now the application closes unexpectedly when you try to delete a chat.

The error occurs in the version of Wire 2.41.359.
Android OS Ver 6.1.
Mobile Phone LG K10 2017
Mobile network LTE.

**Comment by someoneEsle** [comment]
Hi, could you please send us a log right after this happens? You can find it in Settings>Advanced. That would help us understand what's going on :)

**Comment by AyelGoth** [comment]
Ready, the report's been sent.

**Comment by Amp3rwater** [comment]
I have exactly the same issue after update to the latest version (2.41.359) of wire.
OPX running Lineage OS 14.1.

**Comment by rnd83** [comment]
Same here. Sorry but I can't seem to format the code block without linebreaks.
Anyway, seems to be the IndexOutOfBoundsException.

`10-09 18:47:59.795  5028  5028 E AndroidRuntime: FATAL EXCEPTION: main
10-09 18:47:59.795  5028  5028 E AndroidRuntime: Process: com.wire, PID: 5028
10-09 18:47:59.795  5028  5028 E AndroidRuntime: java.lang.IndexOutOfBoundsException: -1
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at scala.collection.immutable.Vector.checkRangeConvert(Vector.scala:132)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at scala.collection.immutable.Vector.apply(Vector.scala:122)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at com.waz.api.impl.ConversationsList.get(ConversationsList.scala:16061)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at com.waz.zclient.api.scala.ScalaConversationStore$$anonfun$nextConversation$2.apply(ScalaConversationStore.scala:1106)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at scala.Option.flatMap(Option.scala:171)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at com.waz.zclient.api.scala.ScalaConversationStore.nextConversation(ScalaConversationStore.scala:105)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at com.waz.zclient.api.scala.ScalaConversationStore.setCurrentConversationToNext(ScalaConversationStore.scala:102)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at com.waz.zclient.pages.main.participants.ParticipantFragment$3.onHideAnimationEnd(ParticipantFragment.java:489)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at com.waz.zclient.views.menus.ConfirmationMenu$3.onAnimationEnd(ConfirmationMenu.java:274)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1153)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1313)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:872)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:618)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
10-09 18:47:59.795  5028  5028 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
10-09 18:47:59.797   728   944 W ActivityManager:   Force finishing activity com.wire/com.waz.zclient.MainActivity
`

**Comment by someoneEsle** [comment]
This should be fixed
