### ISSUE TITLE
Dark theme and edit text

### ISSUE THREAD

**Issue by hchr** [wireapp/wire-android#1149]
With dark theme and version 2.41.359 it's almost impossible to see the text when editing.
Android 8.0.0 and Android 6.01

![screenshot_20170928-102548 2](https://user-images.githubusercontent.com/6417330/30956957-18e6b958-a439-11e7-8d6b-83ddd718ce4c.png)

**Comment by phoenixeliot** [comment]
+1, this is a regression.

**Comment by someoneEsle** [comment]
This should be fixed
