### ISSUE TITLE
is it possible to build from extracting libraries in apk

### ISSUE THREAD

**Issue by FihlaTV** [wireapp/wire-android#1154]
hi
Is it possible to  build wireapp android from extracting pre-built libraries from apk? my gradle crushed several times when I attempted to build from source. this happens even after all Marven plugins are downloaded.

any help

**Comment by someoneEsle** [comment]
Hi, could you give us the logs you get when you fail to build?

**Comment by hub-ch** [comment]
https://github.com/wireapp/wire-android/issues/1892

**Comment by marcoconti83** [comment]
Hi everyone,
The issue has been fixed here: https://github.com/wireapp/wire-android/issues/1892. Please read the instructions at that link. If this is not fixed for you, please report the issue in the linked discussion and not here.

Thanks for your patience!
