### ISSUE TITLE
UI, "..." Icon to show more option can be confusing.

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#1155]
... to me mean the message is longer and can be expanded.

![image](https://user-images.githubusercontent.com/388716/30985705-122ed5c0-a45f-11e7-8836-c6eedf157fe4.png)

I suggest boxing it so that it's more obvious that it's a button.

**Comment by someoneEsle** [comment]
Hi, please post this in the [webapp repository](https://github.com/wireapp/wire-webapp). Here we only collect bugs and feature requests for Android :)
