### ISSUE TITLE
Sharing to Wire contact only work the 2nd time.

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#1159]
It only load the current selected contact but doesn't put the content to be shared.

The 2nd time it would work because the contact is already loaded.

**Comment by someoneEsle** [comment]
Hi, what were you trying to share?

**Comment by kroerig** [comment]
I have the same problem since the update to version 2.41.
I tried sharing a webpage from Chrome browser, a news from Tagesschau-App.

**Comment by cwmke** [comment]
Same problem sharing a link from Firefox. Android 7.1.2 without gapps.

**Comment by someoneEsle** [comment]
You will receive an update with a fix for this bug in a few days. Thanks for reporting!

**Comment by someoneEsle** [comment]
This should be fixed
