### ISSUE TITLE
No way to turn off notifications

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-android#1160]
## The problem
There's no way to turn off notifications on the phone so they don't bother the user while they are at the computer. The phone just keeps waking up. Related to #814 

## Environment

* Wire version 2.41.359
* Android OS version 8.0.0
* stock firmware
* Nexus 5X
* mobile network type EDGE/LTE

## Details

I went to Settings -> Options, unticked everything, yet I still receive notifications

**Comment by someoneEsle** [comment]
Hi, when you create an issue there is a template that we ask our users to fill. This helps us figure out what issues you are having, so we can better help you. Could you please provide all the information in it?

**Comment by budkin** [comment]
I updated my post. Not sure what you would need debug logs for, the issue is pretty obvious

**Comment by someoneEsle** [comment]
Do the notifications on your phone go away after you read the messages on the computer? Also, do they make a sound or are they silent notifications?
When you are actively using Wire on your desktop you should only receive silent notifications on your phone -- and they should go away when you read the messages on your computer

**Comment by budkin** [comment]
>Do the notifications on your phone go away after you read the messages on the computer?
Yes
>Also, do they make a sound or are they silent notifications?
They are silent. Turning off the sound works

>When you are actively using Wire on your desktop you should only receive silent notifications on your phone -- and they should go away when you read the messages on your computer
Yes, I know that. But what bothers me is the fact that my phone keeps waking up. It drains the battery and shouldn't happen. I had to turn off the notifications in the Android menu (not possible on old Androids)

**Comment by Cetyufeproaacut** [comment]
This is the most annoying "feature" ever. At least reduce the blinking frequency.

**Comment by Transisto** [comment]
Every competing apps I use allow to selectively disable notification for a specific group. My people are leaving signal because some of the groups are too active.

**Comment by someoneEsle** [comment]
@Transisto you can mute group chats on Wire https://support.wire.com/hc/en-us/articles/203133704-How-can-I-mute-or-unmute-notifications-for-specific-conversations-
