### ISSUE TITLE
Notification LED utilization per contact

### ISSUE THREAD

**Issue by fbruetting** [wireapp/wire-android#1172]
At the moment, the notification LED lights up with no respect to how important the corresponding person is – so my phone flashes up half the day, although most messages aren’t of importance. First, this is annoying (but deactivating it for Wire at all is no solution), and second, it would be more efficient, if the LED could be restricted to important contacts only. Android allows per-App notifications settings – it would therefore be nice if the LED could be filtered per-contact, too. This could be done both via white- or blacklisting, what should be selectable in the settings.

**Comment by alexpacini** [comment]
+1. I really like the personalized notification light, allowing to work without distraction and to check it only for important persons or conversations.

**Comment by someoneEsle** [comment]
@alexpacini thanks for checking out our github forum. However, I have to ask you to please not bump issues with "+1" comments. That is what the +1 reaction is for -- it triggers no email notifications to people in the thread, and it takes less time for us to read everything. We like your enthusiasm, thanks for your support! :)
