### ISSUE TITLE
Messages don't show as sent but are actually sent.

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#1174]
## The problem

Messages that I write (multiple) don't show up on my side but are actually sent. (visible on desktop vesion)
Messages are shown when contact is quitted and back.

## Environment

latest, Galaxy S7
Happened on 3 occasion with different contacts in 2 days.

**Comment by TubaOrNotTuba** [comment]
I see this all the time, have to kill the Android app and relaunch it.  Never happens on iOS or Desktop.  It's done this for at least a year now.

**Comment by Transisto** [comment]
This still happen way too often

**Comment by makingthematrix** [comment]
Hi.
I'm going through the list of issues and try to figure out which can be closed. What about this one? Since 2017 we changed a lot the functionality of sending messages. Does the problem still appear?
