### ISSUE TITLE
Archiving a Conversation does not work via Swipe menu in the conversations list.

### ISSUE THREAD

**Issue by tokariu** [wireapp/wire-android#1177]
## The problem

conversations can not be archived via the swipe menu in the conversations list.

## Environment

* Wire version that exhibits the issue: 2.41.359
* Last Wire version that did not exhibit the issue (if applicable): n\a
* Android OS version used to run Wire: 6.0
* Is this a custom firmware or a stock one: stock
* Mobile phone model/manufacturer: LG G3
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): doesn't matter.

## Details

When you're in your conversations list, you swipe one conversation to the right and a menu shows up with the following options: archive, block, delete, mute, send pic, call

if you select archive from there, nothing happens. the selected conversation does not get archived and is still in the conversation list.

if you want it to work, you have to archive it by clicking on the conversation, open it, then click on the conversation/nickname at the top, then click on the "..." at the bottom right, (a menu opens) and then select "archive" from there. this will finally archive the conversion.

this is cumbersome and the swipe methode should work again.

**Comment by makingthematrix** [comment]
Hi.
I'm going through old issues in order to figure out which ones can be closed.
I can't reproduce this bug. The functionality was changed a lot since 2017, so I guess it was fixed at some point. Please reopen this issue if you find it again.
