### ISSUE TITLE
No notification when i am in another chat

### ISSUE THREAD

**Issue by electro60** [wireapp/wire-android#1179]
## When I am in chat anyone else chats do not give me notice of new messages

if i chatting with someone the others send messages to me but noway to know, must back to main conversation screen.

## Environment

* Wire version that exhibits the issue: 
2.41.359
* Android OS version used to run Wire: 
6.0.1
* Is this a custom firmware or a stock one: 
Stock one
* Mobile phone model/manufacturer: Samsung SM-G610F
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): 
Wi-Fi/LTE

**Comment by someoneEsle** [comment]
Hi, actually this is going to change very soon :)

**Comment by someoneEsle** [comment]
Hey @electro60, can you confirm that this is not happening to you anymore? Thanks!

**Comment by someoneEsle** [comment]
Closing for now, feel free to reopen if it happens again
