### ISSUE TITLE
Can't tap on a contact, Very basic UI bug

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#1186]
It's happening very often, I haven't been able to figure out exactly what triggers it.

I just can't tap on the contact, it doesn't do anything.

I can swipe the contact but not tap onto it.

Galaxy S7 edge + Android 7.0

**Comment by someoneEsle** [comment]
Are you trying to tap on contacts in the conversations list? Or are you in Wire's search page?

**Comment by Transisto** [comment]
In the wire contact list.

**Comment by Transisto** [comment]
The problem come from the sensitivity of the slide to right movement.

When finger hit the screen it almost always register as a micro slide instead of a tap.
