### ISSUE TITLE
Wire crash when scrolling up onto a specific URL

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#1187]
Wire crash when scrolling up media intensive conversations

This is the exact post that make Wire crash for everyone in the group

It's same link posted twice in a row. here is text version:

`Significant technical development if true: https://themerkle.com/altcoin-exchange-claims-to-have-performed-an-ethereum-bitcoin-atomic-swap/?utm_medium=push&utm_source=onesignal&utm_campaign=traffic%20boost&utm_content=extended%20%traffic%boost`

![image](https://user-images.githubusercontent.com/388716/31523887-3c03f710-af84-11e7-8c25-07d2c052892e.png)

**Comment by someoneEsle** [comment]
Hey, this will be fixed in today's update. Thanks for reporting!
