### ISSUE TITLE
Picture sharing process too dangerous (risk of sending wrong pictures)

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#1191]
When selecting a picture to share only tiny thumbnail are used and when selecting one it get sent without have had a change to look at it larger.

They are so small there is almost no way to know what is on the pictures.

**Comment by someoneEsle** [comment]
After selecting an image, you are indeed shown a full-screen preview of the image you are about to send. Is this not the case for you? Can you provide exact steps to reproduce?

**Comment by Transisto** [comment]
It does not show anything before sending when selecting a picture from Wire (Attachment icon), I've noticed there was a way to have larger thumbnails but these are still thumbnails 1/12 the size of the phone screen.  Could be hard to tell if it's a paper document for example.

It does show a preview when sharing from another app to Wire though.

**Comment by someoneEsle** [comment]
If you are trying to share picture, you can tap the camera icon instead of the attachment one. From here you can select an image and then you'll see a preview to confirm what you are about to send.

**Comment by red-avtovo** [comment]
Also, we are not responsible for size of thumbnails, because as soon as you taped on attachment icon, you've been redirected to your phone's file manager to let you pick a file for sending.
