### ISSUE TITLE
 videos lose sound when forwarded

### ISSUE THREAD

**Issue by freditbn** [wireapp/wire-android#1197]
## The problem

videos lose sound when forwarded

## Environment

* Wire version that exhibits the issue: 2.41.359
* Last Wire version that did not exhibit the issue (if applicable): n/a
* Android OS version used to run Wire: 7.0
* Is this a custom firmware or a stock one: stock LG, V10f-AME-XX, rooted 
* Mobile phone model/manufacturer: LG V20, H990DS
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/WiFi

## Details

No matter how i try to forward videos videos from wire, sound is lost when forwarded. The videos play silently.

The sound also disappears when videos not recorded on wire are forwarded within the app.

The sound is lost on the sender and recipient device. No matter what video player is launched to play the forwarded video.

when the video is saved on the device from within wire, the sound plays when the video is played. However when the downloaded video is sent from the gallery or an explorer to a wire contact. the sound is also lost. 

## Link to Debug logs

N/A

## Screenshots

N/A

**Comment by someoneEsle** [comment]
duplicate #231
