### ISSUE TITLE
Is wire server side source code open?

### ISSUE THREAD

**Issue by atralheaven** [wireapp/wire-android#12]
My question is, is wire open source on server side too? like signal, or codes of the server side are closed like telegram?
Thanks

**Comment by zbsz** [comment]
No, server sources are not released. From security point of view it doesn't matter much, end to end encryption protects clients from it, as server is not able to read your messages.

**Comment by kansujiya** [comment]
@zbsz How can i get Server side code ?

**Comment by tuxayo** [comment]
@kansujiya Over there :) https://github.com/wireapp/wire-android/issues/237#issuecomment-344841084
