### ISSUE TITLE
No notification sound

### ISSUE THREAD

**Issue by fichtennadel** [wireapp/wire-android#1210]
## The problem

No notification sound for new messages and pings. Ringtone is ok.

## Environment

* Wire version that exhibits the issue: 3.0.366
* Last Wire version that did not exhibit the issue (if applicable): don't know, I think the one before was ok
* Android OS version used to run Wire: 7.0
* Is this a custom firmware or a stock one: stock
* Mobile phone model/manufacturer: Samsung S8
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/Wi-Fi

## Details

When I receive a message or ping, no notification sound is played. 
The notification itself is shown. Other apps can play notification sounds, and ringtone in Wire is also ok, so I suppose it's specific to Wire's notifications.
I've tried with preferences for sound set to "All", "First..." and "None", no change. I've also set custom sounds and reset to default, and still no change.
Reproducable on locked and unlocked screen.

Can I download a previous version of the apk somewhere?

**Comment by theincogtion** [comment]
Same on LineageOS nightly.

**Comment by gaboreszaki** [comment]
Same on LG G3(A7.0), Sony Z1 (A4.4), Sony Z3 (A4.4)

**Comment by colonia27** [comment]
Same on OnePlus 3, OxygenOS 4.5.1, Android 7.1.1

**Comment by fichtennadel** [comment]
After one week, could someone from Wire comment on this please? Is this a known issue and a fix on the way?

**Comment by ganego** [comment]
> Can I download a previous version of the apk somewhere?

https://www.apkmirror.com/apk/wire-swiss-gmbh/wire/

**Comment by fichtennadel** [comment]
>> Can I download a previous version of the apk somewhere?
> https://www.apkmirror.com/apk/wire-swiss-gmbh/wire/

Seriously? Downloading an encrypting messenger from a some random, 3rd party website? No way.

**Comment by someoneEsle** [comment]
There is already a fix in our beta version. If you want, you can join our beta program by going here https://play.google.com/apps/testing/com.wire. Know that joining the beta means things could possibly go wrong (either with this update or at any point in the future), so if you don't want to trade peace of mind for quicker updates you should just wait a few days when we'll push this beta to the public.

**Comment by theincogtion** [comment]
This is true slapstick....

> now that joining the beta means things could possibly go wrong

The stable version is wrong here.

**Comment by bitassassin** [comment]
@someoneEsle : Your bedside manner could use some work. I just spent two hours trying to fix this on my phone, only to come here and discover that folks waited six days for a response, and that response was "We already fixed it, we just haven't pushed it yet, hold your horses jeez". 

Some more understanding communication on validated issues would be nicer, just saying.

**Comment by someoneEsle** [comment]
@bitassassin we pushed the fix to beta just a few hours before posting the comment here. So it's not like the fix had been sitting on the beta version for weeks waiting to be found :)

**Comment by fichtennadel** [comment]
Ok in 3.1.369
