### ISSUE TITLE
When writing a message, the last word of the last message gets placed at the beginning of the new message.

### ISSUE THREAD

**Issue by tokariu** [wireapp/wire-android#1213]
## The problem

When writing a message in a conversation, the last word of the last message gets placed at the beginning of the new message in the input area.

## Environment

* Wire version that exhibits the issue: Android 3.0.366
* Last Wire version that did not exhibit the issue (if applicable): Android 2.40.357
* Android OS version used to run Wire: MM 6.0
* Is this a custom firmware or a stock one: Stock
* Mobile phone model/manufacturer: LG G3
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): all

## Details

I'm using two accounts. Sometimes in the latest android versions (> 2.40.357) it happens that the last word of the last message i wrote gets placed at the beginning of a new message. 

for example:
if I wanted to write 2 messages:

1: "The weather is beautiful"
2: "The sun is shining"

then the following happens:
The fist message with: "The weather is beautiful" was sent, then when I beginn to type a 2nd message, the input field already contains the word "beautiful".
if I just start to write my message as I'm used to do, I'd write and send: "beautifulThe sun is shining". 
Only if i manually delete the wrongly placed "beautiful" at the beginning, i could send my 2nd message correctly.

This bug is not happening *all* the time, but when it happens it happens continuously. I figured out sometimes it helps going back to the conversations list, choosing another conversation, touch the input field there to open up the onscreen keyboard and then going all the way back to the last conversation.
But it's happening again after some time, maybe after switching accounts or logout/login to another account again. Killing the application and restarting does not solve the problem.

I barely remember we had this kind of bug about a year ago in an earlier version of android. sometime later this bug got patched and we got rid of it until it resurrected with Android v2.41.359.

**Comment by someoneEsle** [comment]
Hi, thanks for reporting! We have a PR that fixes it -- see https://github.com/wireapp/wire-android/pull/1201. It will be merged soon and will go into an upcoming update

**Comment by someoneEsle** [comment]
Hey @tokariu, are you in the beta program? If so, can you confirm that this is not an issue for you anymore? If you're not a beta tester then no worries, you should receive an update within the next couple of days that fixes this bug. Thanks!
