### ISSUE TITLE
Images are not zoomable on a Galaxy J5

### ISSUE THREAD

**Issue by tokariu** [wireapp/wire-android#1214]
## The problem

While it seems to work on other smartphones, if you got a Samsung Galaxy J5 and click on an image in a conversation to have a bigger preview, you are not able to zoom into the image with the usual two-fingers zoom gesture.

## Environment

* Wire version that exhibits the issue: Android 3.0.366
* Last Wire version that did not exhibit the issue (if applicable): -
* Android OS version used to run Wire: 5.1.1
* Is this a custom firmware or a stock one: Stock
* Mobile phone model/manufacturer: Samsung Galaxy J5
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): *

## Details

While it seems to work on other smartphones, if you got a Samsung Galaxy J5 and click on an image in a conversation to have a bigger preview, you are not able to zoom into the image with the usual two-fingers zoom gesture.

There was a time and an android version about a half-year ago where this worked as intended. I guess it was before the gallery/image preview got an overhaul.

**Comment by juliss95** [comment]
I have the same issue. Pictures are neither zoomable nor rotatable. It has never worked on my device and it's quiet bothering if you always have to download images in order to see any details.

Wire version: all of them till the current beta
OS Version: Android 5.0
Firmware: MIUI 8
Model: Xiaomi Mi2S

**Comment by forteller** [comment]
They are not zoomable in Wire at all, neither in the Android app or on the web. Very annoying! Hope this can be fixed soon!

**Comment by makingthematrix** [comment]
This functionality is rewritten and right now there seems to be no problems with zooming photos. I'll close this ticket - please reopen if it happens again.
