### ISSUE TITLE
Sent images in a conversation are not shown anymore when deleted from the phones gallery.

### ISSUE THREAD

**Issue by tokariu** [wireapp/wire-android#1222]
## The problem

As the title says, images once sent are shown as black if the user deletes the images from their phone/gallery.

## Environment

* Wire version that exhibits the issue: Android 3.0.366 (and probably all previous)
* Last Wire version that did not exhibit the issue (if applicable): -
* Android OS version used to run Wire: 6.0
* Is this a custom firmware or a stock one: stock
* Mobile phone model/manufacturer: independent
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): *

## Details

To reproduce:
1. Take a picture with your phone's camera. it's being saved into the phone's gallery.
2. share the image with a friend, and it's shown in the conversation.
3. delete the very same image from the phone's gallery (NOT wire's gallery!).
4. close and restart wire.
5. see a black placeholder where once the image was shown.

Wire obviously uses a local link to the image on the phone and does not store it in it's own database (neither locally nor remotely).
When the image locally gets deleted, it's also vanished from the wire-conversation and wire-gallery.

What does the user expect?
The user assumes he can safely delete the image from the phone's gallery once it's been sent over wire and is still able to see it in his own conversation view. 

A possible solution?
if wire only uses a local link to the image, the solution might probably be to make a copy of the image in the local wire database, so it's still there after the user decides to delete the image from the phone's gallery and therefor wire is still being able to load the pic from the local database when the user views the conversation with this image.

**Comment by someoneEsle** [comment]
duplicate #932
