### ISSUE TITLE
Opening Wire into a conversation makes keyboard "flash"

### ISSUE THREAD

**Issue by forteller** [wireapp/wire-android#1223]
## The problem

Very often, but not always, when I open Wire so that it goes straight to a conversation (opening from a notification or from the home screen after I've closed Wire while having a conversation open) the keyboard opens and closes repeatedly so fast that it's flashing before my eyes and the conversation part of the UI jumps up and down accordingly, so I can't click on the input field to see if that will make the keyboard stay open.

The solution is to click the back button to the list of contacts and going back into the conversation. 

This could very well be a deal breaker for many new users.

## Environment

* Wire version that exhibits the issue: 3.0.366
* Last Wire version that did not exhibit the issue (if applicable): Last one, I think. Not entirely sure.
* Android OS version used to run Wire: 5.0
* Is this a custom firmware or a stock one: Hm?
* Mobile phone model/manufacturer: Samsung Galaxy Note 3
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Doesn't matter

**Comment by someoneEsle** [comment]
Thanks, this is a known bug. We have a fix that we are testing internally. :)

**Comment by someoneEsle** [comment]
Hey @forteller, are you by any chance in the beta program and can let me know if this is still happening to you? If you are not in the beta, there should be an update in the next day or two that fixes this issue.

**Comment by forteller** [comment]
I am not, unfortunately. Thanks for the heads up!

**Comment by someoneEsle** [comment]
(pssst, if you want to join the beta program you can do so by going here https://play.google.com/apps/testing/com.wire ;) )

**Comment by juliss95** [comment]
I'm in the beta and it still happens with the current 3.2.373

**Comment by someoneEsle** [comment]
Ah, sorry about that. @juliss95 could you please tell us what environment you're in?

**Comment by juliss95** [comment]
Android 5.0 & MIUI 8

**Comment by forteller** [comment]
Now there's been two updates since I reported this, and none of them have either fixed it or mentioned it in their changelogs. Any ETA?

**Comment by someoneEsle** [comment]
What keyboard are you using?

**Comment by forteller** [comment]
Swype + Dragon 3.1.0.X

**Comment by juliss95** [comment]
Swype + Dragon here too

**Comment by someoneEsle** [comment]
Should be fixed by now
