### ISSUE TITLE
Cannot download wire apk from website 

### ISSUE THREAD

**Issue by OneHappyForever** [wireapp/wire-android#1225]
## The problem

I’m trying to download the wire apk from the official website, but it never even starts downloading. Same thing for google play store version. I’m in china, and even through the vpn, it doesn’t work. iOS, Windows, Web versions all work fine.

Briefly describe the issue you are experiencing (or the feature you want to see added to Wire).
Tell us what you were trying to do and what happened instead.

## Environment

* Wire version that exhibits the issue: Latest Version 
* Last Wire version that did not exhibit the issue (if applicable): two weeks ago it downloaded fine
* Android OS version used to run Wire: 2.4 all the way up to 6.0
* Is this a custom firmware or a stock one: Different firmaware all exhibit the same issue
* Mobile phone model/manufacturer: xiaomi, Samsung, LG, huawei
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/WiFi 

## Details

Describe the steps necessary to reproduce the problem in more details. The detailed description
will help us to fix the issue faster.

Go to https://Wire.com/download and try to download the apk on an android device

**Comment by someoneEsle** [comment]
Hi, are you able to download the apk from your computer? Then you can transfer it to your phone and install it that way. Also, please make sure that no extension is blocking the download.
