### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by kolaente** [wireapp/wire-android#123]
I dont know if this the right place to put this (probably not), but what about emojis in wire? I know i can add some via the Android keyboard, but it would be very nice if wire could provide a possibilty to add emojis in messages like whatsapp or telegram do.

**Comment by someoneEsle** [comment]
Hi, as far as I know this is where we can file feature requests: https://support.wire.com/hc/en-us/requests/new

**Comment by kolaente** [comment]
Thank you,  i'll try there.
