### ISSUE TITLE
A bit more about Wire as a normal chat service on the website, please

### ISSUE THREAD

**Issue by forteller** [wireapp/wire-android#1231]
Hey. I 100% understand why you're focusing on the team feature on your website. That's where you can get some revenue to continue the work on this fantastic product! I have no problem with this at all!

At the same time: I now find it harder to just send my friends to the Wire website to tell them to use it as an alternative to Messenger, WhatsApp etc. Because when you go to the site it only looks like an alternative to Slack etc. I think this is bad for you, because people who start out using Wire as a personal chat service might like it enough to start using the team feature after a while or ask their workplace to use it. If they don't start out using it as a chat service because they don't understand that you can use it like that, then you might loose out on potential customers in the future.

I know the first sentence says "Business and personal conversations …", but I think most people just look at the headlines and pictures, and when you do that there's very little to suggest that this is an excellent alternative to Messenger.

I'm not asking that you change up the whole front page, but maybe just that you add a picture and a short text about Wire as a private, one-on-one chat service as the second item when you scroll down the page (between "Protected group chats" and "Crystal clear calls").

Alternatively: I wanted to send the website to a friend and when I noticed how the front page made it look like just a Slack alternative I looked for a page that shows Wire off as a personal chat service, and I thought maybe the "Free for personal use"-link would take me to such a page. But no such luck. Maybe you could make such a page, for example on wire.com/personal for people like me to link to, where the link doesn't say "Create a team" but "Start chatting", "Find your friends" or something like that.

Or you could do both.

Thanks for your amazing work, and best of luck with everything! :)

**Comment by someoneEsle** [comment]
Hi, this is the Android repository so we only collect bugs/feature requests for Android :) However, I have shared your suggestions with the appropriate team. Thanks for your support!
