### ISSUE TITLE
Heads up notifications break timed messages

### ISSUE THREAD

**Issue by TubaOrNotTuba** [wireapp/wire-android#1239]
## The problem

Heads up notifications destroy timed messages settings  The excuse from support is that "When you use quick replies, we do not send timed message -- if we did, it would mean we require people to remember that they had turned on timed mode."  That assumes that no one wants to send timed messages all the time.  The exact opposite could easily be said, "if you don't do this you destroy the security of timed messages that users had preset".  Let's stop with excuses and realize that deciding what we want is a great way to alienate users.  At this point I have two businesses who were looking at Wire and have ceased after the recent notifications fiasco and now this.

Assumptions destroy products.  At the very least please give us the RIGHT to decide that we want one or more conversations to always be timed unless manually changed.  -OR- give us the right to disable Heads up notifications and go back to the previous system that worked 100% of the time, of course until you broke it in v3.0.

## Environment

* Wire version that exhibits the issue: 3.2.270
* Last Wire version that did not exhibit the issue (if applicable): anything before this build
* Android OS version used to run Wire: 7.0.0 w/ October 2017 Android security update
* Is this a custom firmware or a stock one: Stock 
* Mobile phone model/manufacturer: LG V20 unmodified, non-root
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/Wi-Fi

## Details

Get a msg, click on the heads up notification to go back to the app (you don't even have to click reply), this resets the previously set timeout.  What you really need to do is honour the previous setting.  

In point of fact, you do this when sharing images or links to Wire.  You assume untimed messages.  Again, this assumption is inaccurate.  If you look at other security messaging app, say Wickr, they offer default settings that apply 100% of the time unless manually changed, no matter what.

Again, it's VERY important to note that even clicking on the notice resets the previously set timeout, it does not require one to click the quick reply, only click the notification.  This NEVER happened in any previous build.

**Comment by someoneEsle** [comment]
You report one bug correctly, which is that when you tap a notification, we shouldn't reset the timeout previously set for this conversation. This is definitely a bug, and not a design decision (as it wouldn't make much sense). :) I read the email you sent to support and the description of the problem wasn't very detailed, so they probably misunderstood -- this is why we ask for the exact steps to reproduce on github. But we got your issue now, and we're fixing it.

By the way, when you share images or links to wire we do not assume untimed messages. In fact, there is an hourglass in the bottom right corner that allows you to set the expiration time.

**Comment by TubaOrNotTuba** [comment]
This appears fixed in the latest build, thanks!

As for sharing, yes you do assume untimed by setting it to the hourglass rather than the previous message's timeout setting.  What you really should do is allow users the option to set a default timeout setting for each conversation or globally, such that anything sent always uses that option.
