### ISSUE TITLE
When logging on another android phone the previous account is just not connecting anymore

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#1245]
There is not ever an error message coming up, just the top orange line loading endlessly on the original device.

Very disapointing behavior I was expecting to be able to use it like Telegram on two device.

**Comment by someoneEsle** [comment]
Did you by any chance reset your password?

**Comment by someoneEsle** [comment]
We don't have enough information to debug, so I'll close this for now. It should be fixed in the upcoming release anyway.
