### ISSUE TITLE
Reactivate closed case that's not accurate

### ISSUE THREAD

**Issue by TubaOrNotTuba** [wireapp/wire-android#1258]
## The problem

When cases are closed, how does one reactivate it?  In the case of [https://github.com/wireapp/wire-android/issues/1242](https://github.com/wireapp/wire-android/issues/1242), the reason for closing doesn't match real world observations.  I've added photos of the behaviour to show the explanation doesn't match the behaviour. 

Thank you.

**Comment by someoneEsle** [comment]
When you post a comment on a closed issue, you should use the option "comment and reopen"
