### ISSUE TITLE
Draft messages very limited and non-functional in compare with any other messenger

### ISSUE THREAD

**Issue by ghsrcgh** [wireapp/wire-android#1259]
Current realization of draft messages very limited and non-functional in compare with any other messenger.

Let's introduce a few **bugs**.

Steps to reproduce:
1) Open a chat with User1. Copy to buffer one of the messages.
2) Tap back and open a chat with User2. Paste copied message, but do NOT send it.
3) Tap back and open a chat with any other user (for example, User1, or any other, except User2).
4) Now return back to a chat with User2.

Expected behavior:
You will see a draft message with a text that was pasted at step 2.

Current behavior:
You will have an empty block to entering message. It is a **bug**.

It seems that there is a ONE draft-buffer to a full wire application, instead of to have a draft-message saved for **each one user** like it is done in any other messengers (Signal, Telegram, etc).

Please fix this bug. Please make a draft-messages saved unique for each one user.
It is required, when you are trying to copy a few messages for someone and edit text (before sending) later.

**Comment by someoneEsle** [comment]
Hi, thanks for reporting. It's a known bug

**Comment by makingthematrix** [comment]
One more ticket which was fixed and nobody updated it. Closing it now :)

**Comment by Aikatsui** [comment]
https://github.com/wireapp/wire-webapp/issues/11200
