### ISSUE TITLE
Application stuck after password change

### ISSUE THREAD

**Issue by gapop** [wireapp/wire-android#1260]
## The problem

I have changed my password from the Web app. Now, the app cannot fetch new data from server, but it doesn't prompt for new password (doesn't log out).

When I open Wire on my Android tablet (Nexus 7, 2012), it opens to the last accessed conversation and shows an animated blue line at the top, as though it's trying to connect. It does not fetch new data, and there is no way to put in the new password. When I tap on my avatar to go to Account settings, the app jumps back to the conversation where it opened.

I guess that deleting the app data would force me to sign in again and would solve the issue, but I'm afraid that it would also lose all the device verification status information.

## Environment

* Wire version that exhibits the issue: 3.2.373
* Android OS version used to run Wire: 5.1.1
* Is this a custom firmware or a stock one: stock
* Mobile phone model/manufacturer: Asus Nexus 7 tablet, 2012
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi

## Details

Steps as it happened for me:

- Sign in to tablet, open conversation
- Close app, lock tablet
- Change password from different device (was Desktop app in my case)
- Open Wire on tablet

## Link to Debug logs

The bug prevents access to the app settings, cannot provide logs.

## How to send detailed debug report from Wire:

Cannot access app menu because of bug.

**Comment by someoneEsle** [comment]
Hi, this is a known bug that we are currently addressing. Thanks for reporting!

**Comment by someoneEsle** [comment]
Hey @gapop , are you a beta tester? If so, could you update to the latest version and let us know if it fixes your issue? Thanks!

**Comment by gapop** [comment]
I enrolled as beta tester and updated to 3.3.374. At first, I saw the exact same behavior as before. Then I cleared the app's cache (not the "app data") and I got the login screen. After login, all is normal. Device verification information is unaffected.

Before reporting the bug, I did not try to clear the cache, not sure if that would've helped with the old version.

Thanks for the fix!

**Comment by someoneEsle** [comment]
Interesting, thanks for reporting your experience!
