### ISSUE TITLE
Videos not embedded in Android 5.1

### ISSUE THREAD

**Issue by DrAxelbauer** [wireapp/wire-android#1264]
Hi everyone!
If I record a video and post it in a chat, the video is just uploaded as an mp4 but it is not embedded within the chat. I guess it is a bug. On Iphones and within the Linux App embedding works fine (also with the same video which i used for testing within the Android App)! 

## Environment
Wire 3.2.373 on Android 5.1
Meizu MX4

**Comment by someoneEsle** [comment]
Hey, thanks for reporting. So if I understand correctly, whenever you send a video you see a grey placeholder as if you were sending a file instead of seeing the video preview, correct?

What happens when you record a video from within Wire and send it? Do you see the preview then?

**Comment by DrAxelbauer** [comment]
I won't call it a placehilder. It is just the mp4 symbol, the name auf the video and the size. That is all. I tried with a video made within wire. I then sent the video to my computer and attatched it into the chat through the wire desktop app on linux. The same video now shoes up as expected as an embedded video. I hope this is clear 😉

**Comment by DrAxelbauer** [comment]
![s71111-10545197](https://user-images.githubusercontent.com/6152981/32688443-25e59b50-c6d1-11e7-8700-cda04c9c9f57.jpg)
**
[wire_debug_report.txt](https://github.com/wireapp/wire-android/files/1463645/wire_debug_report.txt)
**

**Comment by makingthematrix** [comment]
I believe this is fixed already. It still may happen that a video will not be embedded, but only if it's in a format which Wire can't recognize. It should be ok with mp4. Please reopen this ticket if the problem is still occurring.
