### ISSUE TITLE
Notifications on the phone do not disappear after being read on desktop or phone

### ISSUE THREAD

**Issue by alien2003** [wireapp/wire-android#1265]
## The problem

Notifications on the phone do not disappear after being read on desktop or phone.

## Environment

* Wire version that exhibits the issue: 3.2.373
* Last Wire version that did not exhibit the issue (if applicable): previous non-beta version
* Android OS version used to run Wire: 6
* Is this a custom firmware or a stock one: MIUI 8
* Mobile phone model/manufacturer: Xiamo Redmi Note 3 Pro
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): does not watter

## Details

When I receive message notification I reply to it from my desktop. Those notification should disappear from my phone but it still exists. The same happens if I reply by opening Wire, selecting contact and sending message. Notification still here.

It's very bad for me because I use Mi Band for getting notifications and it's constantly vibrating when I have a conversation with somebody on Wire.

**Comment by someoneEsle** [comment]
Hi, thanks for reporting this issue. Let me understand this better. You have two devices -- your phone and your computer (either using the web app or the Wire app).
When you receive a message, you get a notification on both your phone and your computer. At this point you reply using your computer, but the notification on your phone stays. Correct? How long does it stay? Does it go away after a minute or two, or does it stay until you swipe it away?
Also, does this happen only with notifications about likes, or does it happen with all sorts of notifications (like text messages, pictures, etc)?
Thanks for your help :)

**Comment by juliss95** [comment]
Same issue here...
- When opening the message on the computer:
The notification about the message on the phone stays or even comes a second time as a “new“ notification.
It stays there without disappearing.

- When reading the new message on the phone without opening it over the notifications (but by opening Wire and clicking on the conversation or by having Wire already open), the notification still stays and doesn't disappear.

**Comment by someoneEsle** [comment]
Hi people, please always try to give us complete information when reporting a bug (OS, Wire version, phone model are very basic/important requirements).
If my understanding of the bug is correct, it should have been fixed in the current beta. If you're part of the beta program, could you confirm that it is not happening to you anymore? Thanks!

**Comment by ShawnPConroy** [comment]
I am in the Android beta and this seems fixed.

When I first saw this, I got a notification, read it on the PC, and 15 minutes later it was still on my Android device. However, 15 minutes after that (30 minutes) it had cleared off my android phone. Today I tested it and it happened immediately, or close enough.

Android 7.0
LG G6
3.3.374

**Comment by someoneEsle** [comment]
Thank you for reporting! I'm closing this issue for now. If it happens again, feel free to reopen
