### ISSUE TITLE
APK download link leads to Access denied error

### ISSUE THREAD

**Issue by tomleb** [wireapp/wire-android#1268]
## The problem

I used to be able to download the APK straight from the website at /en/download.
The current link [https://wire-app.wire.com/android/prod/wire-prod-release-3.3.374.apk](https://wire-app.wire.com/android/prod/wire-prod-release-3.3.374.apk) leads to an error page with the following:

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>302D97AB50ED4EFE</RequestId><
HostId>iym/538LTvSCNxQKuvSHCSEGPTlitxEZ0lIpp/TGp7hL45tKo9JFgYwT+dXNF76kRwWWUi1B0sg=</HostId>
</Error>
```

**Comment by red-avtovo** [comment]
Hey, @tomleb 
Thank you for your message. Please check the link again tomorrow. We will fix it soon

**Comment by tomleb** [comment]
Glad to hear that it is a bug and not dropping support for APK download, which is my only way of getting this application.

Thank you

**Comment by RITFW** [comment]
That is highly appreciated. Thank you!

**Comment by someoneEsle** [comment]
Should be fine now. Thanks for reporting!
