### ISSUE TITLE
Default Wire-android open source have multiple problems when built.

### ISSUE THREAD

**Issue by Tyriod** [wireapp/wire-android#1269]
I am trying to build an open source app which uses scala version 2.11.8 (ie wire-android). I tried to compile it, it worked but has some problems like the video not working well so when i used terminal to build it with the gradle code = ./gradlew assembleProdRelease --info, I found out that the scala part of the app is compiling with 2.10.4 instead of 2.11.8. I tried all solutions online but it would say zinc not found.... Please any solution to this?

**Comment by someoneEsle** [comment]
Hi, what problems with videos are you having exactly? It sounds unlikely that compiling with a different version of scala would fix the bugs you're experiencing

**Comment by Tyriod** [comment]
Actually I always see stuffs like scala.** can't find referenced class, com.waz.** can't find referenced class and so many more. Can U try to run the default source code on a new machine?. Note: Am using a Mac is
Please any solution?

**Comment by NetE1** [comment]
Hello,
It already fixed. Follow instruction on https://github.com/wireapp/wire-android/issues/1892
(do not allow plugin update)

This issue able close now.

**Comment by marcoconti83** [comment]
Hi @Tyriod ,
as per link posted by @NetE1 (thanks!), the open source build should now work fine when built locally. Feel free to reopen if needed.
