### ISSUE TITLE
error while opening wire client

### ISSUE THREAD

**Issue by androidguide2** [wireapp/wire-android#1271]
i am a noob here and wanted to build wire client but when i open my client and submit my details on registration page it just closes.
*Note I only build the Wire client UI so if this is the error can anyone tell me how to build it so it won't crash

**Comment by someoneEsle** [comment]
What do you see in the logs?

**Comment by androidguide2** [comment]
java.lang.NullPointerException: Attempt to invoke interface method 'int com.waz.call.RequestHandler.request$1d4ff469()' on a null object reference
at com.waz.call.FlowManager.request(FlowManager.java:365)

and @someoneEsle  i know that you created a client earlier can u tell me how did u do that plz it will help me a lot my email is tdevyanshu@gmail.com if u want to contact me

**Comment by Tyriod** [comment]
Cant wire developers tell us how Wire ought to be built without bugs on our machine? Whats on the wire-android page on github is out of date and doesn't work presently. There is no need of the source on github when we cant really build it. Please help matters.

**Comment by NetE1** [comment]
Hello,
@androidguide2 @Tyriod

1. Use a release or use release branch through studio and do not allow plugin update.
2. Follow instruction here https://github.com/wireapp/wire-android/issues/1892 to avoid a avs bug. it'll nearly goes to release so you dont have to manually check it later.
3. Run ./gradlew command or build > generate apk

That's only.

This issue able close now.

**Comment by marcoconti83** [comment]
Hi @Tyriod ,
The app should build locally now without problem. Thanks @NetE1 for bumping this ticket.
Feel free to reopen if it still doesn't work for you.
