### ISSUE TITLE
Persistent notifications

### ISSUE THREAD

**Issue by mandreyel** [wireapp/wire-android#1277]
## The problem

Notifications won't go away after clicking on them to read the message. This appears to be a new problem as I hadn't had issues before.

## Environment

* Wire version that exhibits the issue: 3.3.374
* Last Wire version that did not exhibit the issue (if applicable): don't know
* Android OS version used to run Wire: 4.4.2
* Is this a custom firmware or a stock one: stock
* Mobile phone model/manufacturer: Samsung Galaxy S3 Neo
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): mostly Wi-Fi

## Details

I'll try to investigate the bug in more detail and update this issue.

## Link to Debug logs

https://gist.github.com/mandreyel/55b3614307cc5e5a00fdedb92017eee1

**Comment by someoneEsle** [comment]
Hey, sorry to hear that. Can you at least swipe the notification away? Or do they not go away whatever you do?
Also, how many accounts are you using on your wire app? One or two?

**Comment by mandreyel** [comment]
@someoneEsle Hey! Yeah, the notifications aren't persistent as such (bad wording there), I can swipe them away. What I meant is that *sometimes* it doesn't go away even if I click on it and read the message, and if I swipe it away, it may reappear. It's very inconsistent, but I'll try not to forget to get some logs the next time I notice this.

**Comment by tokariu** [comment]
I have the same problem on stock android 6.0. sometimes the notifications don't get away when I've read the message.

**Comment by AyelGoth** [comment]
In some cases the notifications appear to me two times. Happens to me with the Android 6.0 operating system

**Comment by eknoes** [comment]
I have the same problem, that notifications reappear some seconds after being swiped away.

**Comment by makingthematrix** [comment]
I think https://github.com/wireapp/wire-android/pull/2702 and https://github.com/wireapp/wire-android/pull/2747 dealt with this problem, although the notification processing is very complex and it's still possible to either have too many or not enough notifications in some cases. I will close this issue for now, but I'm sure it's not the end of our work in this area.
