### ISSUE TITLE
Feature request: Make it possible to protect app with a PIN

### ISSUE THREAD

**Issue by mrbiber** [wireapp/wire-android#13]
As, for example, Signal does it (i.e. the app is running and can receive messages, but to read them you need to enter the PIN which then unlocks the app for a configurable period of time). Of course, that feature should be optional.

**Comment by devurandom** [comment]
I think for this to provide an actual benefit, #14 has to be implemented first.

**Comment by someoneEsle** [comment]
@devurandom I disagree. Although it would be nice to have local encryption, a simple PIN can still be useful in all those situations where we hand our phone to people and don't want our messages to be accessible to them. Of course this wouldn't increase the security of the app, it would just make it more private in many common scenarios. :)

**Comment by raphaelrobert** [comment]
@mrbiber: Thanks for bringing it up, we are looking into adding a screen protection to mobile apps.

**Comment by demichev78** [comment]
+1 for pin/password protection. Especially for the app claiming to be focused on privacy/security.
Thank you, it's a great job done overall!

**Comment by alien2003** [comment]
I switched from MIUI to LineageOS and now I mess the ability to protect apps with TouchID.

Signal has this feature, why Wire should not?

**Comment by nikolayhg** [comment]
+1
