### ISSUE TITLE
Build 3.3.378 and double space period issues

### ISSUE THREAD

**Issue by TubaOrNotTuba** [wireapp/wire-android#1328]
## The problem

Starting with 3.3.378, when I double tap the space bar it ads a space and then the period so the end of a sentence looks like this . Then the next one starts.  What should happen is double tapping the space bar should ad a period and a space after it to start the next sentence. 

## Environment

* Wire version that exhibits the issue: 3.3.378
* Last Wire version that did not exhibit the issue (if applicable): Every previous version worked fine
* Android OS version used to run Wire: 7.0.0
* Is this a custom firmware or a stock one: Stock, Verizon
* Mobile phone model/manufacturer: LG V20
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): WiFi/LTE

## Details

This doesn't happen in any other app including Outlook for Android, WhatsApp, Facebook, Twitter, Chrome, etc...

I'm using GBoard v. 6.7.15.17532024 (latest build).

If you think Debug logs will help let me know and I'll create them.

**Comment by TubaOrNotTuba** [comment]
Do we have any idea when this can be fixed?  Sending even remotely professional msgs is now impossible without significant delays in fixing the periods.  I know it's cosmetic, but it's really a big problem.

**Comment by TubaOrNotTuba** [comment]
The latest beta build, 3.4.379, was released today and this major bug remains.  This makes any semblance of professional communication very time consuming.

**Comment by TubaOrNotTuba** [comment]
Can we at least get an acknowledgment of the bug and that it'll be fixed soon?  Just a little frustrating to report it and then silence.

**Comment by someoneEsle** [comment]
Sorry, I do not have the time to reply to everybody (especially if the bug is clear and easy to reproduce). :) I added the bug label, which means we acknowledge that this is a bug.

**Comment by TubaOrNotTuba** [comment]
Another build, 3.5.383, same bug.  Come on guys, this can't be that hard to fix.  It seriously makes professional communication almost impossible.  I can't believe everyone isn't screaming about this.

**Comment by TubaOrNotTuba** [comment]
Another build, 3.5.387, same bug.

**Comment by TubaOrNotTuba** [comment]
Not sure what the custom InputConnection has to do with this, but here's yet another build, 3.6.391, same bug.  Guys, this has existed for too long now with too many builds.  When you introduce a bug that never existed before, fix it in the next build before you work on other issues and enhancements.  The current slate of issues seems to have all started with multiple logins (like the lack of notifications that happened for too long too).  I'm sorry to sound frustrated, but, well, it's frustrating.

**Comment by luciusbono** [comment]
I also experience this bug on my Pixel 2 running Android 8.1 on Wire 3.6.391 using Gboard

I know it's a relatively minor bug, but I have to actually train myself to type differently in Wire on Android (or correct a lot of mistakes). What can I say, I use a lot of periods!

**Comment by someoneEsle** [comment]
Fixed in latest beta 3.6.393. Feel free to reopen if you still experience it. Thanks!

**Comment by TubaOrNotTuba** [comment]
Yes!!!  Just got it.  Thank you!!!!!!!!!

**Comment by luciusbono** [comment]
Fixed for me as well in the latest beta! Great work!!
