### ISSUE TITLE
Chat jumps up after sending message

### ISSUE THREAD

**Issue by juliss95** [wireapp/wire-android#1331]
Since the update to 3.3.378 after sending a message, the chat jumps up around “10 screens“ - so basically it jumps to around 50 messages before.

Since version: 3.3.378
Android 5.0
MIUI 9
Device: Xiaomi Mi2S

I'll add the reproduction rate in the next days, but i think it's either 100% or something close to it.

**Comment by someoneEsle** [comment]
What keyboard do you have?

**Comment by someoneEsle** [comment]
Also, if you could find a pattern in the way you reproduce, that would be great for us to know. Thanks!

**Comment by juliss95** [comment]
Swype + Dragon Keyboard
The one that also still has the jumping up and down issue in Wire.

I'll look out for a pattern :)

**Comment by makingthematrix** [comment]
Ok, I guess I can close this ticket :) I vaguely remember that we had this problem, but it was fix long time ago. Guess we forgot about this ticket.
Please reopen if it happens again.
