### ISSUE TITLE
Wire Android App - phone instead of tablet mode on Chromebook

### ISSUE THREAD

**Issue by jendit** [wireapp/wire-android#1356]
## The problem

The Wire Android app does get installed in phone version instead of tablet version at a Chromebook.
With Chromebooks becoming the new Android tablets and especially with the large screens that are landscape orientated mostly I was expecting the tablet version of Wire to be installed at my Chromebook. Instead, it's  the phone version.
The tablet version would make a lot more sense to me.
Also resizing Android apps is becoming a thing at Chromebooks with Android 8 so maybe also consider that.

## Environment

* Wire version that exhibits the issue: 3.4.382 (and before that)
* Android OS version used to run Wire: 7.1.1
* Is this a custom firmware or a stock one: stock
* Mobile phone model/manufacturer: Samsung Chromebook Pro

**Comment by makingthematrix** [comment]
We decided not to support tablets officially. Sorry. The number of additional issues which come up with supporting tablets is just too much.
