### ISSUE TITLE
bug: email field at login doesn't take input

### ISSUE THREAD

**Issue by penCsharpener** [wireapp/wire-android#1357]
## The problem

email field on login can't be typed into

## Environment

* latest Wire version as of 31.12.2017 on Android 6
* Last Wire version that did not exhibit the issue (if applicable):
* Android OS version used to run Wire:
* stock android 
* Mobile phone model/manufacturer: Nexus 5
* Mobile network type: LTE / Wi-Fi

## Details

user used mobile number to login. wants to login again (different device or after app reinstall). After entering mobile number and verification code a form shows up with email and password and a link "password forgotten". 

Problem on this form is that placing the cursor in the email field is not possible. The password field works but not email. 

## Screenshots / Gif

See: ![2017-12-31_17-23-40](https://user-images.githubusercontent.com/26190934/34462979-62080050-ee4f-11e7-9064-69b2fb83807c.gif)

**Comment by someoneEsle** [comment]
Hi, thanks for reporting. It's a known bug, and [contacting support](https://support.wire.com/hc/en-us/requests/new?ticket_form_id=101615) will help you. Sorry about that!
