### ISSUE TITLE
Google trackers and others

### ISSUE THREAD

**Issue by azlux** [wireapp/wire-android#1358]
## The problem

I think many people already ask you why your android app have some trackers.
https://reports.exodus-privacy.eu.org/reports/62/
But I didn't found any answer So I'm asking here.

## Environment

* Wire version : 3.4.382
* Android OS version used to run Wire:  7.0

**Comment by raphaelrobert** [comment]
Hi @azlux,

Here is some clarification about the issues:

 - Google Ads: Wire doesn't use Google Ads, but there was a reference in the code base that triggered the scanner. The reference was removed in the next version, this should resolve the problem.
 
 - Google Firebase: While Google Firebase has some tracking functionality, Wire only uses Firebase Cloud Messaging. It is simply the next version of Google Cloud Messaging. Every app that uses push notifications will use it going forward, as required by Google: https://developers.google.com/cloud-messaging/
 For users who do not have the Google Play Services installed, Wire uses a fallback to websockets. 
 
 - HockeyApp: Wire uses HockeyApp only to manage crash reports. No other data is shared with HockeyApp, and crash reports can be deactivated at any time. More information can be found in our privacy whitepaper: wire.com/security.

**Comment by jvoisin** [comment]
Google Ads was removed, but Mixpanel was added in the [latest version]( https://reports.exodus-privacy.eu.org/reports/24561/ ).

**Comment by dm17** [comment]
> Hi @azlux,
> 
> Here is some clarification about the issues:
> 
> * Google Ads: Wire doesn't use Google Ads, but there was a reference in the code base that triggered the scanner. The reference was removed in the next version, this should resolve the problem.
> * Google Firebase: While Google Firebase has some tracking functionality, Wire only uses Firebase Cloud Messaging. It is simply the next version of Google Cloud Messaging. Every app that uses push notifications will use it going forward, as required by Google: https://developers.google.com/cloud-messaging/
>   For users who do not have the Google Play Services installed, Wire uses a fallback to websockets.
> * HockeyApp: Wire uses HockeyApp only to manage crash reports. No other data is shared with HockeyApp, and crash reports can be deactivated at any time. More information can be found in our privacy whitepaper: wire.com/security.

Is this still the case? Is this why Wire is not in F-DROID? Why can't wire have a version without this (Google/tracking stuff) for self-hosted clients/customers?
