### ISSUE TITLE
Timed Message with 1 Month Duration

### ISSUE THREAD

**Issue by derDieDasJojo** [wireapp/wire-android#1366]
## Proposal

Timed Messages are great. But sometimes information is relevant for more than a day but
should still disappear after a while. It would be great to also have the possibility to configure
timed messages to stay: 1 Week or 1 Month

**Comment by red-avtovo** [comment]
@derDieDasJojo, I want to clarify a little bit. Timed messages are starting counting down on receiving side only after receiver saw a message. As soon as you sent a timed message you start counting down only on your device. After your counter reached 0, you see scratch, over your message and that means, that other side didn't read the message yet. After receiver read the message and his timer reach 0, message will disappear on both sides. Receiver can read a message even after 1 or 2 months and message will be still there

**Comment by derDieDasJojo** [comment]
thanks for the clarification.
still the option would be usefull.

**Comment by IpsmLorem** [comment]
Related to https://github.com/wireapp/wire-ios/issues/351 and https://github.com/wireapp/wire/issues/89

**Comment by makingthematrix** [comment]
The timed messages functionality was rewritten and now users are able to set them to "4 weeks". I think I can close the issue now? Please reopen if anything.
