### ISSUE TITLE
[Feature request] Support tall Android screens

### ISSUE THREAD

**Issue by Madis0** [wireapp/wire-android#1367]
[This blog post by Google explains everything.](https://android-developers.googleblog.com/2017/03/update-your-app-to-take-advantage-of.html) Thanks!

**Comment by zhangbao** [comment]
Great, I'm using Xiaomi Mix 2 with 18:9 hight/width raito, really need Wire to support tall screen.

**Comment by Madis0** [comment]
Implemented months ago.
