### ISSUE TITLE
Deleted group is archived — and everyone can still access all messages

### ISSUE THREAD

**Issue by x80486** [wireapp/wire-android#1369]
## The problem

I accidentally create a group with two contacts while my phone was unlocked. Then I "deleted" (by also leaving) it and I realized it was placed on the **Archive** list/section. I asked the other contacts to do the same, but still the group is not deleted on my Wire account, nor on their.

## Environment

* Wire version that exhibits the issue: 3.4.382
* Android OS version used to run Wire: 8.0.0
* Is this a custom firmware or a stock one: Stock Android
* Mobile phone model/manufacturer: Nexus 6P
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/Wi-Fi

## Details

1. Create a group — with two or more contacts.
2. Delete the group (and maybe ask the same to the group's participants) — additionally, check the **Leave Group** option
3. Go to the **Archive** list/section

The group is still there, although you can't type anything else, but still, the call/video options work. Moreover, the "three dots" menu in the bottom-right doesn't exhibit any option(s).

I think that, in general, Wire exhibits the same behavior when you try to delete a contact, or when a contact leaves (by deleting its account).

**Comment by BVollmerhaus** [comment]
I think this issue is already covered by #997 and #1263. Deleting things (be it chats or groups) not working properly has been a known bug for a while now that still needs to be addressed.

**Comment by someoneEsle** [comment]
As @BVollmerhaus said, this is a duplicate so I'll close it
