### ISSUE TITLE
Sailfish OS and a case for including TLS 1.2 support in the Wire App

### ISSUE THREAD

**Issue by pakman** [wireapp/wire-android#1370]
One of the reasons for using Wire is its stance on user privacy, which includes [such statements](https://wire.com/en/security/) as:

> Wire does not sell analytics or usage data to advertising companies or
> anyone else.

However, people who have chosen [Sailfish OS](https://sailfishos.org/) as their mobile platform because of [its stance on privacy](https://sailfishos.org/wiki/Security) (which is similar to Wire's) find that some of Wire's functionality is not available to them. Specifically, media such as images, videos and web page previews just appear as gray boxes. This incompatability within the privacy-respecting world strikes me as unfortunate.

The reasons for the missing functionality are well-understood, and discussed in issues #518, #760 and #830. Sailfish OS uses Alien Dalvik to allow Android apps to run. Alien Dalvik is based on Android versions 4.1-4.4.4 (depending on the exact device which Sailfish OS has been installed on). Alien Dalvik provides neither Google Cloud Messaging nor TLS version 1.2. However the fixes discussed in issues 518 and 760 are not applicable to the Sailfish OS/Alien Dalvik platform, because:

 * No update to Alien Dalvik corresponding to Android version 5 is available
 * Installing Google Play Services, while possible, is not supported. Doing this is also considered by a significant number of Sailfish users as incompatible with the privacy concerns that lie behind adopting Sailfish OS in the first place.

As noted in issue #870 (which is requesting the same as this issue, but for different reasons) it seems to be quite possible to include TLS 1.2 support in an app so that Google Play Services are not required to provide it on Android 4. Another example of this is the Android build of Firefox. Installing Firefox on Sailfish OS/Alien Dalvik and navigating to https://www.ssllabs.com/ssltest/viewMyClient.html displays a page that includes the following text:

> Your user agent has good protocol support.
> Your user agent supports TLS 1.2, which is recommended protocol version at the moment.

This shows that Firefox for Android is also built with TLS 1.2 support included, and does not depend on the underlying platform to provide it.

Please consider enabling people whose choice of platform reflects a similar attitude to privacy to yours, to use Wire on that platform.

**Comment by Invictaz** [comment]
I agree but this might make the app (much) bigger?
How did Signal or Threema do this?

**Comment by pakman** [comment]
Updating to the Jan 25 Wire app has stopped it working on Sailfish OS/Alien Dalvik altogether :cry:. I just get pop-ups saying "unfortunately Wire has stopped". I'll wait until the next update to see if this was caused by something inadvertent and it starts working again. If not, then this issue becomes moot and I'll close it.

**Comment by someoneEsle** [comment]
@pakman have you by any chance looked at the logs to see what's causing the crash for you?

**Comment by pakman** [comment]
@someoneEsle I'm really busy for the next few days, but I will get around to creating s new issue for this breakage.

**Comment by pakman** [comment]
I am closing this issue now because including TLS v1.2 support directly in the Android app is no longer sufficient to use Wire on Sailfish OS. I am no longer recommending Wire to anyone, and have asked my main Wire correspondents to switch to other messaging systems. Here's hoping that my new issue #1437 will help to see Wire on Sailfish OS become possible once again later this year.
