### ISSUE TITLE
Wire always on bottom in some share bottom sheets

### ISSUE THREAD

**Issue by meeDamian** [wireapp/wire-android#1374]
## The problem

While sharing from some apps, Wire icon is placed as the sole occupant of the bottom row.

## Environment

* Wire version that exhibits the issue: All I ever used, but screenshot taken from **3.5.387**
* Android OS version used to run Wire: **8.1**
* Is this a custom firmware or a stock one: **stock**
* Mobile phone model/manufacturer: Google Pixel, **Google Pixel 2**

## Details

Easiest way to observe it is through Chrome custom tabs, so:
1. Open twitter,
2. find tweet with an url,
3. tap url
4. select three dots menu & "Share via…"
5. See Wire alone on the bottom 😢

## Screenshots

![screenshot_20180112-204308](https://user-images.githubusercontent.com/526657/34877751-e9b17f5c-f7d9-11e7-9fd9-7475e4bf06c1.png)

**Comment by someoneEsle** [comment]
Hi, thanks for reporting, but it definitely looks like a bug with Android, not us. It looks like the apps are simply sorted in alphabetical order, but we don't have control over where Wire should appear. I'll close this issue for now, unless other people report this same issue. (Just a thought, maybe that empty spot has something to do with Wikipedia? If a non-beta version of Wikipedia were installed on your phone, it would appear in the empty spot. But to be honest I don't know)
