### ISSUE TITLE
Notification malfunctioning on Android 8.0

### ISSUE THREAD

**Issue by zhangbao** [wireapp/wire-android#1375]
The problem

After updating My Xiaomi Mix 2 from Android 7.1 to 8.0, notification of Wire became malfunction. When I receive any notification from wire contact while unlocked, the heads-up notification first showed up and disappeared instantly, while heads-up notification from other application act normally.

## Environment

* Wire version that exhibits the issue: 3.5.387
* Android OS version used to run Wire: 8.0
* Is this a custom firmware or a stock one: stock MIUI9 8.1.11
* Mobile phone model/manufacturer: Xiaomi Mix 2
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): WiFi/LTE

**Comment by red-avtovo** [comment]
@zhangbao, do you have anywhere another instance of the Wire app opened at the time, you receive notification? Webapp/Wrapper/another Android/iOS?

**Comment by zhangbao** [comment]
No, I only logged 1 account. This case only happened in my Android 8.0 cellphone.

**Comment by hub-ch** [comment]
https://github.com/wireapp/wire-android/issues/777#issuecomment-466763316

**Comment by marcoconti83** [comment]
Hi all,
there are a lot of duplicated issues covering this same problem (or a very similar one), let's unify all conversations and keep it going here: #777 . Closing this one and continuing there.
