### ISSUE TITLE
Introduce @mentions

### ISSUE THREAD

**Issue by fllp** [wireapp/wire-android#1377]
## The problem

In a group chat it can get busy at times. With a mention mechanism like the one used in IRC, one could e.g. answer to someones earlier message without interrupting the topic currently talked about.
Also, a @mention could be used to 'ping' one person only, instead of the whole group.

## Environment

* Wire version that exhibits the issue: 3.4.382 
* Last Wire version that did not exhibit the issue (if applicable): n/a
* Android OS version used to run Wire: 7.1.2
* Is this a custom firmware or a stock one: custom
* Mobile phone model/manufacturer: n/a
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): n/a

**Comment by someoneEsle** [comment]
duplicate of #778 , you can upvote that issue :)

**Comment by fllp** [comment]
Done :)
