### ISSUE TITLE
Login form displayed only partially

### ISSUE THREAD

**Issue by nedaandric** [wireapp/wire-android#1386]
## The problem

When trying to log in I cannot see the whole login form because I am unable to scroll down.

## Environment

* Wire version that exhibits the issue: 3.4.382
* Android OS version used to run Wire: 5.1.1
* Is this a custom firmware or a stock one: Stock
* Mobile phone model/manufacturer: Samsung Galaxy Core Prime
* Screen resolution: 480 x 800 pixels

I don't have that problem on the Huawei P9 lite with Android OS version 7.0 .

## Screenshots

![wire 2018-01-25 at 17 03 14](https://user-images.githubusercontent.com/7448192/35401572-3483f0f8-01fa-11e8-83d9-a2d47e835a47.png)

**Comment by someoneEsle** [comment]
Hi, could you please update your Wire app and get back to us if you still experience this issue? This looks like an old bug we fixed. Current version in the play store is 3.6.391. Thanks :)

**Comment by nedaandric** [comment]
Sorry for not checking if I'm using the latest version. Everything works like a charm now. :)
