### ISSUE TITLE
Suggestion: Help new user to add contacts on empty conversation list

### ISSUE THREAD

**Issue by ShawnPConroy** [wireapp/wire-android#1387]
## The problem

A number of times I have had to instruct people how to add their first contact. The main screen directs the user to add a contact, but some people don't realize they have to tap the contact silhouette icon at the bottom left, since it's so small and out of the way.

## Recommendation

1. Append to the text information about tapping the contact silhouette icon at the bottom left of the screen.
2. When the conversation list is empty, default to the contacts screen.

This should help the minority of users who cannot figure it out, and would greatly improve first impressions with Wire.

**Comment by someoneEsle** [comment]
Hi, interesting that you mentioned this because we've recently been working on the landing page for users who have no conversations yet :) Now they will see a big arrow and a message instructing them to tap the contacts icon.
Thanks for your feedback!
