### ISSUE TITLE
App: huge issues with in-built camera performance and quality- use the usual phone camera app!

### ISSUE THREAD

**Issue by zumbatan** [wireapp/wire-android#1391]
HI Wire!
Nice app! but really, please eliminate this highly disturbing usability flaw:
a) Description:
open Wire, click on one contact, and try to make a photo by clicking on Wire's camera symbol, send this photo to your contact.

b) Expected results:
After clicking on the camera, the USUAL (as if i would open the camera normally, outside of Wire) camera screen appears. You make a photo and then are able to decide to send this one to the contact, or make another one.

c) Currently flawed situation:

Your camera app is opening WITHIN Wire and even within the chat view, this makes the camera screen VERY VERY SMALL!!! because of this, made photos are highly flawed and not in best quality as they would be with the usual camera app! Why did you even implement such a thing?  Not any other chat program uses such micro-size camera screen.  You can proof that photo quality is disturbed by it.

Please act swiftly i am not sure how much of development effort this change will be? Please enlighten us about your opinion on this and when you might take it on?   I bet every 2nd person is annoyed by this.

Thank youuu:)

@someoneEsle   @red-avtovo

**Comment by luciusbono** [comment]
FYI: you can get a full screen camera preview by pressing the camera icon to the left of the shutter button in the preview window. 

![image](https://user-images.githubusercontent.com/5789441/35537302-924bda78-04fe-11e8-829b-5ab7943671c2.png)

**Comment by someoneEsle** [comment]
Hi @zumbatan, thanks for raising this issue. The current behavior of the camera is a design decision that is unlikely to change soon. However, as @luciusbono pointed out you can expand the camera view, so that should solve your problem :)
