### ISSUE TITLE
Sending detailed debug report from Wireapp

### ISSUE THREAD

**Issue by repox18** [wireapp/wire-android#1402]
Sending detailed debug report from Wire.

Why don't you create officially supported "Wire Swiss GmbH" account (e.g. @debugreport). That way people would be able to send "bugreports" to you with little to no effort, using wireapp directly.

Current way: 

Go to Settings -> About

Tap "Wire swiss GmbH" 10 times

Reproduce your issue

Send the report from Settings -> Advanced -> Submit debug report

Go to Settings -> About

Tap "Wire swiss GmbH" 10 times again to disable detailed debug reports, because this slows down Wire

It's good but not as time efficient as this one could've been.

BTW you should implement some √ "tick" after tapping 10 times (or some kind of notification, like it's done when developer mode is activated in Android phone). Because it's hard to say when debugging mode is on or off.

Just an idea.

**Comment by FaizKhan5** [comment]
.

**Comment by ganego** [comment]
Fun fact:
The "Current way:" will not work as the tap 10x does nothing for some time now. I reported that some weeks ago but it was not changed.

**Comment by repox18** [comment]
What's the best way of getting logs while reproducing issues for now ?

**Comment by someoneEsle** [comment]
The detailed logging has been temporarily disabled -- but if you tap the version number multiple times you still get to see some additional information regarding your build.
For now you can just send normal logs.
