### ISSUE TITLE
Wire Crashed on Tablet

### ISSUE THREAD

**Issue by gui-milky** [wireapp/wire-android#1404]
## The problem

Wire Crashed when ping. And sometimes when sending files.
It especially crashed when you ping someone.

## Environment

Samsung Galaxy Tab S2 ( Android 7.0 )

## Details

- Ping Someone.
- Crashed
- Now you Can't chat with that someone because when you open chat it crashed
- Delete chat to stop crashing
(Tested with my mom tablet and my phone. although my phone works without crash)

## Link to Debug logs

https://gist.github.com/gui-milky/c9e3d1d5dd0a630394e7f50ef61c7175

## Note
Why don't wire save debug file directly to file manager ? I have hard time sending debug file to PC
Had to remove wire from tablet as it is unusable

**Comment by someoneEsle** [comment]
Should be fixed now, feel free to reopen if it's still happening
