### ISSUE TITLE
Wire 3.6.391 blocks control of phone in-call volume changing it to Bluetooth control.

### ISSUE THREAD

**Issue by Amp3rwater** [wireapp/wire-android#1410]
## The problem

I took me week to find it out what is causing such issue by freezing apps one by one on my  Lineage-14.1.
Since 3.6.391 wire blocks control of in-call phone volume changing it to Bluetooth control (small bt icon next to handset during call) even though Bluetooth is completely switched off. In-call volume always stays on the same level even though it is moved to the minimum level.

## Environment

* Wire version that exhibits the issue: 3.6.391
* Last Wire version that did not exhibit the issue (if applicable): 3.4.382
* Android OS version used to run Wire: 7.1.2
* Is this a custom firmware or a stock one: Custom Lineage-14.1
* Mobile phone model/manufacturer: One Plus X
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE

## Details

Install/unfreeze and use chat on Wire.

## Link to Debug logs

https://gist.github.com/Amp3rwater/54e55e0ed8c3584ecc91b4f859d2d877

## Screenshots

![screenshot_20180208-102031](https://user-images.githubusercontent.com/15289349/35985397-dd21b928-0cf6-11e8-8e5a-5b69666f59d7.png)
![screenshot_20180208-102039](https://user-images.githubusercontent.com/15289349/35985398-dd457d36-0cf6-11e8-96a7-38b68e98827d.png)

**Comment by someoneEsle** [comment]
Hey, thanks for reporting this issue. We are currently testing some fixes related to the bug you posted, and they have been released to the beta channel. If you feel like it, you can join here (https://play.google.com/apps/testing/com.wire) and let us know if the bug is fixed/not fixed for you :)

**Comment by fllp** [comment]
Wow this is a great catch! I was wondering what caused this.
Having the same issue on OMNI/7.1.2. It even happens when the phone permission is withdrawn.

@someoneEsle:  any chance the beta program will be made available outside of Google Play?
I'd very much like help testing but requiring Google Play is a blocker for me.

**Comment by Amp3rwater** [comment]
@someoneEsle 
I am testing it for 3 hours and so far so good. Thank you for quick response.

**Comment by someoneEsle** [comment]
@Amp3rwater thank you for letting us know it works!
@fllp unfortunately not in the plans for now. Using the google play store to manage the beta program is very easy/effortless and it allows us to reach a very large number of users, so at this point it makes little sense to set up another beta program elsewhere.

**Comment by fllp** [comment]
Thank you for the info and the quick fix!
