### ISSUE TITLE
Notifications force phone into call mode when using bluetooth

### ISSUE THREAD

**Issue by Tautvis** [wireapp/wire-android#1423]
## The problem

When app is active (or in background) and connecting with Bluetooth headphones (I tried with Bose QC 35 gen 1) headphones are forced into call mode. 

This prevents other apps from sending audio to headphones.

After killing the wire app, headphones exit call mode and Bose headphones state "Call ended".
Opening wire app again doesn't cause call mode. Sometimes notifications cause call mode.

## Environment

* Wire version that exhibits the issue: 3.6.391
* Last Wire version that did not exhibit the issue (if applicable): don't know
* Android OS version used to run Wire: 8.1
* Is this a custom firmware or a stock one: stock
* Mobile phone model/manufacturer: Pixel 2
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): All

## Details

1. Open wire app
2. Go to home screen
3. Turn on headphones
4. Headphones will be in call mode
5. Kill wire app
6. Headphones exit call mode

**Comment by someoneEsle** [comment]
Hi, some of the issues related to bluetooth headphones have been addressed and are currently being tested in the beta channel. If you want, you can join [here](https://play.google.com/apps/testing/com.wire) and let us know if you still experience the problem.

**Comment by Tautvis** [comment]
Hi, I can't reproduce the issue on beta app. Seems to be fixed. Thanks!
