### ISSUE TITLE
Sending more images at once

### ISSUE THREAD

**Issue by fbruetting** [wireapp/wire-android#1429]
Now Wire exists for quite a while, but it still isn’t capable of fulfilling ubiquitous standard features, like sending more pictures at once. Why do you actually spend your time on hipster stuff, instead of fixing core problems? There are LOTS(!) of bugs and clearly obvious shortcommings in the program, but somehow they never get fixed…?! I think I even pointed that (among several other faults) out via E-Mail moths ago, but nothing happend. Please fix your faults finally!

**Comment by someoneEsle** [comment]
Hi, thanks for reporting. If you want to send multiple pictures at once you can go to your gallery, select multiple pictures, tap share and send them through Wire.
If this isn't possible for you or if it is not working properly, feel free to reopen the issue. Thanks!
