### ISSUE TITLE
[Bug] Who added whom at which point in time?

### ISSUE THREAD

**Issue by LGro** [wireapp/wire-android#143]
Let X create a group and add Y, Z as group members then a status message in the chat history correctly states "X added Y, Z".
When now Y adds another person W it correctly states "Y added W" but also the previous status message "X added Y, Z" way back in the chat history changes into "X added Y, Z, W".

In that case all users had Android devices.

**Comment by shumengye** [comment]
Clarification: this issue happens for user Y

**Comment by makingthematrix** [comment]
Hi.

This issue is very old and I decided to close it (we're trying to clean up our GitHub issues). 
We made lots of changes to notifications and system messages since them.
If you think this is still relevant, please open a new ticket.

Cheers,
