### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by davidaxing** [wireapp/wire-android#1432]
Error:(272) value LOGIN in object KindOfAccess is deprecated: see corresponding Javadoc for more information.

Error:(22) Unused import

**Comment by JasmineCode** [comment]
The same problem

**Comment by marcoconti83** [comment]
Hi @davidaxing ,
Thanks for reporting this. Are you getting these errors while building the app? The code has changed quite a while since the time you open the issue, can you try again now? Thanks!

**Comment by makingthematrix** [comment]
That old code was removed.
