### ISSUE TITLE
Switch to TLS 1.2 only breaks all Android 4.x devices

### ISSUE THREAD

**Issue by nidico** [wireapp/wire-android#1450]
As communicated via Twitter ([here](https://twitter.com/wire/status/966964532857004032) and [there](https://twitter.com/wire/status/966976138567446528)), Wire stopped supporting TLS<1.2 and thus stopped supporting Android 4.x.

This is a breaking change for many users, as it basically makes Wire usage impossible for them, as you cannot just upgrade Android with many phones, but rather throw it away and buy a new one :(

I'd expect that a move with such high breakage rate would be communicated more clearly.

Wire support says that Wire would still work on devices with Google Play services. How does this work? Of course this doesn't help all those privacy-aware people which install Wire without Google on purpose.

As this is a quite drastic change, is there any hope that #870 will be worked on, so Android 4.x devices will work fine again?

Thanks for taking this issue seriously!

**Comment by someoneEsle** [comment]
Hi, thank you for your feedback.
Unfortunately, upgrading to TLSv1.2 was a necessary step to increase the security of the communications between our servers and the clients, and it is not really something we are open to reconsider. As with all decisions that involve dropping support for older versions of something, there will be people whose devices will be left behind. However, given the gains in terms of security and given the very small number of people that will lose support, we made the decision to upgrade. Know that we're not alone in dropping support for TLS pre-1.2, as [Github itself has done the same](https://githubengineering.com/crypto-removal-notice/).
On top of all these reasons, Android 4.x phones are quite old devices that most likely are not receiving any security updates from their manufacturers, so if you are a "privacy-aware" user I would recommend getting something more recent (Android 5 came out in 2014).
We're sorry if you felt like you were left behind, but please understand that this decision was taken with security in mind as the most important factor.

**Comment by nidico** [comment]
Thanks for your reply. Could you please also quickly elaborate on whether and how Wire on Android 4.x devices and active Google Play services still works, and also say something about #870?

**Comment by someoneEsle** [comment]
It results from our tests that Wire on Android 4.x with GPS still works, but it does not when GPS are not installed. It looks like Google provides system libraries that support TLS 1.2.
