### ISSUE TITLE
Not able to build on command line with debian or arch linux

### ISSUE THREAD

**Issue by AlmightyFrog** [wireapp/wire-android#146]
I did want to build wire-android on my own machine, but can't get it working. In the end i want to be able to do a jenkins job like @zbsz seems to have running. Problem is always the same at building :app

> $ ./gradlew assembleProdRelease
> To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.13/userguide/gradle_daemon.html.
> KEEP_SPECS patched: removed 'activity' root
> KEEP_SPECS patched: removed 'instrumentation' root
> KEEP_SPECS patched: removed 'service' root
> Failed to patch KEEP_SPECS: no 'activity' root found
> Failed to patch KEEP_SPECS: no 'instrumentation' root found
> Failed to patch KEEP_SPECS: no 'service' root found
> Build tools 23.0.3 missing. Downloading...
> 
> FAILURE: Build failed with an exception.
> 
> What went wrong:
> A problem occurred configuring project ':app'.
> 
> > failed to find Build Tools revision 23.0.3
> 
> Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Command gradlew does pull its own android-sdk into homefolder which is ok and working.
By installing about _everything_ with  `~/.android-sdk/tools/android update sdk -u` (which is bloaty as hell) it is going firther to another error

> $ ./gradlew assembleProdRelease
> To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.13/userguide/gradle_daemon.html.
> KEEP_SPECS patched: removed 'activity' root
> KEEP_SPECS patched: removed 'instrumentation' root
> KEEP_SPECS patched: removed 'service' root
> Failed to patch KEEP_SPECS: no 'activity' root found
> Failed to patch KEEP_SPECS: no 'instrumentation' root found
> Failed to patch KEEP_SPECS: no 'service' root found
> 
> FAILURE: Build failed with an exception.
> 
> What went wrong:
> A problem occurred configuring project ':app'.
> 
> > A problem occurred configuring project ':wire-core'.
> > Could not resolve all dependencies for configuration ':wire-core:_debugCompile'.
> >       > Could not find com.wire.avs:avs:2.8.61.
> >         Searched in the following locations:
> >             https://jcenter.bintray.com/com/wire/avs/avs/2.8.61/avs-2.8.61.pom
> >             https://jcenter.bintray.com/com/wire/avs/avs/2.8.61/avs-2.8.61.aar
> >             file:/var/lib/jenkins/.m2/repository/com/wire/avs/avs/2.8.61/avs-2.8.61.pom
> >             file:/var/lib/jenkins/.m2/repository/com/wire/avs/avs/2.8.61/avs-2.8.61.aar
> >             https://dl.bintray.com/wire-android/releases/com/wire/avs/avs/2.8.61/avs-2.8.61.pom
> >             https://dl.bintray.com/wire-android/releases/com/wire/avs/avs/2.8.61/avs-2.8.61.aar
> >             https://dl.bintray.com/wire-android/snapshots/com/wire/avs/avs/2.8.61/avs-2.8.61.pom
> >             https://dl.bintray.com/wire-android/snapshots/com/wire/avs/avs/2.8.61/avs-2.8.61.aar
> >             https://dl.bintray.com/wire-android/third-party/com/wire/avs/avs/2.8.61/avs-2.8.61.pom
> >             https://dl.bintray.com/wire-android/third-party/com/wire/avs/avs/2.8.61/avs-2.8.61.aar
> >             http://dl.bintray.com/consp1racy/maven/com/wire/avs/avs/2.8.61/avs-2.8.61.pom
> >             http://dl.bintray.com/consp1racy/maven/com/wire/avs/avs/2.8.61/avs-2.8.61.aar
> >             http://maven.localytics.com/public/com/wire/avs/avs/2.8.61/avs-2.8.61.pom
> >             http://maven.localytics.com/public/com/wire/avs/avs/2.8.61/avs-2.8.61.aar
> >             https://repo1.maven.org/maven2/com/wire/avs/avs/2.8.61/avs-2.8.61.pom
> >             https://repo1.maven.org/maven2/com/wire/avs/avs/2.8.61/avs-2.8.61.aar
> >             file:/var/lib/jenkins/.android-sdk/extras/android/m2repository/com/wire/avs/avs/2.8.61/avs-2.8.61.pom
> >             file:/var/lib/jenkins/.android-sdk/extras/android/m2repository/com/wire/avs/avs/2.8.61/avs-2.8.61.aar
> >             file:/var/lib/jenkins/.android-sdk/extras/google/m2repository/com/wire/avs/avs/2.8.61/avs-2.8.61.pom
> >             file:/var/lib/jenkins/.android-sdk/extras/google/m2repository/com/wire/avs/avs/2.8.61/avs-2.8.61.aar
> >         Required by:
> >             zclient-root:wire-core:unspecified

Could someone please help me getting it working? Debian is running inside docker container, so if i could manage to get it running properly i would put that config on github in exchange.

**Comment by zbsz** [comment]
My first suggestion would be to not rely on gradlew to download android sdk, try installing it yourself and setting ANDROID_HOME variable before running gradle. That's what we do.

And about second issue (with avs), that was a bug in our config (wrong artifact group id), it's fixed now, so just checkout latest version.

**Comment by AlmightyFrog** [comment]
Ah ok fine - just ran the jop again a some minutes ago, now it goes much further and stops at following point:
> :wire-core:compileReleaseJavaWithJavac/var/lib/jenkins/workspace/wire-android/wire-core/src/main/java/com/waz/zclient/core/api/scala/ScalaPickUserStore.java:95: error: cannot find symbol
>         connectionsResults = zMessagingApi.search().getConnectionsByNameOrEmailIncludingBlocked(searchTerm, numberOfResults, excludes);
>                                                    ^
>   symbol:   method getConnectionsByNameOrEmailIncludingBlocked(String,int,String[])
>   location: interface Search
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 1 error
>  FAILED
> 
> FAILURE: Build failed with an exception.
> 
> What went wrong:
> Execution failed for task ':wire-core:compileReleaseJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
Is that also a problem on my side or is it currently just not compiling properly?

**Comment by zbsz** [comment]
Right, this is because of api changes in latest dev sync engine library, only dev builds can be run on master at the moment, as there is no matching release for sync engine yet.
To avoid those problems I suggest to build from release branch, the latest one is: https://github.com/wireapp/wire-android/tree/rel/2.15.x

**Comment by someoneEsle** [comment]
I still have very similar problems when building on the release branch...

**Comment by NetPr** [comment]
Hello,
This issue able close now. No known build errors or major app issues regardless reported bugs on repository. 
Follow instruction here https://github.com/wireapp/wire-android/issues/1892 a certain avs issue fixed few days ago.

If you met any problem during any additional improvement, ask us. we or wire may possible to help.

**Comment by marcoconti83** [comment]
Hi all,
This issue is quite old and the project has change substantially since then. I'll close this issue an I believe it's solved now, please feel free to reopen if it still a problem for you.
