### ISSUE TITLE
[Feature Request] mark as read functionality

### ISSUE THREAD

**Issue by madLyfe** [wireapp/wire-android#1469]
wire version: 3.8.4.12
android: stock 8.1 march security update
phone: P2XL

is it possible to have the ability when you swipe away a notification manually that it is treated as 'mark as read'. or maybe in the dropdown where the call and reply option are add 'mark as read'? no joke, im requesting this because i had a friend on a PXL with stock android quit the app because there was no 'mark as read' option like signal has and that it was crashing and slow all the time. 
¯\_(ツ)_/¯

**Comment by someoneEsle** [comment]
duplicate https://github.com/wireapp/wire-android/issues/822
