### ISSUE TITLE
Wire UI

### ISSUE THREAD

**Issue by pixelbendr** [wireapp/wire-android#147]
Can I import wire-ui as a gradle plugin or I have to add it as a module to my own project?

**Comment by zbsz** [comment]
Not sure what you mean. You can import whole wire-android as gradle project in Android Studio. Just make sure not to allow it to update the gradle plugin on first start.

**Comment by pixelbendr** [comment]
I have already done that. I just want the UI part of wire to hook up to my own backend. Get it?

**Comment by zbsz** [comment]
wire-ui module only contains couple utils, it's not the whole wire app.
I don't see how you would connect that code to your own backend.

**Comment by pixelbendr** [comment]
Okay. Thank you. 😥😅
