### ISSUE TITLE
run sbt publishM2 errors

### ISSUE THREAD

**Issue by davidaxing** [wireapp/wire-android#1473]
C:\Users\Thinkpad\.android\sbt\sdk\platforms\android-24\android.jar(java/lang/annotation/Retention.class): 主版本 52 比 51 新, 此编译器支持最新的主版本。
  建议升级此编译器。
C:\Users\Thinkpad\.android\sbt\sdk\platforms\android-24\android.jar(java/lang/annotation/RetentionPolicy.class): 主版本 52 比 51 新, 此编译器支持最新的主版本。
  建议升级此编译器。
C:\Users\Thinkpad\.android\sbt\sdk\platforms\android-24\android.jar(java/lang/annotation/Target.class): 主版本 52 比 51 新, 此编译器支持最新的主版本。
  建议升级此编译器。
C:\Users\Thinkpad\.android\sbt\sdk\platforms\android-24\android.jar(java/lang/annotation/ElementType.class): 主版本 52 比 51 新, 此编译器支持最新的主版本。
  建议升级此编译器。
C:\Users\Thinkpad\.android\sbt\sdk\platforms\android-24\android.jar(java/lang/Object.class): 主版本 52 比 51 新, 此编译器支持最新的主版本。
  建议升级此编译器。
C:\Users\Thinkpad\.android\sbt\sdk\platforms\android-24\android.jar(java/lang/String.class): 主版本 52 比 51 新, 此编译器支持最新的主版本。
  建议升级此编译器。
C:\Users\Thinkpad\.android\sbt\sdk\platforms\android-24\android.jar(java/io/Serializable.class): 主版本 52 比 51 新, 此编译器支持最新的主版本。
  建议升级此编译器。
C:\Users\Thinkpad\.android\sbt\sdk\platforms\android-24\android.jar(java/lang/Comparable.class): 主版本 52 比 51 新, 此编译器支持最新的主版本。
  建议升级此编译器。
C:\Users\Thinkpad\.android\sbt\sdk\platforms\android-24\android.jar(java/lang/CharSequence.class): 主版本 52 比 51 新, 此编译器支持最新的主版本。
  建议升级此编译器。
C:\Users\Thinkpad\.android\sbt\sdk\platforms\android-24\android.jar(java/lang/Number.class): 主版本 52 比 51 新, 此编译器支持最新的主版本。
  建议升级此编译器。
C:\Users\Thinkpad\.android\sbt\sdk\platforms\android-24\android.jar(java/nio/ByteBuffer.class): 主版本 52 比 51 新, 此编译器支持最新的主版本。
  建议升级此编译器。
C:\Users\Thinkpad\.android\sbt\sdk\platforms\android-24\android.jar(java/nio/Buffer.class): 主版本 52 比 51 新, 此编译器支持最新的主版本。
  建议升级此编译器。
C:\Users\Thinkpad\.android\sbt\sdk\platforms\android-24\android.jar(java/nio/IntBuffer.class): 主版本 52 比 51 新, 此编译器支持最新的主版本。
  建议升级此编译器。
C:\Users\Thinkpad\.android\sbt\sdk\platforms\android-24\android.jar(java/lang/Throwable.class): 主版本 52 比 51 新, 此编译器支持最新的主版本。
  建议升级此编译器。
C:\Users\Thinkpad\.android\sbt\sdk\platforms\android-24\android.jar(java/lang/Class.class): 主版本 52 比 51 新, 此编译器支持最新的主版本。
  建议升级此编译器。
[info] Executing NDK build
Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-14.
Android NDK: WARNING:C:\D\wire\master\sync\develop\wire-android-sync-engine-develop\zmessaging\src\main\jni\../jni/Android.mk:randombytes: non-system libraries in linker flags: src/main/jni/armeabi-v7a/libsodium.so
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the
Android NDK:     current module
Android NDK: WARNING:C:\D\wire\master\sync\develop\wire-android-sync-engine-develop\zmessaging\src\main\jni\../jni/Android.mk:randombytes: non-system libraries in linker flags: src/main/jni/x86/libsodium.so
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the
Android NDK:     current module
[armeabi-v7a] "Gdbserver      ": "[arm-linux-androideabi] C:\D\wire\master\sync\develop\wire-android-sync-engine-develop\zmessaging\target\android\intermediates\ndk\jni/armeabi-v7a/gdbserver"
[armeabi-v7a] "Gdbsetup       ": "C:\D\wire\master\sync\develop\wire-android-sync-engine-develop\zmessaging\target\android\intermediates\ndk\jni/armeabi-v7a/gdb.setup"
[x86] "Gdbserver      ": "[i686-linux-android] C:\D\wire\master\sync\develop\wire-android-sync-engine-develop\zmessaging\target\android\intermediates\ndk\jni/x86/gdbserver"
[x86] "Gdbsetup       ": "C:\D\wire\master\sync\develop\wire-android-sync-engine-develop\zmessaging\target\android\intermediates\ndk\jni/x86/gdb.setup"
[armeabi-v7a] "Compile++ thumb": "lzw-decoder <= LzwDecoder.cpp"
process_begin: CreateProcess(NULL, C:/Users/Thinkpad/.android/sbt/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -MMD -MP -MF C:\D\wire\master\sync\develop\wire-android-sync-engine-develop\zme
ssaging\target\android\intermediates\ndk\obj/local/armeabi-v7a/objs-debug/lzw-decoder/LzwDecoder.o.d -gcc-toolchain C:/Users/Thinkpad/.android/sbt/sdk/ndk-bundle/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-
x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -g -target armv7-none-linux-androideabi14
 -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-exceptions -fno-rtti -mthumb -O0 -UNDEBUG -fno-limit-debug-info -IC:/Users/Thinkpad/.android/sbt/sdk/ndk-bundle/build//../sources/cxx-stl/system/include -IC:/D/wire/maste
r/sync/develop/wire-android-sync-engine-develop/zmessaging/src/main/jni/../jni -DANDROID -O2 -Wall -pedantic -Wno-variadic-macros -fstack-protector-all -D__ANDROID_API__=14 -Wa,--noexecstack -Wformat -Werror=format-security --
sysroot C:/Users/Thinkpad/.android/sbt/sdk/ndk-bundle/build//../sysroot -isystem C:/Users/Thinkpad/.android/sbt/sdk/ndk-bundle/build//../sysroot/usr/include/arm-linux-androideabi -c C:/D/wire/master/sync/develop/wire-android-s
ync-engine-develop/zmessaging/src/main/jni/../jni/LzwDecoder.cpp -o C:\D\wire\master\sync\develop\wire-android-sync-engine-develop\zmessaging\target\android\intermediates\ndk\obj/local/armeabi-v7a/objs-debug/lzw-decoder/LzwDec
oder.o, ...) failed.
make (e=2): 系统找不到指定的文件。
make: *** [C:\D\wire\master\sync\develop\wire-android-sync-engine-develop\zmessaging\target\android\intermediates\ndk\obj/local/armeabi-v7a/objs-debug/lzw-decoder/LzwDecoder.o] Error 2
[error] ndk-build failed!
[error] (zmessaging/android:ndkBuild) ndk-build failed!
[error] Total time: 27 s, completed 2018-3-15 14:59:34

**Comment by red-avtovo** [comment]
Hi @davidaxing, many thanks for your issue.
According to your inactivity in the ticket, you found the solution or workaround but didn't post it here.
Anyway, feel free to reopen this issue if it still occurs.
