### ISSUE TITLE
"Ghost" Devices

### ISSUE THREAD

**Issue by Da0012** [wireapp/wire-android#1476]
## The problem
My smartphone shows 4 devices that my other devices doesn't shows.
I have one phone and two desktop Wire.
Those "ghost" devices doesn't have fingerprint and i can't logout or reset its sections.
## Environment

* Wire version that exhibits the issue: 3.8.412
* Last Wire version that did not exhibit the issue (if applicable):
* Android OS version used to run Wire:7.1.2 
* Is this a custom firmware or a stock one:Custom LineageOs 14.1
* Mobile phone model/manufacturer: Moto G (falcon)
* Mobile network type (EDGE/LTE/Wi-Fi/Offline):Wifi

## How to send detailed debug report from Wire:

Tap "Wire swiss GmbH" 10 times Doesn't work

## Screenshots

![screenshot_20180313-185519](https://user-images.githubusercontent.com/27793171/37495974-f03ae51e-287d-11e8-8bce-1680bbd73530.png)

![screenshot_20180313-190427](https://user-images.githubusercontent.com/27793171/37495720-a20c95dc-287c-11e8-9b11-988eb8541576.png)
![captura de pantalla de 2018-03-15 18-14-13](https://user-images.githubusercontent.com/27793171/37495756-d58d7a7a-287c-11e8-8ba8-1d52553fb7f0.png)

**Comment by someoneEsle** [comment]
What happens if you tap "quitar dispositivo" and enter your password to remove those devices?

**Comment by red-avtovo** [comment]
Hi @Da0012 ! We made some changes in a code. Is this issue still reproducible on your device on latest version of Wire?

**Comment by Da0012** [comment]
I haven't seen this bug a month+ ago ;) , i wrote this issue on github and those devices disappeared.
I don't know why.

**Comment by red-avtovo** [comment]
Thank you @Da0012 for the issue.
We are not experiencing this issue anymore. If it will happen to you again, feel free to open this issue again
