### ISSUE TITLE
video/audio call fail

### ISSUE THREAD

**Issue by ogiright123** [wireapp/wire-android#1481]
## The problem

i built wire android branch release  repo in android studio and command(gradlew).
it was okay.
But when i call video/audio , wire app is stopeed.

## Environment
wire version is latest branch release
android version is 6.0 and 4.4
api version is 23 and 19
mobile type is samsung s5 and emulator
mobile network is wifi

## Details

Describe the steps necessary to reproduce the problem in more details. The detailed description
will help us to fix the issue faster.

## Link to Debug logs

03-19 16:03:35.909 1920-1953/com.wire.avs D/AudioRecordJni: AttachAudioBuffer
03-19 16:03:35.909 1920-1953/com.wire.avs D/AudioRecordJni: SetRecordingSampleRate(44100)
03-19 16:03:35.909 1920-1953/com.wire.avs D/AudioRecordJni: SetRecordingChannels(1)
03-19 16:03:35.909 1920-1953/com.wire.avs D/AudioRecordJni: total_delay_in_milliseconds: 150
03-19 16:03:35.909 1920-1953/com.wire.avs D/AudioManager: Init@[tid=1953]
03-19 16:03:35.909 1920-1953/com.wire.avs I/org.webrtc.Logging: WebRtcAudioManager: init@[name=Thread-521, id=521]
03-19 16:03:35.909 1920-1953/com.wire.avs I/org.webrtc.Logging: WebRtcAudioManager: audio mode is: MODE_IN_COMMUNICATION
03-19 16:03:35.909 1920-1953/com.wire.avs D/AudioTrackJni: Init@[tid=1953]
03-19 16:03:35.909 1920-1953/com.wire.avs D/AudioRecordJni: Init@[tid=1953]
03-19 16:03:35.909 1920-1953/com.wire.avs E/AVS: ERROR     ; (16: 3:35:914 |    0) AUDIO DEVICE:    1    99;      1953; stereo playout is not supported
03-19 16:03:35.909 1920-1953/com.wire.avs W/AVS: WARNING   ; (16: 3:35:914 |    0)        VOICE:    1    99;      1953; Init() failed to set mono/stereo playout mode (error=8090)
03-19 16:03:35.909 1920-1953/com.wire.avs E/AVS: ERROR     ; (16: 3:35:914 |    0) AUDIO DEVICE:    1    99;      1953; failed to enable stereo recording
03-19 16:03:35.909 1920-1953/com.wire.avs W/AVS: WARNING   ; (16: 3:35:914 |    0)        VOICE:    1    99;      1953; Init() failed to set mono/stereo recording mode (error=8090)

**Comment by camdit** [comment]
I have the same issue:

Release Branch 3.9
Android Version 8.0
min API version 21
Pixel xl 2



03-26 23:06:19.030 26614-26650/com.wire W/MediaPlayer: Use of stream types is deprecated for operations other than volume control
03-26 23:06:19.030 26614-26650/com.wire W/MediaPlayer: See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-26 23:06:19.033 26614-26650/com.wire V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
03-26 23:06:19.033 26614-26650/com.wire V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
03-26 23:06:19.035 26614-26614/com.wire W/Notification: Use of stream types is deprecated for operations other than volume control
03-26 23:06:19.035 26614-26614/com.wire W/Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-26 23:06:19.041 26614-26650/com.wire W/MediaPlayer: Use of stream types is deprecated for operations other than volume control
03-26 23:06:19.041 26614-26650/com.wire W/MediaPlayer: See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-26 23:06:19.072 26614-26614/com.wire W/Notification: Use of stream types is deprecated for operations other than volume control
03-26 23:06:19.072 26614-26614/com.wire W/Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-26 23:06:19.355 26614-26713/com.wire D/FlowManager: getVideoCaptureDevices: 2
03-26 23:06:19.386 26614-26659/com.wire D/EGL_emulation: eglMakeCurrent: 0x92d0e780: ver 3 1 (tinfo 0x8f5b5ce0)
03-26 23:06:21.252 26614-26614/com.wire W/Notification: Use of stream types is deprecated for operations other than volume control
03-26 23:06:21.252 26614-26614/com.wire W/Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-26 23:06:22.244 26614-26650/com.wire W/AudioManager: Use of stream types is deprecated for operations other than volume control
03-26 23:06:22.244 26614-26650/com.wire W/AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-26 23:06:22.246 26614-26650/com.wire W/AudioManager: Use of stream types is deprecated for operations other than volume control
03-26 23:06:22.246 26614-26650/com.wire W/AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-26 23:06:22.327 26614-26650/com.wire W/MediaPlayer: Use of stream types is deprecated for operations other than volume control
03-26 23:06:22.327 26614-26650/com.wire W/MediaPlayer: See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-26 23:06:22.878 26614-26649/com.wire D/JVM: AttachCurrentThreadIfNeeded::ctor@[tid=26649]
03-26 23:06:22.878 26614-26649/com.wire D/JVM: Attaching thread to JVM
03-26 23:06:22.879 26614-26649/com.wire D/JVM: JVM::environment@[tid=26649]
03-26 23:06:22.879 26614-26649/com.wire D/JVM: JNIEnvironment::ctor@[tid=26649]
03-26 23:06:22.879 26614-26649/com.wire D/AudioManager: ctor@[tid=26649]
03-26 23:06:22.879 26614-26649/com.wire D/JVM: JNIEnvironment::RegisterNatives(org/webrtc/voiceengine/WebRtcAudioManager)
03-26 23:06:22.879 26614-26649/com.wire D/JVM: NativeRegistration::ctor@[tid=26649]
03-26 23:06:22.879 26614-26649/com.wire D/JVM: NativeRegistration::NewObject@[tid=26649]
03-26 23:06:22.882 26614-26649/com.wire W/org.webrtc.Logging: Failed to load jingle_peerconnection_so: 
                                                              java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.wire-31wbWleD3Zdch00hS2WWQw==/base.apk"],nativeLibraryDirectories=[/data/app/com.wire-31wbWleD3Zdch00hS2WWQw==/lib/x86, /system/fake-libs, /data/app/com.wire-31wbWleD3Zdch00hS2WWQw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libjingle_peerconnection_so.so"
                                                                  at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
                                                                  at java.lang.System.loadLibrary(System.java:1657)
                                                                  at org.webrtc.Logging.<clinit>(Logging.java:27)
                                                                  at org.webrtc.Logging.d(Logging.java:129)
                                                                  at org.webrtc.voiceengine.WebRtcAudioManager.<init>(WebRtcAudioManager.java:90)
03-26 23:06:22.883 26614-26649/com.wire I/org.webrtc.Logging: WebRtcAudioManager: ctor@[name=Thread-700, id=1191]
03-26 23:06:22.883 26614-26649/com.wire I/org.webrtc.Logging: WebRtcAudioManager: Sample rate is set to 48000 Hz
03-26 23:06:22.894 26614-26649/com.wire I/org.webrtc.Logging: WebRtcAudioEffects: canUseAcousticEchoCanceler: false
03-26 23:06:22.902 26614-26649/com.wire I/org.webrtc.Logging: WebRtcAudioEffects: canUseAutomaticGainControl: false
03-26 23:06:22.909 26614-26649/com.wire I/org.webrtc.Logging: WebRtcAudioEffects: canUseNoiseSuppressor: false
03-26 23:06:22.912 26614-26649/com.wire D/AudioManager: OnCacheAudioParameters@[tid=26649]
03-26 23:06:22.912 26614-26649/com.wire D/AudioManager: hardware_aec: 0
03-26 23:06:22.912 26614-26649/com.wire D/AudioManager: hardware_agc: 0
03-26 23:06:22.912 26614-26649/com.wire D/AudioManager: hardware_ns: 0
03-26 23:06:22.912 26614-26649/com.wire D/AudioManager: low_latency_output: 0
03-26 23:06:22.912 26614-26649/com.wire D/AudioManager: sample_rate: 48000
03-26 23:06:22.912 26614-26649/com.wire D/AudioManager: channels: 1
03-26 23:06:22.912 26614-26649/com.wire D/AudioManager: output_buffer_size: 2308
03-26 23:06:22.912 26614-26649/com.wire D/AudioManager: input_buffer_size: 1440
03-26 23:06:22.912 26614-26649/com.wire D/JVM: GlobalRef::ctor@[tid=26649]
03-26 23:06:22.912 26614-26649/com.wire D/AudioManager: JavaAudioManager::ctor@[tid=26649]
03-26 23:06:22.912 26614-26649/com.wire D/AudioManager: IsLowLatencyPlayoutSupported()
03-26 23:06:22.912 26614-26649/com.wire D/JVM: AttachCurrentThreadIfNeeded::ctor@[tid=26649]
03-26 23:06:22.912 26614-26649/com.wire D/JVM: JVM::environment@[tid=26649]
03-26 23:06:22.912 26614-26649/com.wire D/JVM: JNIEnvironment::ctor@[tid=26649]
03-26 23:06:22.912 26614-26649/com.wire D/AudioTrackJni: ctor@[tid=26649]
03-26 23:06:22.912 26614-26649/com.wire D/JVM: JNIEnvironment::RegisterNatives(org/webrtc/voiceengine/WebRtcAudioTrack)
03-26 23:06:22.912 26614-26649/com.wire D/JVM: NativeRegistration::ctor@[tid=26649]
03-26 23:06:22.912 26614-26649/com.wire D/JVM: NativeRegistration::NewObject@[tid=26649]
03-26 23:06:22.913 26614-26649/com.wire I/org.webrtc.Logging: WebRtcAudioTrack: ctor@[name=Thread-700, id=1191]
03-26 23:06:22.913 26614-26649/com.wire D/JVM: GlobalRef::ctor@[tid=26649]
03-26 23:06:22.913 26614-26649/com.wire D/JVM: AttachCurrentThreadIfNeeded::ctor@[tid=26649]
03-26 23:06:22.913 26614-26649/com.wire D/JVM: JVM::environment@[tid=26649]
03-26 23:06:22.913 26614-26649/com.wire D/JVM: JNIEnvironment::ctor@[tid=26649]
03-26 23:06:22.913 26614-26649/com.wire D/AudioRecordJni: ctor@[tid=26649]
03-26 23:06:22.913 26614-26649/com.wire D/JVM: JNIEnvironment::RegisterNatives(org/webrtc/voiceengine/WebRtcAudioRecord)
03-26 23:06:22.913 26614-26649/com.wire D/JVM: NativeRegistration::ctor@[tid=26649]
03-26 23:06:22.913 26614-26649/com.wire D/JVM: NativeRegistration::NewObject@[tid=26649]
03-26 23:06:22.914 26614-26649/com.wire I/org.webrtc.Logging: WebRtcAudioRecord: ctor@[name=Thread-700, id=1191]
03-26 23:06:22.914 26614-26649/com.wire I/org.webrtc.Logging: WebRtcAudioEffects: ctor@[name=Thread-700, id=1191]
03-26 23:06:22.914 26614-26649/com.wire D/JVM: GlobalRef::ctor@[tid=26649]
03-26 23:06:22.914 26614-26649/com.wire D/AudioManager: SetActiveAudioLayer(5)@[tid=26649]
03-26 23:06:22.914 26614-26649/com.wire D/AudioManager: delay_estimate_in_milliseconds: 150
03-26 23:06:22.914 26614-26649/com.wire D/AudioTrackJni: AttachAudioBuffer@[tid=26649]
03-26 23:06:22.914 26614-26649/com.wire D/AudioTrackJni: SetPlayoutSampleRate(48000)
03-26 23:06:22.914 26614-26649/com.wire D/AudioTrackJni: SetPlayoutChannels(1)
03-26 23:06:22.914 26614-26649/com.wire D/AudioRecordJni: AttachAudioBuffer
03-26 23:06:22.915 26614-26649/com.wire D/AudioRecordJni: SetRecordingSampleRate(48000)
03-26 23:06:22.915 26614-26649/com.wire D/AudioRecordJni: SetRecordingChannels(1)
03-26 23:06:22.915 26614-26649/com.wire D/AudioRecordJni: total_delay_in_milliseconds: 150
03-26 23:06:22.915 26614-26649/com.wire D/AudioManager: Init@[tid=26649]
03-26 23:06:22.916 26614-26649/com.wire I/org.webrtc.Logging: WebRtcAudioManager: init@[name=Thread-700, id=1191]
03-26 23:06:22.916 26614-26649/com.wire I/org.webrtc.Logging: WebRtcAudioManager: audio mode is: MODE_IN_COMMUNICATION
03-26 23:06:22.916 26614-26649/com.wire D/AudioTrackJni: Init@[tid=26649]
03-26 23:06:22.916 26614-26649/com.wire D/AudioRecordJni: Init@[tid=26649]
03-26 23:06:22.936 26614-26649/com.wire D/AudioRecordJni: InitRecording@[tid=26649]
03-26 23:06:22.936 26614-26649/com.wire A/libc: Fatal signal 4 (SIGILL), code 2, fault addr 0x8e8691b3 in tid 26649 (Thread-730)

**Comment by someoneEsle** [comment]
Thanks for bringing this up, looking into it

**Comment by camdit** [comment]
Please let me know if I can assist. I will continue to look on my end as well.

**Comment by camdit** [comment]
I added the dependency to gradle:

compile 'org.webrtc:google-webrtc:1.0.19742'

Now I no longer get:

03-26 23:06:22.882 26614-26649/com.wire W/org.webrtc.Logging: Failed to load jingle_peerconnection_so:
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.wire-31wbWleD3Zdch00hS2WWQw==/base.apk"],nativeLibraryDirectories=[/data/app/com.wire-31wbWleD3Zdch00hS2WWQw==/lib/x86, /system/fake-libs, /data/app/com.wire-31wbWleD3Zdch00hS2WWQw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libjingle_peerconnection_so.so"
at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
at java.lang.System.loadLibrary(System.java:1657)
at org.webrtc.Logging.(Logging.java:27)
at org.webrtc.Logging.d(Logging.java:129)
at org.webrtc.voiceengine.WebRtcAudioManager.(WebRtcAudioManager.java:90)

But the app still crashes right after joining. The call rings and it is only when joining that it crashes.



My new logcat:

03-27 21:03:12.167 12029-12029/com.wire W/Notification: Use of stream types is deprecated for operations other than volume control
03-27 21:03:12.167 12029-12029/com.wire W/Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-27 21:03:12.237 12029-12066/com.wire W/AudioManager: Use of stream types is deprecated for operations other than volume control
03-27 21:03:12.237 12029-12066/com.wire W/AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-27 21:03:12.241 12029-12066/com.wire W/AudioManager: Use of stream types is deprecated for operations other than volume control
03-27 21:03:12.241 12029-12066/com.wire W/AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-27 21:03:12.270 12029-12066/com.wire W/MediaPlayer: Use of stream types is deprecated for operations other than volume control
03-27 21:03:12.270 12029-12066/com.wire W/MediaPlayer: See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-27 21:03:12.421 12029-12116/com.wire D/FlowManager: getVideoCaptureDevices: 2
03-27 21:03:12.447 12029-12029/com.wire W/Notification: Use of stream types is deprecated for operations other than volume control
03-27 21:03:12.447 12029-12029/com.wire W/Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-27 21:03:12.492 12029-12075/com.wire D/EGL_emulation: eglMakeCurrent: 0x8f99c280: ver 3 1 (tinfo 0x8f9fd260)
03-27 21:03:22.165 12029-12029/com.wire W/Notification: Use of stream types is deprecated for operations other than volume control
03-27 21:03:22.165 12029-12029/com.wire W/Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-27 21:03:22.192 12029-12029/com.wire W/Notification: Use of stream types is deprecated for operations other than volume control
03-27 21:03:22.192 12029-12029/com.wire W/Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-27 21:03:22.381 12029-12066/com.wire W/MediaPlayer: Use of stream types is deprecated for operations other than volume control
03-27 21:03:22.381 12029-12066/com.wire W/MediaPlayer: See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-27 21:03:22.965 12029-12065/com.wire D/JVM: AttachCurrentThreadIfNeeded::ctor@[tid=12065]
03-27 21:03:22.966 12029-12065/com.wire D/JVM: Attaching thread to JVM
03-27 21:03:22.966 12029-12065/com.wire D/JVM: JVM::environment@[tid=12065]
03-27 21:03:22.966 12029-12065/com.wire D/JVM: JNIEnvironment::ctor@[tid=12065]
03-27 21:03:22.966 12029-12065/com.wire D/AudioManager: ctor@[tid=12065]
03-27 21:03:22.966 12029-12065/com.wire D/JVM: JNIEnvironment::RegisterNatives(org/webrtc/voiceengine/WebRtcAudioManager)
03-27 21:03:22.966 12029-12065/com.wire D/JVM: NativeRegistration::ctor@[tid=12065]
03-27 21:03:22.966 12029-12065/com.wire D/JVM: NativeRegistration::NewObject@[tid=12065]
03-27 21:03:22.971 12029-12065/com.wire I/org.webrtc.Logging: WebRtcAudioManager: ctor@[name=Thread-410, id=1084]
03-27 21:03:22.972 12029-12065/com.wire I/org.webrtc.Logging: WebRtcAudioManager: Sample rate is set to 48000 Hz
03-27 21:03:22.981 12029-12065/com.wire I/org.webrtc.Logging: WebRtcAudioEffects: canUseAcousticEchoCanceler: false
03-27 21:03:22.989 12029-12065/com.wire I/org.webrtc.Logging: WebRtcAudioEffects: canUseAutomaticGainControl: false
03-27 21:03:22.996 12029-12065/com.wire I/org.webrtc.Logging: WebRtcAudioEffects: canUseNoiseSuppressor: false
03-27 21:03:22.999 12029-12065/com.wire D/AudioManager: OnCacheAudioParameters@[tid=12065]
03-27 21:03:22.999 12029-12065/com.wire D/AudioManager: hardware_aec: 0
03-27 21:03:22.999 12029-12065/com.wire D/AudioManager: hardware_agc: 0
03-27 21:03:22.999 12029-12065/com.wire D/AudioManager: hardware_ns: 0
03-27 21:03:22.999 12029-12065/com.wire D/AudioManager: low_latency_output: 0
03-27 21:03:22.999 12029-12065/com.wire D/AudioManager: sample_rate: 48000
03-27 21:03:22.999 12029-12065/com.wire D/AudioManager: channels: 1
03-27 21:03:22.999 12029-12065/com.wire D/AudioManager: output_buffer_size: 2308
03-27 21:03:22.999 12029-12065/com.wire D/AudioManager: input_buffer_size: 1440
03-27 21:03:22.999 12029-12065/com.wire D/JVM: GlobalRef::ctor@[tid=12065]
03-27 21:03:22.999 12029-12065/com.wire D/AudioManager: JavaAudioManager::ctor@[tid=12065]
03-27 21:03:22.999 12029-12065/com.wire D/AudioManager: IsLowLatencyPlayoutSupported()
03-27 21:03:22.999 12029-12065/com.wire D/JVM: AttachCurrentThreadIfNeeded::ctor@[tid=12065]
03-27 21:03:22.999 12029-12065/com.wire D/JVM: JVM::environment@[tid=12065]
03-27 21:03:22.999 12029-12065/com.wire D/JVM: JNIEnvironment::ctor@[tid=12065]
03-27 21:03:22.999 12029-12065/com.wire D/AudioTrackJni: ctor@[tid=12065]
03-27 21:03:22.999 12029-12065/com.wire D/JVM: JNIEnvironment::RegisterNatives(org/webrtc/voiceengine/WebRtcAudioTrack)
03-27 21:03:22.999 12029-12065/com.wire D/JVM: NativeRegistration::ctor@[tid=12065]
03-27 21:03:22.999 12029-12065/com.wire D/JVM: NativeRegistration::NewObject@[tid=12065]
03-27 21:03:23.000 12029-12065/com.wire I/org.webrtc.Logging: WebRtcAudioTrack: ctor@[name=Thread-410, id=1084]
03-27 21:03:23.000 12029-12065/com.wire D/JVM: GlobalRef::ctor@[tid=12065]
03-27 21:03:23.000 12029-12065/com.wire D/JVM: AttachCurrentThreadIfNeeded::ctor@[tid=12065]
03-27 21:03:23.000 12029-12065/com.wire D/JVM: JVM::environment@[tid=12065]
03-27 21:03:23.000 12029-12065/com.wire D/JVM: JNIEnvironment::ctor@[tid=12065]
03-27 21:03:23.000 12029-12065/com.wire D/AudioRecordJni: ctor@[tid=12065]
03-27 21:03:23.000 12029-12065/com.wire D/JVM: JNIEnvironment::RegisterNatives(org/webrtc/voiceengine/WebRtcAudioRecord)
03-27 21:03:23.000 12029-12065/com.wire D/JVM: NativeRegistration::ctor@[tid=12065]
03-27 21:03:23.000 12029-12065/com.wire D/JVM: NativeRegistration::NewObject@[tid=12065]
03-27 21:03:23.000 12029-12065/com.wire I/org.webrtc.Logging: WebRtcAudioRecord: ctor@[name=Thread-410, id=1084]
03-27 21:03:23.000 12029-12065/com.wire I/org.webrtc.Logging: WebRtcAudioEffects: ctor@[name=Thread-410, id=1084]
03-27 21:03:23.000 12029-12065/com.wire D/JVM: GlobalRef::ctor@[tid=12065]
03-27 21:03:23.000 12029-12065/com.wire D/AudioManager: SetActiveAudioLayer(5)@[tid=12065]
03-27 21:03:23.000 12029-12065/com.wire D/AudioManager: delay_estimate_in_milliseconds: 150
03-27 21:03:23.000 12029-12065/com.wire D/AudioTrackJni: AttachAudioBuffer@[tid=12065]
03-27 21:03:23.000 12029-12065/com.wire D/AudioTrackJni: SetPlayoutSampleRate(48000)
03-27 21:03:23.000 12029-12065/com.wire D/AudioTrackJni: SetPlayoutChannels(1)
03-27 21:03:23.000 12029-12065/com.wire D/AudioRecordJni: AttachAudioBuffer
03-27 21:03:23.000 12029-12065/com.wire D/AudioRecordJni: SetRecordingSampleRate(48000)
03-27 21:03:23.000 12029-12065/com.wire D/AudioRecordJni: SetRecordingChannels(1)
03-27 21:03:23.000 12029-12065/com.wire D/AudioRecordJni: total_delay_in_milliseconds: 150
03-27 21:03:23.000 12029-12065/com.wire D/AudioManager: Init@[tid=12065]
03-27 21:03:23.001 12029-12065/com.wire I/org.webrtc.Logging: WebRtcAudioManager: init@[name=Thread-410, id=1084]
03-27 21:03:23.001 12029-12065/com.wire I/org.webrtc.Logging: WebRtcAudioManager: audio mode is: MODE_IN_COMMUNICATION
03-27 21:03:23.001 12029-12065/com.wire D/AudioTrackJni: Init@[tid=12065]
03-27 21:03:23.001 12029-12065/com.wire D/AudioRecordJni: Init@[tid=12065]
03-27 21:03:23.012 12029-12065/com.wire D/AudioRecordJni: InitRecording@[tid=12065]
03-27 21:03:23.012 12029-12065/com.wire A/libc: Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 12065 (Thread-425)

**Comment by camdit** [comment]
Things I have tried without success:

android:vmSafeMode="true"
minSDK => 17, I could not get the debug to compile quickly due to too many methods but the release compiled with minify
android:hardewareAccelerated="false"
clean - > rebuild

Nothing has worked yet.

On a side note, I am experiencing this with 3.6 on both a Galaxy S9 Edge running Android 7 and a Pixel XL 2 running Android 8. If this was wide spread I would think more than just 2 of us would have posted this issue. This makes me think it's my build environment. I am building with:

Android Studio 3.0.1, 
Java JDK 1.8.0_161
Downloaded zip of the release branch (not cloned via git)
running the gradlew.bat with assembleProdRelease as argument
Windows 10, testing on Android Emulator and physical phone (I have only test 3.6 on physical phone)

If other's can chime in with an environment that has worked for them I would appreciate it.


One last thing, when doing a clean build for minsdk=17, I had to remove the compile line that I added above for webrtc, it showed as a duplicate entry. So, that has been undone in the steps that I used to test.

**Comment by ogiright123** [comment]
add in build.gradle file follows:
       android {

              dexOptions {
              keepRuntimeAnnotatedClasses false
       }

     }

then, debug building will be success
But video/audio call doesnt work yet!

**Comment by kristin-wire** [comment]
Firstly, a big thank you to all of you who have contributed your comments and feedback regarding this issue. Wire developers read these reports first hand, and they are very helpful. 

We are currently reworking that part of the code in preparation of some upcoming features, and this broke source compatibility with the audio/video calling library. We are working on fixing the incompatibility and as we do that, all will work well again - hang tight.

**Comment by camdit** [comment]
Thanks! Do you know when this happened? What was the last version that worked?

**Comment by camdit** [comment]
Any updated ETA on a build where the calling activity works?

**Comment by marcoconti83** [comment]
@camdit please try again with latest master, it should work now

**Comment by camdit** [comment]
Awesome. I'll test it Monday and report back.

**Comment by camdit** [comment]
Too many issues when trying to build master. I will try to see if I can't use the change log in master to fix release branch locally next week. Thanks.

**Comment by camdit** [comment]
I just cloned latest master, switched to release branch version 3.10 and built the app. Two things, first I can not run this on an emulator, the fact that there is no Bluetooth crashes the app. I will log this as a new bug. The second is that the audio call feature is still broken and crashes on joining. This is verified on my S7 running stock Android 7 and a debug/prod build of 3.10 unmodified release branch. If there is a different way that I need to build the app, please let me know.

**Comment by red-avtovo** [comment]
@camdit is it still reproducible on latest version of Wire?

**Comment by weakup** [comment]
// For using local files in app/libs
    implementation (name:'avs', ext:'aar')

2018-10-12 18:33:50.725 25193-25348/com.wire.candidate E/AVS: ERROR     ; (18:33:50:724 |    0) AUDIO DEVICE:    1    99;     25348; stereo playout is not supported

2018-10-12 18:33:50.735 25193-25348/com.wire.candidate E/AVS: ERROR     ; (18:33:50:732 |    5) AUDIO DEVICE:    1    99;     25348; failed to enable stereo recording

2018-10-12 18:33:50.854 26668-26668/? A/DEBUG:     #00 pc 0064d0cc  /data/app/com.wire.candidate-hl4412HfYLy_C3EnTcHoTA==/lib/arm/libavs.so

**Comment by jlavyan** [comment]
@weakup exactly same issue that I have on my side.

**Comment by hub-ch** [comment]
https://github.com/wireapp/wire-android/issues/1892

**Comment by marcoconti83** [comment]
Hi everyone,
The issue has been fixed here: https://github.com/wireapp/wire-android/issues/1892. Please read the instructions at that link. If this is not fixed for you, please report the issue in the linked discussion and not here.

Thanks for your patience!
