### ISSUE TITLE
[UX] Short white startscreen / long startup

### ISSUE THREAD

**Issue by peterpanondrugs** [wireapp/wire-android#149]
When u start Wire from your home android screen, 1st picture you see on your phone is a white screen at startup (approx. duration ~3s, followed by the main wire screen.
I've chosen Dark Background.

In general i find the startup time quite long! 
[debug.txt](https://github.com/wireapp/wire-android/files/464615/debug.txt)

Device: Samsung i9305 / S3 LTE
Android version: 6.0.1

**Comment by someoneEsle** [comment]
I experience a similar lag on my Nexus 5X, Android 7. It's not always that long, but it does happen.

**Comment by bjoernherbig** [comment]
hi, thanks for the feedback. the start up time is nothing we are planning on improving anytime soon.
