### ISSUE TITLE
Video/audio call issue

### ISSUE THREAD

**Issue by ogiright123** [wireapp/wire-android#1499]
## The problem

I built branch release repo successfully.
App runs but when i start  audio/video calling,  app is crashed.
how does it fix?

## Environment
* Wire version                  latest branch release
* android studio 2.3.2 gradle version 1.5.0
* Android OS  is   android 6.0
* Mobile phone model/manufacturer:                samsung galaxy s5
* Mobile network type (EDGE/LTE/Wi-Fi/Offline):  wifi

**Comment by someoneEsle** [comment]
duplicate of #1481

**Comment by hub-ch** [comment]
https://github.com/wireapp/wire-android/issues/1892
