### ISSUE TITLE
Timed messages NOT timing out on 3.9.423

### ISSUE THREAD

**Issue by TubaOrNotTuba** [wireapp/wire-android#1504]
In 3.9.423, timed messages sent to it from another device do not count down and do not disappear.  The same sender's messages received on an iPhone countdown and timeout propertly.

This is a HUGE security risk.  IMHO, this build is so buggy it should be pulled immediately.

**Comment by someoneEsle** [comment]
Hi, what are you using to send/receive the message? I cannot reproduce

**Comment by TubaOrNotTuba** [comment]
Sending phone is LG G3 using production Wire from Google Play.  Receiving phone is LG V20 using 3.9.423 also installed from Play.

**Comment by TubaOrNotTuba** [comment]
Yep, definitely reproducible on LG V20 on Android 7.0.0.  There's an interesting fix, however.  If the other person in the chat sends a photo taking inside Wire, not attached, instantly all the messages that had no timer get a timer.  This was never an issue until this build. Please let me know what I can do to help hunt this down.

**Comment by someoneEsle** [comment]
It is enough for you to go to a different conversation and go back to the first one for the timer to start. We found the issue, we're working on a fix 👍

**Comment by red-avtovo** [comment]
Fixed in latest version
