### ISSUE TITLE
Add sbt support

### ISSUE THREAD

**Issue by charafau** [wireapp/wire-android#151]
Hello! I saw that project is using scala with old gradle plugin (probably fork for old scala gradle plugin ,1.5). While it helps with Android Studio integration, it's probably slower and doesn't offer many benefits. 

Maybe we should add sbt support with scala android plugin ( http://scala-android.org/ ) which would increase build speed, caching and add more features like TypedResources: http://scala-android.org/tips_and_tricks-typed_resources/  and awesome protify plugin  https://github.com/scala-android/sbt-android-protify  . 

Plugin is also compatible with all newest gradle features (ok, jack & jill is experimental). 

I can help with initial support

**Comment by zbsz** [comment]
check out `messages_stream` branch, we have some sbt config there, it's not perfect, have some issues with flavours, would be great if you could fix it :)

**Comment by charafau** [comment]
I am extremely busy right now, but I should take a look in two weeks :)

**Comment by marcoconti83** [comment]
Hi @charafau and thanks for opening the original issue. 
We have plans to start introducing Kotlin to our UI layer, and going forward write more Kotlin than Scala for new features. Given this, it would not make sense to migrate from gradle to sbt, so I'm closing this issue.
