### ISSUE TITLE
scalaCompileOptions -Xfatal-wranings causes issues with future deprecated code.

### ISSUE THREAD

**Issue by camdit** [wireapp/wire-android#1519]
## The problem

With the inclusion of "-Xfatal-warnings" see (https://github.com/wireapp/wire-android/commit/3c331707ce67a4b279edae6b64d8d2fcb9994830), any deprecated code even if it is not deprecated in the target API or min API will cause a compilation error.

## Environment

Wire 3.9
Android Studio 3

## Details

To reproduce make a change that would use deprecated code, i.e. use Notification instead of NotificationCompat. This would then show as deprecated because the constructor Notification.Build(context) is deprecated in API 26, it now must be Notification.Build(context, "string"). 

This will not compile even if the min and target api is 17 where this is NOT deprecated.

This may not be a bug as it does not affect the project as it is presented, however, I don't think this was an intended affect.

**Comment by CalumMcCall** [comment]
This compiler option can be annoying, especially with deprecations, so I sympathise. However, we find ignoring deprecation warnings tends to lead to ignoring other warnings also, which we find is bad for software quality and security. So, we aim to have zero warnings over the codebase, hence adding this option. To deal with deprecation warnings which we can't remove, we suppress warnings individually (See `DeprecatedUtils.java`). If your code is Scala code, I suggest moving the deprecated code into Java, or looking at the `silencer` plugin for Scala.
