### ISSUE TITLE
Minor: "you started a conversation with you" when accepting a new connect request

### ISSUE THREAD

**Issue by maximbaz** [wireapp/wire-android#1528]
## The problem

* Accept a new contact request.
* Observe the message "You started a conversation with you".

Expected result: "Steve started a conversation with you".

## Environment

* Wire version that exhibits the issue: 3.9.428
* Android OS version used to run Wire: 6.0
* Is this a custom firmware or a stock one: Stock
* Mobile phone model/manufacturer: ZTE Blade V7
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi

## Screenshots

![image](https://user-images.githubusercontent.com/1177900/38466403-c3b5a14c-3b28-11e8-8649-95dc507b5732.png)

**Comment by makingthematrix** [comment]
I guess this was fixed a long time ago? I will close this ticket. Please reopen if needed.
