### ISSUE TITLE
Video Conversion before upload

### ISSUE THREAD

**Issue by aqeeliz** [wireapp/wire-android#153]
When uploading videos on WhatsApp, it converts them (I think), reducing the size of videos greatly and thus making it easier to upload.

For instance, a contact tried to upload a minute or so long video taken from mobile's camera (about 78.5 MB), but it failed because of the big size, but the same video got uploaded on WhatsApp without much problem.

If the issue is about not wanting to reduce video quality, maybe you can make it optional, as there are lots of places with not-so-good upload speed which will benifit from this.

**Comment by someoneEsle** [comment]
The video quality is indeed reduced, as all attachment do not exceed the limit of (what I think is still) 25MB. Your friend definitely ran into a bug (that I think is known), but it's not like videos larger than 25mb are impossible to send :) I think I've been able to send videos that were bigger than 78.5MB, it just takes a few attempts lol. Also, sometimes sharing from gallery/from within Wire or even sharing as generic file (and not as video) may work around the bug.

**Comment by makingthematrix** [comment]
Hi.

This issue is very old and I decided to close it (we're trying to clean up our GitHub issues). 
Long videos can be sent as regular files.
If you think this is still relevant, please open a new ticket.

Cheers,
