### ISSUE TITLE
Trying to send video bigger than 26MB deletes video

### ISSUE THREAD

**Issue by danielroehrig** [wireapp/wire-android#1540]
## The problem

Sending a previously recorded video via the share function that is larger than 26MB will not only result in an error message ("file to large") but also deletes the original file.

## Environment

Nexus 5x
Wire 3.9.428
Android 8.1.0

## Details

This is the second time a video file was deleted, after I tried to send it via wire. This time, it was the first steps of my son sent to my wife. You can imagine, we are not very happy about this. Fortunately, the Nextcloud automatic backup feature was fast enough and I already had a copy of the video on my computer.

## Link to Debug logs

I reproduced the error and I can send you the error log if you want. But you should be able to reproduce the error by recording a minute long video and use the share function to send it to a friend. You should see the error and then the video is gone.

I have looked in the log files and the only thing that I found suspicious are these lines:
```
04-14 11:38:51.841 I/zygote  ( 1721): Background concurrent copying GC freed 147146(12MB) AllocSpace objects, 15(332KB) LOS objects, 49% free, 7MB/14MB, paused 174us total 105.166ms
04-14 11:38:56.574 V/NuMediaExtractor( 1721): track of type 'video/avc' does not publish bitrate
04-14 11:38:56.574 V/NuMediaExtractor( 1721): track of type 'audio/mp4a-latm' does not publish bitrate
04-14 11:38:56.617 V/NuMediaExtractor( 1721): track of type 'video/avc' does not publish bitrate
04-14 11:38:56.617 V/NuMediaExtractor( 1721): track of type 'audio/mp4a-latm' does not publish bitrate
04-14 11:38:56.822 W/VideoCapabilities( 1721): Unrecognized profile 2130706433 for video/avc
04-14 11:38:56.828 I/VideoCapabilities( 1721): Unsupported profile 4 for video/mp4v-es
04-14 11:38:57.085 W/OMXUtils( 1721): do not know color format 0x7fa30c04 = 2141391876
04-14 11:38:57.085 W/OMXUtils( 1721): do not know color format 0x7f000789 = 2130708361
04-14 11:38:57.093 I/ACodec  ( 1721): setupAVCEncoderParameters with [profile: Baseline] [level: Level3]
04-14 11:38:57.094 I/ACodec  ( 1721): [OMX.qcom.video.encoder.avc] cannot encode color aspects. Ignoring.
04-14 11:38:57.095 I/ACodec  ( 1721): [OMX.qcom.video.encoder.avc] cannot encode HDR static metadata. Ignoring.
04-14 11:38:57.095 I/ACodec  ( 1721): setupVideoEncoder succeeded
04-14 11:38:57.098 W/OMXUtils( 1721): do not know color format 0x7f000789 = 2130708361
```

**Comment by someoneEsle** [comment]
related #1243

**Comment by lucilacaranza** [comment]
Zendesk ticket #[62704](https://wearezeta.zendesk.com/agent/tickets/62704) has been linked to this issue.

**Comment by lucilacaranza** [comment]
*Comment made from Zendesk by Dilan on 2018-06-22 at 12:53:*

<blockquote><div class="zd-comment">Guten Tag,<br><br>Vielen Dank, dass Sie sich an uns wenden und uns auf den Bug aufmerksam machen!<br><br>Dieser Bug ist bereits bekannt und wird von unseren Entwicklern schnellstmöglich behandelt. <br><br>Wir bitten um Entschuldigung für diese Unannehmlichkeit.<br><br>Liebe Grüße und ein schönes Wochenende,<br>
</div></blockquote>

**Comment by lucilacaranza** [comment]
*Comment made from Zendesk by Astrid Pahl on 2018-06-26 at 10:01:*

<blockquote><div class="zd-comment">
<a href="https://github.com/wireapp/wire-android/issues/1540" rel="noreferrer">https://github.com/wireapp/wire-android/issues/1540</a><br>
</div></blockquote>

**Comment by lucilacaranza** [comment]
*Comment made from Zendesk by Astrid Pahl on 2018-06-26 at 10:04:*

<blockquote><div class="zd-comment">Guten Tag,<br><br>Vielen Dank, dass Sie sich an uns wenden! <br><br>Dieses Problem ist uns bereits bekannt und wird von unseren Entwicklern schnellstmöglich behandelt. <br><br>Wir bitten um Entschuldigung für diese Unannehmlichkeit.<br><br>Schönen Gruß,<br><br>Nora Blomberg<br>Wire Support<br><br><br>
</div></blockquote>

**Comment by lucilacaranza** [comment]
*Comment made from Zendesk by Lucila Caranza on 2018-09-04 at 10:18:*

<blockquote><div class="zd-comment">this was fixed.<br>
</div></blockquote>

**Comment by lucilacaranza** [comment]
*Comment made from Zendesk by Pia Eimer on 2018-09-04 at 11:11:*

<blockquote><div class="zd-comment">Hallo,<br><br>dies ist eine kurze Nachricht, um Dir mitzuteilen, dass dieser Bug behoben worden ist.<br>Bitte update Deine Wire Version und lasse uns wissen, ob Du weitere Fragen hast.<br><br>Ich freue mich von Dir zu hören.<br><br>Beste Grüße,<br>

<span class="collapse-signature"></span><div class="signature"><p dir="auto">Padma Reddy<br>
Wire Support</p></div>
</div></blockquote>

**Comment by mMuck** [comment]
> _Comment made from Zendesk by Lucila Caranza on 2018-09-04 at 10:18:_
> > this was fixed.

If so, please close this issue. (Is there someone who maintains this issue list??)

**Comment by marcoconti83** [comment]
I will close this, if it's still an issue please reopen
