### ISSUE TITLE
Sent Pictures are no longer visible in Wire after being deleted from the Android filesystem

### ISSUE THREAD

**Issue by Larx** [wireapp/wire-android#1569]
## The problem

If I send a photo (possibly other stuff, too) via Android's share feature from the filesystem, they disappear from the local Wire instance as soon as I delete them from the device. 
They are, however, obviously still visible for the recipient of the message, and even in my own Wire account as soon as I access it with Wire instances installed on other devices.

## Environment

This and the other bullets are IMHO not applicable, it rather seems a design question that the local Wire instance does rely on sent items being present on the local file system.

## Proposal

If a sent item is no longer available on the local filesystem, Wire should resort to the item as stored for the communication and available for the other participients of the conversation.

**Comment by someoneEsle** [comment]
duplicate #932
