### ISSUE TITLE
Don't force users to see modal windows with new features.

### ISSUE THREAD

**Issue by tmikaeld** [wireapp/wire-android#157]
Instead show it as a popup at the top or bottom so that it doesn't disrupt usability.

**Comment by someoneEsle** [comment]
Also, I think they look too much like ads. The first time I saw one I really thought it was an ad and dismissed it without really reading it. So I'm not even sure if they are *that* useful.

**Comment by tmikaeld** [comment]
@someoneEsle That's what i wanted to write, but didn't ;-)

**Comment by teller** [comment]
We're trying to find a balance between "showing ads" and complaints from users that they don't know that we've added new features. We have some ideas how to try different ways of drawing attention to new stuff but until then we'll continue with the modals. Easy to dismiss, shown only once and maybe once every couple of weeks.
