### ISSUE TITLE
Markdown not rendered on Android

### ISSUE THREAD

**Issue by gr4v1t0n** [wireapp/wire-android#1577]
# The problem
The markdown described on https://support.wire.com/hc/en-us/articles/115002676029-How-can-I-use-markdown-to-format-text-on-Wire- is not working in the Android app. ("format some text inside **any** conversation on Wire" is unfortunately not working for all clients yet).
Would be nice to have it implemented on all clients.

## Environment
* Wire version that exhibits the issue: 3.10.442
* Android OS version used to run Wire: Android 7.1.2
* Is this a custom firmware or a stock one: LineageOS 
* Mobile phone model/manufacturer: Samsung Galaxy S4 Mini (GT-I9195)
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/Wi-Fi

## Details
Markdown is rendered on the Windows client, but not on my phone (viewing the same conversation).

## Screenshots
![grafik](https://user-images.githubusercontent.com/39697677/40612385-913293f0-627a-11e8-9ddc-5578e8737cb6.png)

**Comment by red-avtovo** [comment]
Hi @gr4v1t0n ! This feature was never developed on Android.

**Comment by marcoconti83** [comment]
Hi @gr4v1t0n ,
this feature was ported to the Android app and is already in the public version - give it a try!
