### ISSUE TITLE
Add direct share

### ISSUE THREAD

**Issue by ConorIA** [wireapp/wire-android#158]
Later versions of Android include a direct share feature that lets you share to a conversation from the share picker. This is really handy.

**Comment by david-wire** [comment]
Thanks for the note @ConorIA. You can already share content from another source like YouTube for instance to a conversation on Wire. Are you referring to this or something else?

**Comment by ConorIA** [comment]
Something else!

[wire_1475080840907.jpg](http://i.imgur.com/3y97WU5.jpg)

See how my most recent Whatsapp conversations show up at the top of my share picker? My suggestion is that Wire conversations show up there too.

**Comment by ffflorian** [comment]
I vote against this feature if it isn't defeatable like in the Twitter app.

**Comment by ConorIA** [comment]
@ffflorian, any reason in particular? Is it because it makes it easier to share to the wrong person?

**Comment by ffflorian** [comment]
Because the sharing view is already huge and the last conversations make it even more cluttered. And yes, it's very easy to accidentally share something with the wrong conversation.
As I said, if this option is defeatable it's perfectly fine for me to introduce it; but it's really a no-go for me like in the Twitter app.

**Comment by someoneEsle** [comment]
Let's not forget that when sharing to Wire, there is still no option to start a conversation with someone new, but you can only pick from the active onversations you have. I think this should take priority.

**Comment by bjo81** [comment]
Thanks @ConorIA for this request, I also missed this feature. 

@ffflorian I know several apps where you can en/disable this feature. So if somebody has "big fingers" and fears to share things to the wrong person, he/she could disable it ;)

**Comment by ConorIA** [comment]
@bjo81, I had closed this thinking it was dead in the water. I'll re-open since it seems like there is still user interest.

**Comment by makingthematrix** [comment]
@ConorIA @bjo81 : I guess we can close it now as we have deep links?
Sorry for a superlate answer. The deep links are available in Wire for almost a year now. We're trying to clean up our GitHub issues and that's how I found this issue.
