### ISSUE TITLE
Video chat and multitask 

### ISSUE THREAD

**Issue by reno-a** [wireapp/wire-android#1589]
Hello,
A suggestion: afford (like web app) a video chat and write, import document in same time.
Thank-you

**Comment by someoneEsle** [comment]
Hey,
this should be possible now if you download the latest beta from the play store. Cheers!

**Comment by reno-a** [comment]
Hello @someoneEsle,
I don't find a Beta version in play store.
The last is update to may 24 (version 3.10.442)

**Comment by someoneEsle** [comment]
It sounds like you're not a beta tester then. You can join the beta here: https://play.google.com/apps/testing/com.wire (careful! It's a beta. Join at your own risk)

**Comment by reno-a** [comment]
@someoneEsle , Not an adventurer for the moment... I need that is works correctly. 
Thanks for the link (maybe later)

**Comment by reno-a** [comment]
With the version 3.12.623, messaging while on a call is now available on Wire.
howto: https://support.wire.com/hc/en-us/articles/360001024289-How-can-I-send-messages-while-on-a-call-
