### ISSUE TITLE
Google Play Services is not available in China.

### ISSUE THREAD

**Issue by yaxinlx** [wireapp/wire-android#16]
Is Google Play Services an essential component for wire?
I feel it is not, for it looks I can safely ignore the popup "Get Google Player Services" dialog.

Although maybe Google Player Services is not an essential component, the popup dialog is very annoying.

It would be cool if there is an option to mute the "Get Google Player Services" dialog for ever, :)

btw, great app!

**Comment by hakonbo** [comment]
We have removed the dialog in the upcoming release.
#45
