### ISSUE TITLE
video message is not deleted on other clients when choosing "delete for all".

### ISSUE THREAD

**Issue by tokariu** [wireapp/wire-android#1609]
## The problem

as the title says: video message is not deleted on other clients when choosing "delete for all".

## Environment

* Wire version that exhibits the issue: Android, 3.10.442
* Last Wire version that did not exhibit the issue (if applicable): ....?
* Android OS version used to run Wire: 7.1.2
* Is this a custom firmware or a stock one: LineageOS
* Mobile phone model/manufacturer: LG G3
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): -

## Details

Steps to reproduce:

- Have 2 friends both using Wire for Android on their smartphone.
- One of them records and sends a video to the other directly within Wire (using the record button in the conversation screen at the bottom line)
- the other person is currently offline without mobile-data/wifi. 
- the recorded video was sent successfully, but no received yet.
- after sending the video, i want the video to be deleted, so the sender of the video opens the menu for the video-message and choose "delete for all".
- sometime later the other person gets online and wire still receives the deleted video.
- even after it received the video clip it does NOT get deleted. It gets downloaded and is still available for further viewing (neglecting the delete command).

what should have happened?
- the video shouldn't have been received by the other phone. Either by really not receiving it at all, or by just deleting it instantly after receiving it and getting the delete command.

**Comment by someoneEsle** [comment]
Hi, thanks for the report. Can you reproduce this bug consistently, or was it just a one-time thing? I am trying to reproduce by following your steps but I can't -- the video gets correctly deleted right after being received

**Comment by tokariu** [comment]
I think it's repeatable, but I'll have to wait for my friend to test it again and to be sure.
I think one key point is that the receiver was offline (no mobile data/wifi) at the point of sending the video file AND deleting it again.

**Comment by tokariu** [comment]
I had a 2nd chance to test it, the same person, the same smartphones involved. I did the same procedure as last time step by step. However, this time it worked. The other person did not get the deleted video. Either it was never received or instantly deleted as he got online.

This leaves a bitter taste.. because even if it's worked this time, it might not work next time. How can I be sure it works when it's really needed? If I haven't seen it by myself yesterday, I would say: okay, one time error, won't happen again. But obviously there is a flaw which under certain circumstances prevents the video from deletion.

**Comment by someoneEsle** [comment]
I understand your concern, but unfortunately there isn't much we can do if neither of us can reproduce the bug :/ I believe you when you say that you experienced the bug, and we'll keep an eye out for it, but as of now there really isn't much I can help with. I'll close this issue but please reopen if it happens again!
