### ISSUE TITLE
error during login on android 4.2: "Something went wrong"

### ISSUE THREAD

**Issue by agolks** [wireapp/wire-android#1610]
## The problem

When trying to login on my android 4.2 with my email i only get the generic error "Something went wrong" with message "Please try again".
same wire version works fine on lineageos 14.1, no error message appears.

## Environment

* Wire version that exhibits the issue: 3.10.422
* Last Wire version that did not exhibit the issue (if applicable):
* Android OS version used to run Wire: 4.2.2
* Is this a custom firmware or a stock one: "stock" fairphone 1.8.7
* Mobile phone model/manufacturer: fp1u/fairphone
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): wlan

## Details

i want to activate account on my old fp1u, cause my new one goes to repair. therefore i backed up using titanium backup, but restore on fp1u does not seem to work correctly, only showing blue moving bar at top of wire app and messaging is not working.
so i tried to simply login and then i wanted to restore the backup of the wire conversations. but on login i only see the said error.
i tried without afwall, without xprivacy restrictions, with clean re-install. nothing worked yet.

## Screenshots

![screenshot_2018-06-11-23-50-07](https://user-images.githubusercontent.com/22833941/41259342-8f2e6584-6dd3-11e8-892d-c0ec68e297fb.png)

**Comment by someoneEsle** [comment]
Hi, do you have google play services installed? If so, which version?

**Comment by agolks** [comment]
thought so.
but wouldn't it be possible to patch wire to enable it, see e.g. https://stackoverflow.com/a/33139635?

i'll try, though it's my first android app project...

**Comment by red-avtovo** [comment]
It's already patched. Basically, if your phone can use TLS 1.2, then we force it to use it. But if it's not...
