### ISSUE TITLE
Tracking off but still connects to mixpanel

### ISSUE THREAD

**Issue by feonixrift** [wireapp/wire-android#1611]
## The problem

I turned off tracking in the android app. Wire still connected to mixpanel very frequently.

## Environment

Android.

## To Replicate

Install wire and use a proxy or firewall that lets you see connections to tracking servers (for example Blokada).

## Uhm...

https://github.com/wireapp/wire-android/blob/master/app/src/main/scala/com/waz/zclient/tracking/GlobalTrackingController.scala

Line 75.

Apparently the tracking preference isn't even being read? It's hard-set to true? This is ... problematic.

**Comment by someoneEsle** [comment]
Hi @feonixrift,

Thanks for the report! This is indeed not how it should be. We fixed it [here](https://github.com/wireapp/wire-android/commit/0a60f12caf20eb1a1a70572176d53bb567a1c12e) and we will publish it in the next release of the Android very shortly. It's already in beta.
