### ISSUE TITLE
Wire-Android can't share recorded video (taken from within wire) /  wire removes audio track from shared video if saved before.

### ISSUE THREAD

**Issue by tokariu** [wireapp/wire-android#1628]
## The problem

There is a problem sharing a video with the internal share function.

## Environment

* Wire version that exhibits the issue: Android 3.11.619
* Android OS version used to run Wire: 7.1
* Is this a custom firmware or a stock one: LineageOS
* Mobile phone model/manufacturer: LG G3

## Details

I recorded a video-clip from within Wire and sent it to a contact. Now I wanted to share this recorded video clip with another contact. To do that, i go to the contact to which I've already sent the video and click on it to get to the submenu. Then I select "share". 
Now, usually I get to a list of contacts where I'm able to select the contact I want to share this video with. But this time nothing happens, I get straight back to the conversion. I'm not able to select a contact to share the video. This is repeatable. 

Then I thought if that does not work I have to find a workaround. The workaround was to save the video and then send it as attachment to the other contact. So I saved the video file, then from wire itself or a file explorer (doesn't matter) I send (share with..) this file to the other contact. 
After the File was sent, the video clip does not have an Audio track anymore, just the video. I checked the file I saved and the saved file has the audio track intact. But the shared and sent file got the audio track cropped.

So there is no working way to share a recorded video clip with another person. My solution then was to save the File on a Wire Desktop-Client and resend it from there to the other contact. That worked and the Audio track was intact.

Oh and BTW: while I saw that the sent video clip doesn't have an Audio track I deleted it from the conversion with "delete for all..". And then it got deleted from the conversation BUT ALSO from the directory where I saved the video clip! This is again the Wire bug where Wire deletes the original video source if deleted from the conversion.. This must not happen!

How things should work:
- Selecting "share with.." from a recorded video clip should successfully open the wire-contact list.
- sharing a recorded video clip after it has been saved, should NOT remove the Audio-Track!
- deleting a videoclip from the conversion should not remove the original video source!

**Comment by someoneEsle** [comment]
Duplicate #231
