### ISSUE TITLE
Failure to set up account on Galaxy S3

### ISSUE THREAD

**Issue by 0xfd000000** [wireapp/wire-android#1635]
## The problem

At first, it got stuck while starting - I cleared background apps (freeing RAM from 1G usage down to 800M usage) and then got it to start.
I am trying to create an account that is linked to the phone number. Code is sent and received, entering the code works. On the next screen it asks for the name. After entering the name and pressing "Done" (arrow right), but now it just quits with "An error occured, please try again" (translated from the German "Ein Fehler ist aufgetreten - Bitte nochmal versuchen".

I re-tried the whole procedure after deactivating WIFI but that does not make a difference.

## Environment

* Wire version that exhibits the issue: 3.11.619
* Android OS version used to run Wire: 4.4.2
* Is this a custom firmware or a stock one: stock
* Mobile phone model/manufacturer: Samsung Galaxy S3
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): WIFI+G3

## Details

Try to register a wire account after a fresh install.

**Comment by someoneEsle** [comment]
Hi, I'm not sure how many times you tried to register the account, but it might be that you were able to successfully register (even though the app is misbehaving). Have you tried logging in with phone number?

**Comment by marcoconti83** [comment]
Hi @0xfd000000 ,
thanks for writing this up. There were many changes in the login flow since July, can you try again with the latest build? I believe this has been fixed since then. Thanks!

**Comment by 0xfd000000** [comment]
Hi,
first of all sorry for the late reply...
I'm afraid I can't reproduce the issue since the device in question is not accessible to me anymore. The account has been set up via email in the meantime.
I will however set up another phone in the next days, but I doubt that it would count as reproduce since it is a whole other device with different android version and everything.
Seeing that I seem to be the only one that experienced this particular issue, I guess it's OK to close this as "can't reproduce"?

**Comment by marcoconti83** [comment]
Thanks for updating us!
