### ISSUE TITLE
Latest build is HORRIBLE

### ISSUE THREAD

**Issue by TubaOrNotTuba** [wireapp/wire-android#1636]
Ok, so this isn't a bug report per sé so much as a  "what were you guys thinking" report and forgive me while I'm blunt.

3.12.622 is just terrible.  First, I used the 30 second and 1 minute timers often.  Now they're gone and replaced with a 4 week timer?  That's just ridiculous.  At least just give us a sliding timer like Wickr does and be done with it.  There's just NO reason not to give us a user-selectable timer.

We used to be able to see to the second how much time was left on a msg now it's rounded to the minute. Who thought that was a good idea?

You've still not fixed the long-standing bug where viewed messages, once they timeout, sometimes disappear from the sender's list but most of the time just stay as squiggly lines.  At least give us status options of "sent, delivered, viewed" if you're going to leave stuff around.

We still can't delete old contacts we never want to talk to again or who have left the company. This is just about the #1 complaint for my clients who have looked at Wire.

Why would you apply a conversation specific timer only to groups?  Why would you not extend that to conversations with individuals?  Same code, 2 people rather than many.  Again, what were you thinking?

**Comment by someoneEsle** [comment]
Hi, thank you for your feedback. You made some interesting points and I shared them with the team. Thanks!

**Comment by 2048-Bit** [comment]
@someoneEsle  - Do you know if this has been written up? If not, would you like me to do it so you guys can prioritize it?

"We still can't delete old contacts we never want to talk to again or who have left the company. This is just about the #1 complaint for my clients who have looked at Wire."

**Comment by TubaOrNotTuba** [comment]
I an others have reported this before and the answer we got back was, "we allow you to block those contacts so you don't have to hear from them again".  The problem with that is you end up with a plethora of blocked contacts cluttering up the GUI.  I literally know of no other app where one cannot remove contacts on the fly.  For example, I made the HUGE mistake of clicking on Otto the Bot and now am stuck with it forever.

**Comment by vincegre** [comment]
Only latest build ?? You're joking, that software becomes worse and worse after each builds, it's just insane to insult your users with such bad applications !!
In june I had to delet all history to be able to continue to use the app and support was just insulting me (stating we are aware of it, should be corrected in future........ just jike if it was a very unimportant bug....
And problems are yet worse on iOs platform so it's general !! I thought that Swiss company were professionals but it looks they do the same bullshit than american ones !!

**Comment by kristin-wire** [comment]
@vincegre Sorry to hear - let's get this sorted out. Firstly, please share your support ticket number - so you don't have to repeat the details of bug you reported. From the ticket, I'll be able to tell you the status of the bug. Regarding iOS - we are here, and I personally am happy to hear any feedback you have concerning how Wire can improve.

@TubaOrNotTuba @2048-Bit You're completely right about 'unfriending' contacts. It's a pain point that blocking does not cover.  I can't promise you a timeline for this to get in app, but I can assure you that I raise it regularly to product. Your feedback is heard - and not just by support!

**Comment by TubaOrNotTuba** [comment]
@kristin-wire What about timers?  Seriously, your people need to be told the absolute cardinal rule of niche product programming, "NEVER, EVER remove a feature unless the overwhelming majority of customers ask for it to be removed." In this case, I've never seen a survey from Wire asking us about timing, but what you have no is terrible.  Even Facebook Messenger Secret Messages has better options.  When everyone else is moving forward, Wire just seems to take steps backwards with every release.

**Comment by vincegre** [comment]
@kristin-wire Well there are so many bugs and you add more at each release that it's impossible to list or I'll need a dictionnary ! And official support that don't care at is is also pretty insulting for users !!
It looks like you don't even test your releases before pushing them :(
I fully agree with @TubaOrNotTuba that each release pushes one step backwards in term of stability, and working features :-1:

**Comment by vincegre** [comment]
Thanks for closing a ticket that has been never fixed as app is still as bad one year and a half later !! Very surprised to see that Wire sells pro service with such a bad app.....
