### ISSUE TITLE
3.12.622 timer broken

### ISSUE THREAD

**Issue by TubaOrNotTuba** [wireapp/wire-android#1637]
In 3.12.622, when I'm in a conversation with a single other person, I'll have the timer set to say 5 minutes, because you got rid of the ones I preferred to use for some crazy reason.  If I switch out of Wire to another app and back, about half the time Wire reverts to an untimed messaged, which, of course, if I don't catch it can't be changed to a timed message.  Timing has been a problem in the past.  I don't understand why you keep mucking with timing when it had finally be stable for a few months.  Please don't take 2 months to fix this this time around.

**Comment by someoneEsle** [comment]
Hi, when you opened this issue you saw a template where we kindly ask our users to provide all the necessary information to debug. Unfortunately we cannot help you without such information, so I'll close this issue for now. Feel free to reopen once you provide us with all the details we need to help you.

**Comment by TubaOrNotTuba** [comment]
You guys need to get your policies straight.  Another rep last time told me in a thread I didn't have to follow your template.  If you guys would actually test your builds rather than pushing them out and waiting for us to report your obvious bugs you wouldn't need a templte.  Anyway, I'll create a new thread with the SAME information you callously closed here.
