### ISSUE TITLE
Msg timer resets to untimed messages at random times 

### ISSUE THREAD

**Issue by TubaOrNotTuba** [wireapp/wire-android#1644]
## The problem

In 3.12.622, when I'm in a conversation with a single other person, I'll have the timer set to say 5 minutes, because you got rid of the ones I preferred to use for some crazy reason. If I switch out of Wire to another app and back, a decent % of the time Wire reverts to an untimed messaged, which, of course, if I don't catch it can't be changed to a timed message. Timing has been a problem in the past. I don't understand why you keep mucking with timing when it had finally be stable for a few months. Please don't take 2 months to fix this this time around.

## Environment

* Wire version that exhibits the issue: 3.12.622 AND 1.12.623
* Last Wire version that did not exhibit the issue (if applicable): The build before this, I have no way to know the build #
* Android OS version used to run Wire: 6.0.1 and 7.0.0
* Is this a custom firmware or a stock one: Stock
* Mobile phone model/manufacturer: LG G3
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): WiFi and LTE

## Details

Seriously just use the app with timed messages, it'll happen to you..  Switch between Wire and other apps, say Snapchat or Messenger or just Chrome and come back and the time will reset to untimed about half the time.  There's NO way you can't reproduce this.

## Link to Debug logs

Logs sent.

**Comment by 2048-Bit** [comment]
Its not random. The timer gets reset when you access a timed thread via a push message. If you access the conversation via opening the app and accessing the conversation directly the issue does not occur. I was about to write this up but noticed that someone beat me to it.  

Reproducability:  

- Start a new conversation, set the timer to 5 mins.  
- Backgound the app.
- Have the other person send you a message.
- Access the conversation via the push message.
- Observe the timer is reset to never expire.

**Comment by TubaOrNotTuba** [comment]
Except, until the sender in my conversation thread was downgraded to the latest build, they never sent an untimed message to me so it was me who was accidentally sending them because these last two builds of Wire don't honour the timeout settings.

Honestly, this isn't the first time Wire has messed up timing and whoever decided the new timeout settings were a good idea clearly doesn't use Wire and timed messages.  Wither we need Wickr or Facebook Messenger Secret Conversation timing options, or just leave well-enough alone and go back to the code prior to last week. Stop breaking things that aren't broken.  Focus on the plethora of other bugs that never seem to be addressed. Sorry to be so short here, but as an IT consultant, I have all but stopped showing anyone Wire for a business because things don't get fixed and other things get broken and time to resolve is too long (and then they send you an e-mail asking for screenshots and yet they should know good and well you can't take a screenshot of Wire for Android (which I think is a good thing, but dang, stop asking for what isn't possible)).

**Comment by 2048-Bit** [comment]
@TubaOrNotTuba venting in issue reports really doesn't do anything but clutter facts and cause slower resolution.  

The issue you're describing is very specifically reproducable via the steps I described above. In this case what the other user did or did not do had no bearing on rather the issue occured or not.

**Comment by TubaOrNotTuba** [comment]
@2048-Bit, my apologies, but with all due respect, @someoneEsle didn't seem even remotely concerned when I posted it last week an hour after you guys released the buggy code using the directions I was told to do months ago where another rep told me I didn't have to use the template, it was just a suggestion.  Bugs are bugs.  He should have asked me to elaborate rather than closing a legit bug report and making me reopen a new one.  I could get business customers to sign up, but those I've shown it to have said point blank they'd rather use Facebook Messenger Secret Conversations or WhatsApp (if they don't require timed messages) because they're more feature rich and seem less buggy.

Anyway, I hope you'll go back to the old timing code and stop messing today and rerelease the code with your new code when it's been properly debugged (and add back the other timing options - Golden Rule of programmer, NEVER remove features).

**Comment by someoneEsle** [comment]
@2048-Bit thanks, that is indeed how you reproduce. We found out ourselves a few days ago and have been working on a fix. Thank you for your constructive feedback :)

**Comment by 2048-Bit** [comment]
@someoneEsle thanks. Do you guys have a "dev" branch, or equivilent that I can pull, build and test on?

**Comment by someoneEsle** [comment]
@2048-Bit the fix is in master, so you can build it and test. Thank you for your help and let us know if you find any other bugs!

**Comment by 2048-Bit** [comment]
@someoneEsle the build with master resolved the issue. I can now access my thread via push or traditional methods and my timer does not get reset.  

I'd assume it was this commit: https://github.com/wireapp/wire-android/commit/ea2e977e6818423bcdc00b11c556f99707843f7b  ?

Thanks for the help!

**Comment by someoneEsle** [comment]
It was indeed. Thanks for double-checking!

**Comment by TubaOrNotTuba** [comment]
Do we have an ETA for availability in the Play Store?

**Comment by red-avtovo** [comment]
Next Beta will be next week

**Comment by 2048-Bit** [comment]
@TubaOrNotTuba you can compile it, or if you're getting killed I can send you an .apk I built.  :)
