### ISSUE TITLE
Open conversation Android using intent

### ISSUE THREAD

**Issue by crunchy234** [wireapp/wire-android#1649]
Is there a way to open a conversation using an Intent?

Using the following code you can open a conversation in WhatsApp from another app.
I was just wondering if there is a way to do the same thing with wire.
```.kt
val uri = Uri.parse("wire://send?phone=$number")
val i = Intent(Intent.ACTION_VIEW, uri)
startActivity(i)
```

**Comment by red-avtovo** [comment]
@crunchy234, no we don't provide such functionality

**Comment by crunchy234** [comment]
That's a shame thanks for the quick reply though.
