### ISSUE TITLE
Can't restore back up

### ISSUE THREAD

**Issue by Solarunit** [wireapp/wire-android#1658]
## The problem

I cant find the setting to restore back up.
There is only back up conversations option.

**Comment by someoneEsle** [comment]
Hi, when you log into a new device you should see the option to import an existing backup

**Comment by someoneEsle** [comment]
You should see a page asking you if you want to import a backup after the login page. If you skip that page then, you won't be able to import your backup later

**Comment by Solarunit** [comment]
Ok it is not very convenient i think. So what should I do to access this page? Log out and clear the app cache and data?

**Comment by someoneEsle** [comment]
Yes, clear the app data and you should see that page. Feel free to reopen if you have any problems with that!
