### ISSUE TITLE
Now able to save timed images

### ISSUE THREAD

**Issue by TubaOrNotTuba** [wireapp/wire-android#1674]
## The problem

Wire support was insistent that timed images should not be allowed to be saved when you changed the feature a while back. Now, the ability to save a timed image has returned.  

## Environment

* Wire version that exhibits the issue: 3.14.628 and at least the immediate previous version
* Last Wire version that did not exhibit the issue (if applicable): Unsure, 2 or 3 versions ago
* Android OS version used to run Wire: 7.0, 7.1.1, and 6.01
* Is this a custom firmware or a stock one: Stock
* Mobile phone model/manufacturer: LG, Motorola
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/Wi-Fi doesn't matter

## Details

Send a timed image, tap the image, the option to save is there.

## Link to Debug logs

Create a [GIST](https://gist.github.com) which is a paste of your Wire logs, and link them here.
It is recommended to directly contact our [customer support](mailto:support@wire.com) and send the debug report by email, because it can potentially contain some private information, that you don't want to share to the public.

## How to send detailed debug report from Wire:

1. Go to Settings -> About
2. Tap "Wire swiss GmbH" 10 times
3. Reproduce your issue
4. Send the report from Settings -> Advanced -> Submit debug report
5. Go to Settings -> About
6. Tap "Wire swiss GmbH" 10 times again to disable detailed debug reports, because this slows down Wire

## Screenshots

Please attach screenshots if you consider them as helpful to understand/reproduce the issue

**Comment by someoneEsle** [comment]
We allow users to save their own images by design

**Comment by TubaOrNotTuba** [comment]
@someoneEsle , if someone SENDS me a timed image I should NOT be able to save it.  If I SEND someone a timed image they should NOT be able to save it.  This is not about me being able to save my own images, it's about the images sent/received by the other side.  Reopen this bug.

**Comment by someoneEsle** [comment]
The steps to reproduce you provided are

> Send a timed image, tap the image, the option to save is there.

And this is by design. If you can save incoming images or if your contacts can save your images, then that's another problem. If that's the case, please provide the steps to reproduce
