### ISSUE TITLE
Images in conversations get stretched unproportionately since latest version.

### ISSUE THREAD

**Issue by tokariu** [wireapp/wire-android#1675]
## The problem

Images I received from my friends in the conversation are now displayed stretched. the aspect ratio is wrong. if you have person on the image, it looks twice as "wide/fat" as normal. this used to work correctly in earlier versions.

## Environment

* Wire version that exhibits the issue: 3.12.623
* Last Wire version that did not exhibit the issue (if applicable): 3.11.x
* Android OS version used to run Wire: android 5.1 + android 7.1
* Is this a custom firmware or a stock one: stock + custom.

**Comment by TubaOrNotTuba** [comment]
I see that too.  Very distracting.

**Comment by someoneEsle** [comment]
Hi, thanks for reporting. We're already working on a fix!

**Comment by someoneEsle** [comment]
This issue should be fixed now, but feel free to reopen if it happens again!
