### ISSUE TITLE
Error:Execution failed for task ':app:transformClassesWithDexForAvsDebug'.

### ISSUE THREAD

**Issue by alirezapir** [wireapp/wire-android#168]
I Get This Error When Trying to Run the Project. 

Error:Execution failed for task ':app:transformClassesWithDexForAvsDebug'.

How Can I Solve This?

**Comment by hakonbo** [comment]
Hey @alirezapir 

Please check out #177 where I describe how to build from command line. Once you get that working and you want to use Android Studio, make sure you set the correct build variant. Go to menu View -> Tool Windows -> Build Variant and in that window set build variant to "devDebug" for "app" module and "debug" for all others.
