### ISSUE TITLE
Error while restoring from backup

### ISSUE THREAD

**Issue by Lorak-mmk** [wireapp/wire-android#1682]
## The problem
I am currently migrating from Xiaomi MI3 to Samusng Galaxy S5 neo. After making backup of conversations and moving the file to new device, I log in, select "Restore from backup", select backup file. After selecting file, a window pops out saying "Something went wrong  Your history could not be restored"

## Environment

* Wire version that exhibits the issue: 3.14.628 (on both devices)
* Last Wire version that did not exhibit the issue (if applicable): not applicable
* Android OS version used to run Wire: 6.0.1 (both devices)
* Is this a custom firmware or a stock one: Both stock (MIUI on old, whatever Samsung is using on new)
* Mobile phone model/manufacturer: Old: Xiaomi MI3, New: Samsung Galaxy S5 neo
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): WiFi, both

## Details

I don't think I can provide any more details, I explained everything already. 

## Link to Debug logs

I don't know if it is going to be useful, as I have to log out to reproduce the issue. 
[Debug log](https://gist.github.com/Minemaniak/0912b203675f85dc900e6393b76072da)

**Comment by someoneEsle** [comment]
Hi, thanks for reporting. Where are you loading your backup from?

**Comment by Minemaniak** [comment]
From internal memory (exact location: /storage/emulated/0/Wire-mmk1-Backup_20180722.android_wbu)

**Comment by HerroBert** [comment]
Almost same problem to me. Restore does simply nothing. History is not shown.

**Comment by makingthematrix** [comment]
Probably related to this: https://github.com/wireapp/wire-android/pull/2577
The fix will be included in the next release.
