### ISSUE TITLE
Call notification is stuck

### ISSUE THREAD

**Issue by Wouterdek** [wireapp/wire-android#1683]
## The problem

When I am called, or make a call to someone else, a calling notification is added. When the conversation ends, or even when I don't pick up the call, the notification is stuck and cannot be removed without force quitting the app. Pressing the notification briefly opens the app and then closes it again.

## Environment

* Wire version that exhibits the issue: 3.14.628
* Last Wire version that did not exhibit the issue (if applicable): N/A
* Android OS version used to run Wire: 5.1
* Is this a custom firmware or a stock one: stock
* Mobile phone model/manufacturer: Motorola Moto G 
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi

## Details

Either make a call, or get called through Wire. After the call ends, either because the conversation ended or because you did not pick up, look in the notification area. The notification is still there and cannot be swiped away. Pressing the notification does not remove it, but briefly opens and then closes the app. Pressing answer on a stuck "being called" notification, starts a new call to the person who's call was missed. (This produces a new "calling" notification that replaces the previous one and also cannot be removed.)

## Link to Debug logs
I have sent the log through email.

**Comment by Quarrym** [comment]
Exactly the same thing - Android 5 and call notification stucks.
