### ISSUE TITLE
zero gapps

### ISSUE THREAD

**Issue by GavelRust** [wireapp/wire-android#17]
I cannot use google apps.  Where do I download the apk without using sketchy mirror sites?

**Comment by est31** [comment]
Related: #5. Not depending on play services is one of the blockers for inclusion into the main f-droid repo.

**Comment by hakonbo** [comment]
You can download the APK directly from [wire.com/download](https://wire.com/download/). This is the same APK as served from Play Store. You will need to handle updates manually for the time being. The app uses Google Play Services for push notifications and location messages, other functionality will still work without it.
