### ISSUE TITLE
App not receiving push notifications when device is sleeping

### ISSUE THREAD

**Issue by komo81** [wireapp/wire-android#170]
Hi, when my device is sleeping (screen is locked etc.) then app is not receiving push notifications with messages. Only call notifications are received. Does your server send push with delay_while_idle=0?

**Comment by RexHackbro** [comment]
@david-wire 2 contacts from me suffer also under this issue, I not.

**Comment by hub-ch** [comment]
https://github.com/wireapp/wire-android/issues/777#issuecomment-466763316

**Comment by marcoconti83** [comment]
Hi all,
there are a lot of duplicated issues covering this same problem (or a very similar one), let's unify all conversations and keep it going here: #777 . Closing this one and continuing there.
