### ISSUE TITLE
Otto The bot We miss you

### ISSUE THREAD

**Issue by golan789** [wireapp/wire-android#1704]
![8736538](https://user-images.githubusercontent.com/42124844/43691224-92cc108a-9919-11e8-883b-8ede7f36564d.png)
![1_otto-compressor](https://user-images.githubusercontent.com/42124844/43691226-98e8ad16-9919-11e8-9433-390a71876972.jpg)
![wire_test_moritz_1-w810h462](https://user-images.githubusercontent.com/42124844/43691229-a25b5240-9919-11e8-97a5-8b0feb6efa5b.jpg)

**Comment by mMuck** [comment]
Although this seems to be a bit emotional I think Otto the Bot was a feature to get a great first UX. Some features needs explanations. This job was well implemented, i think.
Why is this discontinued?

**Comment by marcoconti83** [comment]
Hi all,

Otto was an experiment at UX that we wanted to try out. In the end, we got more negative feedback about Otto than positive. It served a purpose, but it was also causing a lot of confusion and distraction, so while the idea was good, we decided to retire it until we can work on a better implementation of this idea.
