### ISSUE TITLE
[Feature Request] Disable Creating Previews

### ISSUE THREAD

**Issue by Fidgetcetera** [wireapp/wire-android#1724]
## The problem

On wire's web/desktop app, you are able to turn off creating link previews for links you send. On android, that setting doesn't exist. I'd like to be able to have an expected parity between what my sent messages do between devices.

## Environment

* Wire version that exhibits the issue: 3.15.634
* Last Wire version that did not exhibit the issue (if applicable): N/A
* Android OS version used to run Wire: 8.1.0
* Is this a custom firmware or a stock one: Stock
* Mobile phone model/manufacturer: Google Pixel 2
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): All

## Details

There's not much to say here. Add a "create previews for links you send" checkbox in the settings to match the one in options on the web app.

**Comment by marcoconti83** [comment]
Hi @Fidgetcetera ,
I'm trying to consolidate old tickets, there is already an ongoing discussion about this topic here: https://github.com/wireapp/wire-android/issues/1934, let's continue the discussion there!
