### ISSUE TITLE
Text Input field way too small

### ISSUE THREAD

**Issue by axel-rank** [wireapp/wire-android#1726]
The message input field should be bigger, should be resizable, or expanding while typing your text message.
Would be better for overview.

* Wire version that exhibits the issue: 3.15.634
* Android OS version used to run Wire: 7.1.2

**Comment by someoneEsle** [comment]
Thanks for reporting, should be fixed now!

**Comment by kroerig** [comment]
I cannot confirm what has been fixed.

On my mobile I can only type two rows of text until the text scrolls out of the input field.

**Comment by marcoconti83** [comment]
Reopening this one, and linking to: https://github.com/wireapp/wire-android/issues/1900

**Comment by BradleyWire** [comment]
A change has been merged and we'll be tracking this through a feature request raised here: https://github.com/wireapp/wire-android/issues/2289
