### ISSUE TITLE
In a call, notification bar states "UKNOWN"

### ISSUE THREAD

**Issue by ffflorian** [wireapp/wire-android#173]
Wire version: 2.16.282
Android 6.0.1 (CM 13)

I registered on Wire without phone number and my friend did, too.  When I call him, I don't see his name in the notification bar, I only see "UKNOWN - Calling". I also don't have my friend's email address in my contacts.

I found the string in [`CallingNotificationsController.scala`](https://github.com/wireapp/wire-android/blob/master/app/src/main/scala/com/waz/zclient/notifications/controllers/CallingNotificationsController.scala#L86).

![wire](https://cloud.githubusercontent.com/assets/5497598/18814638/07e919c0-831a-11e6-9e5f-e9e0d1380064.png)

**Comment by deanrobertcook** [comment]
Thanks @ffflorian for reporting, this should be fixed now.
