### ISSUE TITLE
Share/forward attachment with non-conversation contact

### ISSUE THREAD

**Issue by peterpanondrugs** [wireapp/wire-android#174]
Steps to reproduce:
- try to share/forward an attachment to a contact, u don't have a conversation with
- its impossible to share/forward that attachment 
  So to resolve this, u first need to start/have a conversation with your contact.

How it should look:
- Give the option to choose all contacts in your list while sharing/forwarding attachments.

[wire_debug_report.txt](https://github.com/wireapp/wire-android/files/492855/wire_debug_report.txt)

**Comment by mykola-mokhnach** [comment]
What is non-conversation contact? Do you mean a contact, which is not directly connected to you, but participates in some common group conversation?

**Comment by peterpanondrugs** [comment]
Its fixed by the option to choose contacts from a list. thx
