### ISSUE TITLE
UnsatisfiedLink error: “wcall_set_video_send_state” when attempting video calls

### ISSUE THREAD

**Issue by elletlar** [wireapp/wire-android#1747]
## The problem

1. Click on contact
2. Press video icon at top to initiate a video call:

The following error appears in logcat:
"E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo(), pcm_get_htimestamp fail, ret = -1, pcm_get_error ="

The only version I've been able to get working audio and videos calls on is:
 2.40.357

This version at least initiates calls even though it crashes quite often.

## Environment

* Happens in both master and release branches
* Android 8.0
* Stock phone
* Sony Xperia XA1
* WIFI

## Details

Android 5:

08-24 22:53:29.877 296-881/? E/FastThread: did not receive expected priority boost

Android 8:

08-24 23:10:02.190 406-4592/? E/AudioALSAPlaybackHandlerBase: -getHardwareBufferInfo(), pcm_get_htimestamp fail, ret = -1, pcm_get_error =

Android 9 Emulator:

08-25 19:56:58.425 1583-3268/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 4108693 , only wrote 4108320

**Comment by JimmyTinsley** [comment]
Same problem here

**Comment by deanrobertcook** [comment]
@elletlar Thanks for the report!

Should be fixed in https://github.com/wireapp/wire-android/commit/4714bf476c68174c6da3d2781360eb62d52665c8

Please let us know if that's not the case!
