### ISSUE TITLE
No ringing

### ISSUE THREAD

**Issue by reno-a** [wireapp/wire-android#1751]
when I call or receive call the phone don't ring. (It's OK with the old Wire version). 
---
App Wire version 3.16.638

**Comment by someoneEsle** [comment]
We need you to provide us with more meaningful information (e.g. phone model, OS, etc) in order for us to help you. Do you actually receive the call, but without sound? Or do you not receive incoming calls at all? Please be more specific as to how you reproduce the issue.
Thanks!

**Comment by reno-a** [comment]
@someoneEsle Hello,
Smartphone : Motorola "moto G3"
System : Lineage OS 14.1 (Android 7.1.2) , update 25/08/2018

**Comment by reno-a** [comment]
I tested Wire in th Web browser and it seems OK, it's ringing.
Now, I don't know why, it's ringing also on the smartphone (a cause and effect?).

**Comment by reno-a** [comment]
Version 3.50.922 (and after a little before), it's OK. No more problem.
