### ISSUE TITLE
Release version 2.41.359 crashes every time the app is opened

### ISSUE THREAD

**Issue by elletlar** [wireapp/wire-android#1754]
## The problem

The most recent non-beta release version 2.41.359 crashes every time I attempt to open the app.

## Environment

* Wire version that exhibits the issue: 2.41.359 
* Last Wire version that did not exhibit the issue (if applicable):  2.40.357
* Android OS version used to run Wire:  Android 8.0
* Is this a custom firmware or a stock one: Stock
* Mobile phone model/manufacturer: Sony XA1
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): WIFI

## Details

The app initially runs normally and allows login, but always crashes after the edit devices screen. The app then crashes every time that you try to open it with the same  stack:

08-25 14:51:02.142 29066-29109/? E/AndroidRuntime: FATAL EXCEPTION: Thread-4 Process: com.wire, PID: 29066 java.lang.NullPointerException: Attempt to invoke interface method 'int com.waz.call.RequestHandler.request$1d4ff469()' on a null object reference at com.waz.call.FlowManager.request(FlowManager.java:365)

**Comment by someoneEsle** [comment]
Hi, the latest version is actually 3.16.638. Please update and reopen this issue if the problem persists. Thanks!
