### ISSUE TITLE
Voice and video connection failure

### ISSUE THREAD

**Issue by davidaxing** [wireapp/wire-android#1757]
The problem
1.Click on contact
2.Press video icon at top to initiate a video call:

Environment
1.Samsung S7 Android 8.0
2. Windows 10
3.Android Studio2.3
4. gradle 2.14.1
5. wire-android release    wire-android-sync-engine master v121

BUG
08-30 15:31:27.000 2058-2140/com.chatbox E/AVS: ERROR ; (15:31:27: 0 | 0) AUDIO DEVICE: 1 99; 2140; stereo playout is not supported
08-30 15:31:27.009 2058-2140/com.chatbox E/AVS: ERROR ; (15:31:27: 5 | 4) AUDIO DEVICE: 1 99; 2140; failed to enable stereo recording
08-30 15:31:27.316 2875-2875/? A/DEBUG: #8 pc 001712e8 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #9 pc 00130190 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #10 pc 000720b8 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #11 pc 00090af8 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #12 pc 000907d8 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #13 pc 0008af80 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #14 pc 0008b040 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #15 pc 0007dfa8 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #16 pc 0006dd08 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #17 pc 0006f674 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #18 pc 0025bfe0 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #19 pc 00259e98 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #20 pc 00064dd8 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:32.904 3008-3065/com.chatbox E/AVS: mediamgr_set_sound_mode failed

**Comment by davidaxing** [comment]
The problem
1.Click on contact
2.Press video icon at top to initiate a video call:

Environment
1.Samsung S7 Android 8.0
2. Windows 10
3.Android Studio2.3

BUG
08-30 15:31:27.000 2058-2140/com.chatbox E/AVS: ERROR ; (15:31:27: 0 | 0) AUDIO DEVICE: 1 99; 2140; stereo playout is not supported
08-30 15:31:27.009 2058-2140/com.chatbox E/AVS: ERROR ; (15:31:27: 5 | 4) AUDIO DEVICE: 1 99; 2140; failed to enable stereo recording
08-30 15:31:27.316 2875-2875/? A/DEBUG: #8 pc 001712e8 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #9 pc 00130190 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #10 pc 000720b8 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #11 pc 00090af8 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #12 pc 000907d8 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #13 pc 0008af80 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #14 pc 0008b040 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #15 pc 0007dfa8 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #16 pc 0006dd08 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #17 pc 0006f674 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #18 pc 0025bfe0 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #19 pc 00259e98 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:27.316 2875-2875/? A/DEBUG: #20 pc 00064dd8 /data/app/com.chatbox-gjL4OzPUt6ShxCTroTw4Qw==/lib/arm/libavs.so
08-30 15:31:32.904 3008-3065/com.chatbox E/AVS: mediamgr_set_sound_mode failed

**Comment by hub-ch-NetE1** [comment]
This issue fixed so you can try again and follow instruction here https://github.com/wireapp/wire-android/issues/1892 further.

**Comment by marcoconti83** [comment]
Hi @davidaxing ,
if this is about the self-compiled client, then please try again with the latest version. The calling library has been bumped and it should work know. 
I'm closing the issue; if this still happens, please reopen let us know more details: does the client crash? does the call get stuck in the "connecting" state? does the call never ring?
