### ISSUE TITLE
Version 3.16.638 seems to have disabled the notification LED

### ISSUE THREAD

**Issue by neroux** [wireapp/wire-android#1762]
## The problem

As of 3.16.638 it seems as if incoming messages do not trigger the notification LED any longer. The message is still shown within the notification bar but there is no LED flashing.

## Environment

* Wire version that exhibits the issue: 3.16.638
* Last Wire version that did not exhibit the issue (if applicable): Cant tell I am afraid, either the previous version or one earlier
* Android OS version used to run Wire: 7.1.2
* Is this a custom firmware or a stock one: LOS 14.1 (Aug 23 build with the August patches)
* Mobile phone model/manufacturer: Nexus 5
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): N/A

**Comment by neroux** [comment]
Thanks for the categorisation, @someoneEsle. Would you have any estimate of how quickly that most likely might get fixed? Next version already or would it take more time?

**Comment by someoneEsle** [comment]
We just pushed a beta with a fix. Sorry I didn't reply earlier. Let us know if you're still experiencing the problem after the update!
