### ISSUE TITLE
change server domain on android client

### ISSUE THREAD

**Issue by wihteHeart** [wireapp/wire-android#1771]
## The problem

when i build my own android client how can i change the domain that android client use to communicate with server

**Comment by elyasimo** [comment]
Hello,
i need your help, i have compiled the android app, how can i change wire server to my local server?

regards, elyas

**Comment by marcoconti83** [comment]
Hi all,
you can change the values in [default.json](https://github.com/wireapp/wire-android/blob/master/default.json).
