### ISSUE TITLE
call icons not visible but it's possible to make a call

### ISSUE THREAD

**Issue by pluschris** [wireapp/wire-android#1785]
## The problem

On the same device for one contact wire does show the call icons in the upper right corner and for another contact it doesn't. But: If you get a message from the contact without call icons, you can establish a call without any problems with the button under the quick notification.

**Call icons visible:** 
![screenshot_20180910-205142](https://user-images.githubusercontent.com/15850620/45318722-07e75100-b53e-11e8-92b9-bbc33effaba3.png)
(Hint: I deleted the contact-information/messages.)

**Call icons not visible:**
![screenshot_20180910-205117](https://user-images.githubusercontent.com/15850620/45318727-0ddd3200-b53e-11e8-994b-4761288449f4.png)
(Hint: I deleted the contact-information/messages.)

## Environment

* Wire version that exhibits the issue: 3.16.638
* Last Wire version that did not exhibit the issue (if applicable): ---
* Android OS version used to run Wire: 7.1.2
* Is this a custom firmware or a stock one: custom
* Mobile phone model/manufacturer: Samsung Galaxy S II
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi

## Details
The bug is always present, no special steps needed to reproduce.

**Comment by someoneEsle** [comment]
Hi, thanks for reporting. Did you by any chance just recently connect to this contact?

**Comment by someoneEsle** [comment]
What I meant is, did you recently send a connection request to this user/received a connection request from this user? I'm not talking about calling, I'm asking if you've just recently become "friends" with this contact on Wire.

**Comment by pluschris** [comment]
Oh, now I got it. Yes, we became "friends" just a few days ago. But that is true for the contact with the icons and the one without. Could be that there was one day between adding them.

**Comment by MihailRussu** [comment]
Just had the exact same issue happen on an Android phone (could not initiate calls to any of the contacts, all are recently added). Removing the app completely and reinstalling it again seemed to help (the audio and video buttons are now back).

**Comment by red-avtovo** [comment]
Hi @pluschris and @MihailRussu! Do you still experience this issue or it was resolved with latest release?

**Comment by pluschris** [comment]
Hi,
I reinstalled the app already in September as @MihailRussu  suggested. After reinstalling, the icons appeared.

**Comment by MihailRussu** [comment]
> Hi @pluschris and @MihailRussu! Do you still experience this issue or it was resolved with latest release?

Hi @red-avtovo, the icons were back after removing and re-installing the app so I can't really comment whether the latest release fixed the issue or not.

**Comment by red-avtovo** [comment]
@MihailRussu thank you for clarifying. I will close this ticket in that case
