### ISSUE TITLE
No notification when a new device gets linked to my account

### ISSUE THREAD

**Issue by skollmann** [wireapp/wire-android#18]
The web app and the iOS app show a green dot next to the cogwheel symbol when a new device was linked to my account, and a notice when I click on it. This is missing in the Android app (v2.12.263).
This seems important for security reasons, because (as I understand it) otherwise anyone with access to the Wire server could just link/unlink devices without the user noticing.

**Comment by hakonbo** [comment]
Added in #21. You will also get an email if a new device is added, this has always been there, so you should get notified even if you don't open the app.
