### ISSUE TITLE
[Bug] Restore backup not implemented for two or more accounts

### ISSUE THREAD

**Issue by ghsrcgh** [wireapp/wire-android#1819]
## Steps to reproduce

1. I have two accounts in WIRE. I had backuped them, so WIRE created two wbu-archives, one is for one account and the second for another one.
2. I had moved these two wbu-files to a new device. I had make a fresh installation of WIRE.
3. Following instruction, I had logged in with the one of the accounts (the second).
4. After logged in, WIRE asked me "do you want to restore from backup?". I had answered yes and I had selected backup file for the second account.
5. History were recovered as planned. (Really not, because of #305 - but it is another bug)
6. And now I want to restore the first account, which have more history...
7. I found at the top of WIRE window that... my second account icon (avatar/etc) were restored too!!! (When I used restore from the second account file -- why it contain information about the first account?! It is a BUG-1).
8. OK, I had taped on this avatar and WIRE show to me blured user list. Than it.... hangs (BUG-2)
9. I had closed it and restart. Now WIRE asked me to enter Password to login to the first account (not restored from backup)
10. I had entered the password for this account.
11. I expected to see the message "do you want to restore from backup?" and select to file for restore the first account's history. But... NOTHING! WIRE just loaded contact list from account. EVERY contact have empty history, of course. Because backup for the first account were never restored (processed) (BUG-3)
12. Moreover, few seconds later WIRE hanged again (BUG-4) and restart of the app were required.

The main bug and the issue, that you CANNOT restore more than one account from backup.
Also, you have no possibility to ask WIRE to restore backup if WIRE did not asked you "do you want to restore"? There is no such menu item like "restore from backup" (with questions like "anyway? overwrite?").

So, I had lost the main account history. Because I have backup, but now I CANNOT restore from it. Because WIRE just do not asking me to restore!

## Additional steps

OK, I had tried to find the workaround.
1. I taped on my account that is now "empty" and clicked "Logout".
2. Then I clicked on "Add account" and logged in again with that account.
3. Now WIRE asked me(!) "do you want to restore from backup?"
4. I had selected yes, and selected a big wbu-file for that account (more than 70mb)
5. WIRE had restored something (LIKE RESTORED, but really - NOT)
6. I got my contact list. Taped on every user and... found nothing! The same empty chats without any restored messages. Just my contact list and every user/groups are empty! With the message "you had started to use this device".

That is terrible!

How to restore my backup for the first (main) account from wbu-file?!

## Environment

* Samsung Galaxy S9
* Android 8.0
* WIRE 3.19.654

**Comment by ghsrcgh** [comment]
Will someone fix this? No one touched.

I had today other steps from previous state:

1. I had click "logout" from my second (small) account on this device and I expected to do the same from my first account, but... after logging out from the second account WIRE had shown me that he have no any accounts logged in! And asked me: create common, create pro or login to exist account. WTF? There is very large amount of buts with working with two or more accounts. They all are connected between each other and produce other bugs.

2. OK. I decide now to login only to the first account and restore from the backup first account at first, to check will it be restored fully? I logged in to the first account, selected to restore main backup and... Yes, it was restored successfully. Then I thought to login to the second account and try to restore it from its small backup. I had entered login information, clicked to restore from its backup and... The second account receive a "chats" from the first account (users!), but all of them were blured. No any messages, and do not possible to select any chat in this account. The first account worked well. So, it is TOTALLY not working.

3. OK. I decide to lost a backup of the second account. Logged out again. (When logouting from one account, it automatically logouting from both - very strange behavior, it is bug! Or maybe they are linked because of such restore-from-backup procedure, I do not know). So, I had logged in in the first account, restored it from backup. And then logged in to the second account, but SKIPPED restore function. Now both accounts are working will, but I lost all of my messages in the second account (because I cannot restore it from backup, because of the bugs mentioned above!)

**Comment by wellinkstein** [comment]
Hi,
I have two accounts set up on Wire and tried to reproduce your issue.

1. I made a backup for both accounts. These backups were fairly small, about 300 KB for the biggest one.

2. I logged out from my first account, it did not log out the other one.

3. I logged out from the second account.

5. I logged in with the first account, Wire asked for a backup and restored it successfully. The only issue I witnessed is that the conversations are not in the correct order and I guess it will fix itself when I'll receive new messages.

6. I logged in to the second account, Wire asked me to use a backup to restore and it worked.

I was not able to reproduce any of the issues described previously.

###Environment

* Moto G5
* Wire 3.21.661
* Lineage OS 15.1

**Comment by fbruetting** [comment]
For me it did not work when I logged in via my phone number, as I was not asked at all, if I want to restore my backup. When I then tried it again by logging in with my mail account, that worked. Please fix!

There also is no option for manually importing the backup in the options! As the backup seems to just be a historic key for accessing an older point in the ratchet history, I think this should not be a huge issue to do, as just additional data would be loaded. Would be cool if this could also get fixed, as it is related!

**Comment by makingthematrix** [comment]
Hi, @ghsrcgh , @fbruetting 
With the new release, 3.55, we finally have new backups functionality in place. Please try it out!

**Comment by makingthematrix** [comment]
Okay then 🤷
