### ISSUE TITLE
Timed messages cannot be edited – but deleted only

### ISSUE THREAD

**Issue by x80486** [wireapp/wire-android#1827]
## The problem

I started using timed messages since there is no point (for my case) to have a long message history...but I've noticed that messages cannot be edited! Is that intended or just a side effect on the mobile app?

## Environment

* Wire version that exhibits the issue: 3.19.654
* Last Wire version that did not exhibit the issue (if applicable): -
* Android OS version used to run Wire: 8.1.0
* Is this a custom firmware or a stock one: Stock Android
* Mobile phone model/manufacturer: Google Nexus 6P
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE or Wi-Fi

## Details

Just set the timer (I use a day) and send a message :wink:

**Comment by someoneEsle** [comment]
Hi, this is by design. Thank you for your feedback though!
