### ISSUE TITLE
Why connections to Amazon Web Services (AWS)

### ISSUE THREAD

**Issue by baimafeima** [wireapp/wire-android#1842]
Why is the Wire android app attempting to connect to Amazon Web Services all the time? I thought you have your own cloud computing infrastructure. Amazon isn't exactly a reasonable choice when it comes to privacy.

**Comment by red-avtovo** [comment]
Hi @baimafeima, thank you for your message. As you could find, we are hosting our servers on AWS and that's why Wire android client is sending so many requests to it.
I will close the ticket if you don't mind as soon as question is answered

**Comment by baimafeima** [comment]
@red-avtovo Please don't use AWS but look for a more privacy-friendly alternative.
