### ISSUE TITLE
[build failure] CallingFragment.scala:81: value setShouldFill is not a member of com.waz.avs.VideoRenderer

### ISSUE THREAD

**Issue by cdbg** [wireapp/wire-android#1844]
## The problem
[build failure] CallingFragment.scala:81: value setShouldFill is not a member of com.waz.avs.VideoRenderer

## Environment

OS used for build: Gentoo, Debian

JDK:
java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
same with icedtea and openjdk

Android SDK:
Android SDK Build-Tools 27.0.3, Android SDK Platform 27, rev 3

## Details
An error occured when building latest snapshot from git (release and master)
 > Task :app:compileProdReleaseJavaWithJavac 
The CompileOptions.bootClasspath property has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the CompileOptions.bootstrapClasspath property instead.
The TaskInternal.execute() method has been deprecated and is scheduled to be removed in Gradle 5.0. There are better ways to re-use task logic, see https://docs.gradle.org/4.4/userguide/custom_tasks.html#sec:reusing_task_logic.

/home/neuromancer/src/wireapp/wire-android/app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala:80: value setShouldFill is not a member of com.waz.avs.VideoRenderer
            vr.setShouldFill(false)
               ^
/home/neuromancer/src/wireapp/wire-android/app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala:81: value setFillRatio is not a member of com.waz.avs.VideoRenderer
            vr.setFillRatio(1.5f)
               ^
/home/neuromancer/src/wireapp/wire-android/app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala:83: value setShouldFill is not a member of com.waz.avs.VideoRenderer
            vr.setShouldFill(true)
               ^
/home/neuromancer/src/wireapp/wire-android/app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala:84: value setFillRatio is not a member of com.waz.avs.VideoRenderer
            vr.setFillRatio(1.0f)
               ^
four errors found

>FAILURE: Build failed with an exception.

* What went wrong:
>Execution failed for task ':app:compileProdReleaseScala'.
> Compilation failed

* Try:
>Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log >output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

>BUILD FAILED in 1m 15s
>32 actionable tasks: 4 executed, 28 up-to-date`

Steps to reproduce:
git clone https://github.com/wireapp/wire-android && cd wire-android && git checkout release && ./gradlew assembleProdRelease
even if ./gradlew assembleProdRelease called several times.

**Comment by suarezu** [comment]
same here, anything we missed?

**Comment by deanrobertcook** [comment]
@cdbg thanks for the report,

This should be fixed in: https://github.com/wireapp/wire-android/commit/4714bf476c68174c6da3d2781360eb62d52665c8
