### ISSUE TITLE
FEATURE REQUEST: the ability to specify a proxy or a domain front.

### ISSUE THREAD

**Issue by Viss** [wireapp/wire-android#1847]
## The problem

There are oppressive regimes around the world that block access to secure messengers. UAE is one of them. To permit people living in these oppressive regimes access to use wire, having an 'advanced menu' somewhere in the settings to specify a new route to get to wire would be amazing.

For example: I've created a cloudfront domain on aws which points at wire: https://d34tz01ix2eicj.cloudfront.net/

If you go to that url you can use wire in the browser just like you would otherwise. 
I'd love the ability to change the endpoint for wire in the android client to use the fronted domain (or an actual real domain front). You can do this, too:

curl -H 'Host: d34tz01ix2eicj.cloudfront.net' https://amazon.com

and get to wire. 
but the network traffic will show you're browsing amazon, because the host header is wrapped inside of ssl.

**Comment by red-avtovo** [comment]
Hi @Viss, thank you for your proposal!
We don't have any plans doing that feature right now. Maybe later wi will pick that up

**Comment by Mikaela** [comment]
Does anyone else than Azure support domain fronting anymore? I think more relevant issue would be using [encrypted SNI](https://github.com/tlswg/draft-ietf-tls-esni).

**Comment by makingthematrix** [comment]
Users are now able to change the backend address with a deeplink:
1. Install Wire and open it first (a technical issue requires that; in the near future it might not be needed anymore).
2. On the side, e.g. in a markdown editor, prepare a link which after clicking will open something like `wire://access/?config=https://blabla.bla`
3. Click on the link. This will open Wire and replace the backend address. Now you should see the registration/login screen for the new backend.
