### ISSUE TITLE
Switch to dark mode

### ISSUE THREAD

**Issue by MartinDelille** [wireapp/wire-android#1854]
## The problem

I want to switch to dark mode because the default design is to bright

## Environment

* Wire version that exhibits the issue: latest
* Last Wire version that did not exhibit the issue (if applicable): ?
* Android OS version used to run Wire: 
* Is this a custom firmware or a stock one: non
* Mobile phone model/manufacturer:
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): wifi

## Details

I just want to switch to dark mode

## Link to Debug logs

Since this is not a bug, I'm not sure you need that

**Comment by red-avtovo** [comment]
Hey @MartinDelille, thank you for you message. 
Please try to activate Dark theme, by going to `Settings` in Wire app, then select `Options` and switch toggle `Dark theme`

**Comment by MartinDelille** [comment]
Ok sorry I missed that.

You have a pretty nice UI by the way!
