### ISSUE TITLE
"no internet connection" error message when logging in on Android 4.2.2

### ISSUE THREAD

**Issue by strypey** [wireapp/wire-android#1867]
## The problem

I've just downloaded the Android app from your website and installed it on a device running Android 4.2.2. It launches fine, and invite me to login. When I enter my login details and try to login, I get an error message saying "No Internet Connection". This isn't the case though, as I'm able to browse normally using the web browser both before and after getting this error message. I wonder if the problem might be related to issue https://github.com/wireapp/wire-android/issues/1610

## Environment

* Wire version that exhibits the issue: 3.20.659
* Android OS version used to run Wire: 4.2.2
* Is this a custom firmware or a stock one: stock firmware
* Mobile phone model/manufacturer: Vodafone 785
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi

I'm happy to dig out and send debug logs etc, but I'll wait to see if this is actually necessary. First, is Wire supported on 4.2.2 (the website suggests 4.2+ is supported if I remember rightly)? Is there an obvious fix someone can suggest?

**Comment by strypey** [comment]
PS I love Wire and I'm filing this bug with the goal of helping your team support as many OS versions as humanly possible. Even if this problem can't be resolved at present, it would be good to change the error message to something that more accurately explains the nature of the problem to the user.

**Comment by strypey** [comment]
Please note, the problem I described was on an Android/Linux device that had been factory reset, and I hadn't provided a Google account for downloading updates. After I was able to use Yalp to download updates to a number of updates for my Android/Linux system, this seems to have resolved the problem. I've successfully logged into the Wire app and received and sent both messages and voice calls. The only issue that remains is that the the app seems unable to detect the presence of Google Play Services, even though these are definitely present on the device.

**Comment by marcoconti83** [comment]
Hi @strypey , 
thanks for the report. This seems to be similar to https://github.com/wireapp/wire-android/issues/1923, linking them to keep track of both.

**Comment by mjk-gh** [comment]
Same problem here: No matter if on Wi-Fi or EDGE/HSDPA, starting the Wire app and trying to login (for the first time on the phone) with the email address I registered on app.wire.com before (on my PC), results in a popup stating "No Internet Connection" and "Please check your Internet connection and try again".

Google Play Services seem to be running, and stopping and disabling them manually doesn't seem to change anything.

After updating a few system components via the Yelp app, the problem persists.


## Environment

Google Play services version name: 6.5.99 (1642632-036)
Google Play services version code: 6599036
Google Play services updated: Oct 2, 2015
Google Services Framework version name: 4.4.2-1289630
Google Services Framework version code: 19

Wire version that exhibits the issue: 3.29.757 and 30.764
Android OS version used to run Wire: 4.4.2
Is this a custom firmware or a stock one: stock firmware
Mobile phone model/manufacturer: Acer Liquid E700 Trio (E39)
Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi/EDGE/HSDPA

**Comment by strypey** [comment]
@mjk-gh are you using Wire through a VPN by any chance? If not, it seems
unlikely ExpressVPN was the cause in my case, and more likely there is a
problem with native Wire support on Android 4.4.2.

**Comment by marcoconti83** [comment]
Hi all,
Wire backend uses TLS 1.2. If your Android 4.2.2 flavor doesn't provide TLS 1.2 support, then you won't be able to use Wire unfortunately. I found [this post](https://stackoverflow.com/questions/28943660/how-to-enable-tls-1-2-support-in-an-android-application-running-on-android-4-1) that mentions that on Android 4.2 TLS 1.2 is disabled by default, and there is an option to enable it.

We don't currently have enough capacity to address this issue for 4.2.2 (we don't even have any such device), but if someone from the community want to give it a try, you can try to apply the suggestion in the question linked above and see if that fixes it for you, and eventually make a PR.

**Comment by strypey** [comment]
Thanks for the update @marcoconti83 
> We don't currently have enough capacity to address this issue for 4.2.2 (we don't even have any such device), 

Just to be clear, are you saying that the Wire team just doesn't have time to work on support for such old devices, and its only going to happen if someone from the wider community submits patches? I ask because I'm currently shopping around for a newer Android device. Once I get it, would it be useful if I sent you my 4.2.2 device for testing purposes?

**Comment by marcoconti83** [comment]
@strypey yes, availability of resources (time and developers) is the main problem, we have to prioritize which platforms we support.

**Comment by strypey** [comment]
Just for the record, I just installed the Wire client on a device running Android 4.4.4. Same result as with 4.2.2. It's definitely  not an internet connection problem, as I was able to get through to app.wire.com (where I got a "your browser is not supported" message *sigh*). FYI wire.com/download still says that it supports Android 4.2+. Since you say you're not actively working on support for Android systems that old, this is clearly misleading and needs to be updated to accurately reflect the oldest Android version you are actively supporting.

**Comment by marcoconti83** [comment]
Hi everyone,

since last public version, Wire dropped support for Android 4.x. This is due lack of resources necessary to keep creating custom solutions for Android versions that are 5 years old, and inability to enforce certain security policies on those versions. I understand that this is a loss for Android 4.x users, but I'm afraid we won't be able to go back on this decision any time soon.

The lowest supported version is now officially 5.0.

**Comment by ptrofimov** [comment]
I have Android 6.0.1 and the same problem.

**Comment by strypey** [comment]
@ptrofimov perhaps the Wire devs have now abandoned Android 5x and 6.x without updating their website, as they did with Android 4.x?
