### ISSUE TITLE
Add Option to enable FLAG_SECURE

### ISSUE THREAD

**Issue by maltfield** [wireapp/wire-android#1870]
This is a feature/security improvement request: please create an option for the user to toggle the FLAG_SECURE option in the wire android app, similar to the implementation in Signal.

 * https://github.com/signalapp/Signal-Android/issues/788

**Comment by maltfield** [comment]
important: FLAG_SECURE should be set to enabled by default.

**Comment by marcoconti83** [comment]
Hi @maltfield ,
thanks for the report, we will look into it.

**Comment by pfahlr** [comment]
I second this. There might be some reasoning that's resolved this issue for many, but there are lots of people looking at wire for secure communication that would be turned off by this. 

Presently when a disappearing message is in view, the flag is set, but as soon as it leaves the screen, screenshots are possible again.

I think this describes a sensible approach:
https://news.ycombinator.com/item?id=18420654

**Comment by makingthematrix** [comment]
It took some time to get to it, but finally we have it in the new release :)
