### ISSUE TITLE
latest beta crashes on startup

### ISSUE THREAD

**Issue by robertnurnberg** [wireapp/wire-android#1889]
I am a beta tester on Android 4.4.2.

The latest wire beta version (updated on 23/11/2018) crashes on startup.

Edit: Update from 29/11/2018 no longer shows this bug, not sure if this is by chance or if the underlying issue was resolved.

**Comment by marcoconti83** [comment]
Hi @robertnurnberg ,
sorry for late reply. This has since been fixed, so I'm closing this issue, please open a new one if it happens again. Thanks for reporting!
