### ISSUE TITLE
[Feature request] Improve notifications in Android 7

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#190]
I don't know if it's appropriate to post feature requests on github, but I've seen it's being done in the iOS repository so here I go.
I have two requests regarding notifications:
1. When receiving a notification, it would be nice if Wire allowed us to reply to the message the way other apps do, without leaving the notification drawer.
2. Use bundled notifications to group messages

**Comment by RexHackbro** [comment]
2 contacts from me suffer also under this issue, I not.

**Comment by agurenko** [comment]
Yes, this looks like a long overdue, since it's already May 2017 and Wire still uses own implementation of quick reply with popup rather than Android 7 style :(
