### ISSUE TITLE
Expand text lines to more than two

### ISSUE THREAD

**Issue by TobiPeterG** [wireapp/wire-android#1900]
When I write a text message, there're just two lines I can actually see.
That's really disgusting, especially when I want to write a longer text and want to read it again.

It would be cool if it would scale with text length to 6 lines +, so it's easier to read.

**Comment by x2k13** [comment]
Yes, that would be great. It's a very annoying design flaw, since the iOS app has this feature already.

Shouldn't be too hard to do, right?

**Comment by BradleyWire** [comment]
A change has been merged and we'll be tracking this through a feature request raised here: https://github.com/wireapp/wire-android/issues/2289
