### ISSUE TITLE
[BUG] new text messages are not shown received sometimes

### ISSUE THREAD

**Issue by germangoergs** [wireapp/wire-android#1901]
Sometimes I'm not able to receive text messages on my android device, since my phone doesn't receive them, I have to open the app and then the message is shown.

**Comment by denic** [comment]
Same here and for most of my peers. Ping me if I should/can provide more info.

**Comment by ivanlechat** [comment]
I have the same issue with the app on Android, if I don't open the app constantly, the incoming messages won't arrive. It happened on my Moto g5 plus with Android 7 and 8 versions.

**Comment by marcoconti83** [comment]
Hi all,
can you please check that "battery optimization" in not turned on for Wire, in your system settings?

**Comment by denic** [comment]
@marcoconti83 

Set to "Optimization enabled" for me. Will switch.

**Comment by marcoconti83** [comment]
@denic did you notice any improvement after switching?

**Comment by denic** [comment]
@marcoconti83 At least it did not happen for me any more. But i am using Wire quiet frequently, so maybe it has gone unnoticed. 

@MisterFossey Could you try and report back?

**Comment by MisterFossey** [comment]
Just turned off the Batterie optimization, report will follow

**Comment by hub-ch** [comment]
Agree with @ivanlechat and found on android 5.1 has this problem always (checked for many days)

----------

a successful solution from **Skype**. it automatically get enabled "protected apps" with installation through google play

![screenshot_2019-02-23-23-48-54](https://user-images.githubusercontent.com/45872460/53290304-a9085200-37d4-11e9-8e42-c2efc51811ba.png)

---------

Another solution from Telegram but that doesnt helps for android 5.1 and nearby versions. (not self start for receive notifications)

![screenshot_2019-02-23-23-57-03](https://user-images.githubusercontent.com/45872460/53290316-d1904c00-37d4-11e9-8ffd-e10cc1573ba7.png)

 ----------

Enhance that both ways. not a joke either it will not malfunction. just ensure apps will keep active or start back if it stopped by anyway suitable for all versions.

**Comment by hub-ch** [comment]
https://github.com/wireapp/wire-android/issues/777#issuecomment-466763316

**Comment by f4grx** [comment]
Even with battery optimization turned off, wire does not give any notification in lineage 14. I do not have background data restrictions.

**Comment by marcoconti83** [comment]
Hi all,
in case it was missed, there's a checklist to go through if you notifications are still acting up: https://support.wire.com/hc/en-us/articles/203624294-What-can-I-do-if-I-m-not-getting-any-notifications-on-Android-

**Comment by marcoconti83** [comment]
Hi all,
there are a lot of duplicated issues covering this same problem (or a very similar one), let's unify all conversations and keep it going here: #777 . Closing this one and continuing there.
