### ISSUE TITLE
[Question] What is use of providing the a phone number when registering in the app?

### ISSUE THREAD

**Issue by tuxayo** [wireapp/wire-android#1904]
Hi, :)

The UI didn't give clue about that when I tried Wire few months ago.

Is it for contact discovery like what [Quicksy](https://quicksy.im/) does?

Edit:
Or is it for passwordless login? Or password recovery? Or 2FA (two factor auth)?

**Comment by tuxayo** [comment]
After having asked in the Matrix chat `#SecureMessagingApps:matrix.org` , there is indeed contact discovery in Wire. The main question in then answered, but it that it's only usage?

**Comment by marcoconti83** [comment]
Hi @tuxayo ,

The phone number is indeed used for contact discovery. Using the phone number for registration is optional, you can register using an email instead if you prefer. You can find more details in the [privacy whitepaper](https://wire-docs.wire.com/download/Wire+Privacy+Whitepaper.pdf).
