### ISSUE TITLE
Wire message content "jumping" down when start typing

### ISSUE THREAD

**Issue by sokke90** [wireapp/wire-android#191]
Steps to reproduce: 
When I go to a conversation, the keyboard is closed. I open the keyboard. Now, when I type the first letter, the message window jumps a tiny bit down. This I think is expected to be happen, as the window scrolls to the last message as you start typing.
As this does not seem to be a big thing, it is very confusing and annoying.
Why not give a "go to last message" button and not jumping to the end of conversation when typing?

In the same context, the new "Contact is typing" overlay, overlaps the message text.

**Comment by someoneEsle** [comment]
What you mentioned is part of a bigger issue with scrolling conversation content, which has been reported (many times, unfortunately). It is being worked on/fixed in the branch "message stream", if I recall correctly.

**Comment by mastad0n** [comment]
Any updates on this?

**Comment by someoneEsle** [comment]
I am running a version of the app that I built myself from the message_steam branch. It works nicely so far, but it still has a few bugs. I'm sure that as soon as they fix those too they'll merge into master.

**Comment by someoneEsle** [comment]
Fixed in today's update!
