### ISSUE TITLE
Request for bubble-like theme

### ISSUE THREAD

**Issue by mimf** [wireapp/wire-android#192]
I recently started using wire with some other people and one thing that they mentioned was that the app was not very "comfortable". They were used to messages in bubbles (like Signal) and so Wire did not feel right to them. The chat felt "heavy"..

I'm sure that if they kept on using it, they would get used to it, but they did not.

In the interest of maximizing the number of active users, I'm wondering how hard it would be to have an option for a bubble-like theme. 

Perhaps an option to change between the way it is now (separated by name) or bubble (signal-like).

**Comment by someoneEsle** [comment]
I second the request for a bubble-like theme, but would discourage the developers from allowing an option for both styles: more options is rarely good for the users, and it also means "more options to maintain" (debug etc). If we are to embrace a new design, it has to be final.
The reason why I would like the bubble-style, besides the obvious reason that it is something everyone is used to, is that sometimes when scrolling up looking for old messages, the right/left layout can help you find them more easily. For example, say you remember you sending a very long message: as you scroll up, you see a big bubble on the right, and that's your message. Or also, say you remember you sending a lot of messages without getting a reply: again, you can find that easily by noticing a lot of messages on the right. Finally, for group chats, say you want to see the last time you sent something: you scroll up until you see something on the right.

I understand that wire wanted to be visually different from the other apps, and it is. The design is beautiful too, no complaints there. When I started using wire I thought that it was just a matter of getting used to it, but the use case I mentioned above prove that it is not. I got used to thw "confusion" of everything on one side, but there are some comforts that inevitably get lost with it.

**Comment by bjoernherbig** [comment]
Reasoning is duly noted. However, we won't include options for different styles anytime soon. Higher maintenance vs. limited capacities at the moment.
We are discussing improving surfacing content from the conversations though.

**Comment by maximbaz** [comment]
I'm hearing the same feedback from literally everyone who started using Wire: it is hard to distinguish who wrote messages in conversation, me or my contact.

Bubbles is a solution, but it's not the only one, it's not the easiest one to implement and it's not something everyone likes. I like the current design for instance, but I also struggle with distinguishing what part of the conversation is written by me.

@bjoernherbig, what do you think of this? Have you heard similar feedback? Perhaps we could brainstorm and find some easy solution (not necessarily bubbles)? And would you accept a pull request if we agree on something?

I have one suggestion, a simple solution to this problem could be to use a slightly different background color. Just having "my" messages with a very-slightly darker grey-ish background than the other messages. 

Have a look at the concept below, what do you think of it?

![image](https://cloud.githubusercontent.com/assets/1177900/21066426/c4bb89a8-be65-11e6-8dbf-424bb975b6ea.png)

**Comment by someoneEsle** [comment]
I really like the idea of the two backgrounds! Something along those lines would be really cool (maybe using the accent color but in a very light/pale version would be good as background too).
Something I proposed some time ago was something like this 
![cvewihpueaapotz](https://cloud.githubusercontent.com/assets/21009625/21066643/506c7cda-be2c-11e6-88ff-b8fc0eb21d6e.jpg)

**Comment by maximbaz** [comment]
@someoneEsle this looks beautiful to me, and "in style" of Wire. And if we add background color to your concept, it doesn't necessarily has to be in a form of a bubble, it could also be a simple strip that is behind the entire line (similar to what I showed).

At this stage it would be really good to get a feedback from Wire members. Would they agree that this is a high-prio issue that has to be solved? Which of the proposed ideas they consider a good solution to the problem, and yet "the least harmful" to the design of Wire (so far proposed: text alignment, background color, both ideas combined)? And to speed things up, after a decision is taken, would pull requests be accepted?

One challenge that I foresee is that any slightest change of a design is likely required to be done on all platforms at once. Assuming pull requests will be accepted, I am confident that one of us here could take care of android app, and I could also take care of the webapp. However I neither can patch the iOS app, nor I know anyone who could help with this.

**Comment by bjoernherbig** [comment]
Thanks for the proposals! We are discussing how to better differentiate sender/receiver content. All your feedback will be taken into this discussion.
For now there is no need for PR's though. This will be a change that we will perform on the Wire side since it needs to be aligned across the platforms.

**Comment by teller** [comment]
No bubbles but if you use app.wire.com / desktop version then you can see that message author name uses their profile color now. Depending on user feedback this may trickle to phone versions as well.

**Comment by mimf** [comment]
I still find everything way too "heavy". (Talking about the android client)

For example, is there really a need for all the bottoms at the bottom? Can't you hide those buttons in the top, somewhere? Usually, the very bottom os a message app is reserved to the chat-box, not buttons to send gifs or whatever.

I really don't mean to diminish wire but you should seriously consider employing a UI guy that likes minimalism.

**Comment by teller** [comment]
@mimf Wire started out with almost all of the UI hidden (look at the screenshots here, for example: https://medium.com/@wireapp/hello-hd-group-calls-now-in-stereo-978ac2c8e21b#.2h9c0jm5r)

However, user testing and usage data showed that people were not discovering and using a lot of the functionality. Over time we brought main actions out in the UI as well. As the app evolves we continue to reconsider and user test different ways of dealing with the UI/UX. This kind of user feedback is also very valuable and helpful in prioritizing next steps so thank you!

**Comment by RITFW** [comment]
Even if it is an old issue and I understand all the arguments here I completely like the interface of wire without the bubbles. I think it reads more easily if you go through the chats and I like that all the space of the screen is used to display messages. Bubbles always make the lines so short and so much screen space is unused. Only because something is "different" it doesn't mean it's bad - it can be just different and good for it's own sake ;)
