### ISSUE TITLE
Settings button disappeared

### ISSUE THREAD

**Issue by charliegreen** [wireapp/wire-android#1927]
## The problem

On the contact list screen, the settings button isn't there.

## Environment

* Wire version that exhibits the issue: 3.24.681
* Last Wire version that did not exhibit the issue (if applicable): I only just noticed this problem, so I'm not sure. I figure I'd have noticed earlier, though, if this was an issue in earlier versions too.
* Android OS version used to run Wire: 5.1
* Is this a custom firmware or a stock one: Stock
* Mobile phone model/manufacturer: Motorola Moto X (XT1058)
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Any

## Details

The settings button is missing. The "create group" button is still there, though.

The settings button appears briefly when first launching the app, but vanishes before the app is fully loaded. Tapping it while it's still there doesn't open the settings activity. It appears to vanish at the same time that the top bar containing my username and the profile picture circle appears, but before my profile picture actually loads. In total, the button is there for about a second. (My phone is very slow, and Wire in particular has become almost unusably slow since updating to 3.24.681. But that's another issue).

I figured it might just be an icon rendering issue, potentially combined with the button being in the wrong place, so I tapped everywhere along the bottom bar; nothing happens, except when I tap the "create group" button, which works normally.

All I have to do to reproduce the problem is to open the app; it happens consistently.

I'd add a link to debug logs, but I can't enable debug reporting, as the settings button is missing. I'm afraid I also can't add screenshots, as the physical "volume down" button on my phone is broken, and there's no way to take a screenshot otherwise. (Yes, I know, I need a new phone....)

**Comment by makingthematrix** [comment]
Hi @charliegreen, thank you for your input!

Maybe we can solve the problem with the lack of screenshot the other way. I made a screenshot of the Profile screen with the Settings button on it. Can you confirm that this is where it's missing on your device?

![settings_button_3](https://user-images.githubusercontent.com/4498008/50513142-26923900-0a96-11e9-8234-4129c2292d63.jpeg)

**Comment by makingthematrix** [comment]
Or should it be on this screen?
![settings_button_2](https://user-images.githubusercontent.com/4498008/50513272-f8612900-0a96-11e9-9fe1-2dd8ffa4a41a.png)

**Comment by charliegreen** [comment]
Oh my goodness. I feel ridiculous.

The settings button works just fine. I'd thought it was still on the bottom right of the screen with all your conversations on it; it must have been moved and I didn't realize. I'm so sorry.... :sweat_smile:
