### ISSUE TITLE
Link preview for youtube does not work

### ISSUE THREAD

**Issue by bpereto** [wireapp/wire-android#1941]
## The problem

link preview for youtube does not work on android.

## Environment

* Wire version that exhibits the issue: 3.24.684
* Last Wire version that did not exhibit the issue (if applicable): -
* Android OS version used to run Wire: 8.1.0
* Is this a custom firmware or a stock one: stock
* Mobile phone model/manufacturer: BQ Aquaris x2 pro
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): wi-fi/edge/lte

## Details

* share a link of a youtube video, ex:
https://www.youtube.com/watch?v=8rVz6Cnj2AY&t=4s
on the android app or on the web-app (vice-versa)

the web-app shows the link preview of the youtube video, the android does not (only the url).

**Comment by marcoconti83** [comment]
Hi @bpereto ,

Thanks for the report, we noted it down and will have a look when time allows.

**Comment by marcoconti83** [comment]
Hi @bpereto ,
this is being addressed here: https://github.com/wireapp/wire-android-sync-engine/pull/542. It should be deployed soon-ish :)

**Comment by johnxnguyen** [comment]
Actually @marcoconti83 it isn't addressed in that PR because youtube links are handled differently from other links. In the case of youtube links we display an embedded player. However I've started to look into the youtube issue and it should be resolved soon.

**Comment by marcoconti83** [comment]
Hi @bpereto ,
Thanks for your patience! This has been addressed in the latest public release, 3.36. If you are still experiencing issues, please feel free to reopen the ticket.
