### ISSUE TITLE
Sharing Multiple Images Broken

### ISSUE THREAD

**Issue by madranet** [wireapp/wire-android#1942]
Wire for Android, version: 3,24,684
Running on Android 6,0

I don't know whether this is an issue with the current release of Wire, or whether Google have broken something in a recent update of their Photos app but, of late, I can no longer reliably share multiple photos by Wire

Previously I could select multiple images in Photos app and then use the Share button to select Wire and share them.

Now, when I do the same, the recipient only receives the first image.  The progress window which briefly shows after clicking on the Share button and selecting Wire will still show  _"Downloading XXX Left"_ [where XXX = number of images selected] but only one image will actually be sent through Wire.

As I said, I'm not sure where the problem lies. Using the Share button in Android, it's a bit difficult to see where the hand-off between the Android system and the app in question takes place. Is it Wire that's broken, or is it Android sharing?  Is anyone else seeing this?

**Comment by makingthematrix** [comment]
Hi. 
In the last year there were at least too fixes connected with this issue:
https://github.com/wireapp/wire-android/pull/2199
https://github.com/wireapp/wire-android/pull/2641

Can you re-test and write back if the issue stil exists?

**Comment by makingthematrix** [comment]
Ok, I guess I can safely close this bug now. Please reopen if the problem still occurs.
