### ISSUE TITLE
Unsent timed message cannot be edited or copied to clipboard

### ISSUE THREAD

**Issue by fortran77** [wireapp/wire-android#1946]
## The problem

A timed message that remains unsent to due to some error cannot be edited or copied to clipboard.

## Environment

This appears to be a version-independent feature by design, as discussed in Issue #1827 (Timed messages cannot be edited – but deleted only). However, I experienced this on stock Android 9.0 on a Moto X4 with Google Fi service in a recent version of Wired about two weeks ago, probably Wire 3.24.684.

## Details

Although inability to edit a timed message is implemented by design, an unsent message is not yet a timed message because there is not yet any recipient.

There are two reasons why editing and copy to clipboard should be permitted for an unsent message, and the current restrictions may be considered a bug or a misfeature.

First, if an unsent message is being manually resent after a delay, editing might be needed for accuracy if conditions have changed.

Second, if Wire is repeatedly failing, and the original message is long, the user should be permitted to copy-and-paste into an alternative messaging application, instead of being frustrated by being forced to retype the entire message into a different app.

If copy to clipboard of the unsent message is permitted, then editing is not essential. The user can merely copy-and-paste the unsent message into a new one, edit that before sending, then delete the unsent one. So I recommend simply allowing copy to clipboard for now (should be an easy change in the code somewhere), then addressing the editing question later as resources permit.

**Comment by marcoconti83** [comment]
Hi @fortran77 ,
This sounds reasonable. Just to set expectations, we have a lot on our plate and this is not the top priority for the moment, so I'm not sure when it will be addressed. 

If anyone is interested in trying to make a fix in the meanwhile, I believe this is a good self-contained task for the community to contribute. We'd be happy to give some pointers.

**Comment by harishvishwakarma** [comment]
Hi @marcoconti83 I would like to investigate this issue. I am very new to the codebase even though I have been using the Mac, Android and iOS version for about 15 months now. 
Could you direct me where to start?

**Comment by marcoconti83** [comment]
Hi @harishvishwakarma ,

Thanks for picking this up! The proper fix would be to make sure that ephemeral messages either succeed or fail within a short timespan, and that if they fail there is an option to resend them. 

However this sounds a bit complicated for now, as @fortran77 suggested we could work around this by allowing copy **on the sender side**.

I believe this change is extremely trivial: https://github.com/wireapp/wire-android/blob/develop/app/src/main/scala/com/waz/zclient/messages/MessageBottomSheetDialog.scala#L121

You should modify the condition to allow you to copy **only if you are the sender** of the ephemeral message. We still don't want to allow the user to copy messages that were sent to them. 

While this is not a strong security feature as it can easily be circumvented, for consistency with other platforms and to keep user expectations that we build with the current behavior, we still don't want to allow you to copy ephemeral messages that others sent you.

FYI @raphaelrobert

**Comment by fortran77** [comment]
Just a minor point, I feel that lack of copy-and-paste should be optional for ephemeral messages. I often set outgoing messages to expire in 4 weeks, just to prevent accumulation of old unimportant messages, and not for security. (Note that Wire does not prevent selection of multiple messages and then deletion in one action, so purging old messages is tedious and involves many long-press then multiple-click actions.)

But that prevents recipients from doing copy-and-paste. It would be nice if we could choose between security/privacy (expire and prohibit copy-and-paste) and convenience (just expire).

**Comment by harishvishwakarma** [comment]
> You should modify the condition to allow you to copy only if you are the sender of the ephemeral message. We still don't want to allow the user to copy messages that were sent to them.

The issue also requests the ability to let users edit the message before sent. How should that be handled?

**Comment by marcoconti83** [comment]
> @marcoconti83 The issue also requests the ability to let users edit the message before sent. How should that be handled?

I would skip that for now. There are a lot of edge cases to consider and we need to do some brainstorming to understand implications before we make any changes. 

We can revisit that after the copy is allowed. Allowing copy already gives a possible solution to this user problem; even if not the optimal one, it's the least complicated to implement.

> 
> Also I tried pushing a branch to create PR for the change related to copy, but the push failed with 403. What is the standard way to push a branch here?

You should fork to your account, work there and when you are ready then create a PR to the upstream repo (this one). This process is nicely described [here](https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project) and [here](https://github.com/MarcDiethelm/contributing/blob/master/README.md).

**Comment by marcoconti83** [comment]
This has been fixed in #2052 and will be released in the next public release
