### ISSUE TITLE
Unread dot in conversation list stays even after reading

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#195]
Steps to reproduce (Android 7, Nexus 5X):
- get a message
- open the conversation, leave it open a few seonds
- swipe left to go back to the conversations list
- see how the unread dots are still present, telling you to read the message you just read

What's worse is that even reopening the conversation and then going back to the conv. list doesn't really help. At some point the unread dots do go away but it's a mystery to me why they do. Maybe closing and opening the app again is the key, but I'm not sure.

[wire_debug_report.txt](https://github.com/wireapp/wire-android/files/504031/wire_debug_report.txt)

**Comment by zeebok** [comment]
I'd like to add that with my phone (also Android 7, Nexus 5X) that when I see this issue, I also cannot send messages (the message just sits at "Sending...") until something causes the app to update/sync/something, *or* closing and opening the app again.

**Comment by someoneEsle** [comment]
I've experienced that as well. And actually, although you keep seeing "sending", the message has been sent (most of the times). I know because either the other party replies or I see the message in another device of mine.

**Comment by someoneEsle** [comment]
I think this issue got fixed because I haven't experienced it in a few days now.
