### ISSUE TITLE
Front camera of Nexus 6P upside down 🙃 

### ISSUE THREAD

**Issue by passsy** [wireapp/wire-android#196]
Using the Play Store version, the front camera of my 6P is upside down. The sent video stream is correct but to me the video is upside down 🙃

**Comment by someoneEsle** [comment]
Same thing on Nexus 5X, I'm assuming you're on Android 7 too. During the video call the other person sees me fine, but I see myself upside down.

**Comment by bjoernherbig** [comment]
fixed in ##275
