### ISSUE TITLE
Feature request: share or send to myself

### ISSUE THREAD

**Issue by fortran77** [wireapp/wire-android#1971]
## The problem

When sharing to Wire from some other app, or sending from Wire, please allow sharing or sending  to myself.

## Details

I hesitate to add another feature request given that the developers probably have a long list already, but this one should be easy to implement and will have a high payback.

There are many use cases.

Suppose I scan a bar code with a smartphone and I want to make the result securely available to myself on a desktop where Wire is also installed and is trusted (verified). Sharing from the bar code scanner into Wire currently does not let me send the result to myself, but only to other Wire users. Sharing to myself would let me get the result on the trusted desktop while using end-to-end encryption.

Suppose I want to make a quick confidential note to myself. Using Wire, I would enter a message to myself. It would appear on other trusted Wire devices, allowing it to be further saved and processed, while taking advantage of end-to-end encryption.

Finally, Wire's ability to allow one to delete one's own messages from all devices would allow the scanned bar code or confidential note to be purged.

**Comment by dani230** [comment]
You should create a wire group and not include anyone. ;)

**Comment by fortran77** [comment]
Creating a group works! However, I discovered odd behavior.

After I create a group "Me", then send messages into that group, the message appears on multiple devices as expected (a Rambox desktop instance on Ubuntu, and two Android devices). But on one of the Android devices (Galaxy Tab S2, Android 7.0, Wire 3.26.694) the message seen in the group is at the bottom of the screen and there is no place where I can type a reply to it. On the other devices there is a reply entry box and I can reply as usual.

If I later delete all content from group "Me" and leave the group, the group name "Me" no longer appears in the list of contacts on the main screen (as one would expect). But when I share from other apps into Wire, the group name "Me" still appears, and a send to it then fails.

**Comment by marcoconti83** [comment]
Hi @fortran77 ,

thanks for starting the discussion. @dani230 gave you a good suggestion - that's what we do too internally :)

For the bug that you are reporting, I believe this might not related to the fact that you create an empty group. Could I ask you to help on this? Can you try again with a non-empty group, and create a separate ticket for this issue with the steps to reproduce? 

Thanks

**Comment by marcoconti83** [comment]
I will close this issue about sharing for now, we'll continue the discussion about not being able to send in another issue.
