### ISSUE TITLE
Wire for Teams link is dead

### ISSUE THREAD

**Issue by different55** [wireapp/wire-android#1981]
## The problem

The link to find more information on teams 404s.

## Environment

* Wire version that exhibits the issue: 3.26.694
* Last Wire version that did not exhibit the issue (if applicable): Unknown
* Android OS version used to run Wire: 7.0
* Is this a custom firmware or a stock one: Stock
* Mobile phone model/manufacturer: Motorola Droid Turbo 2 XT1585
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE and Wifi

## Details

When trying to create a new team from the Android app, there's a link that says "What is Wire for Teams?" This link leads to https://wire.com/en/create-team/#features, which is currently an Error 404 page.

## Link to Debug logs

Emailed to support@wire.com

**Comment by marcoconti83** [comment]
Hi @different55 
thanks for the report, we will fix the link

**Comment by marcoconti83** [comment]
This has been fixed here: https://github.com/wireapp/wire-android/commit/6fde3462bd8ab20fe9572330e74427bc257f0f67. 

It's not released to public yet, but you should expect to see it in the next release though, one to two weeks from now. I will close this ticket for now.
