### ISSUE TITLE
Getting Error when setup on android studio

### ISSUE THREAD

**Issue by akashqss** [wireapp/wire-android#20]
Error:(315, 0) A problem occurred evaluating project ':app'.
<a href="openFile:wire-android/app/build.gradle">Open File</a>

at this point..
if (keepSpecsMap.remove("activity") != null) {

**Comment by zbsz** [comment]
Duplicates #9 

Make sure to not allow Android Studio to upgrade the project to new gradle plugin, we require 1.5 for now.

**Comment by akashqss** [comment]
After download Android studio 1.5 getting same issue.

**Comment by zbsz** [comment]
I didn't mean Android Studio 1.5 but android gradle plugin 1.5.
Could you please try again with a clean repo?
Clone the app in new place, open it in Android Studio (latest version), and make sure to not agree when Android Studio asks if you want to upgrade project to latest gradle plugin.

**Comment by akashqss** [comment]
when I am taking clone  and run this in directory wire-android ./gradlew assembleProdRelease   it give this result


class CallingActivity extends AppCompatActivity with ActivityHelper with PermissionActivity {
                                                                         ^
6 warnings found
8 errors found
:app:compileProdReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileProdReleaseScala'.
> Compilation failed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 21.474 secs

**Comment by zbsz** [comment]
yup, this will fail on first try sometimes, just run it again, our build setup is not perfect

**Comment by akashqss** [comment]
which version of scala is good for project. I am using 2.11.8 and when compile my project it give below error

Failed to patch KEEP_SPECS: no 'service' root found
Information:Gradle tasks [:app:assembleAvsDebug]
Failed to patch KEEP_SPECS: no 'activity' root found
Failed to patch KEEP_SPECS: no 'instrumentation' root found
Failed to patch KEEP_SPECS: no 'service' root found
Failed to patch KEEP_SPECS: no 'activity' root found
Failed to patch KEEP_SPECS: no 'instrumentation' root found


Reading program jar [/home/akash/Development/wire-android/app/build/intermediates/transforms/jarMerging/avs/debug/jars/1/1f/combined.jar]
Reading library jar [/home/akash/Android/Sdk/build-tools/23.0.3/lib/shrinkedAndroid.jar]
Note: android.support.design.widget.CoordinatorLayout calls 'Class.getAnnotation'
      Maybe this is program method 'com.waz.service.ContactsService$$anonfun$com$waz$service$ContactsService$$updatedContactMatches$1$$anonfun$12 { scala.collection.immutable.Set apply(); }'
      Maybe this is program method 'com.waz.service.ContactsService$$anonfun$com$waz$service$ContactsService$$updatedContactMatches$1$$anonfun$11 { java.lang.Object apply(); }'
      Maybe this is program method 'com.waz.service.ContactsService$$anonfun$com$waz$service$ContactsService$$updatedContactMatches$1$$anonfun$12 { java.lang.Object apply(); }'


Please help me to resolve above issue.

**Comment by zbsz** [comment]
Did you get that one in Android Studio? It seems that you are trying to build `avsDebug` variant, which is our internal testing thing, go to variants screen and select a `prod` variant.

**Comment by akashqss** [comment]
Yes this is result of Android studio.

import android.os.PowerManager


In class GlobalCallingController(cxt: WireContext)(implicit inj: Injector) extends Injectable {

these import is not called 
import _root_.com.waz.api.VoiceChannelState._
import _root_.com.waz.model.VoiceChannelData
import _root_.com.waz.service.ZMessaging
import _root_.com.waz.utils.events.Signal

**Comment by akashqss** [comment]
I am not seen any prod variant while prodRelease and prodDebus are exist.I have tried both but not get any luck.

**Comment by zbsz** [comment]
What errors do you get when using prod* variants? There usually are couple warnings (displayed as error) but the app should be built fine.

**Comment by akashqss** [comment]
same error which I have posted above(its peace of error). If you want then i can post full gradle error .
