### ISSUE TITLE
Cannot recevie message notification and phone call when wire app is not opened.

### ISSUE THREAD

**Issue by evan0greenup** [wireapp/wire-android#2012]
## The problem

When end the wire in the background, the new message cannot be pushed in to notification area, and the wire phone call from others cannot either be received. 

## Environment

* Wire version that exhibits the issue: 3.27.697
* Last Wire version that did not exhibit the issue (if applicable): ~
* Android OS version used to run Wire: 8.0
* Is this a custom firmware or a stock one: stock
* Mobile phone model/manufacturer: ~
* Mobile network type (EDGE/LTE/Wi-Fi/Offline):~

NOTE: ~ means irrelevant.

**Comment by marcoconti83** [comment]
Hi @evan0greenup,

Thanks for reporting.

This ticket is another report of https://github.com/wireapp/wire-android/issues/1901, I will close this one and keep tracking there. Please try the suggestion in that thread and let us know.
