### ISSUE TITLE
Feature request: show detailed debug report status.

### ISSUE THREAD

**Issue by evan0greenup** [wireapp/wire-android#2013]
## Feature request

Show the detailed debug report status after enabling or disabling it.

**Comment by evan0greenup** [comment]
Since the triggers of both enabling and disabling detailed debug report are 10 times click. It might be forgotten when it goes several times.

**Comment by marcoconti83** [comment]
Hi @evan0greenup ,
could you please clarify in which screen is this something that takes 10 clicks to enable and 10 clicks to disable? 
I can only think of the "send debug log" button but that requires only one click and there is no "disabling".

**Comment by evan0greenup** [comment]
@marcoconti83 . According to Issue template of this project, "6. Tap "Wire swiss GmbH" 10 times again to disable detailed debug reports, because this slows down Wire", I tap this 10 times but no thing visible shows up. If there isn't things what I say, the issue template need to be revised.

**Comment by marcoconti83** [comment]
Thanks for clarifying. That feature is indeed not available anymore, so I'll remove it from the issue template.

**Comment by marcoconti83** [comment]
Fixed. Thanks for reporting.
