### ISSUE TITLE
When clicking "Resend" it shows me who liked the message instead of sending!!!

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#2036]
when send image failed, click "Send"

**Comment by Transisto** [comment]
also liking the image/post remove the "Send failed, send" for good but obviously didn't send.

**Comment by fungs** [comment]
I had the same issue, somehow solving it by hitting the right spot with my finger with a longer press.

**Comment by makingthematrix** [comment]
Fixed some time ago - maybe together with https://github.com/wireapp/wire-android/pull/2727 ?
