### ISSUE TITLE
Attach android app to releases

### ISSUE THREAD

**Issue by MarionMoseby** [wireapp/wire-android#2044]
Hi! Could you attach the apk to releases? It would make it easier to get it and help include it in IzzyOnDroid's F-Droid Repo

**Comment by marcoconti83** [comment]
Hi @MarionMoseby ,
the APK is available at our website: https://wire.com/en/download/

We can look into adding the APK to GitHub releases via our build system, but it will be tricky due to our current setup and will take a while.

**Comment by MarionMoseby** [comment]
Ok, cool, thanks!

-------- Mensaje original --------

**Comment by MarionMoseby** [comment]
Ok, cool, thanks!
