### ISSUE TITLE
Option to disable sending messages to 3rd parties

### ISSUE THREAD

**Issue by maltfield** [wireapp/wire-android#2085]
Can we please add an option to the Wire settings to "disable sending my messages to 3rd parties"?

Effectively, this would remove the annoying GIF button. I can't tell you how many times I've cursed Wire when I've accidentally tapped it. The "GIF" button sits right next to my keyboard's middle word-auto-complete button.

I sometimes use Wire to send very secret messages (ie: passwords), and hitting this GIF button means that my secret message (password) just got sent to a 3rd party! Not exactly a "feature" for a secure messaging app...

Rather than disabling the GIF button, I think a more general "don't send my messages to any 3rd parties" (anonymous or not) is preferred

**Comment by marcoconti83** [comment]
Hi @maltfield ,
thanks for raising the issue, this sounds like a duplicate of https://github.com/wireapp/wire-android/issues/198 . It's an old issue, but we restarted the conversation recently. Let's continue the discussion there, I will close this one.
