### ISSUE TITLE
"Maintain connection to server" option not available

### ISSUE THREAD

**Issue by marmarek** [wireapp/wire-android#2100]
**Describe the bug**
The "Maintain connection to server" option isn't available in the advanced settings, even though no GCM is running.

**To Reproduce**

1. Get an AOSP + [microG](https://microg.org/) system, but with GCM disabled in microG settings.
2. Install Wire
3. Login
4. Go to advanced settings

**Expected behavior**
A "Maintain connection to server" option available. When enabled, message notifications are properly delivered.
Maybe the option could be made visible there all the time, even if GCM support is detected. With a clear message that it may affect battery life and isn't needed if GCM is in use?

**Actual behavior**

The option not available. New messages show up only when I explicitly open the app.

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.30.764
- Last Wire version that did not exhibit the issue (if applicable): 3.29.757 (but on a different device)
- Android OS version used to run Wire: 9
- Is this a custom firmware or a stock one: custom (no google apps, only microG installed)
- Mobile phone model/manufacturer: Pixel 3
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi

**Additional context**
It worked correctly on previous phone, with Android 8 + microG. When option was enabled, notifications worked great, with very minimal impact on battery life.
On the other hand, on the new phone, Signal has similar option available, which wasn't the case previously.

**Comment by selurvedu** [comment]
Hey, thank you for filing this issue! I just opened the issue tracker to submit a ticket describing this exact problem. In my case I also use microG with FCM / GCM disabled.

**Comment by barkingbandicoot** [comment]
Yes. Same here! No "Maintain connection to server" option either.
Not getting notifications.
Oneplus 5T running 'LineageOS for microg' 16

**Comment by barkingbandicoot** [comment]
SOLVED!
I have been messing around with this for maybe 8 hours!
When I read that "Maintain connection to server" said it is enabled due to lack of google services it hit me!
Arr! This is how also solved my Signal install!

1. Uninstall Wire
2. Go to settings and disable microg
3. Re-install Wire. It will now see you have no google services as microg is no longer masking it!  "Maintain connection to server" will now show up.
4. Re-enable microg!

Good luck!

**Comment by barkingbandicoot** [comment]
NOOO!
The app has lost the ""Maintain connection to server" setting again!
Why??

**Comment by barkingbandicoot** [comment]
ok. I closed out Wire fully.
Disabled microg - opened Wire & "Maintain connection to server" was back - the renabled microg again.
Works - but how long will it stick?
Devs - you need to have the "Maintain connection to server" in there to over ride what the app thinks is happening  - please!

**Comment by barkingbandicoot** [comment]
SOLUTION?
Maybe I have fixed it. I have had an up time close to 8 hours. Hopefully it is permanent.

What I did:
1. Disabled microg
2. Checked notifications were working with Wire- yes.
3. Rebooted phone
4. Checked notifications were working - yes.
5. Enabled microg

**Comment by marmarek** [comment]
I've tried, it works only until you open Wire app. Then it stops (and also notification about wire connection disappear).

**Comment by selurvedu** [comment]
@barkingbandicoot, Wire app disables the "Maintain connection to server" as soon as it detects that microG or Google Play Services are working.

**Comment by barkingbandicoot** [comment]
I had an uptime of 12-16 hours with phone going in and out of sleep mode. I woke up the next day however to find it disconnected -
but noticed two things:
1. I had neglected to disable battery optimisation for that try.
2. I had Do not disturb activated

I re-enabled it this morning -(then a damn random reboot disabled it, grrr - I may have to switch LineageOS for Havoc. Random reboots are starting to cheese me off).
So - working for me unless something upsets it. Hopefully the battery optimisations fixes the night disconnect. I cannot find a setting to omit Wire from 'Do not disturb' mode. Turning that off could be (an imperfect) solution too. More testing needed.

My process:


1. Force stop Wire
2  Disable microg in settings
3. Check notifications were working with Wire- yes.
 4. Reboot phone with microg disabled
 5. Check notifications working with Wire- yes.
 6. Enable microg

Has anyone tried using an older version of the Wire app?

**Comment by marcoconti83** [comment]
Hi all, 
Thanks for the feedback and for pushing the discussion forward. We are open to enable the "Maintain connection to the server" option visible no matter the status of GCM, to address the issues that you describe. We will look into enabling it, but I don't have a roadmap to share at the moment.
If anyone from the community would like to address this before we have a chance to do it ourselves, PRs are welcome!

**Comment by barkingbandicoot** [comment]
Fantastic! Thanks for addressing the issue! 🙏

**Comment by barkingbandicoot** [comment]
Thanks Calum! Is there a testing apk or will we see the update in the next release?

**Comment by marcoconti83** [comment]
@barkingbandicoot this will probably not be in the next release but in the one after.

**Comment by marcoconti83** [comment]
This is now available in the public release, closing the issue.
