### ISSUE TITLE
notifications not working with microG installed

### ISSUE THREAD

**Issue by supermihi** [wireapp/wire-android#2118]
I am not getting any notifications while wire is running in background when microG is installed and enabled. Testet on two Fairphone 2 devices, one with FP Open OS, one with LineageOS for microG.

New messages are only displayed when I explicitly open the wire app. I have the latest wire version (3.31.777), so I assume it is not the same issue as in #10 and #11.

In microG settings, *Google Cloud Messaging* is enabled (and was before wire was installed). However, wire is *not* listed in the apps using GCM in microG settings.
In the debug output, I found this:
```05-03 15:52:54.523 E/GlobalTokenServiceImpl(31433): Failed action on google APIs, probably due to server connectivity error, will retry again
05-03 15:52:54.523 E/GlobalTokenServiceImpl(31433): java.io.IOException: SERVICE_NOT_AVAILABLE
05-03 15:52:54.523 E/GlobalTokenServiceImpl(31433): 	at com.google.firebase.iid.zzq.zza$5f4373ee(Unknown Source:2066)
05-03 15:52:54.523 E/GlobalTokenServiceImpl(31433): 	at com.google.firebase.iid.zzt.then(Unknown Source:4)
05-03 15:52:54.523 E/GlobalTokenServiceImpl(31433): 	at com.google.android.gms.tasks.zzd.run(Unknown Source:2000)
05-03 15:52:54.523 E/GlobalTokenServiceImpl(31433): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
05-03 15:52:54.523 E/GlobalTokenServiceImpl(31433): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
05-03 15:52:54.523 E/GlobalTokenServiceImpl(31433): 	at java.lang.Thread.run(Thread.java:764)
```

With GCM disabled in microG, it does not work either, a similar problem is reported in #2100.

**Comment by barkingbandicoot** [comment]
I was able to get Wire notifications working by installing Wire version 3.16.638 -with GCM turned on in microg. Lineage for microg 16. A poor solution though.
I would like to have GCM turned off and receive notifications on the latest version.
nb. Wire without GCM works on HavocOS with microg.

**Comment by supermihi** [comment]
Indeed, that very old version works - but has some other quirks, unfortunatelly.

**Comment by marcoconti83** [comment]
Hi everyone and thanks for opening this issue.
I would suggest to move the discussion here: https://github.com/wireapp/wire-android/issues/2100, we are working on addressing that issue and I believe the fix will help. I'm closing this one to continue the discussion there. Thanks for your patience!
