### ISSUE TITLE
Read receipts are not sent from Android Client

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-android#2119]
Read receipts are not sent from Android Client

1. Check on sender and recepients that "Send read receipt" is checked. 
2. Send a timed message (1d) from Android -> Desktop : read receipt is displayed on Android client 
3. Send a timed message (1d) from Dersktop -> Android : read receipt is not displayed

**Expected behavior**
Read receipt seen on each end

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.31.777
- Android OS version used to run Wire: 7.0
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wifi

**Comment by IpsmLorem** [comment]
Still present on Wire 3.35.814 on Android

**Comment by IpsmLorem** [comment]
on iOS too

**Comment by marcoconti83** [comment]
This is being addressed in https://github.com/wireapp/wire-android/pull/2396

**Comment by makingthematrix** [comment]
I guess I can close this ticket now? Please reopen if the issue still happens.
