### ISSUE TITLE
Contact name in header not displayed if opening from group participants view

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#212]
(I built from master [at this point in time](https://github.com/wireapp/wire-android/commit/de7a169ec4784b52d89f3c6143be395ee95d24ea))
- Open conversation with contanct X, see the contact name header fetched from the address book. Great thing.
- Go to a group chat contact X is in.
- Open the list of participants
- Tap on contact X
- the contact name (fetched from the address book) is not displayed in the header
  Nexus 5X, Android 7

**Comment by marcoconti83** [comment]
Hi @someoneEsle ,
I'm going through old issues to see if there is any update we can give. I would assume this is not an issue anymore, but if you are still facing this problem, feel free to reopen the ticket.

Thanks!
