### ISSUE TITLE
Cannot call from Android to iOS or vice-versa

### ISSUE THREAD

**Issue by dedaxys** [wireapp/wire-android#2124]
Calls initiated from either an Android device (in my case, Huawei P20) to an iOS device (iPhone 8) or vice-versa, fail to connect and ring forever until call is cancelled. No incoming call notification is received on the receiver's end.

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.32.781
- Last Wire version that did not exhibit the issue (if applicable): not sure, but it was working maybe a month ago
- Android OS version used to run Wire: 9.0.0.256 (EMUI 9.0.0)
- Is this a custom firmware or a stock one: stock
- Mobile phone model/manufacturer: Huawei P20/iPhone 8/Samsung Galaxy S5
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi

**Comment by marcoconti83** [comment]
Hi @dedaxys ,
We released some fixes for our audio-video signalling library in the app (both iOS and Android). Can you reproduce the issue with the latest versions of the iOS and Android app?

**Comment by dedaxys** [comment]
@marcoconti83 yes, the issue has been fixed now. Thanks!

**Comment by marcoconti83** [comment]
Great, thanks for the feedback!
