### ISSUE TITLE
Notifications no longer appearing when messages are received

### ISSUE THREAD

**Issue by jsoberg** [wireapp/wire-android#2130]
**Describe the bug**
For about one week, I haven't been getting notifications on my Android app when receiving messages, either from a group chat or a single user. Two fellow users I use the app with are experiencing the same issue (both on Android devices), another user who uses an iOS device is not. Notifications appear as expected when using the web client.

**To Reproduce**
Receive messages while having the Android app installed, and no notifications will appear.

**Expected behavior**
Notifications will appear when messages are received.

**Smartphone (please complete the following information):**
This info is for my device and a friend's device which is experiencing the same issue.

- Wire version that exhibits the issue: 
    3.32.781 (Latest from Google Play Store, both devices)
- Last Wire version that did not exhibit the issue (if applicable): 
    Unknown, but this issue just started happening to my friends and I about a week ago, so I assume the previous version that was on Google Play.
- Android OS version used to run Wire: 
    Android version 9 (both devices)
- Mobile phone model/manufacturer:
    Device 1: Samsung S9 (SM-G960U1)
    Device 2: Pixel XL
- Is this a custom firmware or a stock one:
    Device 1: Stock Samsung firmware
    Device 2: Stock firmware
- Mobile network type (EDGE/LTE/Wi-Fi/Offline):
    Issues appears while using both LTE and Wi-Fi (both devices). Device 1 uses AT&T for 4G, and device 2 uses Google Fi.

**Additional context**
I removed other devices from my account to see if maybe those were being treated as "active" for some reason and therefore consuming the notifications that would otherwise come in through my phone, but that didn't seem to change anything. I'm going to attempt to uninstall/reinstall Wire completely to see if that fixes the issue.

**Comment by IronJunkie** [comment]
Same as #2127

**Comment by jsoberg** [comment]
Sorry about that, didn't see that issue before putting this up.
