### ISSUE TITLE
Can't receive new messages but can send new ones

### ISSUE THREAD

**Issue by kYwzor** [wireapp/wire-android#2138]
**Describe the bug**
Since around April 28th, I've been having issues receiving messages on my smartphone. Sending messages works perfectly but I can't receive any new messages. There is no loading bar at the top, even if I wait a long time (30min). Relogging doesn't fix the issue. Reinstalling fixes the issue for a couple of days but it comes back eventually.

**To Reproduce**
A detailed description will help us to fix the issue faster. 

1. Go to any chat (group or direct).
2. Notice there is no new messages.
3. Send a new message.
4. Notice that you can see your new message in another device too.

**Expected behavior**
Being able to send and receive messages without any issue.

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.32.781
- Last Wire version that did not exhibit the issue (if applicable): Not sure, somewhere before April 28th
- Android OS version used to run Wire: 4.4.2
- Is this a custom firmware or a stock one: Stock
- Mobile phone model/manufacturer: Vodafone Smart first 6
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi

**Additional context**
I'm using Wire simultaneously on Android, Windows and Linux. I had been using it on Android since around the beginning of the year with no issues.

**Comment by kYwzor** [comment]
Tested it further, turns out it only happens when the messages are too old. Recent messages are still received. Still a weird behavior, but I'll close this issue while I test it further.

**Comment by rothnorton** [comment]
I was also getting the same issue.  Left phone off for 10 days.  Turned it on, opened wire.  Waited about 30 minutes, and it didn't retrieve any messages from the previous 10 days, even though on my desktop app there were many.

I look forward to your analysis of this.

**Comment by kYwzor** [comment]
> 
> 
> I was also getting the same issue. Left phone off for 10 days. Turned it on, opened wire. Waited about 30 minutes, and it didn't retrieve any messages from the previous 10 days, even though on my desktop app there were many.
> 
> I look forward to your analysis of this.

Hey @rothnorton, I wrote a new issue regarding this problem at #2145. If your problems are similar please share your situation too.
