### ISSUE TITLE
Youtube content without preview

### ISSUE THREAD

**Issue by kroerig** [wireapp/wire-android#2162]
**Describe the bug**
When sharing YT content from the YT app wire does not show a preview.

**To Reproduce**
Share a video from the YT app.

**Expected behavior**
Show a preview.

**Screenshots**
**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.33.786
- Last Wire version that did not exhibit the issue (if applicable):
- Android OS version used to run Wire: 9
- Is this a custom firmware or a stock one: Stock
- Mobile phone model/manufacturer: Sony
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): any

**Additional context**
YT uses different Domains. When sharing with the app it is www.youtu.be

**Comment by marcoconti83** [comment]
Hi @kroerig ,
thanks for opening the issue. This is already tracked here: https://github.com/wireapp/wire-android/issues/1941, closing this as a duplicate, please continue the discussion there.
