### ISSUE TITLE
Search doesn't find usernames that are 4 letters long

### ISSUE THREAD

**Issue by Mikaela** [wireapp/wire-android#2176]
**Describe the bug**

I have two friends who registered to Wire recently and they both have a short username that is made of four letters. When I search for them in Wire Android, I receive "no results", when I search for them in Wire Desktop I find them.

**To Reproduce**

1. Open Wire
2. Click on the person icon on lower left corner
3. Search for username that is 4 letters long
4. See "no results"

**Expected behavior**

I expect to see the person I am looking for like happens on Wire desktop.

**Screenshots**

N/A

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.33.786
- Last Wire version that did not exhibit the issue (if applicable): N/A
- Android OS version used to run Wire: 8.1.0 (Go Edition)
- Is this a custom firmware or a stock one: Stock
- Mobile phone model/manufacturer: Nokia 1 (TA-1047) / HMD Global
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi (VoWiFi connected)

**Additional context**

I haven't asked the two friends for permission to list their Wire usernames publicly, but I will link them to this issue.

**Comment by marcoconti83** [comment]
Hi @Mikaela ,
Nice catch. Probably an easy fix, but not the highest in our list of priorities. If anyone from the community would like to give this a try, we'd be happy to provide some hints.

**Comment by CyborgRahil** [comment]
HI @Mikaela 
Follow the steps which is mention by you in issue description but issue is not reproducible. Attach the screen shot in which it shows user list when username is 4 letters long.

![wire_android](https://user-images.githubusercontent.com/16253416/61079823-44772800-a441-11e9-9af8-e171d371f20f.png)

**Comment by Mikaela** [comment]
I am still able to reproduce it by searching for username "nyos" with an account that doesn't have them in contacts.

The other username is "peit" and as I have them in my contacts, they appear under contacts in search.

I am unable to provide a screenshot at the moment.

**Comment by CyborgRahil** [comment]
@Mikaela 
Can you please confirm whether their share contact is turn on from setting?
![Screenshot_20190714-014105](https://user-images.githubusercontent.com/16253416/61176111-bf267b80-a5d8-11e9-959e-d85d570381d0.png)

**Comment by Mikaela** [comment]
>  Can you please confirm whether their share contact is turn on from setting?

I forwarded the message, they will probably reply tomorrow. I can also now attach the two screenshots, but I can say that the account which says "No results" is not intentionally sharing contacts or phone numbers and no one should be aware of that phone number.

![wire-2176-1](https://user-images.githubusercontent.com/831184/61176872-e0c33b00-a5b7-11e9-8b73-0f6744ca9a9b.png)

![wire-2176-2 png](https://user-images.githubusercontent.com/831184/61176874-e587ef00-a5b7-11e9-9ce6-a837f3d63177.png)

**Comment by Mikaela** [comment]
Sorry for long response time @CyborgRahil , they have it turned on and say that they probably haven't been in that screen of settings or they would have enabled dark theme already.

![Wire 2019-07-16 at 5_18 AM](https://user-images.githubusercontent.com/831184/61306388-0c266f80-a7dc-11e9-9bc9-2e69a0701cd5.jpeg)

**Comment by CyborgRahil** [comment]
@Mikaela Now it works fine or still you are facing this issue.

**Comment by Mikaela** [comment]
The situation hasn't changed from https://github.com/wireapp/wire-android/issues/2176#issuecomment-510668690 & https://github.com/wireapp/wire-android/issues/2176#issuecomment-511156158.

Account 1 has Nyos in contacts and finds them in search under contacts.
Account 2 doesn't have Nyos in contacts and searching for them results to "ei tuloksia" (no results).

Account 2 doesn't have contact sharing enabled and I won't enable it as my contacts mostly aren't supposed to know about account 2, which I have lately been mainly using for reproducing this issue.

**Comment by makingthematrix** [comment]
Fixed in https://github.com/wireapp/wire-android/pull/2414
