### ISSUE TITLE
APK Not Installed

### ISSUE THREAD

**Issue by Surajvbinorkar** [wireapp/wire-android#2189]
I am new in Xamarin Forms, And I have created one sample application in vs 2017 community version 15.9.12, All works fine during dubbing and testing, and it run very fine on emulator. But the problem is after creating APK and trying to install it in other android devices its showing error message, "APK not installed", I have searched a lot, but not able to find any solution, let me share you images what i am trying to do.

![0settingandroidversion](https://user-images.githubusercontent.com/34466241/59742462-9356e680-9222-11e9-8465-7a8c80b9f087.PNG)

![1SettingForRelease](https://user-images.githubusercontent.com/34466241/59742134-c8166e00-9221-11e9-8e52-86eea8ac85df.PNG)

![2archvingall](https://user-images.githubusercontent.com/34466241/59742165-d6648a00-9221-11e9-8a75-c341eb1c7dc2.png)

![3successfullycreated](https://user-images.githubusercontent.com/34466241/59742168-d95f7a80-9221-11e9-9bee-2810cfdde504.PNG)

![4adhoc](https://user-images.githubusercontent.com/34466241/59742175-dc5a6b00-9221-11e9-964c-7d0fb9e80e89.PNG)

![5creatingandroidkeystore](https://user-images.githubusercontent.com/34466241/59742181-dfedf200-9221-11e9-843c-4448a3112629.PNG)

![6thsaveasapk](https://user-images.githubusercontent.com/34466241/59742187-e2504c00-9221-11e9-89fa-74b2442c0582.PNG)

At last I am trying to install created apk in other android devices and its showing error message "APK Not Installed".
Can anyone help? 

Thanks In Advance :)

Happy programming.

**Comment by marcoconti83** [comment]
Hi @Surajvbinorkar ,

it seems like your question is related to Android programming with Xamarin in general and not to Wire. There are plenty of places where to ask such question, for example [the Xamarin forum](https://forums.xamarin.com/). I think you will get more help there; this project is specific to Wire only.

Good luck!
