### ISSUE TITLE
Images never load completely

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-android#220]
Inline images (drawings/gifs) received in my Android client never fully load (blue bar keeps spinning). Loading state persist even after restarting the app, reconnections and reboots. The web app loads every image correctly.

I think that when I first started using Wire (`2.13.x`?) the bug was inconsistent - some images would load, others not. At least since `2.16.x`, the bug affects every image.

Currently using `2.17.284` in a custom 4.4.4 ROM, 3.0 Kernel with microG (no GAPPS/Google services).

**Comment by bjoernherbig** [comment]
Could you please send us a debug report when that happens?  ->Settings->Advanced->Submit debug report

**Comment by kehugter** [comment]
Sent.

**Comment by KyleGospo** [comment]
I have this very same problem using a Google Pixel on stock 7.1.2 beta. Debug report submitted to support.

**Comment by bjoernherbig** [comment]
fixed with [https://github.com/wireapp/wire-android-sync-engine/pull/97](url) .
