### ISSUE TITLE
Telemetry/Statistic informations which sending to server

### ISSUE THREAD

**Issue by veyebibice** [wireapp/wire-android#2211]
Hi,

What exatcly android app send to server?

- available wifi list
- my phone id
- as default google play telemetry informations
- my installed app list
- others...?...

Can you please define the list of them.

Thanks in advance

**Comment by marcoconti83** [comment]
Hi @veyebibice ,
you can find details in the security whitepaper that you can find at https://wire-docs.wire.com/download/Wire+Privacy+Whitepaper.pdf

**Comment by veyebibice** [comment]
@marcoconti83 thank you. I have 2 small questions:

- I see firebase on build gradle. So google servers can collect data, right?

- On Wire+Privacy+Whitepaper.pdf writes: "Server-side logs are only kept for a maximum of 72 hours". I am not a lawyer. But as far as I know the server logs (not the data which sended or received) legally required to be kept more than 2 days... Am I wrong?

Thank you

**Comment by marcoconti83** [comment]
Hi @veyebibice ,

- We use Firebase for push notifications, but not for analytics. The notifications that go through Firebase have no information on the content - the backend uses them to suggest to the device to check for new content (via a REST request), the notification that goes through Firebase it's just a "hey, you should check for new content".
- I am also not qualified to answer on the legal implications about the logs, I can just comment on the implementation
