### ISSUE TITLE
Some chats became inaccessible after last update

### ISSUE THREAD

**Issue by alien2003** [wireapp/wire-android#2226]
After last Wire Android update I can't access to at least 3 chats. One group and two contacts. It can be fixed by deleting content but I don't want to delete my memories. 
When broken chat is opened conversation dialog looks like empty or previous opened chat is displayed ![Screenshot](https://i.imgur.com/y82DGbR.png)

I have already sent logs to support

**Comment by middore** [comment]
I have the same problem after the latest update (3.35.807)
![Screenshot](https://user-images.githubusercontent.com/6775577/61870904-a626a000-aedf-11e9-8b42-d7d94c6da8d5.png)

**Comment by m4rkusxxl** [comment]
Same here. Half of my contacts have no history anymore. (They show the messages from the previous contact.)
The desktop version is still showing all histories.

**Comment by kroerig** [comment]
Same for me.

**Comment by Gardosen** [comment]
Hey everyone. 

We have released a hotfix build which should address this issue. 

Please check out our newest beta build and let me know if this solved the issue for you. 

Kind regards
Marco

**Comment by sengork** [comment]
@Gardosen After joining the beta channel and updating Wire it has fixed the issue for me.

I noticed that the new group messages would be readable in the notifications but not when viewed the app itself. Both function now for me. Thanks for the quick turnaround.

**Comment by m4rkusxxl** [comment]
When will it be pushed to the offical strore? Or can I download the beta apk from your homepage?

**Comment by kroerig** [comment]
Yes, the latest version fixed it for me.

**Comment by Gardosen** [comment]
> When will it be pushed to the offical strore? Or can I download the beta apk from your homepage?

I will evaluate the test results and the feedback of the beta testers on Monday morning. If everything looks fine, we will release the update to the public on Monday Lunchtime - Late noon.

I am happy to hear that the issue got fixed for you guys. @alien2003 how is it for you, does it work now? If so, i would solve this issue and close it.

Enjoy your Weekend!

Kind regards
Marco

**Comment by alien2003** [comment]
@Gardosen IDK, I deleted data for broken chats, can't test it :-( I'm sorry

**Comment by m4rkusxxl** [comment]
New version solved it for me.

**Comment by marcoconti83** [comment]
This should have been solved with the previous release (3.35). I'll close the ticket, please feel free to reopen if you still have issues.

**Comment by CeryleRudis** [comment]
> This should have been solved with the previous release (3.35). I'll close the ticket, please feel free to reopen if you still have issues.

This is unfortunately not resolved, and so starting to lose customers.
