### ISSUE TITLE
Unable to receive images

### ISSUE THREAD

**Issue by Parth** [wireapp/wire-android#2232]
**Describe the bug**

Using disappearing messages, received pictures are not viewable on Android. 

Have someone send you 2 pictures, one that disappears 1w from now, and one that doesn't. You will not be able to see the one that disappears on your android device. You will be able to see it on other platforms.

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.35.807
- Last Wire version that did not exhibit the issue (if applicable): The one from yesterday lol. 
- Android OS version used to run Wire: Android P, can provide more detail if needed. 
- Is this a custom firmware or a stock one: Stock
- Mobile phone model/manufacturer: Samsung galaxy s10
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): Doesn't matter

**Comment by crimsun** [comment]
Confirmed, I am also experiencing this symptom on Android Pie when disappearing messages are enabled.

The symptom is active on all released versions including and newer than 3.35.807. It is also, as expected, active independent of apk build (website or Play Store) and websocket ("maintain connection...") settings.

**Comment by crimsun** [comment]
The symptom is reproducible on iOS as well. If the sender has enabled disappearing messages (which is implied, but just stated for clarity—does not matter whether the recipient[s] has enabled disappearing messages), the recipient cannot view the sent image(s).

**Comment by IpsmLorem** [comment]
I can confirm the very annoying bug. Timed pictures has always been unreliable but now it doesn't even work. Keep up the good word by fixing the feature :)

**Comment by crimsun** [comment]
Still reproducible on Android 9 using version 3.36.819 from wire.com

**Comment by squeakyneb** [comment]
3.37.820 also seems to have this, had a channel with a timer that several people have had issues with, disabled the timer and sent an image, which displayed fine for two people who had previously consistently had this problem (my 3.37.820 version app being one of them)

**Comment by marcoconti83** [comment]
Hi all,
Thanks for the reports! We investigated the issue and likely found the cause, we are working on a fix that should be ready soon.

**Comment by marcoconti83** [comment]
Hi all,
thanks for the report. We just released a beta version that should fix your issue. We will probably release it to public beginning of next week, but you can give the beta version a try if you want to provide us some feedback. You can join the beta from the Play store page.

**Comment by crimsun** [comment]
@marcoconti83 The beta version (from the Play Store) appears to resolve the symptom. FWIW, I also did not experience the symptom using the non-beta version by enabling "Maintain connection to server".

**Comment by marcoconti83** [comment]
Hi @crimsun , 
thanks for confirming, that matches our finding too, as long as the connection is kept, everything was working fine.

**Comment by marcoconti83** [comment]
The version has been released to public.
