### ISSUE TITLE
Audio recorded on android does not work on ios

### ISSUE THREAD

**Issue by oetiker** [wireapp/wire-android#2233]
**Issue**

Audios recorded on wire for android 3.35 do show up in the ios client 3.39 but they are not playable ... storing the audio to files and the  opening it in iMovie makes the audio work

**To Reproduce**

Record audio on android and send to ios in a chat. Try to play audio in ios. The audio is not playable ... 

**Expected behavior**
The audio plays

see also https://github.com/wireapp/wire-ios/issues/3654

**Comment by marcoconti83** [comment]
Hi all,
This fix has just been released to public with version 3.42. I'll close the issue, feel free to reopen if this is still a problem.

**Comment by oetiker** [comment]
Now Audios recorded on Android show up nicely on ios, but audios recorded on ios can not be played back on android anymore.
