### ISSUE TITLE
User profile images not visible anymore

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#2238]
I only have a handful of user with an image, the rest are just colored letters.

How to reproduce: Might have cleared the app's cache, not sure.

**Comment by fichtennadel** [comment]
Same for more, even my own profile image isn't shown anymore. 
And I definitely didn't clean the app cache.

**Comment by BradleyWire** [comment]
Hi, 

Are you still able to reproduce this on the latest build (3.44)?

**Comment by fichtennadel** [comment]
no, I did a signout/signin and full sync, then the pictures showed up.

**Comment by BradleyWire** [comment]
I'll close this issue for now and if it comes up again, please don't hesitate to re-open.

**Comment by Transisto** [comment]
I still have the problem, Shouldn't have to resync to get it fixed.
reason : I don't want to risk losing my chat history.
