### ISSUE TITLE
I believe your app suffers from these android push notification quirks:

### ISSUE THREAD

**Issue by Parth** [wireapp/wire-android#2239]
https://www.freecodecamp.org/news/why-your-push-notifications-never-see-the-light-of-day-3fa297520793/

https://hackernoon.com/notifications-in-android-are-horribly-broken-b8dbec63f48a

**Comment by marcoconti83** [comment]
Hi @Parth ,
thanks for the suggestions! 

There is already an extensive discussion about notifications [here](https://github.com/wireapp/wire-android/issues/777), I would like to move the discussion to that issue so it's all in one place. I will close this one.
