### ISSUE TITLE
BETA: Conversations disappearing

### ISSUE THREAD

**Issue by CeryleRudis** [wireapp/wire-android#2249]
**Describe the bug*
Latest conversations do not show when re-opening a conversation.

**To Reproduce**
Occurs randomly, open a conversation.

1. Open a conversation

**Quickfix**
Close wire via the android task switcher and re-open.

**Expected behavior**
Messages should not disappear from a conversation.

**Screenshots**
No

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.35.815
- Last Wire version that did not exhibit the issue (if applicable): Probabl *.7* version
This has occurred for the last 2-3 beta versions.
- Android OS version used to run Wire: 7.0
- Is this a custom firmware or a stock one: No, stock
- Mobile phone model/manufacturer: Sony Xperia L1 G3311
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): WIFI

**Additional context**
This was claimed to be fixed as per the playstore description, but still occurs.

**Comment by CeryleRudis** [comment]
This has re-occurred on the latest version, next version after this listed release in the original post.

**Comment by marcoconti83** [comment]
Hi @CeryleRudis ,
Thanks for posting this issue. A fix has been released to public today. Please let us know if you are still experiencing similar issues.
