### ISSUE TITLE
Resend doesn't work if you edit the message

### ISSUE THREAD

**Issue by maximbaz** [wireapp/wire-android#2254]
1. Disable Wifi and mobile data
1. Send a message (it is marked as `Sending failed. Resend`).
1. Enable Wifi or mobile data.
1. Tap `Resend` - the message is marked as "Delivered" (✅)

Now repeat the same steps, but edit the undelivered message:

1. Disable Wifi and mobile data
1. Send a message (it is marked as `Sending failed. Resend`).
1. **Edit the message** (it is still marked as `Sending failed. Resend`).
1. Enable Wifi or mobile data.
1. Tap `Resend` - the message is marked as "Sent" and it will never be delivered ❌

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.36.819, 3.35.814
- Last Wire version that did not exhibit the issue (if applicable): N/A
- Android OS version used to run Wire: 8, 9
- Is this a custom firmware or a stock one: Stock
- Mobile phone model/manufacturer: Huawei P10 Lite, Vivo Z5x
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wifi, LTE

**Comment by Gardosen** [comment]
Hello @maximbaz ,

i first of all apologie for the late reply
thank you very much for the report.
I was able to verify this as still valid for the latest client of android 3.45.
I have added this as a high priority to our system.

I will keep you updated about the status when this is fixed.
TicketID: AN-6703

Kind regards
Marco from the Android Team

**Comment by makingthematrix** [comment]
fixed in https://github.com/wireapp/wire-android/pull/2727
