### ISSUE TITLE
"Maintain connection" option despite being on stock

### ISSUE THREAD

**Issue by neroux** [wireapp/wire-android#2273]
I recently installed **Wire 3.37.820** and noticed there is a "Maintain connection to server" option, which - as far as I understand - should only show up when FCM is not active, however I am on **stock "Pie"** so I'd assume FCM should be available just fine. The option is switched off and messages only appear after the application is being opened.

Shouldn't that option be unnecessary in this case and messages be delivered via FCM?

**Comment by marcoconti83** [comment]
Hi @neroux ,
we decided to give this option to everyone, regardless of what the app thinks is available on the phone, because sometimes there are false positive in the detection. So we give the user full control on this - you can turn it on and off, whatever works better for your particular phone.
