### ISSUE TITLE
Wire crashes on android 10

### ISSUE THREAD

**Issue by egarff** [wireapp/wire-android#2278]
Upgraded to android 10 (Build QP1A.190711.020), and wire now will not run.  Immediate crash on start.  Cleared cache, same result.

**Comment by makingthematrix** [comment]
> Upgraded to android 10 (Build QP1A.190711.020), and wire now will not run. Immediate crash on start. Cleared cache, same result.

Hi. What phone do you have? We will probably need to get the same model or something similar.

**Comment by TheWey** [comment]
Not sure about OP, but I can confirm this same issue is happening on my Pixel 3.

**Comment by egarff** [comment]
> > Upgraded to android 10 (Build QP1A.190711.020), and wire now will not run. Immediate crash on start. Cleared cache, same result.
> 
> Hi. What phone do you have? We will probably need to get the same model or something similar.

Pixel 3xl.  I'll spin up an android studio instance and see if it fails there as well.

**Comment by egarff** [comment]
`09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: Failed to initialize the app
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: java.lang.UnsupportedOperationException: Writing to internal storage is not supported.
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:481)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at android.content.ContentResolver.insert(ContentResolver.java:1828)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at com.waz.zclient.notifications.controllers.NotificationManagerWrapper$AndroidNotificationsManager$$anonfun$addToExternalNotificationFolder$1.apply(NotificationManagerWrapper.scala:1419)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at scala.Option.foreach(Option.scala:257)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at com.waz.zclient.notifications.controllers.NotificationManagerWrapper$AndroidNotificationsManager.addToExternalNotificationFolder(NotificationManagerWrapper.scala:381)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at com.waz.zclient.notifications.controllers.NotificationManagerWrapper$AndroidNotificationsManager.<init>(NotificationManagerWrapper.scala:316)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at com.waz.zclient.WireApplication$$anon$1$$anonfun$10.apply(WireApplication.scala:1134)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at com.waz.zclient.Singleton.value$lzycompute(Injectable.scala:30)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at com.waz.zclient.Singleton.apply(Injectable.scala:2030)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at com.waz.zclient.Injector$class.apply(Injectable.scala:38)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at com.waz.zclient.Injector$$anon$1.apply(Injectable.scala:45)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at com.waz.zclient.WireApplication.inject(WireApplication.scala:2023)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at com.waz.zclient.WireApplication.ensureInitialized(WireApplication.scala:436)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at com.waz.zclient.WireApplication$$anonfun$ensureInitialized$4.apply(WireApplication.scala:1391)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at scala.Option.fold(Option.scala:158)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at com.waz.zclient.WireApplication.ensureInitialized(WireApplication.scala:390)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at com.waz.zclient.WireApplication.onCreate(WireApplication.scala:383)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at com.waz.zclient.ZApplication.onCreate(ZApplication.java:94)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at android.os.Handler.dispatchMessage(Handler.java:107)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at android.os.Looper.loop(Looper.java:214)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at java.lang.reflect.Method.invoke(Native Method)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
09-05 08:43:14.389 23237 23237 E com.waz.zclient.WireApplication$: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
09-05 08:43:14.433 23237 23237 E AndroidRuntime: 	at com.waz.zclient.WireApplication$$anon$1$$anonfun$10.apply(WireApplication.scala:1134)
09-05 08:43:14.433 23237 23237 E AndroidRuntime: 	at com.waz.zclient.WireApplication.inject(WireApplication.scala:2023)
09-05 08:43:14.433 23237 23237 E AndroidRuntime: 	at com.waz.zclient.WireApplication.ensureInitialized(WireApplication.scala:436)`

**Comment by egarff** [comment]
Sorry to spam, but I wanted to note, above it mentions writing to internal storage is not supported, but looking at the app permissions "Storage" is definitely set to allowed.  Still going to spin up the virtual device, I'll get back to you.

**Comment by egarff** [comment]
I appear to have a workaround.  I tried the android VM, and it worked (but this obviously was a new install of wire).  Being that the error mentions internal storage, I set the storage permission to deny, attempted to open and it still crashed, then set storage to allow and it now opens and works.

**Comment by makingthematrix** [comment]
@egarff Thanks a lot!

**Comment by TheWey** [comment]
@egarff Your workaround works for me as well!

**Comment by makingthematrix** [comment]
Fixed, although I can't find the commit number...
