### ISSUE TITLE
Are You Ever Going to Fix The Android Window Layout?

### ISSUE THREAD

**Issue by madranet** [wireapp/wire-android#2289]
I've been complaining about this for over a year now and it never gets fixed. Responses I've got from Wire people [when mentioning this on Play Store reviews] have ranged from "*Mobile devices aren't supported"* [WTF???] to *"It's a bug. we're planning to fix it"* to *"We have no plans to change it"*

Basically: 

For anyone who composes messages longer than a couple of 'txt spk' words and an emoji *[there are those of us out there who still communicate using actual words and sentences!]* the message composition window in Android is barely functional.  There is only a single line text entry field for composing in and the rest of the screen is devoted approximately 50/50 to the popup keyboard and the display of previous messages & toolbar icons.

This makes composing reviewing and correcting the text of a message before we send it incredibly annoying and frustrating.  Have you ever tried selecting, scrolling or editing text within a one line high input box? It's a nightmare!

I know screen space is limited but why devote seven lines of that available space to showing me icons for rarely used functions and the message/s I've just read –and only one line to letting me compose my reply? 

Also, the toolbar for adding attachments, pinging, drawing, etc permanently occupies a space equal to the height of the text input box. That toolbar could easily be hidden and popped up when needed via [for example] an arrow on top of the keyboard. 

Using a combination of that and devoting less lines to showing me what I've already read, you could easily make the compose box 4 or 5 lines high and less torturous to use, without impacting the usability of the app. 

How's about it?

![Screenshot_20190913-161828](https://user-images.githubusercontent.com/669658/64875454-18e10b80-d645-11e9-9cc8-751c13198903.png)

cf: #1726 and #1900

**Comment by madranet** [comment]
EDIT: I notice that, when typing, I can just about see two lines of text in the input box, which is an improvement on one I suppose! But the point still stands. So much wasted screen space elsewhere. Why not allow the compose box to have some?

**Comment by kroerig** [comment]
I don't use WA but how did they solve this challange?

**Comment by EliasA** [comment]
This truly is an obstacle of broader use. If you really have see what you are about to send, the UI is vary hard to use. For civil servants, lawyers etc. this is a dealbreaker.

**Comment by BradleyWire** [comment]
This has been released with v3.44. You can get the up to date version on the play store.

**Comment by madranet** [comment]
???

So, what exactly is supposed to have changed then?

I've updated to V3,44 and am still seeing exactly the same as before; a 'just-about-2-lines' text input box for composing messages?

![Screenshot_20200106-192412](https://user-images.githubusercontent.com/669658/71843099-09397700-30bb-11ea-88a2-7a0578b57146.jpg)

![Screenshot_20200106-192510](https://user-images.githubusercontent.com/669658/71843115-10f91b80-30bb-11ea-8153-bbcb16cdc40d.jpg)

**Comment by maximbaz** [comment]
it now grows as you keep typing text, to up to five lines, try adding new lines for example

**Comment by madranet** [comment]
By Jove! You're right.   I shouldn't have stopped "blah-ing" so soon.  Thats going to make composing messages a lot less frustrating.

![Screenshot_20200106-194009](https://user-images.githubusercontent.com/669658/71843926-e9a34e00-30bc-11ea-95e2-0887b6525561.jpg)
