### ISSUE TITLE
Cannot switch back to bluetooth headset

### ISSUE THREAD

**Issue by marmarek** [wireapp/wire-android#2294]
**Describe the bug**
Switching back to bluetooth headset output during audio-only call doesn't work, even if it initially worked.

**To Reproduce**
A detailed description will help us to fix the issue faster. 

1. Connect bluetooth headset
2. Initiate audio-only call
3. Verify the audio is routed to the headset
4. Press "speaker" button to switch audio output to the internal speaker
5. Press "speaker" button again to switch back to the bluetooth

At this point, audio stays routed to the internal speaker and there is no way to switch back to bluetooth.

**Expected behavior**
Audio switched back to bluetooth headset.

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.38.826
- Last Wire version that did not exhibit the issue (if applicable): n/a
- Android OS version used to run Wire: 9
- Is this a custom firmware or a stock one: custom (plain AOSP build, without play services)
- Mobile phone model/manufacturer: Google Pixel 3
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): wifi

**Comment by Gardosen** [comment]
this bug has been fixed and it works under our latest version 3.45.

i close this ticket as resolved

Kind regards
Marco from the Android Team
