### ISSUE TITLE
file attachments do not appear on receiving side

### ISSUE THREAD

**Issue by boycottAmazon** [wireapp/wire-android#2298]
When I use the linux app to send a PDF attachment to a user who only uses wire-android, they do not see the file.  There is not even an indication on the receiving side that a file was sent.

**Expected behavior**
Wire-android should show that a file file was sent.

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: Recipient downloaded the default version from Playstore yesterday.
- Last Wire version that did not exhibit the issue (if applicable):
- Android OS version used to run Wire:
- Is this a custom firmware or a stock one: probably stock
- Mobile phone model/manufacturer:
- Mobile network type (EDGE/LTE/Wi-Fi/Offline):

**Additional context**
I know there cannot be a problem on the sending side because the sender (myself) often sends PDFs to android-ios users without issue.

Note as well that the sender has both the linux version and the android version.  The linux version sent the file, but unlike the android recipient, the android version of the ***sender*** can see a record of the transmission.  However, the sender cannot view the PDF that was sent and only has the option to delete the file.

**Comment by marcoconti83** [comment]
Hi @boycottAmazon ,
thanks for the report. We just released a beta version that should fix your issue. We will probably release it to public beginning of next week, but you can give the beta version a try if you want to provide us some feedback. You can join the beta from the Play store page.

**Comment by marcoconti83** [comment]
The fix has just been released to public.
