### ISSUE TITLE
AVS new version of video and voice problems

### ISSUE THREAD

**Issue by lingduzuobiao123** [wireapp/wire-android#2301]
1, I can't see each other after the video call is connected.  
    Maybe onVideoReceiveStateChanged method is not called
2,Voice multiplayer crash

**Comment by marcoconti83** [comment]
Hi @lingduzuobiao123 ,
Thanks for the report, we probably fixed this issue with https://github.com/wireapp/wire-android/pull/2292, we'll ask you to test again as soon as this is published to confirm the fix!

**Comment by lingduzuobiao123** [comment]
The problem still exists, not caused by removing  {showString(view.toString)},
You can try video and voice calls yourself.

**Comment by marcoconti83** [comment]
Hi @lingduzuobiao123 , 
thanks for clarifying, we'll look into it

**Comment by marcoconti83** [comment]
Can you confirm if this happens on a version that you compiled yourself?

**Comment by marcoconti83** [comment]
Hi,
This fix has just been released to public with version 3.42. I'll close the issue, feel free to reopen if this is still a problem.
