### ISSUE TITLE
Forwarding video loses audio

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#231]
I've already reported this issue over two months ago, but since I ran into it again today...
Steps to reproduce (Android 7, Nexus 5X):
- Open a conversation, share a file, select a video*
- Once the video has been sent, long press on it, forward, select another wire conversation
- The new contact you sent the video to will see the video correctly but audio will be missing

Let me know if you need anything else.

*by the way, sharing videos from gallery fails some 99% of the time (I also reported this in the past..), leaving me with the only choice of sharing from within Wire

**Comment by freditbn** [comment]
my issue is very similar:

No matter how i try to forward videos videos from wire, sound is lost when forwarded. The videos play silently.

The sound also disappears when videos not recorded on wire are forwarded within the app.

The sound is lost on the sender and recipient device. No matter what video player is launched to play the forwarded video.

when the video is saved on the device from within wire, the sound plays when the video is played. However when the downloaded video is sent from the gallery or an explorer to a wire contact. the sound is also lost.

Sent videos from gallery that have never been in a wire conversation before seem to keep sound.

Environment

Wire version that exhibits the issue: 2.41.359
Last Wire version that did not exhibit the issue (if applicable): n/a
Android OS version used to run Wire: 7.0
Is this a custom firmware or a stock one: stock LG, V10f-AME-XX, rooted
Mobile phone model/manufacturer: LG V20, H990DS
Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/WiFi

**Comment by makingthematrix** [comment]
@matt3055 Is your bug still happening? From the description I assume it's different from the original one (and that one was fixed afaik).
