### ISSUE TITLE
How to decode android_wbu Assets otrKey and sha256 to JS arrays?

### ISSUE THREAD

**Issue by CroneG** [wireapp/wire-android#2322]

**Comment by marcoconti83** [comment]
Hi @CroneG ,
we don't use JS (JavaScript) in the Android project. Can you elaborate on what you trying to do?

**Comment by Gardosen** [comment]
question was indirectly answered by marcoconti83, 

as there is no response to the question of @marcoconti83, i will close this ticket now.

Kind regards
Marco from the Android Team
