### ISSUE TITLE
Register only with mobile/cellphone number possible, not with email address

### ISSUE THREAD

**Issue by Filbuntu** [wireapp/wire-android#2324]
**Describe the bug**
On the **Wire website** of Wire there is the possibility to register with an **email address** (although it is quite hidden: https://app.wire.com/auth/)  but in the mobile app you can **only** register with a **cellphone/mobile number**.

**Steps to reproduce the behavior:**
1. Open Wire App on a mobile device.
2. Create an account
3. You can NOT choose between email address or cellphone number to register, you can only register with cellphone number.

**Expected behavior**
It would be more user and privacy friendly if you can choose between email address or cellphone number to register in the mobile Wire app.

Thanks!

**Comment by marcoconti83** [comment]
Hi @Filbuntu ,
You are correct, at the moment registering by email is only available on the website. Until this gets on our roadmap, we encourage users that need to register by email to use the webapp to register, then switch to mobile.

**Comment by Filbuntu** [comment]
Hi @marcoconti83!
Thank you for your feedback! 
Hopefully you will be able to set on the roadmap soon as you are a privacy concerned company and not many would know the workaround with the webapp.

**Comment by Gardosen** [comment]
registering via email is implemented since some versions. i mark this ticket as solved.

Kind regards
Marco from the Android Team

**Comment by Filbuntu** [comment]
Hi @Gardosen ! 
Thank you for sharing this great news. Would you be able to share in which versions you can register via email?
Thanks
