### ISSUE TITLE
Wire closes when trying to talk with Otto the Bot

### ISSUE THREAD

**Issue by paulocoghi** [wireapp/wire-android#236]
**Description:**
When I select Otto the Bot in the contact list and enter in his message screen, Wire closes immediately.

**Wire Version:**
2.18.288 (Android, installed from Google Play)

**Phone model:**
Asus Zenfone 2 ZE551ML

**Android Version:**
5.0

**Comment by someoneEsle** [comment]
Have you ever talked to Otto the Bot in the past, or did you just recently sign up? I think the developers could use a debug log too -->Settings>advanced>submit debug report

**Comment by paulocoghi** [comment]
I have never talked with him. I just recently signed up.

**Comment by bjoernherbig** [comment]
thanks for bringing this up here. please send a debug report as mentioned above, or a crash log.

**Comment by paulocoghi** [comment]
@bjoernherbig My pleasure! I am sending a debug report right now :+1:

**Comment by david-wire** [comment]
@paulocoghi Thanks. It looks like we have found the root cause of this issue. We're looking into it.
In the meantime, we have also released version 2.19.289 which includes some fixes. Could you update as well?

**Comment by paulocoghi** [comment]
I can confirm hat the issue is solved with **2.19.289**

Thanks, @david-wire !
