### ISSUE TITLE
Open Up Wire Server Source Code and Implement Decentralization

### ISSUE THREAD

**Issue by balasankarc** [wireapp/wire-android#237]
Even if end-to-end encryption solves the confidentiality issue from a security PoV, it would be great to have Wire server source code.

Enabling users to run their own Wire servers and thus control their data would be a huge help towards the cause of data confidentiality.

**Comment by ffflorian** [comment]
See #12.
Also Wire recently [announced](https://www.facebook.com/wire/videos/vb.201733596663034/635632613273128/?type=3&theater) that they will open source the server code at some point in the future but it's not clear when.

**Comment by teller** [comment]
@balasankarc Check Wire CTO talk from last week https://www.facebook.com/wire/videos/635632613273128/

Skip to 22:05 mark where Alan covers server code and possible timeline.

**Comment by mimf** [comment]
I hate facebook. Is that video not available elsewhere? (youtube, vimeo, whatever). Also, since you've watched the video, can't you just quote what he said, in regards with a possible timeline?

**Comment by ffflorian** [comment]
@mimf
[Let me Google that for you...](http://lmgtfy.com/?q=facebook+video+downloader)

**Comment by tuxayo** [comment]
Open sourcing the server is important, it's a part of the application. Claiming that Wire is libre/open source when the server is not can be perceived as misleading by at least some users.

It's a matter of durability: what happens if the main developers for any reason can't continue developing or running the server? Then the whole project will become unusable.

What happens in case of disagreement in how to do something? The whole project can't be forked due to the dependency on the server. See the LibreSignal story for an example of such disagreement between the devs and some of the users.

**Comment by teller** [comment]
@tuxayo Wire is not a small OS project but a for-profit organization with tens of developers - hope that takes some of the concern away.

In terms of open sourcing the server - we're stated on social media and to journalists that it will be open sourced this year, quite possibly in the first half.

**Comment by tuxayo** [comment]
Awesome! Is there a way to make a donation? Cause tens of developers must eat a lot ^^ (I can't find your business model)

**Comment by alugarius** [comment]
Still waiting

**Comment by teller** [comment]
First step https://medium.com/@wireapp/open-sourcing-wire-server-code-ef7866a731d5

**Comment by survivor303** [comment]
when we can get it and really run on our own servers? :)

**Comment by teller** [comment]
@survivor303 It will be a lengthy process, several months minimum.

**Comment by colans** [comment]
As part of the source code release process, will the TOS be relaxed as well?

> 7.2 Accessing the Service. You agree not to access, or attempt to access, the Service by any means other than through the Site or the Apps. You specifically agree not to access, or attempt to access, the Service through any automated means (including, without limitation, through the use of scripts, bots, unauthorized third party apps, spiders or web crawlers).

This is currently preventing federation with [matrix.org](https://matrix.org/).

**Comment by TechnicLab** [comment]
Any update on this?

**Comment by someoneEsle** [comment]
Have you read this? https://medium.com/@wireapp/wire-server-code-now-100-open-source-the-journey-continues-88e24164309c

**Comment by TechnicLab** [comment]
Thank you, i missed it somehow. Still it would be great to have some kind of ETA.

**Comment by colans** [comment]
I created a separate issue for my comment above, relaxing the TOS to allow external federation.  See https://github.com/wireapp/wire/issues/160.

**Comment by marcoconti83** [comment]
Hi everyone and thanks for contributing. 

Given that this issue has been opened in the android repository, but it's about the server, I would move the discussion elsewhere.

The wire server has been open sourced and it's now technically possible to run your own instance of the wire server. Any issue regarding this can be opened in the [repository](https://github.com/wireapp/wire-server).

For what regards the TOS, @colans has opened a separate [dedicated issue](https://github.com/wireapp/wire/issues/160).
