### ISSUE TITLE
jp.leafytree.android-scala plugin not working

### ISSUE THREAD

**Issue by AkashiHidaka** [wireapp/wire-android#2372]
**Describe the bug**
Gradle compile not working

**To Reproduce**
When Gradle compile it see message "ERROR: Could not find matching constructor for: org.gradle.api.internal.file.DefaultSourceDirectorySetFactory(org.gradle.api.internal.file.BaseDirFileResolver, org.gradle.api.internal.file.collections.DefaultDirectoryFileTreeFactory) Open File" and it show this define part( apply plugin: 'jp.leafytree.android-scala' )

When import project and during run it shows above error.

**Expected behavior**
Stopped work and not advance more.

**Screenshots**
![image](https://user-images.githubusercontent.com/44053447/66901996-71d00500-f032-11e9-8270-1899742662e6.png)

**Smartphone (please complete the following information):**
- I using the last release version and my "Android Studio" version is last version.

**Comment by AkashiHidaka** [comment]
https://github.com/wireapp/wire-android/releases/tag/3.40

**Comment by gizemb** [comment]
Hi, could you possibly have updated the android gradle build tools version? The plugin is compatible w/ version 3.2.1 the latest. We're working on it to update the plugin.
`classpath 'com.android.tools.build:gradle:3.2.1'`

**Comment by gizemb** [comment]
Hi, @AkashiHidaka. Did you try what I suggested?

**Comment by BradleyWire** [comment]
I'm going to close this issue due to inactivity. If you have any further problems, please open it back up again.

**Comment by RAZA-ABBBASI** [comment]
I am also getting the same error, Did someone solve it? Any solution please?

**Comment by RAZA-ABBBASI** [comment]
I am also facing the same error, I am using followng gradle version 
Gradle Plugin version: 4.0.1 
Gradle version 6.1.1
