### ISSUE TITLE
Not possible to make linebreaks in messages

### ISSUE THREAD

**Issue by n3eo** [wireapp/wire-android#2373]
**Describe the bug**
When writing a message to a contact it is not possible to create a linebreak in the message any more.

**To Reproduce**
Setting set to show additional send button in UI

1. Write message to any contact
2. Write anything
3. Try to make line break
    I use the Huawei Swipe keyboard in German -> Button on bottom left says "Weiter" instead of the usual line break symbol
4. Focuses out of keyboard, no linebreak

**Expected behavior**
Show linebreake button and make a line break in message.

**Screenshots**
1. Writing the message
![Screenshot_20191017-103933](https://user-images.githubusercontent.com/36729513/66992737-98da1580-f0ca-11e9-8208-e3f49613248a.png)
2. Clicking on "Weiter"
![Screenshot_20191017-103938](https://user-images.githubusercontent.com/36729513/66992771-abece580-f0ca-11e9-8fa3-52a38921cab0.png)

**Smartphone:**
- Wire version that exhibits the issue: 3.41.848
- Last Wire version that did not exhibit the issue (if applicable): 3.41.844 (not sure)
- Android OS version used to run Wire: 7.0
- Is this a custom firmware or a stock one: stock
- Mobile phone model/manufacturer: Huawei P9
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): makes no difference

**Additional context**
When changing the setting to send by pressing enter, it is possible to make linebreaks, but you can't send anymore.

**Comment by marcoconti83** [comment]
Hi @n3eo ,
thanks for the report, we are looking into a fix

**Comment by Transisto** [comment]
You should have pushed a fix to you newly added bug a few days after.

Last 50 reviews are almost all 1 Star, I suggest you get your shit together.

**Comment by marcoconti83** [comment]
Hi all,
A fix for this has been prepared [here](https://github.com/wireapp/wire-android/pull/2384) and should be released soon.

**Comment by marcoconti83** [comment]
Hi all,
This fix has just been released to public with version 3.42. I'll close the issue, feel free to reopen if this is still a problem.
