### ISSUE TITLE
Cannot send message by enter

### ISSUE THREAD

**Issue by luckyraul** [wireapp/wire-android#2374]
**Describe the bug**
Cannot send by enter in message with hidden send button.

**To Reproduce**
Go to message, write a new one, hit enter

**Expected behavior**
Message sent

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.41.848
- Last Wire version that did not exhibit the issue (if applicable): previous
- Android OS version used to run Wire: 8.1
- Is this a custom firmware or a stock one: stock
- Mobile phone model/manufacturer: Blackberry Key 2
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): wifi

**Comment by marcoconti83** [comment]
Hi all,
Thank for the report, we will look into a fix.

**Comment by marcoconti83** [comment]
A fix for this has been prepared [here](https://github.com/wireapp/wire-android/pull/2384) and should be released soon.

**Comment by marcoconti83** [comment]
Hi all,
This fix has just been released to public with version 3.42. I'll close the issue, feel free to reopen if this is still a problem.
