### ISSUE TITLE
Messages don't get delivered when in standby

### ISSUE THREAD

**Issue by kroerig** [wireapp/wire-android#2399]
**Describe the bug**
When device is in standby messages don't get delivered.

**To Reproduce**
Enable all notification options in Android for Wire-App. Put your device in standby mode (display off). Send a message to the account on this device. You can see it as "sent" but it doesn't get delivered until you open wire on the device. You even don't get a notification.

**Expected behavior**
Messages get delivered in background and notification working

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: at least 3.41.848
- Last Wire version that did not exhibit the issue (if applicable): n/a
- Android OS version used to run Wire: 9
- Is this a custom firmware or a stock one: stock  (MIUI 11)
- Mobile phone model/manufacturer: Xiaomi Redmi 7a
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wifi

**Comment by alien2003** [comment]
Android app is shit. It has so much bugs that it should be rewrited from scratch.
I also have issues with notifications. GCM just randomly stops working for me

**Comment by marcoconti83** [comment]
Hi all,
Please try going through the notifications troubleshooting checklist and let us know if any steps there solved your problem.
https://support.wire.com/hc/en-us/articles/203624294-What-can-I-do-if-I-m-not-getting-any-notifications-on-Android-

**Comment by p4ch1nk0** [comment]
you're setting the bar pretty low for usability if you expect all the users with this problem to have to run down this checklist and reconfigure their phone so deeply. as an added bonus the checklist is still not effective for any of my contacts and we still get delayed notifications including missed calls.

**Comment by Gardosen** [comment]
Hello @p4ch1nk0 , @kroerig and @alien2003 ,

sorry for the late reply, but as a sign of improvement i wanna catch up on this with you all.
over the past 4 versions, our developers worked a lot on the topic notifications, and found some issues which they took their time to rewrite these parts of the code and they are part of the latest wire client version 3.45.

please let me know, if the situation has improved for you. if yes, what issues with the notification system do you still have? if no, i am happy to hear that :)

i will keep this ticket open for another 7 days to wait for your response. after that i will close it for cleanup purpose, but feel free to open another ticket after this is the issue still persists.

Kind regards
Marco from the Android Team
