### ISSUE TITLE
The Android app fails to mention the takeover by US Morpheus Ventures

### ISSUE THREAD

**Issue by dietercastel** [wireapp/wire-android#2416]
When going to the Android app I get no mention that Wire has been bought by a [US holding called Morpheus Ventures](https://morpheus.com/portfolio/) I think as a European user I should get notified when such a thing happen. Transparency is key in this sensitive industry.

[It's also not on the wire blog](https://www.google.com/search?q=site%3Awire.com+Morpheus&oq=site%3Awire.com+Morpheus&aqs=chrome..69i57j69i58.8112j0j1&sourceid=chrome&ie=UTF-8) (but that's not an Anrdroid bug I guess).

**Comment by marcoconti83** [comment]
Hi @dietercastel ,

Thanks for expressing your concern about the future of Wire. There has been no change of ownership ("Wire being bought"). You can read more here: https://wire.com/en/blog/wire_business_update/

Quoting from that article:

> In connection with the financing, our holding company moved from Luxembourg to the U.S., as we believe this will be helpful in future fundraising necessary to support our strong growth. Notwithstanding the foregoing, our current and future customers are licensed and serviced from Wire Switzerland, our software development team remains in Berlin, Germany, and our hosting is European-based. Our enterprise customers can deploy their own instance of Wire in their own data center. 

I'm closing this issue as not related to Android per-se. If you have more questions on this topic, you can reach out at press@wire.com.
