### ISSUE TITLE
Notify of key changes

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#242]
I don't remember ever receiving notifications for key changes in my friends' identities (even though some of them reinstalled the app). Is this going to be implemented?

**Comment by bjoernherbig** [comment]
we will look into this. you should get a notification if a verified device gets changed

**Comment by someoneEsle** [comment]
Interesting! I didn't know that. I don't really verify people's fingerprints because there's no "easy" way to do that -- but I do verify my own devices' fingerprints

**Comment by Be-ing** [comment]
I think it should be considered whether a notification should be shown for key changes even if the fingerprint has not been verified. This would kind of be like trusting upon first contact.

**Comment by bjoernherbig** [comment]
fixed in  [https://github.com/wireapp/wire-android-sync-engine/pull/45](url)
