### ISSUE TITLE
Security bypass of "Lock with Passphrase" screen

### ISSUE THREAD

**Issue by gopherit** [wireapp/wire-android#2424]
**Describe the bug**
Starting with Wire for Android 3.42.863 released on November 14, 2019, the lock screen can be bypassed by simply ignoring the prompt to use fingerprint or passphrase, closing the app, then re-opening the app within 10 seconds.

**To Reproduce**

1.  Let Wire go idle in the background so that it locks itself.
2.  Switch to Wire app and see the Android lock screen asking for fingerprint or passphrase.  There is also a second "Wire" lock screen behind the Android one asking for the Wire password in case the Android prompt is canceled.
3.  Close Wire.
4.  Within about 10 seconds, if you re-open Wire, there will be no lock screen anymore.

**Expected behavior**
* The Android password/fingerprint prompt should not be able to be bypassed.
* The Wire password prompt behind the Android prompt looks a bit odd.

**Screenshots**

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue:  3.42.863
- Last Wire version that did not exhibit the issue (if applicable):  All prior versions
- Android OS version used to run Wire:  Android 10
- Is this a custom firmware or a stock one:  Stock
- Mobile phone model/manufacturer:  Pixel 2
- Mobile network type (EDGE/LTE/Wi-Fi/Offline):  N/A

**Comment by marcoconti83** [comment]
Hi @gopherit ,
thanks for the report. We will look into this issue!

**Comment by gopherit** [comment]
I believe #2423 or #2429 (or both) fixed this issue.  I can no longer bypass the security by closing and immediately opening Wire.
