### ISSUE TITLE
Synchronization issues during internet disconnection

### ISSUE THREAD

**Issue by aurabindo** [wireapp/wire-android#2426]
**Describe the bug**

When experiencing internet connectivity issues, android app fails to synchronize properly, and freezes at a stale state. Full update does not happen immediately after internet connectivity is re-established. Proper update happens after an unknown time in the future. Clearing the app from memory and opening again did not help.

**To Reproduce**

0. Go to a location far far away from Switzerland (about 8000 Km).
1. Random internet disconnection happening
2. Lots of traffic coming in to a group chat.
3. After internet connection is established, Wire does not synchronize properly
1. Only the roster view is accessible. Upon tapping an individual chat or a group chat, its corresponding window does not show up.
2. There is a blue stroke at the top the app indicating unsynchronized state.

**Expected behavior**

Immediately retrieves all messages.

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.41.848
- Last Wire version that did not exhibit the issue (if applicable): Dont know
- Android OS version used to run Wire: Android 9
- Is this a custom firmware or a stock one: stock
- Mobile phone model/manufacturer: Nokia 3.1
- Mobile network type (EDGE/LTE/Wi-Fi/Offline):Wi-Fi

**Additional context**

On the web app, during the internet disconnection, when I'm sending a message, the  text freezes and goes greyed out, indicating that the text is not sent. Even after the internet connection is re established, the greyed out text is not successfully sent. Upon re-sending another text, it succeeds but not the old failed text. 

I am from a location where average ping to servers in Switzerland takes 300ms+ (I assume all wire servers are in Switzerland)

Sorry for such a lame bug report, but I wish wire app and server was more responsive for me.

**Comment by marcoconti83** [comment]
Hi @aurabindo ,

Thanks for the report. From your description it seems like this issue, even if might show different symptoms for you, is the same as https://github.com/wireapp/wire-android/issues/2321. We are tracking comments and progress in https://github.com/wireapp/wire-android/issues/2321 and I will close this issue to avoid duplication. We can continue the discussion there.
