### ISSUE TITLE
Switch off screen in a call

### ISSUE THREAD

**Issue by ffflorian** [wireapp/wire-android#243]
The call functionality is great and I'm impressed by the audio quality!
However, after a call I sometimes end up in some settings menu because I accidentally touched the screen while holding the phone at my ear. It would be great if the screen would switch off while talking (by using the [proximity sensor](https://developer.android.com/guide/topics/sensors/sensors_position.html)) and switch on back again when I want to end the call or the other user hangs up.

**Edit**:
Additional device info:
Wire version 2.18.288
Android 6.0.1 (CM 13) on Nexus 5X

**Comment by bjoernherbig** [comment]
thanks for reporting this. the proximity sensor whould actually deactivate the screen while calling so this indeed is a bug.

**Comment by ffflorian** [comment]
By the way, this was on a Nexus 5X and is resolved by now. 👍
