### ISSUE TITLE
Specific unicode characters in group title cause instant crashes

### ISSUE THREAD

**Issue by stukev** [wireapp/wire-android#2432]
**Describe the bug**
Specific unicode characters such as runes cause wire to crash if they are used as a group name.

**To Reproduce**
Make a new group chat and invite however many people you want. Now change the conversation name to something like "ᚠᚢᚦᚨᚱᚲᚷᚹᚺᚾᛁᛃᛈᛇᛉᛊᛏᛒᛖᛗᛚᛜᛞᛟ" and everyone will crash whenever the app loads the specific conversation.

1. Create a new group conversation.
2. Change the group name to anything containing runic unicode such as ᚠᚢᚦᚨᚱᚲᚷᚹᚺᚾᛁᛃᛈᛇᛉᛊᛏᛒᛖᛗᛚᛜᛞᛟ
3. Everyone in the group chat will crash.
4. If wire is reopened and the group name is loaded again it will crash repeatedly. Making the entire app unusable.

**Expected behavior**
No crash

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.42.863
- Last Wire version that did not exhibit the issue (if applicable): None
- Android OS version used to run Wire: 8.0.0
- Is this a custom firmware or a stock one: Stock
- Mobile phone model/manufacturer: LG G6+
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): All

**Additional context**
I had already reported this to the support email months ago and never gotten a reply except for the automated one.

**Comment by marcoconti83** [comment]
Hi @stukev ,
thanks for the report. We never tried using runes as conversation title 😄  , we'll give it a try and see how we can fix this.

**Comment by BradleyWire** [comment]
This issue has now been released in v3.44 on the playstore. Please update your app.
