### ISSUE TITLE
Missing a "send" key when in landscape

### ISSUE THREAD

**Issue by mimf** [wireapp/wire-android#244]
I don't know if it was always like this or just since the last update. I think it's since the last update, because I never noticed and it's certainly annoying.

When I'm typing a message in landscape mode, there's no "send" key (the arrow-looking button). It's there in portrait mode. So in order to send a message, I type in landscape and then change to portrait, to send.

**Comment by bjoernherbig** [comment]
Thanks for reporting this. We will check. What device are you on?

**Comment by mimf** [comment]
Android 5.0.2

**Comment by bjoernherbig** [comment]
right. i meant the tablet type you are using.

**Comment by mimf** [comment]
It's not a tablet, it's a smartphone. An LG smartphone.

**Comment by vova-lohika** [comment]
We do not support landscape mode for smartphones. Only tablets.

**Comment by mimf** [comment]
Oh, I'm using an app to change orientation for the apps that somewhy do not support it. My bad. I guess I'll create a feature request issue then.
