### ISSUE TITLE
New crashing issue in last beta

### ISSUE THREAD

**Issue by alien2003** [wireapp/wire-android#2441]
https://streamable.com/59wgm

No comments. After one bug is fixed, new bug is added.

I'm done. Wire was great messenger. I used it for few years regardless of electron desktop app. I promoted Wire among my friends and family, I have 50+ contacts on Wire and I'm going to move to XMPP which is at least reliable

**Comment by alien2003** [comment]
Randomly fixed after 30 minutes, IDK how

**Comment by marcoconti83** [comment]
Hi @alien2003 ,

Thanks for opening the report, is there any way for you to get a crash log? E.g. connect to a computer with `adb` and `logcat`?

**Comment by alien2003** [comment]
@marcoconti83 happenned to me again right now.  Logcat output using Termux:
```
11-27 03:46:38.631 27259 27259 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
11-27 03:46:38.631 27259 27259 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
11-27 03:46:38.631 27259 27259 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
11-27 03:46:38.632 27259 27259 W IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
11-27 03:46:38.632 27259 27259 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
11-27 03:46:53.289 27259 27259 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
11-27 03:46:53.289 27259 27259 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
11-27 03:46:53.289 27259 27259 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
11-27 03:46:53.294 27259 27259 W IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
11-27 03:46:53.294 27259 27259 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
```

If it's not enough I'll connect phone to PC and get more logs

Crash caused by me sending message with markdown `> quote`. After few new incoming messages it was fixed, no more crash on app launch but when I open thar chat and scroll up to my `> quote` Wire crashes

**Comment by marcoconti83** [comment]
Hi @alien2003 ,
thanks for the report. We have a fix for this issue! It will be released soon (not in the next release, but in the following one).

We are tracking this issue in this other ticket: https://github.com/wireapp/wire-android/issues/2431. I am closing this issue as a duplicate, let's continue the discussion there so all information is in one place.
