### ISSUE TITLE
crashes in emulator (due to Bluetooth)

### ISSUE THREAD

**Issue by Sophia-Gao** [wireapp/wire-android#2445]
In emulator, When I login in then crash every time. Is it support emulator? 

error is :
JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.bluetooth.BluetoothAdapter.getProfileProxy(android.content.Context, android.bluetooth.BluetoothProfile$ServiceListener, int)' on a null object reference

**Comment by Sophia-Gao** [comment]
Is this must use Bluetooth？

**Comment by marcoconti83** [comment]
Hi @Sophia-Gao ,
the app does indeed crash when it does not find the `BluetoothAdapter`. We'll work on a fix.

**Comment by Gardosen** [comment]
this bug has been fixed.

I close this ticket for cleanup purpose.

Kind regards
Marco from the Android Team
