### ISSUE TITLE
Login timeout

### ISSUE THREAD

**Issue by Sophia-Gao** [wireapp/wire-android#2448]
**Describe the bug**
When I Use  Wire on my phone(Xiaomi  8),login always timeout. 
**To Reproduce**
POST https://prod-nginz-https.wire.com/login/send
    Content-Type: application/json
    Content-Length: 26
    User-Agent: Android 8.1.0 / Wire 3.43.99999-candidate 11/27 15:43:58 / HttpLibrary okhttp/3.10.0
    
    {"phone":"+8615122398***"}
    
    --> END POST (26-byte body)

HTTP FAILED: java.net.SocketTimeoutException: failed to connect to prod-nginz-https.wire.com/69.63.176.59 (port 443) from /10.107.182.145 (port 43442) after 10000ms
HttpClientOkHttpImpl: failure while getting okHttp response.
failed to connect to prod-nginz-https.wire.com/69.63.176.59 (port 443) from /10.107.182.145 (port 43442) after 10000ms
at com.waz.znet2.OkHttpLoggingInterceptor$$anonfun$10.apply(OkHttpLoggingInterceptor.scala:138)

**Comment by marcoconti83** [comment]
Hi @Sophia-Gao ,
thanks for opening the report. Is this the only request that times out? E.g. if you try to log in with email, does it time out too? Even if you don't have an account with an email, try a random email, just to see if the request times out or not.

**Comment by Gardosen** [comment]
we have recently updated OKHttp to the newest version.
also there was no response within 4 months to our questions, i'll close this issue now.
