### ISSUE TITLE
Different Emoticons on different devices

### ISSUE THREAD

**Issue by boldt** [wireapp/wire-android#245]
Hello,

we have three devides:

* Sony Xperia Z5, Android 6.0.1, Wire 2.18.288
* Huawai Mate 8, Android 6.0 weith EMUI 4.0, Wire 2.18.288
* Amazon Fire, Android 5 (Fire OS 5.3.1.0), Wire 2.18.288

Emoticons on the Huaway (Screenshot) and Amazon Fire device:

![wire_1476653991580](https://cloud.githubusercontent.com/assets/750793/19421170/c00d3c20-93fa-11e6-848d-16aca13da713.png)

Emoticons on the Sony device:

![screenshot_20161016-230806](https://cloud.githubusercontent.com/assets/750793/19421238/4e2bcc46-93fc-11e6-9a04-6f59a7116306.png)

As you can see, the Sony has more Emoticons than the Huawai. 
Sending a not existing from the Sony to the Huaway, the Huaway just produces a crossed box.

**Comment by bjoernherbig** [comment]
We use the system emoticons, so there can be differences in what the keyboard shows.

**Comment by boldt** [comment]
Are you sure, this issue should be closed?

I mean, the as a sender, I dont know which emoticons exist on the receiving device. Unfortunatley, I produce quite a lot of "crossed Xes" by using my icons.

**Comment by bjoernherbig** [comment]
we are using standard android fonts. if the receiving font does not provide support for certain emoticons, an empty box with a cross will be shown. this is in line with what you see e.g. in text messages.
