### ISSUE TITLE
Login buttons overlapping in Spanish.

### ISSUE THREAD

**Issue by daviddlaiton** [wireapp/wire-android#2450]
Hi. I was testing out the Android app in a physical device and when I tried to do the Login some buttons were overlapping. I think is related to the fact that it was in a Spanish version. Here is a ss showing the overlapping:

![UX-UI-Bugs](https://user-images.githubusercontent.com/22827454/69829936-35c2bf00-11f0-11ea-9cb4-bcd4552a583d.jpg)

The buttons that are overlapping are "Forgot password" and "Enterprise Login" or something related with that. This happens with the official release available in the Play Store. The device is a Samsung A5.

**Comment by marcoconti83** [comment]
Hi @daviddlaiton ,
thanks for the report!

**Comment by Gardosen** [comment]
Hello,

this issue will be fixed with 3.46 which contains the new login flow.

Kind regards
Marco from the Android Team
