### ISSUE TITLE
[Feature Request] Allow read/write messages, while having a call

### ISSUE THREAD

**Issue by boldt** [wireapp/wire-android#246]
This is a FR: 
Unfortunately, it is not possible to read/write messages, while having a call.

**Comment by xtotdam** [comment]
Hey! You say this is duplicate of #487 which is duplicate of #246 which is duplicate of #487 which is duplicate of #246 which is duplicate of #487.... I don't think I get it :)

**Comment by someoneEsle** [comment]
Hey everyone! We just pushed a beta to the play store that adds this functionality. Let us know if you find any bugs!

**Comment by boldt** [comment]
Nice to see, that my 2.5 years old issue got fixed. I'm looking forward to test it.
