### ISSUE TITLE
[Feature Request] Simplified unlock

### ISSUE THREAD

**Issue by KaKi87** [wireapp/wire-android#2483]
An app lock feature should allow the user to use another unlock method than the account password.

For example :

- Shorter password
- PIN
- Schema

Despite these methods are less secure, they are safe enough considering that it's overlaying the Android lockscreen.

Having to type our account password often, which is ment to be a very secure one, either long to type, or long to copy/paste from your password manager, in long-term, will lead to either disable app lock or shorten the account password, both solutions unacceaptable.

Thanks

**Comment by ArchiveBase** [comment]
> An app lock feature should allow the user to use another unlock method than the account.

Definitely agree.

**Comment by KaKi87** [comment]
> pin, pattern, password or biometric

Yes, but this is related to your Android native lockscreen.

If you don't have fingerprint unlock but something else, you'll be able to unlock with whatever the other thing is.

However, the problem is : what if the Android unlock fails ? You'll always need your account password.

That's what I'm actually talking about.

For instance, we can take example from the ProtonMail app, which I use often. If fingerprint fails, you can enter a PIN you specificly configured for the mail app.

Thanks

**Comment by makingthematrix** [comment]
@KaKi87 If your phone support a fingerprint identification, Wire will show a prompt for that on top of the password dialog. It was done exactly because we thought that typing in the password may be too annoying. But currently we don't plan to implement a secondary, shorter password, or other options.

**Comment by KaKi87** [comment]
I understand.
