### ISSUE TITLE
Lock with passphrase allow to read message

### ISSUE THREAD

**Issue by bobsaintcool** [wireapp/wire-android#2511]
**Describe the bug**

When "Lock with Passphrase" option is turned on it is still possible to see plain text message from notification tray or just by transparency the conversation is displayed.

I believe when we turn on this feature, one should not be able to read message without having entering the passphrase first.

**To Reproduce**

1. Open wire apps
2. Go to settings > options
3. Enable Lock with Passphrase
4. Wait until someone send you a message
5. The data inside the message is displayed into the Android notification (if turned on)
6. Clicking the notification open wire on this conversation and ask for the passphrase to add something to the conversation. However you can still read pretty much of it.

**Expected behavior**

When lock with passphrase option is enabled:
  - Don't display data into notification
  - Do not display anything on background while asking for passphrase but some kind of generic screen.

As both are made by other apps on Android (eg: Signal) I believe this is something that wire can provide too.

**Screenshots**

![p0](https://user-images.githubusercontent.com/13803031/71450680-158a0f80-275e-11ea-971b-fea338e3d3a5.png)
![p1](https://user-images.githubusercontent.com/13803031/71450681-158a0f80-275e-11ea-9b90-d23c0382c734.png)

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.43.870
- Last Wire version that did not exhibit the issue (if applicable): N/A
- Android OS version used to run Wire: 10
- Is this a custom firmware or a stock one: Stock
- Mobile phone model/manufacturer: Google Pixel 3 the small one
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE

**Comment by marcoconti83** [comment]
Hi @bobsaintcool ,
Thanks for writing this up. About notifications, there is a setting to disable displaying the body of the message in notifications. The setting is independent of the app lock, so you can configure them in the right combination for you.

**Comment by bobsaintcool** [comment]
Thanks for the heads up.I've probably mixed a bit too much the message but regarding notification it may be a good things to have a switch in the settings that allow to only hide content of wire notification and turn this on when lock is enabled. Because unless I'm misstaken working android setting will only allow me to hide content of all application?

**Comment by marcoconti83** [comment]
There is a Wire specific setting to hide the body of messages in notifications. You can find it inside Wire, in your profile -> Settings -> Options -> Message previews

**Comment by bobsaintcool** [comment]
Didn't get it, thanks!

**Comment by bobsaintcool** [comment]
What about the transparency lock screen do you believe its something that may change ?

**Comment by BradleyWire** [comment]
@bobsaintcool please check version 3.44 and see if this problem persists.

**Comment by bobsaintcool** [comment]
With 3.44.XYZ and the same env I do now have a black and opaque screen in background of password prompt!

Thanks.
