### ISSUE TITLE
Huawei p8 not receiving notifications

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#253]
Huawei p8 with Android 6 does not receive notifications after fresh install unless you go into the battery settings and turn on background data for wire when the screen shuts off.
Other apps like WhatsApp and telegram do this automatically so it would be nice if wire did the same.

**Comment by DivineOmega** [comment]
This might be related to the issue I've need experiencing (#254).

**Comment by someoneEsle** [comment]
I'm fairly sure they aren't related, as this was caused by a setting specific to some Huawei devices that just needs to be turned off.

**Comment by DivineOmega** [comment]
Oh, I'm sorry. I misread your original post. You're very right.

**Comment by hub-ch** [comment]
https://github.com/wireapp/wire-android/issues/777#issuecomment-466763316

**Comment by marcoconti83** [comment]
Hi all,
there are a lot of duplicated issues covering this same problem (or a very similar one), let's unify all conversations and keep it going here: #777 . Closing this one and continuing there.
