### ISSUE TITLE
Feature Request: Screen sharing on mobile

### ISSUE THREAD

**Issue by xingped** [wireapp/wire-android#2552]
I know Wire has screen sharing on the desktop, but it would be nice to have mobile screen sharing as well so we can share our mobile device screens with others. Is there any thought or plan to possibly make this happen for mobile?

**Comment by makingthematrix** [comment]
Hi, @xingped .
Unfortunately we don't have such plans for the near future. The general idea is that Wire can serve as a platform for presenting some materials from a computer to people watching on their phones, but the other way around does not seem to give much additional value.

**Comment by Gardosen** [comment]
as @makingthematrix stated, there is currently no plans in near future to provide this. 
never the less, we will keep this in mind for the future.

i close this thread for now, as it was answered.
