### ISSUE TITLE
When opening a conversation, last message scrolls out of view

### ISSUE THREAD

**Issue by sokke90** [wireapp/wire-android#257]
Everytime I open a conversation view by clicking on a name, the last message scrolls out of view, because there is some animation that shows some more information below the messages. I'd rather see the last message than this; because now the last message is really easy to miss. Is this intended behaviour?

**Comment by someoneEsle** [comment]
It's a known issue that is being worked on and fixed in the branch message_stream

**Comment by someoneEsle** [comment]
For reference, this is related to #191

**Comment by mastad0n** [comment]
I have the same issue on  2.18.288

**Comment by bjoernherbig** [comment]
yes, this is a known issue and being worked on as referenced by @someoneEsle 
closing this one.
