### ISSUE TITLE
Are images stored on Wire servers?

### ISSUE THREAD

**Issue by sengork** [wireapp/wire-android#2571]
Hi,

When I use Android app offline, I am unable to load older history of images/pictures from the chat history search. As soon as I connect back online the images load as if they're being downloaded from the Wire servers.

I was under impression that all chat level assets are sent to the recipient's device and not retained on the servers.

Is this normal behaviour?
If so, what is the retention time of the assets being stored on the servers?

Guessing it is until all of the recipient's devices receive the copies which should have happened by now for my conversations.

Thank you.

**Comment by gopherit** [comment]
@sengork from https://github.com/wireapp/wire-desktop/issues/2944#issuecomment-521919765

> All your images which are not older than 6 months will be re-downloaded from the server (and decrypted) after switching to the appropriate conversation.

So I presume that means images are stored for 6 months max on Wire server, hopefully 100% with the keys only the two users have (or those in a group chat).

**Comment by marcoconti83** [comment]
Hi all,

the images are indeed on the server, but they are encrypted with a key that only the sender and receiver devices have, so the server can not decrypt them. For more details, please refer to our [security whitepaper](https://wire.com/en/security/).
