### ISSUE TITLE
can i get My owne Server?

### ISSUE THREAD

**Issue by Nemra1** [wireapp/wire-android#259]
this is first time her and i have some questions !
I like this app much more any app seen before...
iwant ask if i can Get my owne server ( Wire self-hosted ) in my server and mange my owne users?

**Comment by legovini** [comment]
The server is currently not open source, but they say they'll release it at some point, see: https://github.com/wireapp/wire-android/issues/237.

**Comment by bjoernherbig** [comment]
closing as duplicate
