### ISSUE TITLE
Visual Feedback while loading shared video

### ISSUE THREAD

**Issue by DrAxelbauer** [wireapp/wire-android#2643]
This is not a bug but an enhancement request.
On my Android Version of Wire, there is no visual feedback of the download progress of a video file. Within the Linux Desktop App there is such a progressbar for videos. As far as I see, many users which are new to wire are a little bit confused, that "nothing" is happening when tapping on a video (alhtough the download starts and is functioning). A simple visual download progressbar like in the desktop app would be of great use!

Best, Benjamin.
...still totally cool messenger!

I am on
Android 7.0 with Wire App Version 3.44.887

**Comment by BradleyWire** [comment]
Hi @DrAxelbauer,

Thanks for your valuable observation. Seeing as this was a simple change I have committed the enhancement in this PR: https://github.com/wireapp/wire-android/pull/2650. 

It'll be put into the next public release, so, keep an eye out for it on v3.46. 

And as always please don't hesitate to raise any other issues in the future with any improvements you have for the Wire app!
