### ISSUE TITLE
[feature request] Add support for Openpush

### ISSUE THREAD

**Issue by zabbal** [wireapp/wire-android#2651]
The recently announced https://bubu1.eu/openpush/ could be instrumental in finally resolving issues like #233 - basically it's FCM replacement which could be decentralized, it's completely FOSS and it's still battery efficient.

Granted it's in early stage of development but that also enables wire devs to influence the design and implementation early on.

**Comment by shadow00** [comment]
Related: #1903

**Comment by Gardosen** [comment]
Hey  @zabbal,

thank you for bringing this to our attention, i will note this down into my sheets for the upcoming developer discussion.
I will close this ticket for now and make a reference about it in the existing #233 ticket.

Kind regards
Marco from the Android Team
