### ISSUE TITLE
Does wire-android have plans to use kotlin?

### ISSUE THREAD

**Issue by zequnjiang** [wireapp/wire-android#2672]
Does wire-android have plans to use kotlin?

**Comment by makingthematrix** [comment]
@zequnjiang : Yes, we're already started a migration to Kotlin. It will be gradual and in most cases users won't see any difference, but you can see the progress on the main page of our GitHub's repo, on that line showing how much of the code is in what language.

**Comment by zequnjiang** [comment]
wow~ nice.
