### ISSUE TITLE
Such slow syncing

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#2682]
to reproduce:

Turn your secondary phone's wifi off for 1-2 weeks.

Turn it on and wait for Wire to sync.

more than 1h later it's still replaying the past drop by drop.

**Comment by makingthematrix** [comment]
Might be related to https://github.com/wireapp/wire-android/pull/2702, although probably also other things slow down the sync considerably when there are many messages to process at once. We're working on it, one at the time.
Thanks for the report, @Transisto :)

**Comment by Transisto** [comment]
https://youtu.be/KIJE8s_6Dvw

**Comment by Transisto** [comment]
https://youtu.be/yJ5GH18rxNw

**Comment by makingthematrix** [comment]
Does this still happen on (or after) 3.47.911?
