### ISSUE TITLE
Do not disclose email address to contacts

### ISSUE THREAD

**Issue by devdan** [wireapp/wire-android#271]
If you add a contact, they cannot see your phone number, but they can see your email address. 

Also hide the email address from contacts by default.

**Comment by teller** [comment]
This is unlikely to get actioned in the near future due to low number of requests. If you're uncomfortable showing your real email then switch to a throwaway one you're ok exposing.

**Comment by raphaelrobert** [comment]
With the introduction of usernames the email address is not shown to other users anymore.
