### ISSUE TITLE
Restoring backup leads to Device ID / fingerprint mismatch

### ISSUE THREAD

**Issue by mss-hh** [wireapp/wire-android#2741]
I bought a new phone and wanted to add it to my Wire devices. So I installed Wire on it and made sure the version on my old phone was up to date. Then I backed up my conversations and restored them on the new phone. This lead to an unusable Wire installation because the Device ID of the old phone was restored on the new phone while the fingerprint remained the same.

1. Install Wire on a new phone
2. Back up your conversations on a different phone
3. Start Wire and log in on the new phone
4. Restore your conversations on the new phone
4. Wire on the new phone now has the same Device ID as on the old phone while it has a different fingerprint.

Expected behavior:
Only conversations should be restored on the new device, not the Device ID.

Smartphones:
- Wire version that exhibits the issue: 3.46.890
- Last Wire version that did not exhibit the issue (if applicable): works in 3.44.877
- Android OS version used to run Wire: old phone 9.0 / new phone 10.0
- Is this a custom firmware or a stock one: custom (LineageOS 16.0 / crDroid 6.4)
- Mobile phone model/manufacturer: Motorola Moto G5 / Xiaomi Redmi Note 8T
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/Wi-Fi

Additional context:
Restoring backups from older versions of Wire does not work either. There is no error message but nothing gets restored. I have another device where version 3.44.877 was still installed. So I did a backup there, installed 3.44.877 on my new phone and restoring worked as intended.

**Comment by makingthematrix** [comment]
Hi,

Thanks for the report. We're aware of this problem and it's scheduled for fixing.

**Comment by macruspareto** [comment]
Isnt it the way it supposed to be?
When I back it up (via TWRP) and then restore to the same phone, I do get Fingerprint mismatch aswell.

Then I have to reset all sessions. But I thought it's by design.

**Comment by mss-hh** [comment]
Great to hear that a fix is on the way. Thanks for working on it.

@macruspareto At first I also thought this might be by design. But then I found out that all my contacts were notified about the problem and told to reset the sessions. So it became clear to me it had to be a bug. Otherwise you couldn't recommend Wire to normal users, these messages would scare them away, I guess. I never used TWRP for backups so I don't know if it would happen on my phone, too. I have always used Wire's internal function.

**Comment by makingthematrix** [comment]
Hi,
With the new release, 3.55, we finally have new backups functionality in place. The device ID should not change anymore with data restoration - unless you reinstalled the app or wiped the data clean.

**Comment by mss-hh** [comment]
That's good news. Will give it a try soon.
