### ISSUE TITLE
[Request] Add wire to Huawei App Gallery?

### ISSUE THREAD

**Issue by LinuxDonald** [wireapp/wire-android#2751]
What about adding Wire to the Huawei App Gallery Store?

**Comment by makingthematrix** [comment]
The topic of putting Wire Android on other platforms than Google Play Store comes back every few months. We agree it would be great to do that but we don't have enough time and energy to handle this. After a lot of discussion we decided that we want to focus on Google Play Store only for near future.

**Comment by LinuxDonald** [comment]
What would must be done to add it into app gallary? Maybe an new maintainer would be interested on this.

**Comment by makingthematrix** [comment]
@LinuxDonald : Adding the apk to a new platform means that we need to spend some time regularly to maintain it. One of us would have to be responsible for it, and right now we can't afford it.

**Comment by Archive5** [comment]
> @LinuxDonald : Adding the apk to a new platform means that we need to spend some time regularly to maintain it. One of us would have to be responsible for it, and right now we can't afford it.

@makingthematrix Does wire get volunteer employees? If then i prefer do that. I wonder how you guys dont have a time to do that few clicks task at same time when release app to google play.

**Comment by KizunaH** [comment]
https://github.com/wireapp/wire-android/issues/233
