### ISSUE TITLE
Crash on startup with 3.47.909 update

### ISSUE THREAD

**Issue by Porkepix** [wireapp/wire-android#2798]
**Describe the bug**
Application crash on startup

**To Reproduce**
Only start the application

**Expected behavior**
It shouldn't crash

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.47.909
- Last Wire version that did not exhibit the issue (if applicable): Previous version
- Android OS version used to run Wire: Android Marshmallow - 6.0.1
- Is this a custom firmware or a stock one: Stock
- Mobile phone model/manufacturer: Xperia Z3 Compact
- Mobile network type (EDGE/LTE/Wi-Fi/Offline):

**Additional context**
Result of an `adb logcat -v threadtime`:
```
04-28 13:56:24.253   930   992 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{ee946a9 u0 com.wire/com.waz.zclient.LaunchActivity t7594 f} time:1041197345
04-28 13:56:24.436   930   992 I ActivityManager: Displayed com.wire/com.waz.zclient.MainActivity: +323ms (total +752ms)
04-28 13:56:24.436   930   992 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{54eb18c u0 com.wire/com.waz.zclient.MainActivity t7594} time:1041197528
04-28 13:56:24.504  5093  5093 D AndroidRuntime: Shutting down VM
04-28 13:56:24.505  5093  5093 E AndroidRuntime: FATAL EXCEPTION: main
04-28 13:56:24.505  5093  5093 E AndroidRuntime: Process: com.wire, PID: 5093
04-28 13:56:24.505  5093  5093 E AndroidRuntime: java.lang.NoSuchMethodError: No static method hashCode(F)I in class Ljava/lang/Float; or its super classes (declaration of 'java.lang.Float' appears in /system/framework/core-libart.jar)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at com.waz.zclient.core.images.transformations.ScaleTransformation.hashCode(ScaleTransformation.kt)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at java.util.AbstractList.hashCode(AbstractList.java:528)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at com.bumptech.glide.load.MultiTransformation.hashCode(MultiTransformation.java:63)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at com.bumptech.glide.load.resource.gif.GifDrawableTransformation.hashCode(GifDrawableTransformation.java:64)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at androidx.collection.SimpleArrayMap.hashCode(SimpleArrayMap.java:748)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at com.bumptech.glide.util.CachedHashCodeArrayMap.hashCode(CachedHashCodeArrayMap.java:52)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at com.bumptech.glide.load.engine.EngineKey.hashCode(EngineKey.java:67)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at java.util.Collections.secondaryHash(Collections.java:3427)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at java.util.HashMap.get(HashMap.java:300)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at com.bumptech.glide.load.engine.ActiveResources.get(ActiveResources.java:94)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at com.bumptech.glide.load.engine.Engine.load(Engine.java:2326)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at com.bumptech.glide.request.SingleRequest.onSizeReady(SingleRequest.java:449)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at com.bumptech.glide.request.target.ViewTarget.getSize(ViewTarget.java:1376)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at com.bumptech.glide.request.SingleRequest.begin(SingleRequest.java:251)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at com.bumptech.glide.RequestManager.track(RequestManager.java:6043)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:641)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:700)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at com.waz.zclient.common.views.BackgroundImageView$$anonfun$2.apply(BackgroundImageView.scala:1042)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at com.waz.utils.events.SignalSubscription$$anonfun$changed$1$$anonfun$apply$4$$anonfun$apply$1.apply$mcV$sp(Events.scala:112)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at com.waz.utils.events.SignalSubscription$$anonfun$changed$1$$anonfun$apply$4$$anonfun$apply$1.apply(Events.scala:2112)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at scala.util.Try$.apply(Try.scala:192)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at com.waz.utils.events.SignalSubscription$$anonfun$changed$1$$anonfun$apply$4.apply(Events.scala:112)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:234)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5526)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-28 13:56:24.505  5093  5093 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by makingthematrix** [comment]
@Porkepix : Hi. Thanks for the report. The next release, 3.48, is coming soon and we might be able to have a fix ready for it. 
It's a weird bug. It appears only on Android 5 and 6 and in a place which we didn't expect to have any problems with.

**Comment by AuWire909** [comment]
Same bug here on Android 6.0.1 & a Samsung S5 Neo. 
Stopped working completely.

As you guys released the 3.47.909 as a stable, non-beta update for all users via Play Store, I would appreciate a rather fast fix very much. Might not be alone with that...

**Comment by penCsharpener** [comment]
I'm on Android 8.0 and face these issues. Please remove this update from play store before other people get it.
https://github.com/wireapp/wire-android/issues/2803

**Comment by gizemb** [comment]
Addressed in #2805 and will be included in the next release

**Comment by thrimbor** [comment]
> The next release, 3.48, is coming soon and we might be able to have a fix ready for it.

@makingthematrix 
Did you just really tell us that we'll have to wait ~a month before we get a fix for a crash on startup?

Why was this version ever distributed (also considering #2803)? Why is it still being distributed? Why do your users have to wait so long every time you distribute a broken version (comparing with the quotes causing crashes issue here)?
Do you think we can still recommend Wire to our friends and family after it failing like this in times like these?

**Comment by frafu** [comment]
> Addressed in #2805 and will be included in the next release

I have this issue also. There is no "emergency fix" or so for that? We have to wait till the next regular release? Are you joking?

**Comment by hylkevds** [comment]
Also crashes on start-up on my wife's Note 4 with Android 6.0.1. Seems this update needs a rollback, or an emergency patch...

**Comment by frafu** [comment]
Now, this update rolled out to all four devices in my home (kids, wife) and all wire installations are now useless.
Great Job!

**Comment by Miss-Lara** [comment]
I have same issue I can't enter the app I can see the notifications but when I try to access to the application it doesn't work I have  samsung SM-N910C anyone have same issue ?

**Comment by Geo-D** [comment]
![WireInfo](https://user-images.githubusercontent.com/5768220/80868297-42e05000-8c5f-11ea-8f6c-97668f185293.jpg)
Can you make the previous version available ??? Download here / PlayStore / APK !! Any which way
This is very inconvenient / Down Hard !!!

**Comment by makingthematrix** [comment]
Hi,

We have just released a hotfix which should fix the crash on Android 5 & 6. The new version is 3.47.911. It may take a while until Google Play Store make it available. Let us know if it worked.

Cheers,

**Comment by Porkepix** [comment]
Crash seems fixed, I guess this can be closed.

**Comment by Geo-D** [comment]
Android 6 on Galaxy S5 ... FIXED

~GeoD
