### ISSUE TITLE
Bug when opening previous conversation on last update (3.47.909)

### ISSUE THREAD

**Issue by Sinewyk** [wireapp/wire-android#2799]
**Describe the bug**
I updated to 3.47.909, it seemed to clean my quick access (no more conversations). I found them in my contacts.

I opened one, i had my history BUT it said "You added **UserImTalkingToo** to the conversation", and now I'm in a group conversation (no more read receipts) even though I'm talking to the same person and I opened the history via the contacts list.

**To Reproduce**
Take previous app, create a 1 on 1 conversation with read receipts working. Update to 3.47.909, select conversation in contacts.

**Expected behavior**
I'm not in a group conversation when talking to a single person.
BONUS: it does not remove my quick access list.

**Screenshots**

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.47.909
- Last Wire version that did not exhibit the issue (if applicable): the previous one I think ?
- Android OS version used to run Wire: 7.1.2
- Is this a custom firmware or a stock one: LineageOS14.1-20180808
- Mobile phone model/manufacturer: Fairphone 2
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE

I'm open to complicated procedures to try to fix this.

**Comment by makingthematrix** [comment]
Please try Settings -> Options -> Perform full sync

**Comment by Sinewyk** [comment]
It seems to have done the trick. Thanks.

**Comment by makingthematrix** [comment]
@Sinewyk : Great! By the way, there will be another release shortly and there we will force full sync on update.
