### ISSUE TITLE
Message previews not showing on notifications despite option being enabled

### ISSUE THREAD

**Issue by cachapa** [wireapp/wire-android#2814]
**Describe the bug**
Despite enabling "Message Previews" in the settings, notifications still appear as "Someone sent a message".

I've played with this option on and off and nothing changes. I even tried resetting the push notifications token with no success.

**To Reproduce**
I'm not sure how to reproduce. I know I was getting message previews correctly, then I disabled that option and despite re-enabling it I haven't gotten any previews since.

**Expected behavior**
I'd like to be able to preview the content of my messages when the option is enabled.

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.47.909
- Android OS version used to run Wire: 10, latest April update
- Is this a custom firmware or a stock one: Stock
- Mobile phone model/manufacturer: Google Pixel 4
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): All of them (except for offline obvs)

**Additional context**
When playing with these options I enabled "Lock with passphrase", which worked as expected.
When I tried to disable it, it wasn't working: Wire kept locking the screen after 10s in the background. Eventually I managed to disable it, but it might have involved reinstalling the app (I forget everything I tried).
Could it be that these settings aren't being correctly saved?

**Comment by cachapa** [comment]
On further investigation, I also enabled "Hide screen content" at some point.
Despite disabling it now, the screen content is still hidden in the task switcher.

Are the settings replicated in the Wire servers? That might explain some of the weirdness I've been seeing: During testing I was suddenly and forcefully logged out of my device. Sometimes some settings (like disabling `hide screen content`) are respected for a while, and then they revert back to hiding the screen.

Also: the conversation I'm testing with has messages set to auto expire (1 day). Does that make a difference?

**Comment by makingthematrix** [comment]
@cachapa : 
The new Wire Android version, 3.78, was just released with reimplemented notifications. Please test it and let me know how it works. 
By the way, the notification saying "Someone sent a message" means that the message i a self-destructing one. In such cases we don't display the contents in the notification to ensure security.

**Comment by cachapa** [comment]
Hi, thanks for the reply. Unfortunately I'm no longer actively using Wire so I can't test it.

In any case it seems my problem was that the messages were self-destructing, as you mentioned. I'm closing this issue since it seems the behaviour is by design.
