### ISSUE TITLE
I can't enter the application after last update 

### ISSUE THREAD

**Issue by Miss-Lara** [wireapp/wire-android#2817]
**Describe the bug**
I can't enter the app when I try to access message appears it says send report I deleted the app and installed it again but same issue I can see the notifications from friends but I can't access to it its happened after last update my mobile Samsung-N910C I'm using wifi before last update it doesn't happen please solve this problem this urgent 
A clear and concise descriptiwhat

**To Reproduce**
A detailed description will help us to fix the issue faster. 

**Expected behavior**
It shouldn't happen at all 

**Screenshots**

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue:
- Last Wire version that did not exhibit the issue (if applicable):
- Android OS version used to run Wire:
- Is this a custom firmware or a stock one:
- Mobile phone Samsung N910C model/manufacturer:
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): wifi 

**Additional context**

**Comment by makingthematrix** [comment]
@Miss-Lara : Hi. It looks like your operatino system might be Android 5 or 6, right? The current version of Wire is crashing on those due to an error in how our new code works on older Androids. We're working on a patch which will fix it. It should be ready in a few days.

Sorry for inconvenience.

**Comment by Miss-Lara** [comment]
> @Miss-Lara : Hi. It looks like your operatino system might be Android 5 or 6, right? The current version of Wire is crashing on those due to an error in how our new code works on older Androids. We're working on a patch which will fix it. It should be ready in a few days.
> 
> Sorry for inconvenience.

Few days ? How much ? My wire it's stopped working and it's the only app that I can communicate with please solve it as soon as possible 
I send report to wire support but they don't even respond what should I do in this case ?

**Comment by makingthematrix** [comment]
@Miss-Lara : We have just release the hotfix version which should help you with your problem. It's number is 3.47.911 (the old one is just 3.47). It may take a while until Google Play Store make it available, so please check later today or maybe tomorrow.

Let me know if it worked.
