### ISSUE TITLE
Feature: device agnostic chat export and import

### ISSUE THREAD

**Issue by penCsharpener** [wireapp/wire-android#2822]
I've read this also in a recent issue. Please implement a format of chat history export that can be imported on all devices: ie. people lost messages in #2803 and they should be able to go to their browser version of desktop client of Wire, export their chat history and import that on android or iOS and vice versa.

**Comment by makingthematrix** [comment]
We are talking about this but this would be a huge new feature.

**Comment by madranet** [comment]
**Support platform agnostic backup/restore** [#1929, #2822]

> ...No plans are made for it now.

Seems to be the standard response from Wire, whenever users ask for any of the ongoing usability issues to be addressed.  

Some of these Issues date back to 2016:

**Support for landscape mode** [#1570, #455, #1088]

> ...We experimented with the landscape mode in the past but the sheer number of issues it created convinced us to drop it. Currently there are no plans to try it again.

**Support for Ability to change Font-Size** [#977, #321, #4]

>...thank you for the suggestion. unfortunately we have no plans to add that. you can change the font size via the phones settings already.

[Yes. Seriously.  That was the response!]
