### ISSUE TITLE
Taping a search result doesn't jump to the message location

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#2827]
Instead of the expected behavior it goes down to the last message.

I think this started happening about a month ago, Sorry for not reporting earlier.

It happen no matter how short the conversation being searched is.

Latest version on Samsung S10

**Comment by kreegahbundolo** [comment]
I can confirm this. In addition, search results turn up multiple hits on the same entry so the search result list is full of duplicates for each hit. Tapping a result does not work. Instead the screen flickers and takes me to the last message in conversation. Have tried full sync, force stop, clear cache. Nothing seems to remedy it. I have the same problem with files, long press + reveal in conversation does not work.

**Comment by Transisto** [comment]
Zoom is worth $60 000 000 000 because they can do multi-user video call.

Wire could can do it for 4 possibly 10 people at once and encrypted. But they can't figure out to hire someone to acknowledge github issues within a month. 

Pathetic.

**Comment by kreegahbundolo** [comment]
Yes, the free version is not getting much love, it seems. Let's hope they pick up on this. This issue is crippling, I use search a lot. Coupled with the reports of backup/restore not working properly I'm scared of doing a complete backup/reinstall/restore cycle in case I lose my data.

**Comment by Transisto** [comment]
Have you tried finding a user with search? Everyone on Wire shows before
your own contacts.

**Comment by makingthematrix** [comment]
Thanks for the report. This will be fixed in the next release.
https://github.com/wireapp/wire-android/pull/2856
