### ISSUE TITLE
The ❤ notifications popup multiple times

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#2834]
If there's one type of notification I don't need to see even once it's those, Yet they seems to want to come back again and again more than others.

**Comment by kirillt** [comment]
What is status of this issue? Can it be reproduced?

**Comment by Transisto** [comment]
It's been happening a lot again lately

**Comment by makingthematrix** [comment]
There is some issue (a bug?) in Android so that even when notifications are cancelled, they can sometimes come back. With the new Wire Android version, 3.78, we tried to make it a bit better on our side. Please test it and let me know how it works.
