### ISSUE TITLE
Wire android application crash on launch

### ISSUE THREAD

**Issue by Archive5** [wireapp/wire-android#2851]
**To Reproduce**
Download Memu 7.1.6 (2020.3.25)
https://drive.google.com/file/d/1mFJllEdvnwzsNZl8Q2QQyMo8Kv_SATTJ/view
(source https://www.memuplay.com/blog/release-archive.html)

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: v3.48.915.915
- Android OS version used to run Wire: 5.1.1
- Is this a custom firmware or a stock one: memu
google-user 5.1.1 20171130.276299 (build)
4.0.9 dxu@mv-mobl1#106 (kernal)
2015-12-01 (android patch level)
- Mobile phone model/manufacturer: G011A (memu)
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): none

**Additional context**
Unfortunately, Wire has stopped.

**Comment by mosiser** [comment]
Same, with Wire 3.49.917, Android stock 5.1.

**Comment by mosiser** [comment]
> Same, with Wire 3.49.917, Android stock 5.1.

Don't know for the OP, but for me it is solved with new ver. 3.49.918. Thanks.

**Comment by makingthematrix** [comment]
Hi, @mosiser. Sorry for inconvenience. We'll try our best to prevent it from happening again.

**Comment by Archive5** [comment]
@makingthematrix this issue haven't fixed. you can reproduce using above details.
