### ISSUE TITLE
User search show 10 globals before existing contacts [Major usability issue]

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#2858]
Tap first icon at bottom for users.

type the first letters of someone is your contacts,

All 5 result shown are from random people, not contacts.

Also the "Show all 10"  doesn't expand them.

**Comment by Transisto** [comment]
Fuck sake, is anyone using this app, not to realize basic features are broken?

**Comment by makingthematrix** [comment]
@Transisto : This attitude is really unnecessary. We have it scheduled. It will be fixed.

**Comment by makingthematrix** [comment]
https://github.com/wireapp/wire-android/pull/2874
