### ISSUE TITLE
After receiving video call once, screen doesn't go to sleep anymore

### ISSUE THREAD

**Issue by h-2** [wireapp/wire-android#287]
... even if wire is in the background, the screen won't turn off. Turning screen on/off or restarting wire doesn't fix this. I guess a reboot will, but I haven't tried yet.

OnePlusOne, CM13, Wire from apk, no GAPPS

**Comment by shumengye** [comment]
Verified and created ticket https://wearezeta.atlassian.net/browse/CM-1120

**Comment by bjoernherbig** [comment]
#312

**Comment by bjoernherbig** [comment]
fixed in #312
