### ISSUE TITLE
Android App: Files being shared are not getting stored on the minio servers

### ISSUE THREAD

**Issue by ramesh8830** [wireapp/wire-android#2871]
Hi,

I configured the production server with 3 minio servers (dedicated VM's) but the files being shared on the android app are not getting stored on the minio servers. But can able to receive the files on the android app shared by others through webapp.

Please help me resolve this issue.

**Comment by android10** [comment]
Hello @ramesh8830. I'm not sure if I understood your problem correctly:

Are you trying to see all pictures and files being shared in a conversation through the android client, to exist in the server and have access to them?

**Comment by ramesh8830** [comment]
Hi @android10 

There is something wrong with minio configuration given for production setup using 3 minio servers. I can't able to see all the images on the chat window. So I used only one minio servers and configured to fix this problem.

Thank you.
