### ISSUE TITLE
Message Previews

### ISSUE THREAD

**Issue by 5an1ty** [wireapp/wire-android#288]
The iOS app version has the option to disable message previews. This is a great feature and I'd love to see this introduced in the android client. Is there a technical limitation why this feature isn't available on android?

**Comment by bjoernherbig** [comment]
Thanks for bringing this up. No technical reason, just capacity/priority. We have no timeline on this currently though.

**Comment by bjoernherbig** [comment]
i think i misunderstood. what you are referring to is the notification preview in the lock screen, correct? if so, you can do that from your system settings already

**Comment by 5an1ty** [comment]
You can indeed already do this for the lock screen, but when you leave your phone unlocked and you look at notifications you would see the message sender and it's contents. With the iOS version this is working as intended but on android it's not possible to do.

Even if you want to just hide the contents on the lockscreen, if you change the system setting, it's for all applications, some people would prefer to still see contents on the lockscreen for their other applications but not for wire.

**Comment by bjoernherbig** [comment]
I see what you mean, thanks for clarifying. we have discussed something along the lines but have not yet put it on our roadmap. as mentioned before, it's a matter of capacity.

**Comment by PyRoAcIdK** [comment]
+1. I agree, it should show "New Message" or just the notification rather than the full plain text of the message.

**Comment by makingthematrix** [comment]
Implemented in https://github.com/wireapp/wire-android/pull/2234
