### ISSUE TITLE
A blank screen will appear after kicking people in the group details.

### ISSUE THREAD

**Issue by LryCamille** [wireapp/wire-android#2881]
**Describe the bug**
A blank screen will appear after kicking people in the group details.

**To Reproduce**
A detailed description will help us to fix the issue faster. 

1. Go to 'conversation list' with group conversation
2. Click on 'item of list ' and click the title of conversation page and enter to conversation detail
3. enter to "DETAILS" page and kick people

**Expected behavior**
After the kicking operation in the group details is completed, the kicking success should appear, return to the details page, and no white screen should appear

**Screenshots**
![device-2020-06-09-115217](https://user-images.githubusercontent.com/17874422/84104278-cd2e8780-aa47-11ea-9832-f73b798e2c90.png)

**Smartphone (please complete the following information):**
- Wire version：3.49.921
- Android version used to run Wire:
- Is this a custom firmware or a stock one:
- Mobile phone model/manufacturer: SM-G9650/DS / Galaxy S9+
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): WIFI

**Comment by makingthematrix** [comment]
Hi,
Thanks for the report. A fix to that will be included in the next release.
https://github.com/wireapp/wire-android/pull/2857
