### ISSUE TITLE
Feature request: horizontal support

### ISSUE THREAD

**Issue by survivor303** [wireapp/wire-android#2889]
How much work it needed to get that horizontal support to android app, that is the only reason why we dosnt change to wire by large.

In our education environment, we use android tablets, large over 9" sized ones. For now every other videocalling app support horizontal. I believe on wire as a great open source project but not very long, not anymore because lag of this one (rather small) feature.

Why ios version have this?

**Comment by makingthematrix** [comment]
@survivor303 : I'm sorry, but we don't support tablets and the landscape mode in Android :( We made attempts at it, but there were so many additional issues involved that we finally decided that we don't have time and people to do it.

**Comment by survivor303** [comment]
Make a #helpwanted list for features that your core team cannot do for now, Perhaps other open source developers can do some of that work just for supporting the effort.

**Comment by makingthematrix** [comment]
@survivor303 : We do have a plan for future which will bring back the landscape mode:
https://github.com/wireapp/wire-android-reloaded
