### ISSUE TITLE
Profile picture update bug

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-android#290]
I just updated my picture (avatar) via desktop client but mobile client still uses old one. Reloaded it — avatar remains the same. Tried to kill it and start it over — no result.

**Comment by someoneEsle** [comment]
Clearing the cache of the app might help. What device/os are you on?

**Comment by timur-davletshin** [comment]
Clearing cache for sure will help, but it should work without it. Android 6 (latest update)/Nexus 5.

**Comment by someoneEsle** [comment]
Well, if even after clearing the cache it doesn't update, that would be good for the developers to know. :) What OS/client version are you using on your computer?
Also, if you have any other devices besides your computer and android phone, could you check if your profile picture is showing correctly there?

**Comment by timur-davletshin** [comment]
Linux + latest desktop version from wire.com and web-app + Firefox (on Linux) has synced perfectly (they just don't cache anything as far as I understand).

**Comment by bjoernherbig** [comment]
there can be cases where it takes longer to fetch the user profile. acknowledged as a bug

**Comment by makingthematrix** [comment]
I think we can safely close it now :)
