### ISSUE TITLE
Successfully downloaded video is not in the gallery

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#291]
I received a video today, it's 3min long and original size was 650mb. I was able to play it just fine. I then wanted to download it to my gallery, so I clicked "save", waited some time, and then eventually wire said the video had been successfully saved. However, it's nowhere to be found on my phone. It's not in the gallery, it's not in my downloads, and it's not in any folder I'm looking in. I tried downloading again, same result.
I'm attaching a debug log. Nexus 5X Android 7 Wire 2.20.293
[wire_debug_report.txt](https://github.com/wireapp/wire-android/files/574020/wire_debug_report.txt)

p.s.: the video does not show a preview

**Comment by Strit** [comment]
Pictures I save does not show up in Gallery either. But they are on the phone in the folder: /Pictures/Wire/.
Maybe the video is in /Videos|Movies/Wire/?

The Gallery apps does not monitor these folders, so it makes sense that it does not show up in it.

**Comment by bjoernherbig** [comment]
fixed in #556
