### ISSUE TITLE
Add new language for wire

### ISSUE THREAD

**Issue by valaria247** [wireapp/wire-android#2913]
#### Requested language
Sinhala language

#### Project
https://crowdin.com/project/wire-android

#### Additional Details
Sinhala language currently enabled for wire desktop

**Comment by BradleyWire** [comment]
Hey @valaria247, 

Thank-you for your important feedback. We have now added Sinhala to the Wire-android crowdin project. I'll close this issue. 

Please don't hesitate to reopen or raise a new issue if you have any further problems. 

Thanks
