### ISSUE TITLE
Any plans to make the app independent of GSF?

### ISSUE THREAD

**Issue by 2011** [wireapp/wire-android#2930]
I always shake my head at privacy apps whose notifications go through Google's servers (a significant flaw). I wanted to ask if Wire has any plans to remove the GSF dependency (like Signal did).

**Comment by mHatsune** [comment]
See #233

**Comment by 2011** [comment]
I guess this question concerns only a subset of the steps required for inclusion into F-Droid. Disappointing (but not surprising) that no progress has occurred over the past nearly four years, especially since new alternatives have emerged since then. I will close this and follow the issue you mentioned. Thank you.
