### ISSUE TITLE
How do Chinese users receive notifications?

### ISSUE THREAD

**Issue by zequnjiang** [wireapp/wire-android#2937]
Google FCM cannot be used in China, It is also not possible to connect to Google services in China, We already have more than 1,000 devices using Wire, But the lack of notification makes us very painful. please help me.

**Comment by KizunaH** [comment]
There're serious lazy people work in wire.

https://github.com/wireapp/wire-android/issues/233 - Bring the app to f-droid
https://github.com/wireapp/wire-android/issues/2751 - Add to Huawei app gallery (already closed due no time for upload same apk file).

**Comment by makingthematrix** [comment]
@zequnjiang : I don't know if it can help you in any way, but you can try to always maintain the connection to the server. Go to Settings -> Advanced -> set the toggle on "Maintain connection to server". 
In the normal mode, we use Google Play Service only to get informed that something came up and then we contact the server directly to get new events. When the connection to the server is always maintained, new events should be fetched directly. However, we have some issues with this functionality and sometimes it my not be reliable. Especially if your Android tries to save battery, it may prevent Wire from maintaining connection (you can also try to whitelist Wire from the battery saving mode in the Android settings).

**Comment by zequnjiang** [comment]
Thank you very much, that's what we did.There is no better solution. @makingthematrix

**Comment by makingthematrix** [comment]
@zequnjiang : 
The new Wire Android version, 3.78, was just released with reimplemented notifications. Please test it and let me know how it works.
