### ISSUE TITLE
Android 11 (R) Breaks All Transitions, Causing UI to be Unreadable

### ISSUE THREAD

**Issue by dmz38** [wireapp/wire-android#3002]
**Describe the bug**
After updating to Android 11, Wire's transitions cause the application to be unreadable after certain actions.

- Scrolling on the contact list on the homepage
- Closing a conversation and going back to the main contact list.

All of these actions will result in the text to "train" with the scrolling instead of moving in place.  For security reasons, I have included only a partial screenshot below, but I've been able to reproduce it on every Android beta device I have.  

**To Reproduce**
Home Page:
1. Open the app
2. Scroll the contract list

Closing the conversation and going back to the home screen:
1. Hit the back arrow or use the back gesture.

**Expected behavior**
The text should still be readable and not act like someone dragged the text across the screen.

**Screenshots**
![Screenshot_20200825-055556~2](https://user-images.githubusercontent.com/6808885/91161585-ecc56b80-e698-11ea-8be2-b10ef5d1e422.png)

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.53.934
- Last Wire version that did not exhibit the issue (if applicable): None
- Android OS version used to run Wire: 11
- Is this a custom firmware or a stock one: Stock Android Beta Program
- Mobile phone model/manufacturer: Google Pixel 3, 4a
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): All

**Additional context**
The Android beta program is available on all Pixel devices generation 2 and later.  Android 11 is expected to launch in September according to reports.  To me, this issue makes the application unstable and virtually unusable.  The only way to "fix" the issue is to close and open the app every time.

Thank you for your help in correcting this issue!

**Comment by makingthematrix** [comment]
Hi,

Thanks for bringing this up.
We are currently busy working on a few big things and for sure we will not be ready for Android 11 when it comes out. We will try to address these issues during the next few months.

**Comment by BradleyWire** [comment]
Just as an update, i'll be working on resolving Android 11 issues as high priority.  Will post updates as and when we have them.

**Comment by dmz38** [comment]
Thanks so much for doing this!  I'm really glad to see a fix and some memory leak cleanups.

I saw this was just merged into the release branch.  Does that mean it'll be on the beta channel of the Google Play listing relatively soon?

**Comment by BradleyWire** [comment]
@dmz38 You're very welcome. Thanks again for raising this with us, we appreciate all feedback. We're releasing this as a hotfix, so, we will most likely just roll this out to the public directly (which should be tomorrow).

**Comment by BradleyWire** [comment]
The public build should be available today. I'll be closing this issue.
