### ISSUE TITLE
Screen goes black and phone is unresponsive when in a Wire call

### ISSUE THREAD

**Issue by maltfield** [wireapp/wire-android#3021]
**Describe the bug**
Every time I'm in a Wire call, as soon as I press the "call" button (or accept someone else's call), my screen goes totally black and none of the soft buttons work.

In the worst case, the phone-call connection becomes degraded/broken, the person on the other end doesn't cancel the call, and the only thing I can do to gain control of my phone again is to hold down the power button to force a hard reboot.

**To Reproduce**

1. Put piece of opaque tape or sticker over your front-facing camera (so that it covers both the camera lens and--by accident--the proximity sensor also)
2. Make a phone call

**Expected behavior**

I should be able to use my phone in a wire call. At the very least, I should be able to exit the call without having to hard reboot.

If the proximity sensor is disabling the screen (perhaps unknown to the privacy-conscious user who covered their front-facing camera with tape), then Wire should have some sort of UI notification to let the user know that the screen has gone black *because* the proximity sensor, and it should hint that they may have accidentally covered it when covering the camera.

That, and there should also be a way to disable the "automatically disable the screen via proximity sensor" functionality in the Wire settings.

**See Also**

 * https://github.com/wardellbagby/Sensor-Disabler

**Comment by maltfield** [comment]
I'm creating this bug now that I know the cause of the issue, but it took me a few months to figure it out. I was ripping my hair out thinking it was a bug with Wire and perhaps some edge-case with my device.

It wasn't until today that I realized it affected other apps. That's when I peeled-off the tape that always covers my front-facing camera and discovered the root cause of this issue.

Considering the userbase of the Wire app, I expect that this is a bug that will probably affect a lot of other folks too. Especially for people whose handset have the proximity sensor right next to their front-facing camera lens.

My suggestion:

1. There must be an option added to the Wire Settings screen to disable the "feature" for folks who always leave their front-facing camera covered and don't want their phones to lock-up when they're in a call.

2. Improve the UI so that the UX isn't so shitty for people who aren't aware that they covered-up their proximity sensor when they actually just meant to cover the front-facing camera. Otherwise, these folks will probably uninstall Wire thinking it's unusable & buggy.

**Comment by maltfield** [comment]
Also, as is common in other apps, the screen should never be disabled (no matter what the proximity sensor reads) when the headphones are plugged-in.

**Comment by makingthematrix** [comment]
@maltfield :
Hi, the new Wire Android version, 3.78, was just released with reimplemented notifications and fixes to the calling functionality. Please test it and let me know how it works.

**Comment by maltfield** [comment]
@makingthematrix I'd like to download it, but -- where to get the apk?

Did you remove the link to download the apk from your website?? It just redirects me to the google play store.

 * https://wire.com/download

Note that, for security reasons, I do not have Google proprietary binaries installed on my phone and thus cannot use Google Play store.

if your old APK's signature matches the existing install's signature, then downloading the apk from your website directly is no less secure than downloading it from the Google Play store.

Where can I obtain the apk safely from the wire.com domain?

**Comment by makingthematrix** [comment]
I answered at #2934 but I will copy-paste my comment also here:
APKs are now on the release page at GitHub: https://github.com/wireapp/wire-android/releases/tag/3.78.13
We are also on F-droid, but it takes a bit to upload there.
