### ISSUE TITLE
Media and pictures backup

### ISSUE THREAD

**Issue by lucagoetheil** [wireapp/wire-android#3029]
Is it possible to backup and restore media as well? I only seem to be able to restore text messages.
Will the new backup update allow media to be backed up and restored?

**Comment by makingthematrix** [comment]
@lucagoetheil : Currently we don't plan to do this. For media, only identifiers of objects are stored in the backup, and after restoration, when you open a conversation with some media, the app looks to the backend to see if it's still possible to download them (they are stored for limited amount of time, I think it's 4 weeks).
