### ISSUE TITLE
Error ： cannot execute

### ISSUE THREAD

**Issue by dyfan** [wireapp/wire-android#304]
![image](https://cloud.githubusercontent.com/assets/15817271/20205007/e57d8ec8-a80f-11e6-830f-01384718da24.png)

**Comment by someoneEsle** [comment]
Were you trying to build? Usually you have to run the ./gradlew command twice -- the first time always fails, the secondary time it succeeds.
Could you please give more details about what you were trying to do? (Something more than just the screenshot)

**Comment by dyfan** [comment]
Can't run app .Always appear this mistake.

**Comment by JPonte** [comment]
Which flavour (build variant) are you trying to build? Try the dev one.

**Comment by NetE1** [comment]
Try again @dyfan consider use a release. 
1. ./gradlew command or 2. build > generate apk

Follow instruction https://github.com/wireapp/wire-android/issues/1892 for avoid avs bug.

No known build errors. Let's close this issue.

**Comment by marcoconti83** [comment]
Hi all,
This issue is quite old and the project has change substantially since then. I'll close this issue an I believe it's solved now, please feel free to reopen if it still a problem for you.
