### ISSUE TITLE
German website has old download link

### ISSUE THREAD

**Issue by nidico** [wireapp/wire-android#3048]
The German download website - https://wire.com/de/download/ - still links to https://wire-app.wire.com/android/prod/wire-prod-release-3.55.939.apk - whereas the English site already has https://wire-app.wire.com/android/prod/wire-prod-release-3.57.944.apk

**Comment by marcoconti83** [comment]
Thanks @nidico for pointing this out! 
We fixed it and you should see the website deployed within an hour or so.
