### ISSUE TITLE
Failed to resolve com.wire:avs:6.4.4

### ISSUE THREAD

**Issue by cgskbhatt** [wireapp/wire-android#3050]
**Compilation error while cloning the repo and build locally**

**To Reproduce**
1.Check out the wire-android repository.
2.From the checkout folder, run ./gradlew assembledebug. This will pull in all the necessary dependencies from Maven.

**Error Log**
See compilation error. Failed to resolve: com.wire:avs:6.4.4

### What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all files for configuration ':app:candidateDebugAndroidTestCompileClasspath'.
   > Could not find com.wire:avs:6.4.4.
     Searched in the following locations:
       - file:/E:/SDK/extras/m2repository/com/wire/avs/6.4.4/avs-6.4.4.pom
       - file:/E:/SDK/extras/m2repository/com/wire/avs/6.4.4/avs-6.4.4.aar
       - file:/E:/SDK/extras/google/m2repository/com/wire/avs/6.4.4/avs-6.4.4.pom
       - file:/E:/SDK/extras/google/m2repository/com/wire/avs/6.4.4/avs-6.4.4.aar
       - file:/E:/SDK/extras/android/m2repository/com/wire/avs/6.4.4/avs-6.4.4.pom
       - file:/E:/SDK/extras/android/m2repository/com/wire/avs/6.4.4/avs-6.4.4.aar
       - https://dl.google.com/dl/android/maven2/com/wire/avs/6.4.4/avs-6.4.4.pom
       - https://dl.google.com/dl/android/maven2/com/wire/avs/6.4.4/avs-6.4.4.aar
       - https://jcenter.bintray.com/com/wire/avs/6.4.4/avs-6.4.4.pom
       - https://jcenter.bintray.com/com/wire/avs/6.4.4/avs-6.4.4.aar
       - https://dl.bintray.com/wire-android/releases/com/wire/avs/6.4.4/avs-6.4.4.pom
       - https://dl.bintray.com/wire-android/releases/com/wire/avs/6.4.4/avs-6.4.4.aar
       - https://dl.bintray.com/wire-android/snapshots/com/wire/avs/6.4.4/avs-6.4.4.pom
       - https://dl.bintray.com/wire-android/snapshots/com/wire/avs/6.4.4/avs-6.4.4.aar
       - https://dl.bintray.com/wire-android/third-party/com/wire/avs/6.4.4/avs-6.4.4.pom
       - https://dl.bintray.com/wire-android/third-party/com/wire/avs/6.4.4/avs-6.4.4.aar
       - https://maven.google.com/com/wire/avs/6.4.4/avs-6.4.4.pom
       - https://maven.google.com/com/wire/avs/6.4.4/avs-6.4.4.aar
       - https://repo.maven.apache.org/maven2/com/wire/avs/6.4.4/avs-6.4.4.pom
       - https://repo.maven.apache.org/maven2/com/wire/avs/6.4.4/avs-6.4.4.aar
     Required by:
         project :app

**Comment by makingthematrix** [comment]
Yes, AVS 6.4.4 is not yet available in public. There were major changes recently. We will release it soon.

**Comment by cgskbhatt** [comment]
Okay. I hope you publish it soon and we can use the latest code.

**Comment by cgskbhatt** [comment]
> Yes, AVS 6.4.4 is not yet available in public. There were major changes recently. We will release it soon.

Okay, thanks. If possible then please share the estimated date so I can check for AVS library accordingly and use the latest code of the wire app.

**Comment by makingthematrix** [comment]
@cgskbhatt : I think it should take us about a month to sort things out, but after that next updates should be simpler. The current situation when we maintain different AVS versions and switch between them depending on compilation options is just not possible to work with anymore. Sorry for the inconvenience.

**Comment by jspittka** [comment]
AVS 6.4.4 is now available as source code or binary format as 6.4.232.
