### ISSUE TITLE
How to configure different notification sounds for different users?

### ISSUE THREAD

**Issue by octogonz** [wireapp/wire-android#3078]
**Describe the bug**

Telegram enables me to manage notifications separately for each user that I chat with:
- what notification sound is played
- whether notifications are enabled at all
- what LED color to show
- whether to show a pop-up or not
- "mute for 1 hour"

Does Wire support anything like this? Even just the ability to customize the sound per user?

**To Reproduce**

I cannot find any settings like that in the Wire menus.

**Comment by Transisto** [comment]
Signal does that, WTF is Wire doing, for not even acknowledging well done issues over months.

**Comment by makingthematrix** [comment]
@octogonz : 
The new Wire Android version, 3.78, was just released with reimplemented notifications. The Android notification channels should now work correctly and you should be able to configure it from Android settings. Please test it and let me know how it works.
