### ISSUE TITLE
Wire 3.61.963 crashes when removing the Phone permission.

### ISSUE THREAD

**Issue by shiftre** [wireapp/wire-android#3119]
**Describe the bug**
A clear and concise description of what the bug is. Briefly describe the issue you are experiencing. Tell us what you were trying to do and what happened instead.

I fetched Wire from the Play store, up until now I've been using it without any permissions, (contacts/voice/etc).
Once the app was updated I tried to opened it but the application crashed.

I'm using Pixel 4, Android 11. 

**To Reproduce**
1. Download Wire from the App Store, remove all permissions from the app.
2. Try to open Wire.
3. App should crash.

**Expected behavior**
The App should crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/303679/102204432-8a57db80-3ed2-11eb-9e9c-8ad9a9d2d801.png)
![image](https://user-images.githubusercontent.com/303679/102204466-917ee980-3ed2-11eb-877c-ae0e46d56da9.png)

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.61.963
- Last Wire version that did not exhibit the issue (if applicable): Previous version? I don't know what it was.
- Android OS version used to run Wire: 11
- Is this a custom firmware or a stock one: Stock.
- Mobile phone model/manufacturer: Pixel 4
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE.

**Additional context**
I'm not a Scala expert here but I believe the root cause happens due to the lack of try / catch in 
https://github.com/wireapp/wire-android/blob/56623fc6e4cc7c68700ac736824940ddaf78a2a2/app/src/main/scala/com/waz/services/websocket/WebSocketService.scala#L46

This is where a NULL Pointer exception is actually thrown due to lack of Permissions.

```
class WebSocketController(implicit inj: Injector) extends Injectable {
  private lazy val global = inject[GlobalModule]
  private lazy val accounts = inject[AccountsService]

  private lazy val cloudPushAvailable =
    for {
      gpsAvailable   <- global.googleApi.isGooglePlayServicesAvailable
      devPrefEnabled <- global.prefs(PushEnabledKey).signal
    } yield gpsAvailable && devPrefEnabled
````

The Exception that is thrown is a NullPointerException, but if you dig deeper you will see that it is actually a java.lang.SecurityException.

I can try building wire on my own and verify that, (with a bit of help I guess), the right fix is wrapping it with try/catch clause 
but watching git blame logs in WebSocketService.scala shows that these lines have not been
modified in the past year or so, so I imagine the root cause for this task is somewhere else in the code
but I am not sure where yet.
If you could give me a few hints where to look I can open a PR and fix it myself.

Hoping to hear from you.

Thanks,
  Guy

**Comment by makingthematrix** [comment]
Hi,

Thanks for the detailed report!
If by "the Phone permission" you mean the one we just introduced in the code, READ_PHONE_STATE, then we will today release a hotfix where this permission is no longer necessary. Interesting that you caught this bug in WebSocketService. We made changes around NetworkStateService because the new SDK 30 deprecates and breaks parts of the code we used to check if the user is connected to WiFI, a cellular network, or is offline.

When the hotfix is released, please let us know if it fixes your problem.

**Comment by shiftre** [comment]
Hi,

Thanks for the quick response!
I believe this is the problematic permission, I'm looking forward to try your hotfix and see if it works 👍 

Thanks!

Guy
