### ISSUE TITLE
When switching app during a call there is now a permanent notification that's blocking the upper part of the screen.

### ISSUE THREAD

**Issue by Transisto** [wireapp/wire-android#3128]
This notification oddly enough say.  "MyName is calling", 

1, I can't call myself,
2. We're already on the phone
3. 80% of action buttons are at the top and blocked by that non-dismissible pop-up notification.

Do you need a screenshot to know what I'm talking about?

I think this began about 3 months ago.

**Comment by makingthematrix** [comment]
@Transisto : 
The new Wire Android version, 3.78, was just released with reimplemented notifications. Please test it and let me know how it works.

**Comment by Transisto** [comment]
Since then I figured it has to be swiped up, 

A similar issue is that we can't unlock the phone when taking a call when locked.

Can you test that, close this issue, and create a new one for that?

**Comment by makingthematrix** [comment]
@Transisto : I'm afraid we can't do anything about it, at least not in the close future.
