### ISSUE TITLE
opening a conversation does not scroll to bottom

### ISSUE THREAD

**Issue by Be-ing** [wireapp/wire-android#313]
When I view a conversation from my contacts list, it is scrolled up a little bit, which can hide the contents of the most recent message in the conversation. It's not always obvious that there is more recent content in the conversation that I am not seeing. This is on a Galaxy S5 Mini.

**Comment by someoneEsle** [comment]
Duplicate of #112 and related to #191 .

**Comment by bjoernherbig** [comment]
correct as stated by @someoneEsle . work in progress, closing it as duplicate
