### ISSUE TITLE
Improve performance when sending audio messages

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#314]
Something I've noticed is that Wire is rather slow at sending audio messages. I don't know if it's because of the encryption or because it doesn't compress them, but what I do know is that it takes quite a while. Many times it takes so long that it just fails after a few minutes.
I'm on Android 7 Nexus 5X, and I've had this problem on many recent versions. The audio messages I send are unfiltered (i.e. I'm not using the alien/church/whatever filter) and are usually about 2-3 minutes long. The other day I tried sending one that was 7 minutes long (okay, I talk too much) and it just kept failing to send. I can provide a debug log though it should be fairly easy to reproduce when connected to an average wifi.

**Comment by makingthematrix** [comment]
There was a lot of changes in the meantime. Sending/receiving assets are still not perfect performance-wise, but we keep track on it. Here's our internal issue:
https://github.com/wireapp/android-project/issues/415
