### ISSUE TITLE
Images are not loaded from Servers

### ISSUE THREAD

**Issue by 8FordPrefect8** [wireapp/wire-android#3149]
**Describe the bug**
I am lacking all images and videos from the past untill a certain time point. Everything later then 2020. There are black placeholders  indicating the position and metadata like send time and likes.

Performing a full sync deleting cache etc. doesn't help.

My wife with a different Android phone has the same issue. One friend with an iphone can see the very same pictures in our group chat.

**To Reproduce**
A detailed description will help us to fix the issue faster. 

**Expected behavior**
I expect the old images and videos to be reloaded again from the servers.

**Screenshots**

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.62 and earlier
- Last Wire version that did not exhibit the issue (if applicable): don't know
- Android OS version used to run Wire: 11
- Is this a custom firmware or a stock one: LineageOS
- Mobile phone model/manufacturer: Xiaomi Poco F1
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): not applicable.

**Additional context**

**Comment by 8FordPrefect8** [comment]
I edited the initial description as I could outline that it has anything to do with backups. A second phone with continious usage has the very same issue in personal chats and group chats. A friend with an iphone can see all the images from 2019 and before.

**Comment by makingthematrix** [comment]
@8FordPrefect8 : We don't store images and videos on the servers longer than a few weeks. If your friend have images from 2019, it means they are on the local storage. In general, Wire shouldn't be treated as a way to keep data for long, but only as a way to receive it and store it somewhere else. We aim for privacy which means that we don't want to handle your data if we don't have to.

**Comment by 8FordPrefect8** [comment]
Hmm thats strange because it means my wife just lost the data without any interaction.

If you don't store it, and indeed it's a resonable decision, you should provide a backup option that backups media too.
