### ISSUE TITLE
UI for answering a call could be clearer

### ISSUE THREAD

**Issue by Be-ing** [wireapp/wire-android#316]
It is not very obvious that a user needs to slide the caller's icon towards the answer icon to receive a call. It would help to enclose the caller's icon and answer icon in a border and add an arrow in the background pointing towards the answer icon.

**Comment by bjoernherbig** [comment]
thatnks for the feedback. we are considering some changes regarding this. no timeline to share yet though

**Comment by someoneEsle** [comment]
I just video called someone who is 50+ and they really struggled understanding that they had to slide the icon to pick up the phone. They kept tapping the green icon instead
