### ISSUE TITLE
Replying to Message via Notification Does Not Send Until App is Opened

### ISSUE THREAD

**Issue by dmz38** [wireapp/wire-android#3167]
When you reply to a message via the Android notification, the message is not sent until the Android application is opened and brought into the foreground.

1. Receive a message from another user
2. Click "Reply"
3. Write a message
4. Hit Send
5. Observe user does not receive message
6. Open up the Wire application 
7. Open the conversation
8. Message goes from sent to delivered
9. Other user receives the message

**Expected behavior**
The message will be sent as soon as the send button is pressed in the notification.

**Screenshots**
N/A, but happy to provide if helpful.

- Wire version that exhibits the issue: 3.63.974
- Last Wire version that did not exhibit the issue (if applicable): Unknown
- Android OS version used to run Wire: Android 11
- Is this a custom firmware or a stock one: Stock
- Mobile phone model/manufacturer: Google Pixel 5
- Mobile network type (EDGE/LTE/Wi-Fi/Offline):  All network types

**Comment by makingthematrix** [comment]
@dmz38 :
The new Wire Android version, 3.78, was just released with reimplemented notifications. Please test it and let me know how it works.
