### ISSUE TITLE
Who is Constantin? :dizzy_face:

### ISSUE THREAD

**Issue by h-2** [wireapp/wire-android#317]
"Constantin has accepted your invitation to chat" or something like that appeared this morning. Now I have "Constantin" in my chat list.
But I don't know who Constantin is. I definitely didn't invite him to anything and Wire provides no information on how it connected Constantin to me, i.e. does a phone number or e-mail-address in my address book match Constantin's? Or am I just in Constantin's address book? There should definitely be some indication on who this person is and why he is being shown...

**Comment by bjoernherbig** [comment]
It very well may be that you are in his address book. if you don't want him in your contacts, just block him.

**Comment by h-2** [comment]
I am aware that I can block him, but I think there could be some default behaviour that if a person is not in my address book, I should be notified about it.
Also it would help if I where able to see the person's registered e-mail or phone number. If they are not readable by wire servers (which would be cool but isn't the case I think), the person could disclose them to me on first contact / key exchange.
