### ISSUE TITLE
Increasing amount of data

### ISSUE THREAD

**Issue by Zahlentheorie** [wireapp/wire-android#318]
Why does the amount of data of the Wire app increase steadily on my device even if I deleted whole chats, group chats, and archived chats? [Android 6.0]

**Comment by someoneEsle** [comment]
Because deleting a chat doesn't actually delete it from the local db, it just hides it from you. :( I've reported this as well and it's bound to change in the future. The proble is when.
Side note: I would love an automatic trim like in signal

**Comment by bjoernherbig** [comment]
correct as @someoneEsle stated. expect some changes in the future. no timeline there yet.

**Comment by Zahlentheorie** [comment]
Thank you for your reply, @someoneEsle ! Let's hope that they will change it in the near future. So, temporary messages will be kept on the local db? It would be really good, and a step to a more secure messenger.

**Comment by someoneEsle** [comment]
Temporary messages are not kept on the local db if I recall correctly. Also, deleting individual messages *will* delete them from the database, but of course no one wants to delete message after message...

**Comment by Zahlentheorie** [comment]
Good news! Thank you!
But why is the amount of storage increasing after I've deleted a lot of photos, videos, and files in the chats? -- Yeah, I've really done it.

**Comment by someoneEsle** [comment]
Uhm, that's weird, but wait I think I've had the same problem in the past. Reboot your phone maybe?

**Comment by Zahlentheorie** [comment]
Yes, it's weird. I'm rebooting my phone every [second] day but it doesn't change anything.
