### ISSUE TITLE
Download apk from website gives Error

### ISSUE THREAD

**Issue by baroni309** [wireapp/wire-android#3191]
When trying to download the apk from website it gives an error message.

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>C32A2CD6518D9830</RequestId>
<HostId>niV58ioMOFOBEaJTdsM+pOP5IRSlsCVlEufP2oB7f/h81HmfLQ9DlzOn5ptud9C+U6M+8ku33/s=</HostId>
</Error>

**Comment by baroni309** [comment]
It seemed that the issue has been fixed today

**Comment by makingthematrix** [comment]
@baroni309 : Yes. Thanks for pointing it out! :)
