### ISSUE TITLE
Import Scala Sdk

### ISSUE THREAD

**Issue by akashqss** [wireapp/wire-android#32]
How to import proper scala sdk in project because every time when try to run project always says "Setup Scala Sdk". How can I fix it?

and getting this error

/home/akash/wire-android/app/src/main/scala/com/waz/zclient/GlobalCallingController.scala:118: value SCREEN_BRIGHT_WAKE_LOCK in object PowerManager is deprecated: see corresponding Javadoc for more information.
      PowerManager.SCREEN_BRIGHT_WAKE_LOCK | PowerManager.FULL_WAKE_LOCK | PowerManager.ACQUIRE_CAUSES_WAKEUP
                   ^
/home/akash/wire-android/app/src/main/scala/com/waz/zclient/GlobalCallingController.scala:118: value FULL_WAKE_LOCK in object PowerManager is deprecated: see corresponding Javadoc for more information.
      PowerManager.SCREEN_BRIGHT_WAKE_LOCK | PowerManager.FULL_WAKE_LOCK | PowerManager.ACQUIRE_CAUSES_WAKEUP
                                                          ^
/home/akash/wire-android/app/src/main/scala/com/waz/zclient/WireApplication.scala:40: value Global is not a member of object com.waz.zclient.controllers.tracking.events.connect.OpenedGenericInviteMenuEvent.EventContext
    bind[CameraPreviewController] to new CameraPreviewController()(EventContext.Global)
                                                                                ^
/home/akash/wire-android/app/src/main/scala/com/waz/zclient/WireApplication.scala:69: value Global is not a member of object com.waz.zclient.controllers.tracking.events.connect.OpenedGenericInviteMenuEvent.EventContext
  override def eventContext: EventContext = EventContext.Global
                                                         ^
/home/akash/wire-android/app/src/main/scala/com/waz/zclient/WireApplication.scala:75: value Global is not a member of object com.waz.zclient.controllers.tracking.events.connect.OpenedGenericInviteMenuEvent.EventContext
    callingController.onCallStarted.on(Threading.Ui) { _ => CallingActivity.start(this) }(EventContext.Global)
                                                                                                       ^
/home/akash/wire-android/app/src/main/scala/com/waz/zclient/WireApplication.scala:25: Unused import
import com.waz.media.manager.MediaManager

**Comment by nirzonpop192** [comment]
How did you solved it ??
