### ISSUE TITLE
A few key features that some will appreciate

### ISSUE THREAD

**Issue by thebettersort** [wireapp/wire-android#321]
Hi, I just started using Wire and I think I've been using it long enough to recognize some features that it might be missing. Here are some remarks on the Android experience.
One big feature addition would be the ability to change the font size or layout of the chat window 
Another would be an option to hide the message content in notifications (similar to Telegram)
It would also be great to hide the profile picture on the main screen and have a white/dark background (matching the theme).

Thanks for considering these.

**Comment by bjoernherbig** [comment]
Thanks for your feedback! Regarding font size and notification exposure you can already use your phone specific settings to adjust. App specific settings are currently not planned. 
The profile picture is something we will discuss internally, thanks again.
