### ISSUE TITLE
Could not find com.wire.gradle:gradle-android-scala-plugin:1.6.

### ISSUE THREAD

**Issue by awaisriffat** [wireapp/wire-android#3215]
A problem occurred configuring root project 'zclient-root'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.wire.gradle:gradle-android-scala-plugin:1.6.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/wire/gradle/gradle-android-scala-plugin/1.6/gradle-android-scala-plugin-1.6.pom
       - https://dl.google.com/dl/android/maven2/com/wire/gradle/gradle-android-scala-plugin/1.6/gradle-android-scala-plugin-1.6.jar
       - https://repo.maven.apache.org/maven2/com/wire/gradle/gradle-android-scala-plugin/1.6/gradle-android-scala-plugin-1.6.pom
       - https://repo.maven.apache.org/maven2/com/wire/gradle/gradle-android-scala-plugin/1.6/gradle-android-scala-plugin-1.6.jar
       - https://jcenter.bintray.com/com/wire/gradle/gradle-android-scala-plugin/1.6/gradle-android-scala-plugin-1.6.pom
       - https://jcenter.bintray.com/com/wire/gradle/gradle-android-scala-plugin/1.6/gradle-android-scala-plugin-1.6.jar
       - https://plugins.gradle.org/m2/com/wire/gradle/gradle-android-scala-plugin/1.6/gradle-android-scala-plugin-1.6.pom
       - https://plugins.gradle.org/m2/com/wire/gradle/gradle-android-scala-plugin/1.6/gradle-android-scala-plugin-1.6.jar
     Required by:
         project :

Android studio 4.1.3

**Comment by makingthematrix** [comment]
@awaisriffat : Our dependencies are slowly being migrated from Bintray to Sonatype, but it will take time. `gradle-android-scala-plugin-2.0.3` is already available from Sonatype but your compilation will still fail on one of those which weren't migrated yet.
