### ISSUE TITLE
issues establishing connection to server with version 3.66.985 when auto-starting on boot

### ISSUE THREAD

**Issue by modernNeo** [wireapp/wire-android#3249]
**Describe the bug**
A clear and concise description of what the bug is. Briefly describe the issue you are experiencing. Tell us what you were trying to do and what happened instead.

When I boot up my phone, I see the notification that says `Establishing Connection`, but it fails to do so even after 2 minutes. I need to `Force Stop` the app and manually open in order to get it to connect to the server.

**To Reproduce**
A detailed description will help us to fix the issue faster. 
1. Install Wire Version [3.66.985](https://wire-app.wire.com/android/prod/wire-prod-release-3.66.985.apk) on GrapheneOS phone.
2. Reboot phone

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.66.985
- Last Wire version that did not exhibit the issue (if applicable):
- Android OS version used to run Wire: [GrapheneOS Android 11](https://github.com/GrapheneOS/platform_manifest/releases/tag/RQ2A.210405.005.2021.04.05.20)
- Is this a custom firmware or a stock one: custom firmware
- Mobile phone model/manufacturer: Google Pixel 4
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi

**Comment by makingthematrix** [comment]
@modernNeo : Sorry, we don't support GrapheneOS. If you didn't do it already, please try Settings -> Advanced -> Maintain connection to server. If it doesn't work, unfortunately I don't know how else can I help you.

**Comment by modernNeo** [comment]
@makingthematrix out of curiosity, if yall dont support grapheneOS, what OS do yall support that does not use FCM [Given that wire has the ability to poll without using Google Play Services]?

**Comment by makingthematrix** [comment]
@modernNeo : Sadly, we don't. We only support AndroidOS from 7.0 up. We don't have enough people to support anything else. 
From what I know, Wire Android works on LineageOS. But I'm not 100% sure.

**Comment by modernNeo** [comment]
I see. Would yall be opposed to getting logs from my phone to see if its maybe an "easy" fix or is a hard rule on "no support for non-Google phones"?

**Comment by modernNeo** [comment]
Also, I am a bit confused by your response. what is the use case of this functionality if not to support Android Phones that do not use Google Services?

**Comment by modernNeo** [comment]
issue resolved via email correspondence with support team
