### ISSUE TITLE
Possibilty to delete call listings

### ISSUE THREAD

**Issue by Zahlentheorie** [wireapp/wire-android#325]
Can you implement a function so that I am able to delete call listings like ping listings, and messages?

**Comment by bjoernherbig** [comment]
Not sure I understand. You want to be able to batch delete depending on type?

**Comment by bjoernherbig** [comment]
If your question is about individual deletion of messages, pings, etc, you can do that. Long press and you will get the option.
Batch deletion is not planned.

**Comment by Zahlentheorie** [comment]
Yes, my question was about deleting the call notifications in my chat window when I've missed some calls. Otherwise my chat window is full of call notifications.
