### ISSUE TITLE
Cross Platform Conversation History Restore - iOS to Android

### ISSUE THREAD

**Issue by mjflower** [wireapp/wire-android#3252]
I can see that this is currently not available to restore from iOS backups to Android App. Is this on the roadmap at all. I tried to find a road map but couldn't find one.

Alternativelym is there any longwinded way I could do it via using a dekstop?

**Comment by makingthematrix** [comment]
@mjflower : Sorry, there are no plans for that currently. We did some work to make it possible in the future (the backups are now in json and in theory they can be converted from one platform to another) but to implement it will require a huge effort and currently we are busy with other things.
