### ISSUE TITLE
File not found when sharing video from gallery

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#327]
What I did:
1. Recorded a video from camera
2. Opened the gallery
3. Hit share to Wire
4. Select conversation
5. Video loads for a couple seconds and then Wire says "File not found"

Sharing the video from within wire (that is, sending it as a file) works.
Here is the debug log.
[wire_debug_report.txt](https://github.com/wireapp/wire-android/files/601628/wire_debug_report.txt)

**Comment by zarere** [comment]
Here 
[1_wire_debug_report.txt](https://github.com/wireapp/wire-android/files/613249/1_wire_debug_report.txt)
is the debug log

**Comment by bjoernherbig** [comment]
#343

**Comment by someoneEsle** [comment]
I'm going to close this since it was merged into master -- but I haven't tested it myself
