### ISSUE TITLE
display users' icons next to name in contact list

### ISSUE THREAD

**Issue by Be-ing** [wireapp/wire-android#332]
This would assist with remember who is who in big lists of contacts.

**Comment by bjoernherbig** [comment]
not sure i understand correctly. we currently show the users avatar in the contact list.

**Comment by Be-ing** [comment]
Hm, well they're not showing up for me...

**Comment by bjoernherbig** [comment]
the avatars (icons) show up if you are connected to them or if they are on wire. people that are not on wire, but in your address book don't have an avatar.
if that is different from what you are experiencing, please post a screenshot or create a ticket with our support on https://support.wire.com/hc/en-us/requests/new . we can follow up then. thanks

**Comment by someoneEsle** [comment]
@Be-ing maybe you mean the conversation list, and not the contact list? Are you talking about the list of conversations you see when you open wire, or are you talking about the list of contacts you see when you click on "contacts"?

**Comment by Be-ing** [comment]
The list of conversations I see when I open Wire.

**Comment by bjoernherbig** [comment]
Thanks for clarifying. I'm afraid we do not plan any changes in regards to this any time soon.
