### ISSUE TITLE
improved key- and contact-management

### ISSUE THREAD

**Issue by kolAflash** [wireapp/wire-android#336]
I'd like to collect and share some ideas about how Wire could manage keys and contacts.

1. Provide backup import/export. The backup should especially contain the private key, but maybe also more (see 4. and 5.).

1.1. Possibility to save the backup on the local storage as file. (optionally encrypted)

1.2.  Possibility to save the backup to an integrated remote storage, mandatory encrypted with a password. Remote storage can be:
-> Wire server
-> Android backup (Google)
-> iOS server backup

1.3. There is also the theoretical possibility to use the same password as for login, while maintaining the same level of security as with separate password.
To archive this, the client software has to derive to separate strings from the password, using two separately salted (salt A and B) hash functions.
-> Hashing with the salt A gives the actual secret for authentication, which is being send to the login server. 
-> Hashing the with the salt B gives the actual secret for backup encryption.
The salts are static (hardcoded). So if the user starts using a new client it knows how to derive the authentication secret and the backup secret form the provided password. The trick is, that there should be no way to derive the backup secret if you only know the authentication secret.
Just ensure, that the user changes his password when introducing such a new method. Because the old password may already be known to the server.

2. When logging into a new client, provide the choice to generate a new key (as it's happening now) or to use an old key from a backup. By this the user can still use different keys on computer with different security/trust level. E.g. work smartphone and private computer.

2.1. There's one dilemma to 1.3. Scenario: You got your smartphone from work W and your private computer P. And P is more secure than W. In that case you shouldn't export P's key to the Wire server encrypted with your authentication password (see 1.2.1), because W can also request the key from the server and decrypt it.

3. Cross sign device keys and store that information in the backup. See: #69

4. Provide the possibility to rename contacts.
Because it's more than annoying if you have to remember the stupid nicknames all of your friends use.

5. Store that names in the backup.

6. Provide additional possibility to compare the fingerprint via QR code. See: #217
The classical way to manually compare the fingerprints should still be possible, because it's preferred by some people and some devices may not have a decent camera.

**Comment by kolAflash** [comment]
Related: https://github.com/wireapp/wire-desktop/issues/210
"Synchronize / Update users between devices"

**Comment by darkbluelight** [comment]
IMO all very important points, that would finally bring Wire up to a level with Threema. I want to get rid of Threema, because it's not open source, but it has at the moment a far better backup and export functionality than Wire. Wire is lacking it completely.

**Comment by witchent** [comment]
That backup feature should also allow you to backup your messages, which is pretty important for me as I'm switching ROMs quite often.

**Comment by marcoconti83** [comment]
Hi everyone,
we added the ability to create a backup. The backup will contain your messages, but not your keys, so even after restoring a backup, your contacts will see that you are using a new device.

This feature has been in public for a long time now, give it a try on the latest version.
