### ISSUE TITLE
History could not be restored from backup file

### ISSUE THREAD

**Issue by BenjaminGalliot** [wireapp/wire-android#3387]
Hello,

I recently changed my Android phone and exported an archive of conversations from the old one (password required). On the new one, however, when I ask to import my data after a first login, after selecting the archive (in `android_wbu` format) the app tells me that this backup is password protected, I press OK, then it tells me in a single window that `an error has occurred` (title), that `the history could not be restored` (content) – translated, maybe not exact English messages –, and that's it!

I had also tried copying this `Android/data/com.wire` folder to the new phone and then running Wire, but without success (no history, as if the moved folder was not read at all). Is there any way to solve the problem this way?

Digging around in the `Android/data/com.wire` folder, I saw that the chats were in different files with explicit names, but I don't know where the media files (especially the audio/microphone files) sent within the chats are. Is there any way to retrieve them?

Details:
- Wire version: 3.70.999 (it was the same with 3.69.996 beta)
- Android OS version: 9 (old) and 11 (new)
- Firmware: stock from Play Store
- Mobile phones: Honor 9 Lite (old) and Poco F3 (new)
- Mobile network type: LTE

**Comment by makingthematrix** [comment]
Hi, @BenjaminGalliot .
Could you send us the log report? Log in without the backup restoration, go to Settings -> Advanced, turn on "Collect usage data", log out, log in again and try to restore the backup. When it fails, log in without the backup again, go to Settings -> Advanced, and click "Create debug report". You can send it to me directly: maciej.gorywoda at wire.com .

**Comment by makingthematrix** [comment]
Also, what was the old Wire version which you used to make the backup? Was it the same?

**Comment by BenjaminGalliot** [comment]
Yet, it was the same. 

Wire version: 3.70.999 (it was the same with 3.69.996 beta)

**Comment by BenjaminGalliot** [comment]
@makingthematrix, is there any way at the moment to simply copy and paste the content of the Wire folder to the new phone (possibly with some file changes)?

**Comment by AyoungDukie** [comment]
Just for reference, my old backups that I had used to restore my data when I changed phones in the fall of 2020 were `android_wbu` extensions, while the last backups I made were `android_wbu.bin` . Was this not the case for your backups?

**Comment by BenjaminGalliot** [comment]
Oh, nice catch, @AyoungDukie!

My (very recent) backups were with `.android_wbu` extension, so I renamed them as `.android_wbu.bin`, and then Wire asked me for a password, and the restoration seemed to word!

**Comment by makingthematrix** [comment]
Haha, nice :)

@BenjaminGallion : Sorry, I'm working on something with a high priority and I wasn't able to look at your issue. I'm happy that it was solved. Thanks, @AyoungDukie :) We don't add the .bin extension to the filename. Can it be something Android does?... Anyway, I will make a note that this may happen and in that case we should ignore this suffix.
