### ISSUE TITLE
During Voice or Video call Getting this exception

### ISSUE THREAD

**Issue by akashqss** [wireapp/wire-android#34]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.wire-1/base.apk"],nativeLibraryDirectories=[/data/app/com.wire-1/lib/arm, /data/app/com.wire-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libjingle_peerconnection_so.so"

Fatal error in mediaengine/webrtc/modules/audio_device/android/audio_device_template.h, line 105

**Comment by mykola-mokhnach** [comment]
Is the issue still reproducible in the recent version?

**Comment by marcoconti83** [comment]
Hi @akashqss ,
this is a very old issue and I'm closing because it's probably not relevant anymore. Feel free to reopen if it still happens.
