### ISSUE TITLE
Failed to resolve AVS, Audio-notifications, Koin, Pin-editText, count, Zoom layout, Kluent, icu4j-shrunk after following the wire instructions.

### ISSUE THREAD

**Issue by RAZA-ABBBASI** [wireapp/wire-android#3403]
Whlie gradle sync I am getting failed to resolve for various libs, as clear in the following screen shot. 
SDK, NDK, JDK all set according to the mentioned version. 

**To Reproduce**
Clone the wire-android repo, and sync the gradle files. 

<img width="627" alt="Screenshot at Jul 07 19-04-20" src="https://user-images.githubusercontent.com/6930624/124774339-29b7eb00-df57-11eb-9813-34cdea7f4655.png">

**Screenshots**

**Comment by makingthematrix** [comment]
Hi,
Because of Bintray closing up, some of our dependencies are now not available publicly. We try out other public repositories but this is a slow process. It will probably take a few months.

**Comment by RAZA-ABBBASI** [comment]
any update on this?

**Comment by zequnjiang** [comment]
any update on this? @makingthem

**Comment by makingthematrix** [comment]
No update.

**Comment by ontologiae** [comment]
So it's impossible to compile ourself your app...
I'm stuck with : "Could not find com.wire:icu4j-shrunk:57.1."

Any way to compile it, even by recompiling stuffs ?

**Comment by obfusk** [comment]
fyi: I've started working on getting wire into F-Droid, which also requires this to be fixed :)

**Comment by ontologiae** [comment]
@obfusk I would be very interested, I urgently need to use Wireapp with a bug fix I made and I'm unable to verify it and make the apk...
I tried to compile wire-avs, but it's very difficult
Thank you

**Comment by ontologiae** [comment]
@obfusk Ok, I see, I though you did it at home. Will this build will be public ?

**Comment by obfusk** [comment]
@ontologiae of course, all apps on [F-Droid](https://f-droid.org) are public and 100% free software.

My work-in-progress merge request is here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9682

**Comment by obfusk** [comment]
So... we're still working on making the artefacts available properly.

In the mean time, you can find a `.zip` (with `.jar` and `.aar` files provided to me by the development team) [here](https://github.com/obfusk/wire-android/releases/tag/foss-wip-artefacts), which you can use to install them to `mavenLocal()` with `mvn install:install-file -Dfile=$file.jar -DpomFile=$file.pom` (e.g. [like this](https://github.com/obfusk/wire-android/blob/foss-wip/maven-local.sh)).

You will need to modify some version numbers (since a few don't match the latest tag here) and add `mavenLocal()` to some `repositories {}` blocks.

F-Droid's build system complains about firebase and `.so` files, so I haven't been able to get a working build yet myself, but gradle seems to find all the dependencies now.

**Comment by obfusk** [comment]
I cleaned up the `.zip`, which contained more than necessary; you should be able to get some of the dependencies using `jcenter()` (until Jan 2022), and koin by using the `io.insert-koin` namespace instead of `org.koin`.

**Comment by obfusk** [comment]
See also https://gist.github.com/obfusk/33aecbc5577018f4188a927112b8f12a

**Comment by ontologiae** [comment]
@obfusk It's great,  thank you very much !

**Comment by ontologiae** [comment]
@obfusk It's asking for avs-6.6.239, and you zip contains 7.2.3. WHich branch do you use ?

**Comment by obfusk** [comment]
@ontologiae I'm using my own fork atm; I [modified `scripts/avs.gradle` to use 7.2.3](https://github.com/wireapp/wire-android/compare/develop...obfusk:foss-wip#diff-573044648274c84a9b95a0e686df380a4317ea3338e473dfa6bc93f7eb8cfc04).

**Comment by ontologiae** [comment]
@obfusk It's far better thank you, now, thank you again, I just have problem with wrong version of NDK etc.. To be sync with you, what version of Android SDK (30 I presume ?) and NDK do you use, and do you compile it with arm64-v8a ?

**Comment by zequnjiang** [comment]
@ontologiae @obfusk Can your wire-android run successfully?

**Comment by obfusk** [comment]
@ontologiae I'm currently using [ndk r20b](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9682/diffs); gradle seems to install `Android SDK Build-Tools 30.0.2` and `Installing Android SDK Platform 30` automatically.

**Comment by obfusk** [comment]
@zequnjiang I'll let you know when my F-Droid build is successful (almost there...) :)

**Comment by obfusk** [comment]
the [build succeeded](https://gitlab.com/obfusk/fdroiddata/-/jobs/1561503987/artifacts/file/tmp/com.wire_1134313.apk), will test apk soon.

**Comment by obfusk** [comment]
APK seems to be working :)

**Comment by Gardosen** [comment]
@ontologiae you could use this docker script to build the client with the propper ndk and sdk which we also use at wire
you just have to map a volume containing the wire android client to this container. then you can build it.

```FROM openjdk:8

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get update && \
    apt-get install -yq libc6 libstdc++6 zlib1g libncurses5 build-essential libssl-dev ruby ruby-dev --no-install-recommends docker.io vim && \
    apt-get clean

RUN gem install bundler

# Cleaning
RUN apt-get clean

ARG USER=android-agent
ARG USER_ID=1000
ARG GROUP_ID=1000
RUN useradd -m ${USER} --uid=${USER_ID}
USER ${USER_ID}:${GROUP_ID}
WORKDIR /home/${USER}
ENV HOME /home/${USER}

# Download and untar Android SDK tools
RUN mkdir -p /home/${USER}/android-sdk-linux && \
    wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O tools.zip && \
    unzip tools.zip -d /home/${USER}/android-sdk && \
    rm tools.zip

# Download and untar Android NDK tools
ENV ANDROID_NDK_HOME /home/${USER}/android-ndk
ENV ANDROID_NDK_VERSION r20
RUN mkdir /home/${USER}/android-ndk-tmp && \
    cd /home/${USER}/android-ndk-tmp && \
    wget -q https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip && \
# uncompress
    unzip -q android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip && \
# move to its final location
    mv ./android-ndk-${ANDROID_NDK_VERSION} ${ANDROID_NDK_HOME} && \
# remove temp dir
    cd ${ANDROID_NDK_HOME} && \
    rm -rf /home/${USER}/android-ndk-tmp

# Set environment variable
ENV ANDROID_HOME /home/${USER}/android-sdk
ENV ANDROID_SDK=${ANDROID_HOME}
ENV PATH ${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/emulator:${ANDROID_HOME}/tools/bin:$ANDROID_NDK_HOME:$PATH

#define the values to install/setup via the sdk manager
ARG BUILD_TOOLS_VERSION=30.0.2
ARG PLATFORMS_VERSION=android-29
ARG ARCHITECTURE=x86

# Make license agreement
RUN yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses

# Update and install using sdkmanager
RUN $ANDROID_HOME/tools/bin/sdkmanager "tools" "platform-tools" "build-tools;${BUILD_TOOLS_VERSION}" "platforms;${PLATFORMS_VERSION}" "system-images;${PLATFORMS_VERSION};default;${ARCHITECTURE}" "extras;android;m2repository" "extras;google;m2repository"
```

Kind regards
Marco

**Comment by ontologiae** [comment]
Thank you very much @Gardosen 
I spent some days to make it working, and I had to fix the Dockerfile for myself : https://gist.github.com/ontologiae/c015c257b8955f510499406afbb76beb
Most of the problem was some things to add in the apt install
Finally, I stuck with an error  (full compil log [here](https://gist.githubusercontent.com/ontologiae/1488e5ad71f95afddd4ad04ef8d58232/raw/2b1f3edb768303d46ee4649695db2bf574b064a9/gistfile1.txt) ):


```
Starting process 'command '/home/android-agent/android-ndk/ndk-build''. Working directory: /home/android-agent/wiredev/wire-android/zmessaging Command: /home/android-agent/android-ndk/ndk-build NDK_PR
OJECT_PATH=null APP_BUILD_SCRIPT=/home/android-agent/wiredev/wire-android/zmessaging/src/main/jni/Android.mk NDK_APPLICATION_MK=/home/android-agent/wiredev/wire-android/zmessaging/src/main/jni/Applica
tion.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-24 NDK_OUT=/home/android-agent/wiredev/wire-android/zmessaging/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=/home/android
-agent/wiredev/wire-android/zmessaging/build/intermediates/ndkBuild/release/lib /home/android-agent/wiredev/wire-android/zmessaging/build/intermediates/ndkBuild/release/obj/local/x86/liblzw-decoder.so
Successfully started process 'command '/home/android-agent/android-ndk/ndk-build''
Android NDK: WARNING:/home/android-agent/wiredev/wire-android/zmessaging/src/main/jni/Android.mk:randombytes: non-system libraries in linker flags: /home/android-agent/wiredev/wire-android/zmessaging/
src/main/jni/x86/libsodium.so
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the
Android NDK:     current module
[x86] Compile++      : lzw-decoder <= LzwDecoder.cpp
[x86] StaticLibrary  : libstdc++.a
[x86] SharedLibrary  : liblzw-decoder.so
Build randombytes x86
externalNativeBuildRelease: Executable : /home/android-agent/android-ndk/ndk-build
arguments :
NDK_PROJECT_PATH=null
APP_BUILD_SCRIPT=/home/android-agent/wiredev/wire-android/zmessaging/src/main/jni/Android.mk
NDK_APPLICATION_MK=/home/android-agent/wiredev/wire-android/zmessaging/src/main/jni/Application.mk
APP_ABI=x86
NDK_ALL_ABIS=x86
NDK_DEBUG=0
APP_PLATFORM=android-24
NDK_OUT=/home/android-agent/wiredev/wire-android/zmessaging/build/intermediates/ndkBuild/release/obj
NDK_LIBS_OUT=/home/android-agent/wiredev/wire-android/zmessaging/build/intermediates/ndkBuild/release/lib
/home/android-agent/wiredev/wire-android/zmessaging/build/intermediates/ndkBuild/release/obj/local/x86/librandombytes.so
jvmArgs :


Executable : /home/android-agent/android-ndk/ndk-build
arguments :
NDK_PROJECT_PATH=null
APP_BUILD_SCRIPT=/home/android-agent/wiredev/wire-android/zmessaging/src/main/jni/Android.mk
NDK_APPLICATION_MK=/home/android-agent/wiredev/wire-android/zmessaging/src/main/jni/Application.mk
APP_ABI=x86
NDK_ALL_ABIS=x86
NDK_DEBUG=0
APP_PLATFORM=android-24
NDK_OUT=/home/android-agent/wiredev/wire-android/zmessaging/build/intermediates/ndkBuild/release/obj
NDK_LIBS_OUT=/home/android-agent/wiredev/wire-android/zmessaging/build/intermediates/ndkBuild/release/lib
/home/android-agent/wiredev/wire-android/zmessaging/build/intermediates/ndkBuild/release/obj/local/x86/librandombytes.so
jvmArgs :


Starting process 'command '/home/android-agent/android-ndk/ndk-build''. Working directory: /home/android-agent/wiredev/wire-android/zmessaging Command: /home/android-agent/android-ndk/ndk-build NDK_PR
OJECT_PATH=null APP_BUILD_SCRIPT=/home/android-agent/wiredev/wire-android/zmessaging/src/main/jni/Android.mk NDK_APPLICATION_MK=/home/android-agent/wiredev/wire-android/zmessaging/src/main/jni/Applica
tion.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 APP_PLATFORM=android-24 NDK_OUT=/home/android-agent/wiredev/wire-android/zmessaging/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=/home/android
-agent/wiredev/wire-android/zmessaging/build/intermediates/ndkBuild/release/lib /home/android-agent/wiredev/wire-android/zmessaging/build/intermediates/ndkBuild/release/obj/local/x86/librandombytes.so
Successfully started process 'command '/home/android-agent/android-ndk/ndk-build''
Android NDK: WARNING:/home/android-agent/wiredev/wire-android/zmessaging/src/main/jni/Android.mk:randombytes: non-system libraries in linker flags: /home/android-agent/wiredev/wire-android/zmessaging/
src/main/jni/x86/libsodium.so
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the
Android NDK:     current module
[x86] Compile        : randombytes <= randombytes.c
[x86] SharedLibrary  : librandombytes.so
clang++: error: no such file or directory: '/home/android-agent/wiredev/wire-android/zmessaging/src/main/jni/x86/libsodium.so'
make: *** [/home/android-agent/wiredev/wire-android/zmessaging/build/intermediates/ndkBuild/release/obj/local/x86/librandombytes.so] Error 1
:zmessaging:externalNativeBuildRelease (Thread[Daemon worker,5,main]) completed. Took 1.767 secs.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings
92 actionable tasks: 21 executed, 71 up-to-date

```

**Comment by obfusk** [comment]
@ontologiae if you're using my fork, you need to build `libsodium.so` from source (since I had to remove the .so files from the repo as pre-built binaries are not allowed by f-droid).

I'm using this script in [my f-droid build](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9682):

```sh
wget -O libsodium-1.0.18.tar.gz -- https://github.com/jedisct1/libsodium/releases/download/1.0.18-RELEASE/libsodium-1.0.18.tar.gz
printf '17e8638e46d8f6f7d024fe5559eccf2b8baf23e143fadd472a7d29d228b186d86686a5e6920385fe2020729119a5f12f989c3a782afbd05a8db4819bb18666ef  libsodium-1.0.18.tar.gz\n' | sha512sum -c
tar xzf libsodium-1.0.18.tar.gz
cd libsodium-1.0.18
for arch in armv7-a armv8-a x86 x86_64; do ./dist-build/android-$arch.sh; done
cd ..
mkdir zmessaging/src/main/jni/{arm64-v8a,armeabi-v7a,x86,x86_64}
mv libsodium-1.0.18/libsodium-android-armv7-a/lib/libsodium.so zmessaging/src/main/jni/armeabi-v7a/
mv libsodium-1.0.18/libsodium-android-armv8-a/lib/libsodium.so zmessaging/src/main/jni/arm64-v8a/
mv libsodium-1.0.18/libsodium-android-i686/lib/libsodium.so zmessaging/src/main/jni/x86/
mv libsodium-1.0.18/libsodium-android-westmere/lib/libsodium.so zmessaging/src/main/jni/x86_64/
rm -fr libsodium-1.0.18
```

**Comment by obfusk** [comment]
> @ontologiae if you're using my fork [...]

it's also very much work in progress (I'm currently replacing google maps with openstreetmap), though you're welcome to use it of course.

**Comment by rider8581** [comment]
@obfusk, thank you for your work. According to your comment, I was able to fix a lot of issues but the following error is still remaining:
Could not find com.poovam:pin-edittext-field:1.2.1
Would you please share this dependency library?

**Comment by obfusk** [comment]
@rider8581 (as you can see in [this gist](https://gist.github.com/obfusk/33aecbc5577018f4188a927112b8f12a)) it's still available -- for now -- using `jcenter()`; this dependency has been removed in de6af443adcf176808466ff3e051de73a87b0d47 (though my fork is a bit behind `develop` and doesn't include that commit yet).

**Comment by rider8581** [comment]
@obfusk thank you for your comment, it solved the issue, but there are other issues coming. Where can I find your fork version?

**Comment by obfusk** [comment]
@rider8581 https://github.com/obfusk/wire-android

**Comment by obfusk** [comment]
@rider8581 

```sh
# generate a key
$ keytool -genkey -v -keystore /path/to/your-keystore -alias your-key-alias -keyalg RSA -keysize 4096 -sigalg SHA512withRSA -validity 10000

# sign an apk
$ apksigner -v sign --ks /path/to/your-keystore --ks-key-alias your-key-alias /path/to/some.apk
```

**Comment by rider8581** [comment]
@obfusk , I am new in android development and I don't have any keystore. How can I get it?

**Comment by obfusk** [comment]
@rider8581 if the keystore doesn't exist, the `keytool` command will create it; you just need to choose a path to store it (or use the default: `~/.keystore`).

**Comment by ontologiae** [comment]
@obfusk and @Gardosen Thank you very much, it built perfectly.
I had to fix the Dockerfile but it's perfect. Just have to test my bugfix in situation !

**Comment by rider8581** [comment]
@obfusk I built the apk with signature. And now I am studying the source code and trying to make an apk that works with my private wire-server.
I already deployed wire-server with docker-mode (https://github.com/wireapp/wire-server/blob/develop/deploy/services-demo/README.md) and checking default.json of APK to change the configuration parameters.
But I couldn't understand some fields:
 - enableBlacklist
 - blacklistHost
 - certificatePin
 - countly_server_url
 - ...
Is there any documentation about these configuration parameters? Or would you give me some samples?
I deployed wire-server and want to connect my app to it.

**Comment by rider8581** [comment]
@obfusk would you please check this issue?
https://github.com/wireapp/wire-android/issues/3502

**Comment by Gardosen** [comment]
hello everyone,

i am happy to let you all know that we were able to finally fix this issue once and for all with the help of @obfusk .
all libraries required for wire-android are available for the public now.
this has been part of the huge ongoing topic to become f-droid compliant, which we are now in our last steps and hopefully soon be able to announce to be part of the f-droid store.

Kind regards
Marco
