### ISSUE TITLE
"Undead" notification coming again and again

### ISSUE THREAD

**Issue by hannob** [wireapp/wire-android#3408]
**Describe the bug**

I happen to regularly get a notification from the same message from Wire on Android. The message is about a deleted group.

Somehow the app does not seem to recognize that I've gotten this message already plenty of times.

**To Reproduce**

The message reappears without any apparent pattern, but a reliable way to retrigger it is sending a message to a group in which I'm the only member from the desktop app.

**Expected behavior**
The app should stop notifying me again and again about the same message.

**Screenshots**
![wire-undead-message](https://user-images.githubusercontent.com/990588/125432210-3c201de6-7727-4153-8b80-0482a3fd308b.png)

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.71.1000
- Last Wire version that did not exhibit the issue (if applicable): [not applicable/unknown]
- Android OS version used to run Wire: 11 (Pixel 4a, latest patchlevel)
- Is this a custom firmware or a stock one:stock
- Mobile phone model/manufacturer:Google Pixel 4a
- Mobile network type (EDGE/LTE/Wi-Fi/Offline):LTE/Wifi (probably irrelevant for the problem)

**Comment by makingthematrix** [comment]
Hi,
Thank you for the report.
We are working in the new notification system, however this behaviour has something to do with underlying Android's notification manager. We will see what we can do.

**Comment by makingthematrix** [comment]
@hannob :
The new Wire Android version, 3.78, was just released with reimplemented notifications. Please test it and let me know how it works. (Although, I suspect it won't fix this issue).
