### ISSUE TITLE
error saving image

### ISSUE THREAD

**Issue by zarere** [wireapp/wire-android#342]
Hi there,

I'm using android 4.4.4 and wire Version: 2.22.298 (November 14, 2016) and when someone send me a picture and I click on it and click save I see "error saving image" and the image is not saved.

Can someone check on this please?

**Comment by zarere** [comment]
Here is the debug log.
[1_wire_debug_report.txt](https://github.com/wireapp/wire-android/files/613251/1_wire_debug_report.txt)

**Comment by zarere** [comment]
![screenshot_2016-11-25-14-49-52](https://cloud.githubusercontent.com/assets/7449132/20626023/73bef540-b31f-11e6-8a06-febd0693bdb2.jpg)

**Comment by zarere** [comment]
I think the issue is the same like this one
https://github.com/wireapp/wire-android/issues/220

**Comment by zarere** [comment]
I also use 3.0 Kernel with no GAPPS/Google services.

**Comment by zarere** [comment]
Anyone looking at this?

**Comment by bjoernherbig** [comment]
thanks for reporting. yes, we will look at it :)

**Comment by zarere** [comment]
Just to share that I'm having this issue  using Android 7.1.1 also without  google services installed.

**Comment by zarere** [comment]
Here is the report 
[wire_debug_report.txt](https://github.com/wireapp/wire-android/files/660636/wire_debug_report.txt)

**Comment by zarere** [comment]
Is this bug going to be fixed soon as  there is no sense for me installing google stuff in order to use wire even I haven't tried if wire is working when google services are installed?Google is not equal to privacy or security at all.

**Comment by makingthematrix** [comment]
OK, I think it is safe to close this issue :) The assets functionality was completely rewritten since then + we no longer support Android 4.x.
