### ISSUE TITLE
Video preview webm files

### ISSUE THREAD

**Issue by gautrr** [wireapp/wire-android#346]
Video preview and play button does not appear on sent/received webm files. In order to view the webm file you must first save it and then open it from within another app to view it.
It works as expected for mp4 files though.

Nexus 5
Android 4.4.4
Wire 2.22.298

**Comment by Gardosen** [comment]
I closed this ticket as it is outdated. 

what is addressed here, works in the latest version 3.45

Kind regards
Marco from the Android Team
