### ISSUE TITLE
Cannot build the APK

### ISSUE THREAD

**Issue by rider8581** [wireapp/wire-android#3492]
Good day,

Thank you for your contribution.

I downloaded the project and tried to build it through the following command:
gradlew build

But faced some errors:
![image](https://user-images.githubusercontent.com/52605718/132501651-c87fcea7-737e-4e59-bfee-14f3c49aecfe.png)

When I add my NDK version to build.gradle, I faced another error:
![image](https://user-images.githubusercontent.com/52605718/132501728-5908afcb-ea41-4c03-9322-4c30813c0885.png)
![image](https://user-images.githubusercontent.com/52605718/132501771-90149c97-f3f0-4aca-8f95-14438dac0862.png)

Would you kindly guide me on this issue?

**Comment by ontologiae** [comment]
Look at this [issue](https://github.com/wireapp/wire-android/issues/3403) which you give a lots of helps
