### ISSUE TITLE
[UX] Inconsistent view bug

### ISSUE THREAD

**Issue by PowerInside** [wireapp/wire-android#35]
When a non empty conversation or a group chat is viewed and then when we go back to the contact list and select a user (who is already on wire, but who we haven't talked to before and hence no chat history), then the previous view (of whatever conversation you were viewing before) is displayed but with the user's name in title.

The view resets properly when you send a new message though.

Steps to reproduce this bug:
1. Open a user and "delete" chat to remove chat history.
2. Navigate to some other user who has a chat history or open a group chat with a chat history.
3. Initiate a chat with the user from step 1. (notice the bug manifests as view from step 2)
4. Send a message nevertheless and realize everything's fine.

**Comment by sirodoht** [comment]
I also have this bug. It happened to me with archiving the first user instead of deleting.

**Comment by peterpanondrugs** [comment]
Kinda same issue.
- Create a drawing fox alice
- leave conversation with alice and open bobs conversation
- the drawn image from alice conv. is shown at bobs conv.

(to see u are in the right chat, just type smth to bob, and the alice drawing disappears.
[Uploading wire_debug_report.txt…]()
