### ISSUE TITLE
Block New Logins

### ISSUE THREAD

**Issue by cwmke** [wireapp/wire-android#350]
It would be a nice feature to be able to set an option in settings on a currently logged in device to disallow any new devices to login. It would be a toggle that the user could un-check when they want to add a new device. Thanks for any consideration.

**Comment by someoneEsle** [comment]
I don't think this is a good idea. Say that you create your account on your phone, and decide to prevent any other device from logging in. If you then lose your phone, there is no way to recover your account.

**Comment by cwmke** [comment]
That's a good point. A warning message can be added after selecting the box to confirm and the option could be grayed out if there is only one device associated with the account. 

I've heard other app developers say that the average user doesn't go into settings so I would think the people enabling it would know what they're doing.

**Comment by someoneEsle** [comment]
This sounds very complicated, and what does it really achieve? I guess the problem is that I don't see the advantage in preventing log ins from new devices. Why would you want that? Sorry if I sound insisting :)
If it's for security reason, know that you get a notification (and an email, if you signed up with one) every time a new device logs in, so that should suffice.

**Comment by cwmke** [comment]
You don't sound like you're insisting at all =). Maybe you're right and it's overkill. The thought popped in my head the other day that it would be nice to eliminate even the chance of someone gaining access even though this isn't a likely occurance. I am a fan of the notifications of new devices and the list of all that currently are connected and am happy to stick with using them if there is no interest from developers in implementing my idea.

**Comment by bjoernherbig** [comment]
I'm afraid we won't get to that anytime soon. The benefit is not really outweighing our approach of keeping the settings very lean, also given that we do have notifications on device changes.
