### ISSUE TITLE
How Can I Open Passcode Setting Page after first signup?

### ISSUE THREAD

**Issue by rider8581** [wireapp/wire-android#3517]
After the user creates the account and sets his unique username, I want to show the passcode lock setting so the user sets it first before using it.
How can I make it? Where and what should I add to the source code?
Kindly guide me, please.

**Comment by makingthematrix** [comment]
@rider8581 : Sorry, but if you want to customize the code, you're on your own. I can only tell you that if aside from the client app you only use your own backend, you can enforce using the passcode lock on users. Look at `com.waz.sync.handler.FeatureConfigsSyncHandler`. But if the backend doesn't enforce it, the client's code leave it to the user.

**Comment by rider8581** [comment]
I see, how can I make the backend enforce it?

**Comment by makingthematrix** [comment]
@rider8581 : The backend needs to return the right `AppLockFeatureConfig` on the applock endpoint (follow the code from the handler class). You may also mock that endpoint on the client's side and just return that "yes, the app lock is forced".
