### ISSUE TITLE
APK Direct Download Link Missing From Site

### ISSUE THREAD

**Issue by Sledge-Hammer** [wireapp/wire-android#3529]
Hello,

Could you bring back the direct download link for the APK on the website ( https://wire.com/en/download/ )?

Currently it only links to the Google Play Store but not everyone has an account there... or at least consider adding it to F-Droid if you're not willing to bring back the link. Or maybe add the APK to the GitHub releases page.

Right now everyone without a google account has to guess the link and it's quite annoying.
For example the current latest version is still hosted on the website but there's no public link there at all - https://wire-app.wire.com/android/prod/wire-prod-release-3.74.1018.apk

**Comment by makingthematrix** [comment]
@Sledge-Hammer : Hi. I reported this but it takes a bit longer to be fixed. So I decided to refresh a webpage which I set up when the last time we had this problem: https://makingthematrix.github.io/Wire-Android-Archive
And I will continue to nudge people responsible for our webpage.

**Comment by ehdis** [comment]
I second that request. Since the choice was made for Wire based on the availability of APK's. The last years it was always downloadable. BTW, on the website ( https://wire.com/en/download/ ) the version 3.73 is still mentioned as the current version. Thank you for assign this internally.

**Comment by makingthematrix** [comment]
@Sledge-Hammer , @ehdis : 
We decided that the Downloads page instead of giving a link to APK directly, will redirect you to our Releases page on GitHub and there we will publish both the APK and its SHA sum. This is not completely ready yet, that is, for the timebeing there are no SHAs yet, and please ignore the SHA displayed in the popup on the Downloads page. But the APKs are there:

https://github.com/wireapp/wire-android/releases

**Comment by ehdis** [comment]
This sounds reasonable, thank you for taking care of this. 

BTW. The mentioned SHA (Certificate fingerprint (SHA256)) on the wire.com download page is also
a important information. It would not hurt to include it also on the github page.

That fingerprint allows it to verify (and more robust then just a SHA hash) the integrity of the apk additionally.

While checking the APK one thing came up:

```
$ ls -1 Wire/
wire-prod-release-3.72.1009.apk
wire-prod-release-3.72.1009.apk.sha256sum
wire-prod-release-3.73.1017.apk
wire-prod-release-3.73.1017.apk.sha256sum
wire-prod-release-3.76.2.apk
wire-prod-release-3.76.3.apk
```
I looked for the validity of the mentioned certificate fingerprint (in META-INF/CERT.RSA)

```
$ find Wire/ -name *apk |xargs -n1 bash printcert.sh 

Warning:
The certificate uses the SHA1withRSA signature algorithm which is considered a security risk. This algorithm will be disabled in a future update.
1626e3f85dfd8434f78666444861f4e5c8fb377a284c1c304cb9d585288fa352

Warning:
The certificate uses the SHA1withRSA signature algorithm which is considered a security risk. This algorithm will be disabled in a future update.
1626e3f85dfd8434f78666444861f4e5c8fb377a284c1c304cb9d585288fa352

Warning:
The certificate uses the SHA1withRSA signature algorithm which is considered a security risk. This algorithm will be disabled in a future update.
1626e3f85dfd8434f78666444861f4e5c8fb377a284c1c304cb9d585288fa352

Warning:
The certificate uses the SHA1withRSA signature algorithm which is considered a security risk. This algorithm will be disabled in a future update.
1626e3f85dfd8434f78666444861f4e5c8fb377a284c1c304cb9d585288fa352
```

The fingerprint is correct but the used signature algorithm seems to be a problem. On the googleplay page
the requirement for the OS is >= Android 7.0. That supports already stronger algorithms ...

Thanks!

**Comment by Sledge-Hammer** [comment]
@makingthematrix Thanks, I have no problem downloading from GitHub.
I also saw in the release notes of the latest version that you're planning to add F-Droid support, which is awesome.
