### ISSUE TITLE
When in full screenmode for a picture, swiping left or right should advance to the next/prev picture

### ISSUE THREAD

**Issue by DavyLandman** [wireapp/wire-android#354]
I've been using the app for a while now, and liking it in general.

I noticed that when sharing pictures with family, I want to browse through them as if a gallery. Especially when there are 3 to 4 pictures send after eachother, I noticed I put the first on full-screen, and expected to swipe left or right to go to the next picture in the stream.

I hope this is the right place for this kind of suggestions.

**Comment by bjoernherbig** [comment]
Thank you for the proposal. We plan some changes regarding this, I will pass your feedback on for discussion.

**Comment by makingthematrix** [comment]
I think we can close it now. The feature was implemented long time ago.
