### ISSUE TITLE
Play sound notification when call isn't answered

### ISSUE THREAD

**Issue by Be-ing** [wireapp/wire-android#357]
Wire plays a beeping sound (which is nicer to listen to than an old-fashioned dial tone, thanks) while a call is ringing. If the callee does not answer, Wire stops playing this sound. This can be a little confusing because on an old-fashioned phone call, the caller would typically be notified by an automated voicemail message that the callee did not answer. It would helpful if Wire played a different sound from the ringtone when the callee does not answer to notify the caller without the caller needing to see their screen.

**Comment by AmoliShah** [comment]
I would like to work on this issue. @bjoernherbig

**Comment by selurvedu** [comment]
I would like to hear the different hangup sound when

- the callee did not respond;
- the callee dismissed an incoming call.

**Comment by marcoconti83** [comment]
Hi everyone,
thanks for the suggestion. Just to set the expectations, we would need to consider the privacy implications of this feature before we dive in.

**Comment by makingthematrix** [comment]
My understanding is that this is on purpose. Whether the callee decides to cancel the instead of responding, ignores the call, or the call is dropped for technical reasons, we don't want to give the caller any explicit information about that.

I'm closing this issue for now.
