### ISSUE TITLE
Since Nov 2nd Update 3.76.1 Update I can no longer send messages and even send button becomes unresponsive

### ISSUE THREAD

**Issue by mjflower** [wireapp/wire-android#3581]
On a long standing conversation I can no longer press send since the last update. Even if I press multiple times. Then the message will appear as sent saying 'sending...' but does not appear to deliver. Messages are still coming in.

Steps to reproduce the behaviour:
1. Open wire
2. open conversation
3. type message and press send
4. nothing happens. 
5. closing the app (force closing or normal closing) does not fix the issue. 
6. Cache cleared does not fix the issue
7. Exhibits this behaviour on wifi or LTE. Airplane mode enabled between tries.

**Expected behaviour**
the message should send as normal

**Screenshots**

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.76.2
- Last Wire version that did not exhibit the issue (if applicable): 3.75.8
- Android OS version used to run Wire: 11 RKQ1.200826.002
- Is this a custom firmware or a stock one: Stock
- Mobile phone model/manufacturer: Red Mi Note Pro 9
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE and Wifi

**Additional context**

**Comment by charlag** [comment]
Same: FP3, Android 10

This is an incredibly level of bugginness

**Comment by makingthematrix** [comment]
Working on it.
https://github.com/wireapp/wire-android/pull/3582

**Comment by froman753** [comment]
> Thanks for the input. Working on it. #3582

Is the fix released yet? Or is there a way to roll back to the previous version without uninstalling?

**Comment by makingthematrix** [comment]
Hi all,
The fix is released. Google Play Store should propagate it to you today or tomorrow.
If you prefer, you can also get the hotfix APK from my personal page](https://makingthematrix.github.io/Wire-Android-Archive/). The version number is 3.76.2.

**Comment by mjflower** [comment]
Thank you. Yes it looks like it's all working again on the updated version.

Thanks for your efforts..
