### ISSUE TITLE
Could not load dependencies from Bintray

### ISSUE THREAD

**Issue by nicolaierbs** [wireapp/wire-android#359]
After importing the project into Android Studio 2.2.2, Gradle tries to load all dependencies. It fails with the following error message:

> Could not GET 'https://dl.bintray.com/wire-android/releases/com/wire/avs/2.9.69/avs-2.9.69.pom'. Received status code 403 from server: Forbidden

This also occurred when using the command `./gradlew assembleProdRelease` or accessing the folder in a browser and trying to download the file manually. Isn't everyone supposed to access the file?

**Comment by someoneEsle** [comment]
Got a similar error today when building from another branch (message_stream). Were you building from master using ./gradlew assembleDevDebug? By the way it will probably be fixed very soon, looks like a human mistake or something like that.

**Comment by hakonbo** [comment]
We have reached the usage limit on Bintray for our open source account. We're working to fix this, currently waiting for feedback from JFrog. Will let you know as soon as it's sorted.

**Comment by nicolaierbs** [comment]
@someoneEsle I tried to build the release branch.
@hakonbo Many thanks for your answer.

**Comment by hakonbo** [comment]
@nicolaierbs @someoneEsle The issue should be resolved now.
