### ISSUE TITLE
Cannot send messages with Pixel C keyboard

### ISSUE THREAD

**Issue by bufke** [wireapp/wire-android#360]
1. Try a message using a Pixel C keyboard
2. Press enter

I would expect this to send the message. Instead of inserts a newline.

Trying some alternatives like Shift+Enter, Ctrl+Enter does not work either.

If I go into Settings, Options and uncheck the "Send Button" option I get the following behavior

1. I can no longer send messages by touching the send button on the screen.
2. I still am unable to send messages using the enter button. In this mode it appears impossible to send message at all while a keyboard is attached.

**Comment by bjoernherbig** [comment]
#363
