### ISSUE TITLE
Reply from Notification Fails to Send

### ISSUE THREAD

**Issue by MrsBingleBop** [wireapp/wire-android#3607]
Open notification in pull down menu and select Reply 
Type message and send (without opening full app)
Open wire app and see the message failed (there is no notification that it failed other than when you open the conversation and check the message itself)
Click on it and it will resend successfully

This happens without fail on wifi and LTE

**Expected behavior**
Sending replies through notification sends successfully or reply button opens the full app to type response so it will send correctly

- Wire version that exhibits the issue: 3.76.3
- Last Wire version that did not exhibit the issue (if applicable): 3 updates prior if I recall correctly
- Android OS version used to run Wire: Android 10, Samsung One UI 2.5
- Is this a custom firmware or a stock one: stock
- Mobile phone model/manufacturer: Samsung Galaxy S9+
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): wifi and LTE

**Comment by makingthematrix** [comment]
@MrsBingleBop : We didn't do anything recently that could affect this functionality, but, anyway, I'm right now rewriting the notifications. I will let you know when it's done.

**Comment by makingthematrix** [comment]
@MrsBingleBop :
The new Wire Android version, 3.78, was just released with reimplemented notifications. Please test it and let me know how it works.

**Comment by MrsBingleBop** [comment]
The first time I tried sending from notification, it did not send until I opened up the full app. However, I have not been able to recreate the problem, so this update seems to have fixed the issue for me! Thank you for following up. I'm thankful for an app with developers who listen to users even if their problems sound odd 😋
