### ISSUE TITLE
Autocorrect not working when sketching text

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#361]
When sketching on a pic, the keyboard that opens up while writing text does not have autocorrect enabled -- despide my keyboard settings.

**Comment by bjoernherbig** [comment]
We cannot repro this here. Can you provide some more info on phone and keyboard used?

**Comment by someoneEsle** [comment]
Yes sorry, Nexus 5X Android 7

**Comment by someoneEsle** [comment]
oh and google keyboard. Sorry I only now realized that you asked for which keyboard I use.

**Comment by makingthematrix** [comment]
I think we can safely closed this ticket now - fixed a long time ago.
