### ISSUE TITLE
Improve expired pictures

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#362]
- activated timed mode, set to 1 minute
- tap the camera icon, take a picture
- send
After one minute, the picture turns into a neutral plain color (I guess it depends on your accent color?). However it's not clear that what you are looking at is the placeholder for an expired picture. It would be better if it had a caption saying "expired picture".
I was actually going to report a bug where Wire had me stare at an "empty image", and then realized that I was just staring at an expired picture. If it too me a while to understand what I was looking at, surely other people may be confused too.
Thanks!

**Comment by bjoernherbig** [comment]
Thanks for the feedback. We will discuss this.

**Comment by Gardosen** [comment]
this topic was discussed several times so far. 
there is no plan to change this design implementation currently

I close this ticket as "won't do".

Kind regards
Marco from the Android Team
