### ISSUE TITLE
Can not receive video call notification

### ISSUE THREAD

**Issue by HaoyeTianCoder** [wireapp/wire-android#3650]
**Describe the bug**
can not receive the notification of video call from another user

**To Reproduce**
A detailed description will help us to fix the issue faster. 

1. Open wire app
2. Click user B and click on video invitation on the right up corner.

**Expected behavior**
User B receives this video call notification

**Actual behavior**
No notification

**Screenshots**
![image](https://user-images.githubusercontent.com/24488003/150429530-f512dc63-e8e6-4ab5-b46d-2db23ad63041.png)

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.77.7
- Last Wire version that did not exhibit the issue (if applicable):
- Android OS version used to run Wire: MIUI 12.5.20
- Is this a custom firmware or a stock one:
- Mobile phone model/manufacturer: Mi 11 Ultra
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi

**Additional context**

**Comment by makingthematrix** [comment]
@HaoyeTianCoder :
Hi,
Thank you for the report.
We are working in the new notification system: https://github.com/wireapp/wire-android/pull/3617
When it's ready it should solve this problem. I will let you know

**Comment by makingthematrix** [comment]
@HaoyeTianCoder :
The new Wire Android version, 3.78, was just released with reimplemented notifications. Please test it and let me know how it works.
