### ISSUE TITLE
java.security.cert.certpathvalidatorexception: trust anchor for certification path not found flutter

### ISSUE THREAD

**Issue by umersafeer** [wireapp/wire-android#3661]
**Describe the bug**
A clear and concise description of what the bug is. Briefly describe the issue you are experiencing. Tell us what you were trying to do and what happened instead.

**To Reproduce**
A detailed description will help us to fix the issue faster. 

**Expected behavior**
A clear and concise description of what you expected to happen instead

**Screenshots**

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue:
- Last Wire version that did not exhibit the issue (if applicable):
- Android OS version used to run Wire:
- Is this a custom firmware or a stock one:
- Mobile phone model/manufacturer:
- Mobile network type (EDGE/LTE/Wi-Fi/Offline):

**Additional context**

**Comment by makingthematrix** [comment]
@umersafeer : Please describe the problem according to the template above.
