### ISSUE TITLE
No longer receiving push notifications as of 3.78.13

### ISSUE THREAD

**Issue by embeddedt** [wireapp/wire-android#3664]
**Describe the bug**

I no longer receive push notifications when Wire is in the background. No changes were made to any power management settings on my device, and battery optimization is disabled for the Wire app.

When Wire is open, and on the list of contacts, I see the contact move to the top of the list when they send a message.

**To Reproduce**

1. Open Wire.
2. Go to the home screen.
3. Have someone send a message.

**Expected behavior**

A push notification should be sent and displayed at the top of the screen, even if Wire is in the background.

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.78.13
- Last Wire version that did not exhibit the issue (if applicable): previous version on the Play Store (3.77.10?)
- Android OS version used to run Wire: 9 (Pie)
- Is this a custom firmware or a stock one: stock
- Mobile phone model/manufacturer: Samsung SM-T380 tablet
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi

**Additional context**

The app has always had a glitch where it sometimes stops receiving notifications, but this has always been solved by closing and reopening it. That workaround is no longer effective.

Push notifications still work correctly in the web app.

**Comment by embeddedt** [comment]
@makingthematrix Thanks. I've sent logs to that email.

I can't find anything related to notification channels on my tablet, but it's an older version of Android (9) so that might be expected. Here is a screenshot of the notification settings; I think this is normal? I have always had "Maintain connection to server" set as silent and minimized; that didn't seem to cause issues. I did try changing it but it didn't help.


![Screenshot_20220215-090836_Settings](https://user-images.githubusercontent.com/42941056/154078554-c55fee12-cf10-4397-84d8-7dcb581edbd7.jpg)

On another note, while pop-up notifications no longer work, the app no longer seems to stop receiving messages entirely like it used to, so thanks for the work put in there.

**Comment by embeddedt** [comment]
Here's what it looks like for Firefox.

![Screenshot_20220216-080919_Settings](https://user-images.githubusercontent.com/42941056/154271659-ac37ca65-66db-4cfe-89a3-10db989d9c51.jpg)


What you've described would make sense, but unfortunately I seem to not have the option to enable any other notification channels for Wire. It might be a quirk in my OS, but this tablet is fairly old so it's not going to be getting fixed there. Any other suggestions?

**Comment by embeddedt** [comment]
I should also note that even with the previous version of Wire, I believe there was only that one category under the notification settings.

Thanks for your responsiveness!

**Comment by makingthematrix** [comment]
@embeddedt :

There was a bug in this before 3.78. Now you should see something like this:
![Wire 2022-02-16 at 2_12 PM](https://user-images.githubusercontent.com/4498008/154274221-7b7ede3d-fceb-4d36-8e2b-cb33cbc3d22f.jpeg)

If you don't then unfortunately I'm not sure what's going on. This is Android functionality. It should be the same on all devices.

**Comment by SystemOutPrintHelloWorld** [comment]
I have the same problem with my wire on Android 9 (Oneplus 6). I do not get notifications about messages. However, calls work well through wire. When I checked my logs I see this.

> 2022-02-16T21:10:59.112Z-TID:2/V/AndroidNotificationsManager: buildNotificationChannels
> 2022-02-16T21:10:59.115Z-TID:2/V/AndroidNotificationsManager: buildNotificationChannels
> 2022-02-16T21:10:59.117Z-TID:2208/V/AndroidNotificationsManager: trying to get sounds for messages and pings...
> 2022-02-16T21:10:59.119Z-TID:2193/V/AndroidNotificationsManager: msgSound Some(android.resource://com.wire/2131820552)
> 2022-02-16T21:10:59.119Z-TID:2193/V/AndroidNotificationsManager: trying to get sounds for messages and pings...
> 2022-02-16T21:10:59.120Z-TID:2193/V/AndroidNotificationsManager: pingSound Some(android.resource://com.wire/2131820554)
> 2022-02-16T21:10:59.122Z-TID:2208/V/AndroidNotificationsManager: msgSound Some(android.resource://com.wire/2131820552)
> 2022-02-16T21:10:59.125Z-TID:2196/V/AndroidNotificationsManager: pingSound Some(android.resource://com.wire/2131820554)
> 2022-02-16T21:11:02.829Z-TID:2/I/BackendController: Retrieved stored backend config for environment: prod

When I try messages, ping and calls. So I get no notifications about ping or messages. Call only works. This makes me suspect that wire can not access the sound files correctly. When I try to change sound files I can not do it on messages and ping. However, it was possible to change the sound of calls. I do not even get the selector to select which sound I want to use for messages and ping sounds. See screenshot.
![Wire_screenshot](https://user-images.githubusercontent.com/99843333/154364780-61ade78c-6c5f-455a-aaa4-a233382f24e7.png)

**Comment by makingthematrix** [comment]
You should use Android notification channels to set the sounds of messages and pings. The options in Wire settings are there only for people who still use Android 7.0 which does not support notification channels.

That being said, we always had problems with tablets, to the point where we decided that oficially we won't support tablets. Android makes it too difficult. 
You may try to backup your data (Settings -> Account -> Back up conversations), uninstall and re-install the app, and during the first login restore data from the backup. Maybe that will make your tablets notice that Wire uses notification channels now. Other than that, I don't have any more ideas, unfortunately...

**Comment by embeddedt** [comment]
@makingthematrix, I would like to begin by stating that I greatly appreciate the work you and others have put into continued development of Wire. It has been very reliable and the security model is excellent. Nonetheless, I think this is a regression that needs some more attention. There are now 2 users reporting the same problem, one of whom is using a phone, so I think there is some issue with the way Wire is registering the notification channels (assuming @SystemOutPrintHelloWorld also doesn't see them listed in their settings).

Lack of notifications severely hampers my ability to use Wire as a realtime communication medium, as I have to continuously check the app to see if a new message has been sent. At this point, I would rather downgrade to Wire 3.77 if it means my notifications will work again. I did try fully uninstalling and reinstalling the app as you suggested, but that did not help.

I have some experience with Android Studio; if there is something I can try to debug on my device, please let me know. I understand reproducing this kind of issue without hardware is essentially impossible. :slightly_smiling_face: 

Alternatively, is there a way to build the app in such a way that it believes it's running on Android 7, so it doesn't even try to use notification channels?

**Comment by makingthematrix** [comment]
@embeddedt @SystemOutPrintHelloWorld :

Thanks for your feedback, but I can tell you for sure that there will be no further changes in this functionality. The new code actually fixed notifications for many people, so we won't revert it, and we don't have time and people to work on it any further. Sorry. Maybe you can update your Android OS? Would it be possible?

**Comment by embeddedt** [comment]
@makingthematrix Do you accept external PRs? I found that the issue is caused by calling an Android Q+ function unconditionally without checking that the device is running at least that version. See #3675.

**Comment by makingthematrix** [comment]
@embeddedt : wow 😀 yes, please open a PR, and if you don't have time or something will go wrong, I will do it tomorrow.

**Comment by SystemOutPrintHelloWorld** [comment]
@embeddedt Nice. Should be interesting to test for me.

btw I can see the notification channel groups and have set them up correctly with sound. So it will be interesting to try the fix.

_Oneplus 6 - Android 9_
