### ISSUE TITLE
stop excluding users who don't chronically upgrade their phones (environmental ethical issue)

### ISSUE THREAD

**Issue by bruceleerabbit** [wireapp/wire-android#3677]
**Describe the bug**
F-Droid only distributes the last three versions of Wireapp, and all of them require Android OS 7.0.  Android phones are not like linux deskops-- users cannot simply upgrade their OS unless the manufacturer independantly releases a new OS (this is very rare; most phone makers abandon their users after 1 OS upgrade and generally it's just a minor version update).

Every time Wireapp increases the AOS version requirement, users are forced to buy a new phone (hardware!).  There are a lot of ethical problems with that.  Old phones end up in the trash (along with batteries that still have lots of life on them).  New phones have a carbon footprint.  Labor conditions are bad for those mining for rare earth metals.  Every phone purchase yields more profit for an unethical corporation (including but not limited to Google).

A user of a ~5-6 year old phone should not be forced to buy new hardware in order to overcome a serious Wire bug like dropped msgs (https://github.com/wireapp/wire-android/issues/1101)

At the same time, the desktop wireapp has fallen behind to the point of disrepair:

https://github.com/wireapp/wire-desktop/issues/5270

So Wire devs are failing to keep up with changes in the desktop domain, and then needlessly excluding phone users due to excessive upgrading that forces hardware upgrades.  This is an inversion of what should happen with good engineering practices.  Perhaps the Wire desktop developers should switch places with the Wire Android devs.  Upgrade ambition is healthy & constructive on a desktop where users can upgrade their software at will, but upgrade ambition is deconstructive & harmful inside Google’s walled garden of corporate control.

**Comment by vitorhugods** [comment]
Hello @bruceleerabbit. I'm sorry you were affected by the min SDK bump back in 2020.

I've seen the comments you made here and in https://github.com/wireapp/wire-desktop/issues/5270 and you are getting pretty much what you asked for: an app completely rebuilt from scratch. The minimal text-based client exists in [Kalium/cli](https://github.com/wireapp/kalium#supported-platforms), and this shared core-platform is being used to build a [new Android client](https://github.com/wireapp/wire-android-reloaded).

It's far from being an oficially supported Wire product and it's more like a testing tool, but the text-based client does work.

Whilst the current members of the Android team at wire were not around when that happened to explain the reasons behind the choice to raise the min Android version, I can say that:
- We currently have no plans to increase it again,
- The new client will keep requiring the 6+ year old Android 7.0,
- We will keep your comments in mind if the idea to raise the requirements comes,

I'm closing this issue now as there's one more thing I can guarantee: this project here won't have any requirement change, as the new project should replace it.

**Comment by bruceleerabbit** [comment]
> I've seen the comments you made here and in wireapp/wire-desktop#5270 and you are getting pretty much what you asked for: an app completely rebuilt from scratch. 

I said the desktop app needs to be rewritten from scratch to ditch Electron, not necessarily the Android app.

Due to the designed obsolescence problems that plague Android OS, an Android re-write would only be useful if it targets a much older platform like AOS 2.3, which would then run on just about any Android in existence. A phone app rewrite that targets a newer AOS version is where the damage is done.

The problem has now worsened. When I wrote this bug report, the problem was that AOS 5 users were denied access to new releases going forward. But at least they could still use their old version if they wanted. Now it’s a total disaster because we have been booted off our old version while at the same time we are blocked from updating. It’s effectively an outright denial of service (see bug 3751).

There is also no APK file for version 3.53:

https://github.com/wireapp/wire-android/releases/tag/3.53

We can’t move forward, we can’t move backward, we can’t stay where we are. And this happened without warning.
