### ISSUE TITLE
Message_stream branch issue

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#373]
Hi,
I am recently following the development on the message_stream branch. Within the past few days, a new bug was introduced (I'm on a Nexus 5X with Android 7). Basically the following happens:
1. Open the app, tap on conversation A
2. Conversation loads all messages properly
3. Go back to conversations list, tap on conversation B
4. Conversation B doesn't load any message, all is white
5. Go back to conversation list, tap any conversation (A included), nothing loads anymore in any of them

The only thing that "fixes" this is if you receive a new message to conversation X: you can then tap on X and all messages are loaded properly. Forcing the app to stop brings you back to step 1.

**Comment by wire-android** [comment]
This should be fixed now.
