### ISSUE TITLE
Possible info leaking

### ISSUE THREAD

**Issue by p3tr0v** [wireapp/wire-android#3733]
**Describe the bug**
After opening and closing Wire, when you press the "recent apps" button in nav bar, you can the contacts and groups that user has contact.
Even if your Wire is protected by pin password, you can see in behind the box asking the pin code, in darkness, some contacts and groups.

**To Reproduce**
1. Set a pin code to unlock Wire.
2. Close the app then open again, Wire will ask you about the pin. 
3. Dont answer the pin, wait around 5 seconds, press "home" button in nav bar.
4. Press "recent app" button in nav bar.
5. You will see the image of app with the dialog pin, in behind you can see some contacts and groups.

There is a worst scenario:
After setting you Wire pin code:
1. Close the app then open again, Wire will ask you about the pin. 
2. Answer the pin, Wire will be unlocked.
3. Press "home" button in nav bar.
4. Press "recent apps" button in nav bar.
5. Even if Wire is configurated to ask a pin, you will see all contacts and groups.

This is not good because if someone (the police, the wife) have physical access to the cellphone, you can see some contacts and groups even if Wire asks a pin code.

**Expected behavior**
When pressed "recent app" button in nav bar, the user wouldn't be able the see anything in the app. It had better show a total gray, or black, area in app. With no chance to see anything.

**Screenshots**
I wont post screenshots in order not to disclose my contacts and groups.

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.82.38
- Last Wire version that did not exhibit the issue (if applicable): xxx
- Android OS version used to run Wire: 12
- Is this a custom firmware or a stock one: Pixel Experience 12 begonia
- Mobile phone model/manufacturer: Xiaomi Redmi note 8 pro
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): xxx

**Comment by vitorhugods** [comment]
Thank you for the issue report.

Whilst I don't believe we will implement any fix for this in this current project, I'm creating an internal ticket so we can track it down during the development of the [new Android client](https://github.com/wireapp/wire-android-reloaded) which should be available for download soon.

I guess we could add an option to prevent screenshots and screen recording, like other privacy-foccused applications like banking apps or even streaming apps that prevent copying of the shown content.
