### ISSUE TITLE
app denial of service (“Important update… Please install the latest version…”)

### ISSUE THREAD

**Issue by bruceleerabbit** [wireapp/wire-android#3751]
**Describe the bug**
The Wire app has been partially¹ functional for years. A few days ago it became obnoxiously dysfunctional without warning. Upon launching the app, there is now a blue screen saying:

> Important update
> Please install the latest version of Wire
> [Download]

If you tap “[Download]” on a deGoogled phone, Wire app attempts to launch into Google Playstore anyway. Since that’s a dead-end, users are trapped. There is no way to clear the nag screen. So it’s a nag (in itself a bug) & the nag has the bug of denying service.

This happened out of the blue, without warning.

**To Reproduce**
1. Launch the app

**Expected behavior**
The nag screen never should have happened. I did not ask for update nags. That should be an opt-in feature. The app should have continued functioning to the extent that it has in the past.

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.38.826
- Last Wire version that did not exhibit the issue (if applicable):
- Android OS version used to run Wire: 5.1.1
- Is this a custom firmware or a stock one: stock

**Additional context**
There are many bugs here. Nine bugs:

1. update nags were not requested by the user; it is a disservice to nag users that didn’t sign up for nags.
2. the unwanted nag denies service to the user & gives no way to clear the nag. This is the most obnoxious part of the bug. Someone decided for everyone else to deliberately force an upgrade & render the partially functioning app wholly unusuable.
3. the download button sends the user to a privacy offender (Google). The Wire apk is directly downloadable from wire.com so there is no reason to put a surveillance capitalist (Google) in the loop.
4. the app offers a download button then fails to detect that the device is incapable of Playstore interaction. It also fails to detect that F-droid is installed, and use it.
5. the app fails to look at the AOS version and tell the user which version of Wire is the latest that will run on their version of AOS.
6. the app fails to tell users where they can download the latest compatible version to accommodate users who prefer to side-load their apps.
7. notifications are incomplete. That is, the app denies visibility on new inbound msgs but still shows users the first few words of new msgs in the notifications. So the app still continues fetching msgs from the server and opens them, but merely denies the user visibility to the whole msg.
8. users cannot send msgs
9. no announcement was made on the Wire blog warning users of this anti-feature.

① regarding the app being /partially/ functional, it has always had the bug of random/arbitrary silent dropping of messages. A quite serious bug, but in some situations the app was better than nothing and in other situations worse than nothing. But at least we had a choice. Now we effectively just have nothing.

**Possible workaround (also broken)**
I happen to know from another [bug report comment](https://github.com/wireapp/wire-android/issues/1101#issuecomment-1056945179) that this is the latest compatible version of the app:

https://github.com/wireapp/wire-android/releases/tag/3.53

That version could possibly enable users to move forward but there is no APK file there. Where can we get the APK?

**Comment by tmspzz** [comment]
Hello,

Thank you for your kind words abs for opening an issue. 

The nag screen is intentional as is the inability to bypass the nag screen.

You can download the latest compatible version of Wire with the Wire public cloud at https://github.com/wireapp/wire-android/releases/tag/3.82.38 in case you don't have Google services installed. 

Alternatively please refer to the F-Droid Store.

In case your device does not support the required version of Android you can:
- use the power of open source to find a maintainer that will back port the code and make it compatible with your version of Android OS
- update the software distribution on your phone
