### ISSUE TITLE
Update Google Play Nag

### ISSUE THREAD

**Issue by liocalset** [wireapp/wire-android#413]
Hi,

I updated Wire to version 2.24.303 by downloading the APK directly from Wire's website. My Android 6.0.1 phone is not tied to any Google account, therefore I don't use Google Play. Every time I open Wire or click on **Contacts** within Wire, a dialoge box pops up which reads:

> **Update Google Play services**
> Wire won't run unless you update Google Play services.

The previous version of Wire didn't display the aforementioned dialoge box on my device. My phone is a few years old and recently stopped getting updates, and I don't plan on ever tying it to a Google account.

Thank you.

**Comment by bjoernherbig** [comment]
Hi,

can you please check if you have Google Play installed on your phone?
We recently updated the Google Play version to 10.0.1, so should you run a version previous to that, Wire will ask you to update every time you start the app. You can however ignore that and Wire will run with notifications via web sockets. One thing we will do is to decrease the showing of these warning to one time only.
You will not receive that warning if you don't have Google Play Services installed. Wire will solely rely on web sockets in this case

**Comment by landry314** [comment]
you must be using microg gcm, right? i think they just need to update themselves. i posted on their github here:
