### ISSUE TITLE
Feature request: render markdown syntax just like web and desktop apps do

### ISSUE THREAD

**Issue by maximbaz** [wireapp/wire-android#414]
Web and desktop applications have a very good implementation of rendering the markdown syntax, including the syntax highlighting.

However the android app is not rendering markdown at all, and people get confused that the text is rendered differently on the phone and on the desktop. See https://github.com/wireapp/wire-webapp/issues/355 and https://github.com/wireapp/wire-webapp/issues/250 for reference.

Please implement the markdown rendering on all devices.

**Comment by bjoernherbig** [comment]
Thanks for the request. We have that on our (very long) list, but currently unfortunately no priority on it. Small team, limited resources.

**Comment by Strit** [comment]
Please move this issue up the priority list a bit. It's really annoying going through code snippets on the go. 😄

**Comment by marcoconti83** [comment]
Hi all,
I'm going through old issues to see if there is any update we can give. Markdown has been implemented on Android a long time ago, so I'll close the issue.
