### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by MR-GuoQing** [wireapp/wire-android#418]
hi,
I want to know how can i get the zmessaging-android-88-1328 jar file?
thanks

**Comment by JPonte** [comment]
The aar files for the sync engine (zmessaging-android) are in a bintray repository. The gradle file should be pointing to them already. If you wish to compile it yourself, you can check the repository: https://github.com/wireapp/wire-android-sync-engine

**Comment by marcoconti83** [comment]
Hi @MR-GuoQing ,
as @JPonte pointed out, you can compile the sync engine (zmessaging) yourself, or just compile the [main application](https://github.com/wireapp/wire-android) that will in turn pull in a binary version of zmessaging.
