### ISSUE TITLE
Bug: During device verification the client ID is rendered incorrectly when it starts with a zero

### ISSUE THREAD

**Issue by maximbaz** [wireapp/wire-android#419]
Open a conversation > tap on a contact name > tap on Devices.
Here the device ID is rendered correctly, even if it starts with a zero.

Tap on the device whose ID starts with a zero.
**Issue**: the starting zero is gone, the ID is rendered incorrectly so that pairs of characters do not match.

------

One picture worth a thousand words :smile: 
The text in red is the expected result.

![image](https://cloud.githubusercontent.com/assets/1177900/21329196/bca8fc6c-c637-11e6-9cb0-3ceeea1a28f6.png)

**Comment by Gardosen** [comment]
this bug has been fixed.

i close this ticket as "fixed".

Kind regards
Marco from the Android Team
