### ISSUE TITLE
No network connection notification

### ISSUE THREAD

**Issue by mcg** [wireapp/wire-android#426]
Unfortunately I don't have a screenshot of this issue, but more than once when I've when I've opened the app I have had a yellow bar/notification at the top of the app letting me know I have a problem with my network connection. When this happens I don't actually have any issues with my connection, outside of Wire. The only way I can clear this is to "close" Wire by swiping it away from Android task list and re-launch it.  Could this be Doze related? I am using Android 7.1.1 on a Nexus 6P.  Using Wire v2.24.303.

**Comment by bjoernherbig** [comment]
Thanks for bringing this up. It is a known bug we are currently working on.

**Comment by MrLe0** [comment]
I don't know if it has a direct correlation but, I have seen the same bug with the issue that messages don't download (sending is ok, receiveing isn't) when this bug appears.

**Comment by bjoernherbig** [comment]
fixed in [https://github.com/wireapp/wire-android-sync-engine/pull/50](url)
