### ISSUE TITLE
Move text cursor when sketching

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#427]
While sketching, tapping on a text area doesn't allow to move the text cursor. (I'll show a picture to clarify what I mean)
![example](https://cloud.githubusercontent.com/assets/21009625/21445489/1d9eb7fc-c87f-11e6-8ea4-78683ac79c72.png)
Take this example and say that I want to move the text cursor right after "estas". If I tap on the word "estas" I would normally expect the cursor to move from "feliĉa" to "estas", but this is not what happens :/ The only way to go back is to actually delete the word "feliĉa", which is way too much work for the average lazy user (that I am).

**Comment by Gardosen** [comment]
this issue seems to be fixed,

jumping to another point of the written text is possible via the google keyboard space slide.

I closed this ticket as obsolte

Kind regards
Marco from the Android Team
