### ISSUE TITLE
UX for simply messaging is starting to become a mess (iOS also applies I guess)

### ISSUE THREAD

**Issue by notNSANE** [wireapp/wire-android#428]
There are currently 5 functionality buttons on Portrait view. We need to to tap on the "..." button to access 3 more functionalites, for a total of 8 usable buttons.
If Wire keeps on following trends, they would add Stickers soon, and that's 9 buttons. **It will be a mess**.

My suggestion will be to first merge all camera functionality on one button: press a camera icon to open a small popup (non-obscuring) with the option to take a **photo** or **video**, I also suggest adding the **drawing** right here too, in a popup... and maybe the **attachment** icon too, or plan for a better usage of it. **Telegram has excellent UX, _preloading the camera_ so you can instantly see the preview**.

**Location** and **ping** buttons are extremely situational, so I suggest to either merge it or remove them entirely. Do you have data to support showing ping on the first part of the bar? 

Another small UX fix might be moving the ping button right to the left of the Timed messages. It's more logical having it there than in the bottom bar.

Last, and maybe the most important feedback of them all: **let us hide the functionality we don't ever use**. I can live with only GIFs and attachments. Other uses might add just photos and videos. Other, might only use pings and attachments. And others maybe just want to post texts and that's it, they won't ever use all the other stuff. Old school! 

What's important is that **we as users should have the choice to select what we want, and not what's forced to us**. Any of these changes should help with UX immensely.

And please, suggest more ideas!

**Comment by bjoernherbig** [comment]
Thanks for the suggestions. We have some plans to make it more customizable what you get as primary options. no timeline to share yet though.

**Comment by Gardosen** [comment]
this ticket is now over 3 years old and hasn't touched since then.
also the design of this element as it is is intended and the team does not plan to change this.

I close this ticket for now as "won't do".

Kind regards
Marco from the Android Team
