### ISSUE TITLE
App crash when call starts

### ISSUE THREAD

**Issue by komo81** [wireapp/wire-android#43]
Hi, I downloaded your code, build it by 'gradlew clean assembleProdRelease' uploaded to my two devices. Always when I call from one device to second one (I created two different users) and accept call (audio or video) on second device then app on first device crashes. In adb log I saw this error:

'A/libc: Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 5109 (re_main)'

Do you know where the problem can be? 

Note: When I install official app from Play Store then everything is working fine.

**Comment by zbsz** [comment]
Try using latest avs version, change build.gradle:81 to `avsVersion = '2.8.61@aar'`
