### ISSUE TITLE
Crash on playing video before sending

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#430]
Android 7.1, Nexus 5X.
- open a conversation
- start recording a video
- before sending it, tap the "play" icon to see what you've recorded
- app crashes, video is lost.
(can't provide the debug log right now but it's 100% reproducible on my device)

**Comment by mykola-mokhnach** [comment]
Is it still reproducible?

**Comment by someoneEsle** [comment]
Yes
