### ISSUE TITLE
Typing indicator not very reliable (?)

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#431]
Unfortunately I don't have concrete evidence for what I'm about to report, but I hope I won't sound like I'm starting a conspiracy theory - and hopefully other people can comment with their own experience.
I feel like the typing indicator isn't very.. truthful. Like, it has happened many times that while wire says that "X is typing", X is not typing at all. In fact they are not only not looking at the phone, but in some cases they are not even connected to the internet. This issue seems to occur when you are having a "rather active" conversation with someone: at some point you'll be staring at the screen waiting for your friend to send this loooong message, just to find out in a few seconds that they are not typing at all.
Useful information:
- I'm on Android 7.1, Nexus 5X, I've been experiencing this issue since I downloaded wire (months ago)
- my friends are using their phones, not the web app or desktop clients. I haven't noticed if this happens more often or only with iOS/Android users -- I feel like it happens with both but I'll keep an eye on it.

**Comment by mykola-mokhnach** [comment]
Is this still the case?

**Comment by someoneEsle** [comment]
Yes, still experience this on a daily basis

**Comment by someoneEsle** [comment]
This should have been fixed in the latest iOS release. I'll close for now, reopen if it happens again
