### ISSUE TITLE
Support for sending photosphere

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#433]
Nexus 5X, Android 7.1
Sending 360-degree pictures from my nexus results in sending flat pictures that the receiver is not able to open properly (even if their phone supports them). They do see the picture, but as a normal flat one. My understanding is that part of the information is lost upon sending, and the receiver's phone can't tell it's a panoramic photo.
Unfortunately, sending the picture as file does not help. When sending a picture (or anything really) "as file" I would expect Wire to not compress it or do anything with it, just send it as it is. This would probably allow the receiver to open the photosphere properly.

**Comment by Gardosen** [comment]
as this ticket is over 3 years old now, and as there is no plan to implement this feature, i close this ticket for now.

Kind regards
Marco from the Android Team
