### ISSUE TITLE
Opening a chat occassionally starts at the oldest rather than the newest message

### ISSUE THREAD

**Issue by MadEgg** [wireapp/wire-android#434]
Sorry to be a bit vague, I'm reporting on behalf of one of my contacts that's using Wire on Android (I'm using iOS myself). 

Sometimes when a conversation is opened, it starts at the very oldest message, rather than the newest message. There is no way to scroll to the bottom with one button press (may be a good idea, as well: a scroll to bottom button when you're not at the bottom), so it takes a lot of time to scroll through a huge list of messages.

Unfortunately, I don't have any direct steps to reproduce this issue, as it doesn't occur on my own phone. Hopefully this report is still of some use.

**Comment by someoneEsle** [comment]
Yes, this has already been reported several times. It is a known bug that is being worked on (see the message_stream branch and the collections branch). Should be fixed in a future release, not too many weeks from now I believe.

**Comment by MadEgg** [comment]
Ah, thanks for the tip, I'll pass the hint. Good that it's being worked on, too!

**Comment by someoneEsle** [comment]
Should be fixed in today's update!

**Comment by someoneEsle** [comment]
Are you still experiencing this? Otherwise you may close the issue :)

**Comment by MadEgg** [comment]
It hasn't happend since so I'm guessing it's fixed! Thanks!
