### ISSUE TITLE
Wire to silent after connecting headphones with microphone (also for iOS)

### ISSUE THREAD

**Issue by peterpanondrugs** [wireapp/wire-android#436]
Hello,

whenever i connect a headset with an inbuild microphone to the phone connector, tthe volume for my chatpartner is dropping too much. I really need now to focus on the voice, which is in sourrunding noise ofc not possible. 
The same happenz to the iOS version.

Cruz!

**Comment by jspittka** [comment]
Hello peterpanondrugs, Can you please check if you have the same issue with any other communications app?! Sounds like it may be a problem with your headset.

**Comment by peterpanondrugs** [comment]
The fault was my phone, it's solved for the S3 LTE, but the other part has iPhone5 and when he connects with headphone, i barely can't hear him. 
I tested with iPhone 6s, Samsung S7 <- no problem.
I will watch this a bit more.
