### ISSUE TITLE
High battery drain in flight mode

### ISSUE THREAD

**Issue by supermihi** [wireapp/wire-android#440]
I am using the android app on a Fairphone 2 with Open OS installed (no gapps / GCM). Besides the generally high battery comsumption reported in #164 I noticed that the battery usage is particularly high when the phone is in flight mode (which I use at nights).
Before Wire was installed, the phone lost virtually no battery during a night, while now it drops about 20%. Not sure if this is related to Websockets or a general Wire issue, but I think the app should notice flight mode and completely deactivate itself until a network connection is available? The same probably also applies to the case that both WiFi and mobile data are deactivated.

**Comment by ec1oud** [comment]
It takes half the battery all the time, out of flight mode.

I think it needs a setting to not run in the background.  (And automatically stop running in flight mode.)

**Comment by joaobarcia** [comment]
Might it be related to #853 ?

**Comment by supermihi** [comment]
Sounds like, yes.

**Comment by damnms** [comment]
The funny thing is that this is labeled as bug but #853 is labeled as enhancement. which is of course wrong, this is a killer-bug. wire tends to destroy batteries or make them live much shorter.

**Comment by Gardosen** [comment]
i can't verify this anymore with the latest build 3.46.
as the last commend on this topic is 1 1/2 years old, i close this ticket for cleanup purpose.

if someone can provide more detailed information from his phone if this is still the case for them, feel free to create a new ticket and i will address it as soon as possible.

Kind regards
Marco from the Android Team
