### ISSUE TITLE
Can't open link preview

### ISSUE THREAD

**Issue by Kasmetski** [wireapp/wire-android#441]
If I send a link from the desktop app and see a preview of the link (with picture and etc.) people can't open it on Android devices. When someone clicks on the preview, nothing happened. Tested on Android 4.4.2

**Comment by marcoconti83** [comment]
Hi @Kasmetski ,
I realize this ticket is extremely old :) Thanks for filing it. I believe this has been fixed a while ago. I will close the ticket, if this is still happening, please re-open and mention which version and, if possible, which link.
Thanks!
