### ISSUE TITLE
Implement email-only registration in android app

### ISSUE THREAD

**Issue by varac** [wireapp/wire-android#442]
Following up #328, please implement email-only registration in android app. 
The reasoning is already layed out in #328.

**Comment by haroon-ali** [comment]
I hope you can implement this soon.

**Comment by Feuermurmel** [comment]
I've heard that registering without providing a phone number is possible though the website. But I can't find out where. Maybe this should be documented as a workaround for the meantime?

**Comment by PacoBell** [comment]
This is still unresolved a year later? I guess privacy just isn't a priority for them.

**Comment by someoneEsle** [comment]
This is now possible so I'll close this issue
