### ISSUE TITLE
Feature Request: Add Android Wear support

### ISSUE THREAD

**Issue by edintomato** [wireapp/wire-android#446]
Android Wear support would be nice for when people are unable to use their phones to respond. right now it just opens the app on the phone.

**Comment by bjoernherbig** [comment]
thanks, unfortunately we have very limited resources. added it to the request log

**Comment by JamesDBartlett** [comment]
@bjoernherbig This request can probably be closed now, as the latest version of Android Wear allows users to reply to Wire messages by tapping the Reply button on the incoming message notification on the Wear device.

**Comment by Gardosen** [comment]
Closed as requested.

Kind regards
Marco from the Android Team

**Comment by JamesDBartlett** [comment]
@Gardosen, 
The current implementation of Wire on Android Wear only allows the user to read the most recent incoming message, and send a single response to said message. Sadly, it doesn't allow for initiating new outgoing messages, viewing the current conversation history, or selecting other conversations. 

These features are all available in text/chat apps like "Messages" (the default SMS app on Android), and Google Hangouts, and have been for some time now. Any plans to implement similar functionality in Wire? Thanks!
-James
