### ISSUE TITLE
GIF not playing (working) before & after sending

### ISSUE THREAD

**Issue by peterpanondrugs** [wireapp/wire-android#450]
Hello,

if i share a GIF out of WIRE, it does not preview the GIF file choosing it, neither does it play after it was sent. Also not after a some minutes, closing conversation, closing wire (with the return/home button)

Dirty solution: Force Crash Wire -> start Wire -> GIF is playing.

[GIF not working.txt](https://github.com/wireapp/wire-android/files/691791/GIF.not.working.txt)

**Comment by peterpanondrugs** [comment]
Update: Gif is working now immediately after sending to contact, but still the preview is not working.

**Comment by freijon** [comment]
I noticed the same issue. Inserting a GIF from a local folder on the phone only seems to insert a static image which is not animated. Same happens when GIFs are shared from lets say Google+ to a Wire contact. This works with other messengers.

**Comment by ShawnPConroy** [comment]
I'd like to clarify that it's not the 'preview' that is not working, but the GIF edit. While editing, it only shows the first frame.

**Comment by Gardosen** [comment]
gifs are animated now in edit mode, i guess this was fixed a long time ago.

Closed as fixed.

Kind regards
Marco from the Android Team
