### ISSUE TITLE
Request: Allow local rename of wire contacts (or use of nicks)

### ISSUE THREAD

**Issue by gilshwartz** [wireapp/wire-android#451]
The App (as well as the webapp) displays the name of contacts as chosen by the respected users. However, I find it useful to rename my contacts to some less cryptic names used by my friends to actually recognize them. It would be very useful for Wire to allow the user to rename his or her own contacts (or allow for personal nicks, which will be used for contact display) for ease of recognition. Of course, the default nick can be the contact name so this would not force a behavioral change on users.

**Comment by 3raserHead** [comment]
+1 on that request.
