### ISSUE TITLE
End-to-end authentication ineffective

### ISSUE THREAD

**Issue by supermihi** [wireapp/wire-android#462]
Wire allows for secure end-to-end authentication by comparing device fingerprints out-of-band, which completely eliminates the requirement to trust the server operator. The android app allows to manually mark a contact's device key as "verified", turning the shield icon from blue/white into completely blue.

However, this step is completely ineffective, because the app does not allow to encrypt messages only for verified devices and, more critically, silently adds new devices of contacts as they are announced by the server. This means that, even if I have verified my contact's fingerprint, an attacker with access to the servers can register a new device for that contact, and my wire-app immediately starts to encrypt all subsequent messages for the attacker's key as well, without me ever being notified about the additional device. Worse, as the attacker can likewise unregister his device any time, even a check of my contact's device list after a conversation might not reveal the intermediate presence of the attacker's device key.

There are several resolutions for this issue, varying in tradeoff bewteen convenience and security:
1.  Generally encrypt only for verified keys (weak version: add config option for this behavior)
2.  Notify on newly added devices of my contacts and ask whether to add them or not. Don't allow sending messages before this question has been answered (weak version: add config option for this behavior).
3. As soon as the user has explicitly verified the fingerprint of at least one device of a specific contact, apply either 1. and/or 2. to all conversation with that contact. The rationale is that a user manually approving fingerprints can be assumed to be privacy-sensitive. This method would not get into the way of users who don't care about enhanced privacy.

**Comment by supermihi** [comment]
Okay, so apparently under some conditions there **is** something like 2. implemented but it does not always appear – some of my contacts told me that they got a warning when I used a new device, but on my own phone I am not getting those messages. Could this be a bug?

**Comment by someoneEsle** [comment]
If you verified the contact's fingerprint, you do get notified when their fingerprint changes. Moreover, if you log in using a new device, you get notified on all your other devices about it (plus you get an email)

**Comment by supermihi** [comment]
Thanks for clarifying the intended behavior. Now, this definitely did not happen on my device, though I had verified the contact's fingerprint before. I'll try to reproduce and provide a more detailed report asap.

**Comment by supermihi** [comment]
Found the reason – I had not verified my _own_ second device, such that of course the conversation wasn't verified in the first place. Now it works – however, the windows client does NOT show a warning. Is this intended?

**Comment by mykola-mokhnach** [comment]
@supermihi Please try the most recent version of Windows client - everything should be smooth now.

**Comment by supermihi** [comment]
Great, thanks for the update!
