### ISSUE TITLE
Cannot delete an expiring message or an expiring file

### ISSUE THREAD

**Issue by fortran77** [wireapp/wire-android#467]
On the Android client (Android 7.1.1, Wire 2.24.303), I am unable to delete an expiring message or an expiring file. A long press yields no context menu.

On the web app the deletion works OK, by clicking on the three dots and reaching a context menu. Android shows no corresponding menu.

**Comment by someoneEsle** [comment]
I would add that even if this is by design, we should still be able to delete expiring messages if they failed to be sent.
- send a timed message while phone in airplane mode
- message fails sending
- now you can't delete the message, the only option is "resend"

**Comment by bjoernherbig** [comment]
fixed in #621
