### ISSUE TITLE
Hourglass disappears

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#468]
Nexus 5X Android 7.1
I know this is an edge case but I have high morals so here it goes.
- disable the send button in settings>options
- open a conversation
- start typing
- tap the hourglass
- set any time
- hourglass disappears

The only way to get it back is to open another conversation and then go back to this one again.

**Comment by xuanzhaopeng** [comment]
BUG: AN-4644

**Comment by makingthematrix** [comment]
I think we can safely close this issue - the whole timed messages UI was changed since.
