### ISSUE TITLE
Feature Request: Disable screenshots when in Wire app

### ISSUE THREAD

**Issue by coderjoe** [wireapp/wire-android#478]
When switching between communicating with my Signal and Wire friends I noticed that attempted screenshots are being blocked when in Signal, but Wire allows me to screenshot any portion of the application including communication.

Would it be possible to disable screenshots from within the Wire app making it more difficult to download content via methods other than long-press -> download?

**Comment by someoneEsle** [comment]
If this gets implemented, I think it should be opt-in. Most people want to be able to take screenshot and send them to friends.
(related: when you send timed messages, screenshots are disabled)

**Comment by coderjoe** [comment]
Hmm, I didn't test with timed messages. Thanks for the note! I think that might just satisfy me enough to be happy. I'm going to close this so it doesn't generate work that might not be necessary.

**Comment by KaKi87** [comment]
Does this feature also prevents video recording ? Thanks.

**Comment by pfahlr** [comment]
I was under the impression that screenshots were disabled as a defense against an adversary attempting to use screencapture as an alternative means to intercept unencrypted messages. If they were able to get a root kit on one of the devices, it's possible to bypass FLAG_SECURE... But... 

I mean, I know someone could bust the windows out of my car, or pick the lock on my front door. That doesn't mean I leave those things unlocked...
