### ISSUE TITLE
Finding users by username not working

### ISSUE THREAD

**Issue by 0xdade** [wireapp/wire-android#485]
## Unexpected behavior
For instance, I was trying to add @\alan earlier (without the slash) by username, at his request. When I went to do so, I ended up having to type his full name before he showed up in the list of people to add. Screenshot below.

![@alan](https://0xda.de/img/wire-alan.jpg)

## Expected behavior
When using someone's @ handle to add them, they should show up at the top of the list, perhaps in their own designated section to differentiate between the intended user and the "suggested" users.

**Comment by mykola-mokhnach** [comment]
Can you please try it in the most recent version?

**Comment by makingthematrix** [comment]
Fixed https://github.com/wireapp/wire-android/pull/2414 (or even earlier).
