### ISSUE TITLE
Can't chat when call is running

### ISSUE THREAD

**Issue by JustAskin** [wireapp/wire-android#487]
Please enable us to exit the call screen and chat with the call still going on.

**Comment by someoneEsle** [comment]
duplicate https://github.com/wireapp/wire-android/issues/246

**Comment by xtotdam** [comment]
Hey! You say this is duplicate of #246 which is duplicate of #487 which is duplicate of #246 which is duplicate of #487.... I don't think I get it :)

**Comment by someoneEsle** [comment]
Hi @xtotdam I'm not sure what you mean. #246 was created before this issue, therefore this is a duplicate. I didn't say that #246 is a duplicate of #487 -- but you will see that I have referenced this issue in #246. That's just how github works :)

**Comment by xtotdam** [comment]
Hi @someoneEsle I think I just got a bit confused :) I swear I thought it was a cycle of duplicate references
