### ISSUE TITLE
Get Wire on F-Droid

### ISSUE THREAD

**Issue by YogliB** [wireapp/wire-android#5]
Please get Wire on the F-Droid FOSS app store.

**Comment by feer921** [comment]
Start the wire app,it shows me "Important update" ,crashed when click the "Download" button

**Comment by mvdan** [comment]
At a first glance, blockers for our official repo:

* Third party maven repo - `url "https://dl.bintray.com/wire-android/third-party"` (mavenCentral/jcenter/jitpack are allowed)
* Use of play-services (non-free android lib)
* I see api keys are missing in `app/api-keys.properties.template`

Seems like an easier way would be for Wire to set up their own F-Droid repo, like others did: https://f-droid.org/wiki/page/Known_Repositories

Instructions on how to set up a binary repo: https://f-droid.org/manual/html_node/Simple-Binary-Repository.html

**Comment by dev-rke** [comment]
I'd also like to see wire on f-droid. :-)

**Comment by zuglufttier** [comment]
F-droid would be very nice!

**Comment by mvdan** [comment]
Stop giving +1 comments. This is what :+1: emojis are for.

**Comment by beerisgood** [comment]
A F-Droid version without google service is a must!

**Comment by mrshankly69** [comment]
Agree that a version that doesn't rely on Google Play Services for GCM would be very welcome and F-Droid would be the best place to publish it.

**Comment by vrms** [comment]
+1

**Comment by someoneEsle** [comment]
@mvdan they already have a version that works without google play services on their website. I think (but I am not 100% sure) that that version is the equivalent of compiling the app from the github repository. Maybe they could get that version to F-Droid?

**Comment by mvdan** [comment]
By all means the app can be included if it meets the inclusion policy, which basically is no non-free software.

**Comment by h-2** [comment]
I am confused, they publicly said they have a version that works without Play. Is this rue or not?

**Comment by someoneEsle** [comment]
They do have that version, it's published regularly on their website. But so far they aren't putting it on f-droid

**Comment by MoSal** [comment]
@someoneEsle 

https://github.com/wireapp/wire-android/blob/e5f08bbc9c00d9446ce1086f8992d7fe82d9ad5d/build.gradle#L120-L124

Are you sure they publish a build that does not depend on the Google Play Services **library**. 
Where is that build?"

**Comment by someoneEsle** [comment]
It's here: https://wire.com/download/
If you download the APK, that should be the version that doesn't rely on Google-proprietary libraries. At least this is what I've always thought given their tweets

**Comment by mvdan** [comment]
Let's focus on source code. Unless you can find source code that builds without play-services, talking about apks is going nowhere.

**Comment by MoSal** [comment]
@mvdan  Agreed.

@someoneEsle 
Google Play Services are not disabled in that build. 
You can see for yourself:
```
mkdir test_wire
cd test_wire
wget https://wire-app.wire.com/android/prod/wire-2.16.282.apk
unzip wire-2.16.282.apk
dexdump classes.dex -h | grep gms | less
```

**Comment by someoneEsle** [comment]
This is why I said that: https://twitter.com/wire/status/775616447976529920

**Comment by treba123** [comment]
If wire works with [microG](https://microg.org/), wouldn't that be enough for inclusion in fdroid (with a big warning that one needs a gcm implementation)?

**Comment by mvdan** [comment]
For that to be true, someone would have to patch and maintain a fork of the wire client with those.

**Comment by someoneEsle** [comment]
Why do you need a gcm implementation? The latest version should use websockets for notifications

**Comment by est31** [comment]
It still lists gcm as dependency: https://github.com/wireapp/wire-android/blob/master/build.gradle#L122

**Comment by h-2** [comment]
> This is why I said that: https://twitter.com/wire/status/775616447976529920

Yeah, I asked in that thread, too, no answer :(

Can someone official please clarify if the websocket version requires non-free build dependencies or whether they were just included to give the option of using GCM? If the latter is the case, shouldn't it be trivial to add a  build flag for a completely free build?

**Comment by hakonbo** [comment]
Hi all,

sorry for slow response. I'll try to address the issues mentioned here.

The APK available to download from our web page is the exact same version as we release through Google Play Store. This direct download is there for people who for some reason are unable to access Google Play Store.

We do use Google Play Services in our app. This is used for GCM and for sending location messages. If your device doesn't have Google Play Services installed/available for Wire, Wire will still work, but GCM and sending location messages will not. We detect this and have a fallback solution using a websocket, so you will still receive notifications when receiving messages. This solution is most likely not as battery friendly as GCM though.

So for the original question, publishing Wire on F-Droid. At the moment we don't comply with the inclusion policy, as there are some dependencies that are not open source. We are certainly interested in getting Wire on F-Droid, but for the time being it will not happen. 

It is on our (ever growing) TODO list and we will revisit this in the future.

Thank you all for your valuable input!

**Comment by sxiii** [comment]
I would be super-happy if you manage to make clean app version that will work okay. I am ready to compile it myself if needed :)

**Comment by leedoyle** [comment]
Any progress so far?

**Comment by Soundtoxin** [comment]
Still wanting this.

**Comment by nextgenthemes** [comment]
Question: If GCM is used how does the simple in browser app work without it then? Why can't it at least be a option?

Things like this really piss me off. Doing a App that actually competes with Signal and others and offers more features and yes again fucking Google play BS. The "security" of any app pretty much is thrown overboard by using Google servives. I use copperhead OS that comes without any Google Play and I do not plan to install them (and yes I know there are just empty messages send thought GCM) or

**Comment by hex-m** [comment]
@nextgenthemes: this issue was closed by @hakonbo because he says Wire does have a fallback that is used on devices without play services. You may just want to try and install Wire on your device.

The f-droid/free software issue is continued here: https://github.com/wireapp/wire-android/issues/233

**Comment by nenadandric** [comment]
+1 for F-Droid app. It is the only thing left to be done in order to use Android without Play Store

**Comment by fungs** [comment]
Maybe, if you (Wire team) would embrace the technical community a little more, you would get help with some of the things which are important to the community but seemingly low priority to you.

BTW @hakonbo : There is a fallback for message push notification without GCM but apparently not for location services. To send someone a location, I open a navigation app and share the location from there. That's sad. How difficult can it be to obtain a location from the device without relying on Google?

**Comment by eighthave** [comment]
@fungs since you don't find it difficult to do, it sounds like you're the best candidate to do the work :slightly_smiling_face:

**Comment by fungs** [comment]
@eighthave I would but I'm not a mobile dev. I would allocate other resources if necessary. It's all about lowering the barriers for participation, apparently just opening the source code is not enough. But this is not a discussion board...

**Comment by trymeouteh** [comment]
Is this still in the works! I want to use Wire on my LineageOS devices.

**Comment by barkingbandicoot** [comment]
> Is this still in the works! I want to use Wire on my LineageOS devices.

Yes, me also. It does work well in Havoc os though! 🤷
In Lineage for microg, if you disable mircog it works. Not a solution though.
It seems that with microg in LOS it reads the GCM replacement of microg, drops the fall back "Maintain connection to server" toggle in settings, but cannot utilise the GCM replacement of microg!

**Comment by JonasDralle** [comment]
Android (AOSP) can provide location via [LocationProvider](https://developer.android.com/reference/android/location/LocationProvider). It works okay for navigation.
It's not as well-engineered as the properitary google [FusedLocationProvider](https://developers.google.com/location-context/fused-location-provider/) which also uses cell tower triangulation and properitary google data in order to make good guesses.
Google has an interest in making their APIs better than the open source APIs and they can't be blamed for that.

Current best practice is to use the most suitable provider available on the device. Using the open source Location provider as a fallover guarantees that location will work on _any_ device. When the user has the google location API installed that will be used, if not then the open source location will be used.
I never had trouble with this approach on my LineageOS devices. I also tested this on phones with google APIs.

Notice: it's annoying to use different APIs for the same task. The location API is not the only one which is affected by the API policy of Google. I recommend using a library which acts as an abstraction layer for the various APIs. There are already ready-to-use wrapper librarys out there.

Summary:
The Location API is not really a hindrance. I solved this sufficiently for my use case within an afternoon. [This book](https://commonsware.com/Android/) has an excellent chapter on location API.
<sub>Disclosure: I am not affiliated with the authors or distributors of "The Busy Coder's Guide to Android Development" in any way. I have bought and read it and it's _really_ good.</sub>

**Comment by EdaNano** [comment]
Hi, anyone knows why this issue is closed? I thought that it was on the TODO list (see official comment up https://github.com/wireapp/wire-android/issues/5#issuecomment-251411885).

Is this still the case?

**Comment by pepper-jk** [comment]
> Hi, anyone knows why this issue is closed?

Some maintainers close issue to keep the bug tracker "clean", which kinda defeats the purpose of a bug tracker imho. Since there was no official response to why they closed the issue, I'm assuming that is the case.

However they left the ["new" issue regarding this topic](https://github.com/wireapp/wire-android/issues/233#issuecomment-253722552) open.

**Comment by EdaNano** [comment]
Oh thanks for the new issue link, I missed it :)

> However they left the ["new" issue regarding this topic](https://github.com/wireapp/wire-android/issues/233#issuecomment-253722552) open.

**Comment by makingthematrix** [comment]
We're trying to clean up our GitHub issues a bit. This one will stay closed. Please see https://github.com/wireapp/wire-android/issues/1903 for discussion.
However, I can already tell you that currently we have no plans to remove FCM.
