### ISSUE TITLE
Error in the Polish translation of the registration form.

### ISSUE THREAD

**Issue by makingthematrix** [wireapp/wire-android#516]
There is no "Issues" tab in wire-android-translations, so I decided to create the issue here. 

In the registration form, where the user is supposed to type in her name, the Polish translation says "Should we call you?" ("Czy powinniśmy do Ciebie zadzwonić?"), instead of "How should we call you?". Probably the first word went missing and that changed the meaning of the whole sentence before it was translated. It's nothing big, but it's almost the first thing the user see when she starts to use Wire. My friend was very confused when she read that. 

The proper translation should be something like "Jak się nazywasz?" ("What's your name?") or "Jak mamy Cię nazywać?" ("How should we call you?" literally).

**Comment by mykola-mokhnach** [comment]
Thanks for the report @makingthematrix 

It would be better if you report translation issues directly into Crowdin. There is such possibility. Please see the screenhot for more details:
<img width="958" alt="crowdin_issues" src="https://cloud.githubusercontent.com/assets/7767781/22173615/22378846-dfc9-11e6-8751-d66a3bddcde1.png">

**Comment by makingthematrix** [comment]
Hi Mykola,

I went to https://crowdin.com/project/wire-android/pl# . It asks me to join the translators team before I can do anything else. I have sent the request to join the team, but maybe there's another way to get to that page from the screenshot?

**Comment by mykola-mokhnach** [comment]
Accepted your request. Enjoy :)

**Comment by makingthematrix** [comment]
Ok, thank you :)
