### ISSUE TITLE
Thousands of notifications during video/audio call

### ISSUE THREAD

**Issue by FSMaxB** [wireapp/wire-android#517]
During a video/audio call, wire's ongoing call notification is spawned many times per second, if not hundreds. Usually you don't notice it because it just looks like one static notification in the UI. But I have run into problems with two things:

1. I am using a pebble Smartwatch with [Gadgetbridge](https://github.com/Freeyourgadget/Gadgetbridge) and during a call with Wire, my pebble starts constantly receiving new notifications and vibrating and after some time even the OS crashes in a way that I have to reflash the firmware.
2. When recording notifications with a notification recorder app, the log get's spammed with thousands of notifications from wire.

This doesn't happen with persistent notifications from other apps. Unfortunately I don't really know how Android's notification system works, but it seems like there is a way to do it properly because other apps manage to make it work.

I would be really grateful if you could fix this behavior. I think it also decreases battery life during calls.

This happened to me on Android 5 and 7.

**Comment by makingthematrix** [comment]
I guess this was fixed a long time ago? If the problem occurs again, please reopen the ticket.
