### ISSUE TITLE
(randomly) Can't open wire over notification / wire crash

### ISSUE THREAD

**Issue by peterpanondrugs** [wireapp/wire-android#520]
- receive a notification 
- power on screen and click the notifaction (to switch to wire)
- sometimes wire gets stuck in the background without seeing contacts for +-1min and wire gets sometimes closed alone or when i press the back button, wire crashes. 

This happenz quite often! 

[wire_debug_report_not2.txt](https://github.com/wireapp/wire-android/files/722297/wire_debug_report_not2.txt)

[crash_after_notif.txt](https://github.com/wireapp/wire-android/files/722290/crash_after_notif.txt)
see debug log please

**Comment by makingthematrix** [comment]
I think we can safely close this issue already ;)
