### ISSUE TITLE
Call unreliable / Call is stuck in the "joining" - iOS problem too?

### ISSUE THREAD

**Issue by peterpanondrugs** [wireapp/wire-android#521]
- Try to call a friend
- Both sides accept
- wire gets get stuck in the "joining" and closes after not building up the conversation.
- No matter who is gonna recall or how often, the call will not start! 

 Special Case for iOS user: 
- same problem as described 
- Solution: but if he closes the ios wire app (Long press home button, and remove apps from recents) and a call is initiated again (no matter which side recalls) all works immediately!

[wire_debug_report_nocall.txt](https://github.com/wireapp/wire-android/files/722296/wire_debug_report_nocall.txt)

**Comment by someoneEsle** [comment]
Can you provide more details as to whether you/your friend(s) are on wifi or mobile data?
I've experienced similar issues only when one of the people in the conversation was on a wifi that had a firewall (like with my university's wifi).

**Comment by peterpanondrugs** [comment]
One example from yesterday.
- ios version and me logged into same wifi <-- **not working**, even after we tried each combination with 3G. After we went out and returned it worked again? Maybe server problems?
We would have loved to send a debug log, but there was another problem i opened an issue for. See: https://github.com/wireapp/wire-ios/issues/609
I experienced this btw also with android to android. Even after "force close" wire several times. No chance to get him on the line, no matter who calls. After a time its working then again!?
All wifi calls are not blocked by special firewalls. I think all may have an inbuild router firewall?
Can you tell me which ports are used?

**Comment by jspittka** [comment]
Thanks for reporting. We are aware of the issue and work on a fix.

**Comment by peterpanondrugs** [comment]
Btw, this bug occurs in Audio and Video Call.

**Comment by makingthematrix** [comment]
Okay, I guess I can safely close this bug :)
