### ISSUE TITLE
Remove device nonfunctional

### ISSUE THREAD

**Issue by fortran77** [wireapp/wire-android#522]
Android 7.1.1, Wire app 2.25.305, when I go to the Devices menu, tap on a specific device (which in this case is Chrome), and then tap on Remove device, I am prompted for a password. When I enter my password and tap on OK, nothing happens. I'm reasonably sure I am entering the correct password (I am using a password manager). In any case I would expect a positive or negative response, not lack of any response.

**Comment by xuanzhaopeng** [comment]
He @fortran77 , thanks for your report. I guess in fact the device (in your case is Chrome) is removed from the device list. So if I understand correctly, the thing you expect is a popup or any information that let clients know the device is deleted successfully. 

That would be a nice improvement, I will follow on it.

**Comment by fortran77** [comment]
To clarify further:

After I enter my password into the small window that asks for the password, and tap on the OK button, the entire screen remains unchanged. The window with the password prompt remains in place, and the password prompt remains on the screen. If I press Cancel, and then look around, I see no change in the listed devices, i.e., the device I was trying to remove is still in the list.

I would have expected the window with the password prompt to have vanished from the screen as soon as I had entered the password and tapped on OK.

**Comment by fortran77** [comment]
Additional information: I tried again, and the same thing happened several times, i.e., nothing happened.

Each time, I was pasting the password with a long press.

Then I did something different. I first tapped in the password field and then pasted the password. This time the window vanished and the device was deleted.

I have encountered similar behavior in other applications and on various websites, where the code processes typed and pasted data differently.

**Comment by fortran77** [comment]
On further testing, it's not reproducible.

Sometimes, tapping in the password field and then pasting the password works correctly, the password window vanishes, and the device is deleted.

Sometimes, after tapping in the password field and then pasting the password, nothing happens.

And sometimes, after I paste the password and nothing happens, and I tap on Cancel, and then try to delete the device again, I get the Android message saying the Wire app has stopped.

**Comment by bjoernherbig** [comment]
Thanks for all the additional info. We will monitor this and reopen if it pops up again.
