### ISSUE TITLE
Input window is too small

### ISSUE THREAD

**Issue by fortran77** [wireapp/wire-android#523]
On my Nexus 6P (Android 7.1.1, Wire 2.25.305), the input window is about three lines high. This is a bit too small. Scrolling this tiny window up or down with a finger, to see the entire text before sending it, is hard.

Even on a Nexus 9, which has a bigger screen, the input window is still only three lines high.

I see that WhatsApp on a Nexus 6P screen uses an input window that is five lines high. This seems about right to me.

Suggestions, in order of increasing development effort. Item 1 should be considered now, 2 later, 3 even later when time permits.

1. The input window should be increased to five lines. This should be suitable for most small screens.
2. The input window should be automatically larger on devices with larger screens.
3. It should be possible to optionally switch between the normal input window and an expanded input window that fills the screen.

**Comment by bjoernherbig** [comment]
Thanks for the feedback and suggestions. We are considering changes for this. No timeline to share yetthough

**Comment by Gardosen** [comment]
this was changed some time ago to a max increase heigth of 5 lines depending on the resolution of the device.
i close this ticket as solved

Kind regards
Marco from the Android Team
