### ISSUE TITLE
Nothing happens when sharing picture in expiring mode

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#544]
1. double tap the hourglass to turn on expiring messages
2. tap the camera icon
3. tap the bottom right icon to open the files explorer
4. choose a picture to send, tap on it
5. ?? Nothing happens. Would expect to see a preview with the sketching options

Note that if at step 2 I select a picture without opening the files explorer, things work as expected.
log: 
[wire_debug_report.txt](https://github.com/wireapp/wire-android/files/737095/wire_debug_report.txt)

**Comment by deanrobertcook** [comment]
Can no longer reproduce
