### ISSUE TITLE
The screen doesn't turn off by itself after showing an incoming call

### ISSUE THREAD

**Issue by MakisH** [wireapp/wire-android#545]
How to reproduce:
1. Alice video-calls Bob. Bob has two devices, a Wire-Web (Firefox/Linux) and a Wire-Android (Motorola Moto G 4G, Android 5.1, Wire 2.26.209).
2. Bob gets notified in both his devices.
3. Bob answers the call from the Web app, they talk and he ends the call.
4. The notification on Bob's phone goes away but his screen never turns off (he needs to turn it off manually).

Maybe related to #287, which is reported as fixed.

**Comment by xuanzhaopeng** [comment]
Hey @MakisH , do u still suffer this issue?  

Thanks

**Comment by MakisH** [comment]
Looks (almost completely) fixed!

1. After answering an audio call from the web, the screen of the phone goes off as expected. After ending the audio call, the screen remains off.
2. **But:** After answering a video call from the web, the screen of the phone initially goes off (as expected), **while after ending the video call, the phone screen gets activated for a few seconds (without any notification) and THEN goes off.**

Not exactly the same bug, but also not really an expected behavior. In all the cases, the phone remains untouched and all the operations happen through the web app.

Wire-Android version: 2.27.314.
Wire-Wed version:  2017-02-17.

**Comment by MakisH** [comment]
I just tried again today, it looks fixed now.
