### ISSUE TITLE
Add ability to export conversations

### ISSUE THREAD

**Issue by Bugsbane** [wireapp/wire-android#546]
Hi there,
Given that you (wisely) have chosen to limit how long you store user data for, and given that I manage to lose my phone with alarming regularity, I'm nervous about losing all of my conversations as currently, as far as I can see, they're only saved locally on my device (and the devices of the people chatted with).

So it would be great if you could add the ability to backup conversations, preferably in an encrypted manner, so I could restore them after replacing my phone. Ideally there would be a "backup to cloud" option that let me use WebDAV to backup to my Nextcloud, but even just a manual option to export a file with all conversations would make a huge difference.

**Comment by ruppalsingh** [comment]
This is also one of my main considerations while seeking to move away from alternate IMs. I flash my phone frequently and would love to have export/import options between installs/flashes.

**Comment by ImAnnoying2** [comment]
This has been fixed? Though apparently you can only restore backups made on the same platform, meaning if you backup your chat on Android, you can't restore it on Web or iOS...
