### ISSUE TITLE
Ping button is easily clicked 

### ISSUE THREAD

**Issue by GopianiS** [wireapp/wire-android#562]
I've noticed that the ping button is easily clicked when I go to click on the input box in chat and thus annoying people. Would it be possible to move it to a more out of the way location?

**Comment by radiohe4d** [comment]
i have found the same issue happens me too using the android app.

**Comment by someoneEsle** [comment]
duplicate of #484

**Comment by GopianiS** [comment]
Oh sorry. That's good to hear that I'm not the only one anyway!
