### ISSUE TITLE
Keyboard not working properly after video call

### ISSUE THREAD

**Issue by peterpanondrugs** [wireapp/wire-android#566]
Hi folks,

- start a video call
- end it
- type to the same person immediately after video call.
- keyboard is accepting letters, but doesnt show them in the preview window

Solution:
- leave conversation
- join conversation and type smth...

[wire_debug_report_video.txt](https://github.com/wireapp/wire-android/files/749684/wire_debug_report_video.txt)

**Comment by makingthematrix** [comment]
A lot of this code was rewritten and I didn't experience (nor can reproduce) this bug for a long time. I'll close the ticket. Please reopen if it happens again.
