### ISSUE TITLE
Error:Failed to open zip file.

### ISSUE THREAD

**Issue by khoydesign** [wireapp/wire-android#569]
Pleas Help 

`
Error:Failed to open zip file.
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)
Re-download dependencies and sync project (requires network)

`

![sdd](https://cloud.githubusercontent.com/assets/17418538/22587270/e39a9b7c-e9b5-11e6-976d-944217fe7277.png)
![sddu](https://cloud.githubusercontent.com/assets/17418538/22587399/5a7d7d40-e9b6-11e6-9dc5-b9cf29fa5add.png)

**Comment by hub-ch-NetE1** [comment]
Hello,
@khoydesign You can try with latest wire release and follow instruction here https://github.com/wireapp/wire-android/issues/1892 for avoid avs bug.

That's bit out of scope but expect helpful, you need to have proper internet connection first as you may able download any common software, video via web browser without interrupt same as wire require download necessary files through studio as default way for begin build 
and make sure you have configured firewall properly also your PC security solution's HIPS, containment components etc doesnt prevent android studio related processes and access to required files.

**Comment by marcoconti83** [comment]
Hi @khoydesign ,
Please try again with the latest code. It has been a while since you opened this issue and the build process went through many changes. I'm closing this for now, feel free to reopen if this is still an issue.

Thanks @hub-ch-NetE1 for bumping this issue.
