### ISSUE TITLE
Android resend issue

### ISSUE THREAD

**Issue by DOFfactory** [wireapp/wire-android#576]
Hi, love the app. I noticed an interesting behaviour, namely, when I send a message and I lose  WiFi/data connection (i.e. the message have not been sent), after re-connection to any WiFi/Data connection is not resent automatically. Might be a "feature," but would be lovely to have an automatic resend option at least in the Preferences, to get these messages resent by default (if one wishes) as soon as a connection is re-established (often an issue in big cities, e.g. London, etc.)

**Comment by bjoernherbig** [comment]
Thanks for the feedback. We deliberately opted against an automatic resend. The app will try within a timeframe of 30 sec to resend, after that has expires, the message or whatever you were trying to send, will get marked as failed to send. you will, however, have the possibility to resend when tapping on a failed to send indicator.

**Comment by Mladia** [comment]
Most of my messages don't get delivered at all, since my phone doesn't have a strong internet connection almost all the time and much later I see that they need to be resent.
Is there a possibility of having an automatic resend feature as an option in the settings?
