### ISSUE TITLE
Sending message after opening notification doesn't scroll up

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#584]
At this point everyone knows how passionate I am about scrolling issues.
- premise: wire is not open in the background
- receive a notification
- open wire by tapping the notification
- type some message, hit send
- the sent message doesn't cause the conversation to scroll up, so now you can't see what you sent.

Can reproduce consistently on my Nexus 5X, Android 7.1

**Comment by bjoernherbig** [comment]
[https://wearezeta.atlassian.net/browse/AN-4992](url)

**Comment by someoneEsle** [comment]
Just tested #606 and it fixes this.
