### ISSUE TITLE
Color of status bar.

### ISSUE THREAD

**Issue by fablissimo** [wireapp/wire-android#585]
When app is opening a status bar become a yellow. But in settings I made that main color was blue. After hiding and restore app, status bar color become blue. I using Android 5.1.1, FlymeOS.

**Comment by bjoernherbig** [comment]
Hi,

that yellow bar that you are seeing is a no internet or bad connection indicator. It currently is a bit too sensitive, so you might see it a bit too often. We are fixing the currently though.
