### ISSUE TITLE
(force crashed) chat not loading / stuck / won't open

### ISSUE THREAD

**Issue by peterpanondrugs** [wireapp/wire-android#594]
- open wire.
- open specific chat.
- wire stuck / isn't loading the chat. Even if you force.crash wire. And try to open again.

Solution:
- open another chat 1st. Then try again and its opening.

Its reproducible: 
- force crash wire application in a chat. 
- start wire again. try to open again the last chat.
- this chat won't open. 

Dirty Solution see above.

Maybe.related to #595 

[wire_debug_report.txt](https://github.com/wireapp/wire-android/files/768006/wire_debug_report.txt)
 
[wire_debug_report-doesntload.txt](https://github.com/wireapp/wire-android/files/768002/wire_debug_report-doesntload.txt)

**Comment by peterpanondrugs** [comment]
@wire Can u confirm this bug? This is really killing my mood for using wire. If I nonstop have to switch conversations to get the right one working.

**Comment by mykola-mokhnach** [comment]
> force crash wire application in a chat.

How do you force crash? Do you mean force stop the app from Settings?

**Comment by peterpanondrugs** [comment]
Developer Option. To kill the APP with pressing back button for my preset time. But FC is no needed for this bug.

**Comment by avently** [comment]
I already told to Wire support about that. They said it will be fixed. But for now it's not

![screenshot](https://cloud.githubusercontent.com/assets/7953703/24224159/ac280c26-0f6a-11e7-93d8-337abda1b118.png)

**Comment by avently** [comment]
@mykola-mokhnach
What's your thoughts about that? Can you show this issue to developers? I can't believe it doesn't annoy other users including developers.

**Comment by peterpanondrugs** [comment]
Update: - now i encountered for the 1st time, that not only the top chat isn't loading, also another one (in this case 3rd). This is the most annoying bug i've ever seen in an app!
[wire_debug_report_nochat.txt](https://github.com/wireapp/wire-android/files/891671/wire_debug_report_nochat.txt)
