### ISSUE TITLE
mobile data saving

### ISSUE THREAD

**Issue by azlux** [wireapp/wire-android#596]
Hi all.
Do there are in the roadmap the option to save mobile data.
Option to not dowload image and/or gif if not on wifi ?

Thanks,
Az

**Comment by mykola-mokhnach** [comment]
There is a setting called "Download Pictures" in Options->Media. You can select either to download images only if Wi-Fi connection is available or for all types of mobile networks.

**Comment by azlux** [comment]
hops. didn't see the button. thank
