### ISSUE TITLE
Notification on delivery failure is empty

### ISSUE THREAD

**Issue by sokke90** [wireapp/wire-android#605]
If a message sending fails when the wire app is closed, I get an empty notification which only shows my name. When clicking on it, wire goes to the correct message stream, so I can see that the message sending failed. But the notification is still quite confusing.

Anyone else having this issue?

**Comment by someoneEsle** [comment]
Yes, I have the same issue. The empty notification needs to contain a more useful message

**Comment by xuanzhaopeng** [comment]
JIRA https://wearezeta.atlassian.net/browse/AN-5035

**Comment by hub-ch** [comment]
https://github.com/wireapp/wire-android/issues/777#issuecomment-466763316

**Comment by makingthematrix** [comment]
I think I can safely close this issue now. Problems with notifications happen but I wasn't able to reproduce this one.
