### ISSUE TITLE
Working account reset with mandatory phone and email registration

### ISSUE THREAD

**Issue by wireusr** [wireapp/wire-android#610]
I’ve been using wireapp on my mobile for about a month (it’s worth noting that I registered it with my everyday phone number when I was signing up). Few days ago all of the sudden my account was reset by itself (for no reason) and I needed to get code again to activate it and after that I was forced to register my email as well (there was no way to skip it). So why wireapp reset my account and ask me to do it all over again ? I’m using wireapp 2.27.314 installed through google play.

**Comment by bjoernherbig** [comment]
We are working on a fix for the logout issue, stay tuned on that one. The email page you're seeing is being worked on in #607
