### ISSUE TITLE
Chat window remains static after sending message

### ISSUE THREAD

**Issue by SuperHaze** [wireapp/wire-android#611]
Issue on Wire for Android (Wire 2.27.314)

After typing a message to a contact and hitting send, the message is sent however the chat window does not automatically scroll down.  You have to manually 'tap' the chat window and scroll yourself. (Using AOSP keyboard)

On a somewhat related note, please remove the bar (the one showing the ping, camera icon, squiggle, etc) under the 'type a message' box until AFTER someone has already clicked on the 'type a message' box.  Having it show up there before a keyboard even is visible just causes accidental clicks or pings when attempting to bring up the keyboard.

**Comment by bjoernherbig** [comment]
please check if you opened the conversation from a notification directly. if so, this is likely fixed in #606 

regarding the conversation options we are planning some optimization of the UI soon.
