### ISSUE TITLE
To save received photos it needs to be done twice

### ISSUE THREAD

**Issue by wireusr** [wireapp/wire-android#614]
Approximately once out of 10 times picture will be saved into gallery in first attempt, most of the time it takes 2 attempts. The notification “saved” message only shows on second attempt (strangely, sometimes, for some reason I have same photo duplicated in gallery).

**Comment by someoneEsle** [comment]
related to #291

**Comment by xuanzhaopeng** [comment]
Related ticket : https://wearezeta.atlassian.net/browse/AN-5034

**Comment by makingthematrix** [comment]
I think we can safely clsoe this ticket :) Please reopen if the problem still occurs.
