### ISSUE TITLE
Make it possible to disable message popups

### ISSUE THREAD

**Issue by thenktor** [wireapp/wire-android#615]
Hi,

Wire shows message popup bubbles on new messages. Please make it possible to disable them. For me they are annoying and not helpful.

Thank you

**Comment by someoneEsle** [comment]
You're talking about the popup in the top left corner when you're already within the app, right? I have to say I'm with you on this one. I mainly see two problems:
1. the bubble is too small anyway, so it's not *that* useful;
2. sometimes when I open Wire that small bubble pops up, even though I've already read everything.

Removing the bubble altogether doesn't sound too bad to me. But at the same time, I like the idea of having an in-app notification popup of some sort, maybe something that is more useful than the current cant-see-any-of-the-content-anyway popup

**Comment by thenktor** [comment]
Yes, exactly. Especially point 2 is annoying. And to be honest: I've never missed such in app notifications in other messengers.

**Comment by someoneEsle** [comment]
Looks like they're going to disappear :) https://github.com/wireapp/wire-android/commit/80e5fe1cf03b9aecf45d1ca940d6ac689d3ec1f4

**Comment by bjoernherbig** [comment]
notification bubbles will get removed with #647
