### ISSUE TITLE
Security enthusiast claims Wire isn't secure and that end-to-end encryption can be intercepted

### ISSUE THREAD

**Issue by notnsane** [wireapp/wire-android#617]
I'm not going to claim that I know the slightest about security, but I'm going to leave these links here so the community and developers can review them:

* https://medium.com/@pepelephew/how-to-intercept-all-wire-voice-and-video-calls-13da1246675c#.fmyybvcn6
* https://medium.com/@pepelephew/wires-certificate-validation-vulnerability-f2b415298e2e#.vsdmp5eo5

The whole point is getting the community involved. I did a couple searches and didn't found anything related to these articles.

Also, I don't know if this repo is the best one to publish this, but I chosen this one becase the wire (core?) repository has only 1 issue. Excuse me if I made any mistake.

**Comment by darkbluelight** [comment]
Wire's advertised security is a huge, essential selling point for users like me. If these linked concerns hold true, this is a massive problem that needs urgently fixed.

**Comment by someoneEsle** [comment]
While you wait for an official reply from one of the developers, you may as well know that pepe_le_phew is an internet troll who has been spreading intentionally misleading rumors about Wire and its security. Wire's protocol implementation has been reviewed by a real company, people with a much better credibility than some internet troll: https://medium.com/wire-news/wires-independent-security-review-61f37a1762a8#.6edc257or

As for the bug regarding certificate pinning it's already been fixed, and authenticated calls should be on their way very soon since (if I remember well) they are being heavily tested by the team.

**Comment by raphaelrobert** [comment]
Hi @notnsane,

As @someoneEsle mentined, some misleading blog posts were written about Wire's security and were quickly debunked by the community (https://twitter.com/tqbf/status/830126993156997120).

Wire addressed the calling:
https://medium.com/@wireapp/we-have-always-been-open-about-how-end-to-end-calling-on-wire-works-70b6a6f03cae

The code for the pinning on Android was fixed days before the blogpost:
https://github.com/wireapp/wire-android-sync-engine/pull/47

To be clear about the pinning: It was never possible to perform a MITM attack with self-signed certificates. The threat model in the blogpost is quite misleading.

**Comment by darkbluelight** [comment]
@someoneEsle It's very nice to see that Wire had its Proteus **messaging** protocol implementation reviewed by Kudelski Security and X41D-Sec but they didn't review audio and video calls (yet).

You mentioned a wider review of the code that is coming, I'm very much looking forward to it. @raphaelrobert good to see that a new improved version of calling is coming and the code for the pinning was fixed.

I also can't wait for the server code to be released (end Q1 2017), this will be a big advantage over Signal etc.

**Comment by notnsane** [comment]
Awesome! Thanks to all who contributed to this thread 😃 It will help a lot to clarify Wire's security in the future. I'm going to close it this issue.

**Comment by jawz101** [comment]
It's odd you all are calling someone a troll while claiming fixes for the security issues you say he cited were either fixed within days of an article or say are about to be fixed.

That's like quitting a 10 year drug habit yesterday and claiming you are drug free today... except for the paint you're still huffing, that is.

I just saw a link to this post on Reddit and it reads like you all use the words "myth" and "debunked" incorrectly.

**Comment by teller** [comment]
@jawz101 Troll in the sense that their Twitter and Medium have been set up with a singular goal of attacking Wire. They did not disclose discovered bug in a responsible manner that is the norm in the infosec community, instead made it public without prior warning (we got the fix live in 8 days).
