### ISSUE TITLE
UX: Text dissapears from login form when you switch apps

### ISSUE THREAD

**Issue by davidak** [wireapp/wire-android#635]
I installed the APK and tried to login with my account.

Because i have very long e-mail address and password, i copy them from my password manager (like you should do).

When i switch the app again and came back to Wire, the login form was empty. I was not able to fill in both fields.

### expected behaviour

text stays in form fields when you switch apps

### video

https://youtu.be/ycvp-baQBdY

---

Fairphone 2 with Open OS
latest Wire APK (downloaded today)

**Comment by ImAnnoying2** [comment]
Isn't this fixed?

**Comment by makingthematrix** [comment]
This was fixed at some point in the past :)
