### ISSUE TITLE
Huawei/Honor EMUI: notification LED not working

### ISSUE THREAD

**Issue by thenktor** [wireapp/wire-android#636]
Hi,

on Huawei EMUI 4.1 & 5 the notification LED does not work. New messages only appear in the Android status bar, but no LED blinking. Tested on Huawei Honor 8.

**Comment by ElvisPresly** [comment]
Xiaomi mi5s
LED a bulb, shines sometimes white, sometimes blue. In settings of an operating system blue is set.
Make setup in application, a choice of color of notification messages.
