### ISSUE TITLE
Weird visual glitch in collections

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#638]
Android 7.1, Nexus 5X
- open collections
- open a picture, zoom in
- switch to a different app
- switch back to wire
- visual glitches don't go away until you hit back (also, it's impossible to swipe left or right)

**Comment by red-avtovo** [comment]
Approved. Have the similar behavior on 7.0 Nexus 5X

**Comment by makingthematrix** [comment]
I think I can safely clsoe it now. The functionality was rewritten. I can't reproduce the bug.
