### ISSUE TITLE
Timed pictures sent from iOS phone

### ISSUE THREAD

**Issue by Zahlentheorie** [wireapp/wire-android#644]
I [Android 6.0] often haven't received timed pictures [1 day] sent from an iPhone [iOS >= 9] but my other phone [iOS 9.3.5] does. Every phone has been updated to the newest version of Wire. Sometimes it's really annoying because the pictures included important information. Is it a known bug?

**Comment by kozality** [comment]
I'm seeing something similar, only between two Android phones. Timed photos show up blank. Turning off the timed destruction seemed to solve the problem. Versions are 2.27.314 for sender and receiver.

**Comment by red-avtovo** [comment]
Tested between iPhone 6, wire app 2.30 (2780) and Galaxy S6, Android 6.0.1, wire app 2.27.314
Everything works fine for me

**Comment by red-avtovo** [comment]
@Zahlentheorie what phone model do you have? Is it still reproducible on the latest 2.28 app version?

**Comment by Zahlentheorie** [comment]
Yes, it is still happening on my Sony Xperia XA, and also on the phones of my friends, Moto G3, Samsung S4, etc. – but not constantly – when people are sending us timed pictures from their iPhones [>= 6]. We all have updated Wire to the newest version. Side note: Yesterday it happened twice on my phone.

**Comment by mykola-mokhnach** [comment]
Can it be the issue happens in mobile network only and is not reproducible on WiFi or it does not matter?

**Comment by Zahlentheorie** [comment]
It happens on both, WiFi and mobile network. I'm on WiFi most of the time.

**Comment by mykola-mokhnach** [comment]
We still cannot reproduce the issue :( 
@Zahlentheorie Could you please attach the logcat output to this ticket when the described issue happens again?

**Comment by Zahlentheorie** [comment]
Yes, sure. To be sure, which steps do I have to do when this is happening?

**Comment by Zahlentheorie** [comment]
Yes, of course. To be sure, what steps are required when this happens again?

**Comment by mykola-mokhnach** [comment]
First make sure your phone has [developer mode](http://www.greenbot.com/article/2457986/how-to-enable-developer-options-on-your-android-phone-or-tablet.html) enabled.
Then download and install Android SDK on you computer and save the log using the _adb logcat_ [utility](http://stackoverflow.com/questions/2882253/how-do-i-get-the-logfile-from-an-android-device). You might also consider to [set larger buffer size](http://stackoverflow.com/questions/6321555/what-is-the-size-limit-for-logcat-and-how-to-change-its-capacity) for logs in Developer options to make sure nothing important has been rolled out.

**Comment by makingthematrix** [comment]
Both assets and ephemeral messages functionality was rewritten since this ticket was opened. I can't reproduce the bug. I'll close the ticket now. Please reopen if the problem is still occurring.
