### ISSUE TITLE
Messages delayed or not recieved when device is in Power Saving

### ISSUE THREAD

**Issue by kozality** [wireapp/wire-android#646]
I've been having a lot of intermittent performance with messages not being received or sent when I've had Power Saving mode activated. Friends will not get my messages, and I will go long periods without notifications of messages sent to me.

I started to suspect if Power Saving was influencing this. And I read this:
https://developer.android.com/training/monitoring-device-state/doze-standby.html

If Wire is not using FCM, is it possible that some of the network delay issues being seen are a result of users having Power Saving enabled?

https://developer.android.com/training/monitoring-device-state/doze-standby.html#using_fcm

**Comment by someoneEsle** [comment]
Also see #254

**Comment by hub-ch** [comment]
https://github.com/wireapp/wire-android/issues/777#issuecomment-466763316

**Comment by marcoconti83** [comment]
Hi all,
there are a lot of duplicated issues covering this same problem (or a very similar one), let's unify all conversations and keep it going here: #777 . Closing this one and continuing there.
