### ISSUE TITLE
Changed E-Mail does not show up in Settings

### ISSUE THREAD

**Issue by Parthenos** [wireapp/wire-android#652]
I recently changed my e-mail adress but it does not show up in the settings in the mobile app or the browser or the desktop client.

**Comment by mykola-mokhnach** [comment]
which client did you use to change the email? did you verified the new email address?

**Comment by Parthenos** [comment]
I used the Android app. Yes, I verified the new address. I also cleared app data and cache but it still shows the old email

**Comment by mykola-mokhnach** [comment]
Is the old email address still active? Which one works if you, for example, want to reset your password?

**Comment by Parthenos** [comment]
Yes the old address is still active.
I'd rather not reset my password but I can use both email addresses to log in.

**Comment by mykola-mokhnach** [comment]
Something is not OK there for sure. Can you please contact our [customer support](https://support.wire.com/hc/en-us/requests/new) and provide more details on your registration, like email addresses. We'll try to investigate the problem together with the backend team.

@david-wire FYI
