### ISSUE TITLE
Full screen image rotation is broken

### ISSUE THREAD

**Issue by RebelCoderRU** [wireapp/wire-android#658]
Steps to reproduce:

1) Tap on the image you sent/received
2) Select arrow icon to  make it full screen
3) Rotate to landscape view

Image does not rotate and we see black blinking screen.

Device: Samsung Galaxy A9 Pro
Android: 6.0.1

**Comment by RebelCoderRU** [comment]
But still exists in the latest update.

**Comment by makingthematrix** [comment]
This functionality was much changed since 2017. I think I can safely close this bug.
