### ISSUE TITLE
Visual glitch when opening the app from background

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#659]
I have had this issue since day 1 on wire, but never opened an issue about this because I guess I got used to it with time.
Android 7.1, Nexus 5X.
- open wire
- tap button to switch apps --> transition isn't smooth, there is a visual glitch
- switch to a different app
- switch to wire again --> transition isn't smooth, there is a visual glitch

I don't know if a debug log would show useful information, but if that's the case I can surely post one. This should be easy to reproduce because it's happened 100% of the time for the last year, despite the fact that I have reinstalled many times. All other apps on my phone do not suffer from this problem.

**Comment by makingthematrix** [comment]
@someoneEsle Do you still see those glitches?
