### ISSUE TITLE
Wire is open twice after "quick-replying"

### ISSUE THREAD

**Issue by Namnodorel** [wireapp/wire-android#664]
Hey,
it's nothing big or anything, but when someone texts me via Wire and I tap the "Reply" button in the notification, after closing the popping up UI (which looks awesome by the way) I can long-press home and now see Wire opened twice, once for the normal app and once for the quick-reply-UI. Again, it's really just a minor issue but worth noting nonetheless ;)

**Comment by someoneEsle** [comment]
What device and OS are you on? Doesn't happen on my Nexus 5X with android 7.1

**Comment by Namnodorel** [comment]
I'm using a Samsung S3 Mini with Android 6 installed (to be exact, it is ResurrectionRemix, but the changes aren't that big), and it was happening on Android 5.1/CyanogenMod, too.

**Comment by selurvedu** [comment]
Same here on Android 6 (LineageOS 13).

**Comment by makingthematrix** [comment]
I think this bug is fixed by now. I'll close the issue.
