### ISSUE TITLE
Network switch during the call is not handeled

### ISSUE THREAD

**Issue by RebelCoderRU** [wireapp/wire-android#665]
Hello.

Wire does not handle network switch on the fly.

Scenario:
1) Use Cell Network to call from Android to Android.
2) During the call, switch on/walk in to the WiFi area, to make your device connect to it
3) After network switch has accrued, it will  cause the call to stay active, still counting the call time, but no data is being sent between callers.

Scenario can be used for both cases Use Cellular network and switch to WiFi, or use WiFi and switch to 4G during the active call.

As an example, Skype handles this good and re-connects with a new IP and continues the Video/Audio call.

Tested on:
Devices: Samsung Galaxy A9 Pro, Galaxy A7.
Android 6.0.1

Thanks.

**Comment by someoneEsle** [comment]
Was going to open a similar issue myself! In my case, after switching from wifi to data during a call, the call just dropped. I think it may be because my phone took too long to reconnect after it lost the wifi connection (?). Happened on a Nexus 5X, Android 7.1

**Comment by bjoernherbig** [comment]
Thank you for reporting. You can expect changes regarding this soon

**Comment by makingthematrix** [comment]
This was fixed at some point in the past. The switching still cause a small glitch but all works now.
