### ISSUE TITLE
No visual indication of an attachment upload

### ISSUE THREAD

**Issue by lightswitchr** [wireapp/wire-android#672]
Android 7.0
Wire 2.28.317

I just uploaded an attachment to a group chat, but there was no visual indication that the file was being sent, or even a progress indicator or a way to cancel it. I ended up sending the file twice because I didn't know if the first one was being sent.

**Comment by red-avtovo** [comment]
Checked that on Google Nexus 5X, Android 7.0, Wire Prod 2.28.317.
Everything worked fine.
Which phone are you using? Have you been connected to WiFi or not?

**Comment by lightswitchr** [comment]
I'm using a OnePlus 3, and I was connected to WiFi at the time.

**Comment by red-avtovo** [comment]
Is it 100% reproducible or happened only once?

**Comment by lightswitchr** [comment]
I've just tried uploading an attachment whilst connected to 4G (I am unable to connect to WiFi currently) and the progress indicator did appear. I will try again on WiFi later and report the results.

**Comment by red-avtovo** [comment]
Checked that with the OnePlus3, Android 7.0.
Everything works fine from WiFi. What kind of file are you sending?

**Comment by bjoernherbig** [comment]
@lightswitchr were you able to reproduce this issue or can we close this

**Comment by bjoernherbig** [comment]
unable to reproduce this. closing it for now
