### ISSUE TITLE
[Feature Request] Option to manually disable sending to individual devices

### ISSUE THREAD

**Issue by FSMaxB** [wireapp/wire-android#68]
This is not specific to wire-android but applies to wire in general.

I'd like to have the possibility to disable sending and receiving messages on a per device basis. So if my contact has more than one device, I want a switch that disables or enables me sending messages to it or receiving messages from it (or if I receive messages from it, highlight that it is not trusted).

It should be quite obvious why this is useful from a security perspective, but here is an example where this could be useful:

Let's say one of my contacts suddenly has a new device and I don't know if it is legitimate. If I accidentally accept the new device, I can only securely communicate through another channel (not wire) until the new device is either deleted by my contact or the fingerprint is verified. I can not do the verification of the new device via Wire because I can't trust any message from my contact because it might come from the new, unverified device.

**Comment by raphaelrobert** [comment]
This is indeed an edge-case our current UX doesn't cater for. We will address this in the future.
