### ISSUE TITLE
Connection interrupts too often

### ISSUE THREAD

**Issue by avently** [wireapp/wire-android#687]
Connection interrupts really many times. I see the yellow line above a chat tens times in a day. I can only restart the app to get it to work. 
I didn't do anything unusual. No audio/video call. Just a text. On wifi, seems like it's stable because i can play games without connection interruptions. 
2.28.317, Android 7.1.1 AOSP.

**Comment by mykola-mokhnach** [comment]
Is it still possible to send/receive messages when the bar is visible? Is the quality of your mobile connection good enough for other apps that use internet connection, for example browser?

**Comment by avently** [comment]
[Screenshots.zip](https://github.com/wireapp/wire-android/files/826004/Screenshots.zip)

**Comment by david-wire** [comment]
Hello, we can keep looking into this and we have something in mind that we can try. 
Could you send us a note here: https://support.wire.com/hc/en-us/requests/new and we will follow up.

**Comment by avently** [comment]
Done

**Comment by sulbig** [comment]
I am having a similar issue. I intermittently see the yellow bar, usually after waking my display to use the app. If I send a message, it's status is 'sending'. If I try to make an audio/video call, a message about "No Internet Connection" pops up. I am on WiFi, and am able to browse the internet and use other internet connected applications (Hangouts, Maps, GMail, Spotifiy, etc) during that same time. I usually navigate back to the main conversation screen, then go back into another conversation, and the yellow bar goes away (or maybe it's just coincidence).

Google Pixel, Android 7.1.2, Wire 2.36.343

**Comment by sulbig** [comment]
Update to my last comment... it appears that pressing the back button to return to the conversations screen, the back button again to leave the app, then re-open the app from launcher will resolve the 'no internet' scenario.
