### ISSUE TITLE
[Feature Request] Cross sign device keys

### ISSUE THREAD

**Issue by FSMaxB** [wireapp/wire-android#69]
A feature request for all wire versions, not only android:

It would be nice if accepting the keys of another device automatically creates a signature with the current device key for the other device. That way you can display to other users that you added the device yourself and verify that it is legitimate.

I don't know if this is possible though, because in your security whitepaper you only mention the use of a Curve25519 key, not an Ed25519.

There are ways to [derive an Ed25519 key from a Curve25519 key](https://github.com/jedisct1/libsodium/issues/335), but it is recommended to use an Ed25519 key as the main device key and sign the Curve25519 key with that. In this case the Ed25519 key can be used to sign the Ed25519 keys of your other devices.

**Comment by raphaelrobert** [comment]
Thanks for the input. For now the verification has to happen manually between all devices. However we are looking to simplify this in the future.
