### ISSUE TITLE
Some problems with audio calls

### ISSUE THREAD

**Issue by avently** [wireapp/wire-android#697]
1. I hear an echo (my voice) while calling someone. 
2. Interlocutor hears my voice after a second or even more. It's not what i want to have. 
3. Calls were dropped at random stages while I walked over the street. I have called many times because of the drops. 
4. Calls were droped when Interlocutor or me tried to answer on a call. Ah, it's so terrible. I couldn't answer on the call because when I pressed on the green button calls were dropped and chat appears. So no way to answer. Sometimes it works fine. Maybe one of five tries. 

I used lte and the quality of the internet was really good. You can say that's related to my connection. But it's not. Whatsapp doesn't have any problems I'm writing here. No problems at all.  Of course I was surprised because I really love Wire and hate WhatsApp. My Interlocutor used wifi with 100Mbit connection and iPhone with latest Wire. I use the latest Wire on AOSP 7.1.1.

**Comment by mykola-mokhnach** [comment]
Hi @avently 

Sorry for the inconveniences. There is a known integration issue on iOS side, that causes call connectivity problems and is going to be fixed very soon in the upcoming iOS release.

**Comment by avently** [comment]
@mykola-mokhnach What call connectivity problems do you mean? 1,2,3,4? Or all?
I looked at the code and found interesting part about "degraded calls". What does it means? As I understand it's type of call when user didn't verify all devices added by receiver, right? If it is a problem will it be fixed now if user will verify all devices?

**Comment by mykola-mokhnach** [comment]
No it's something different. It's an internal iOS problem, that has to be fixed by developers (and it is, actually, fixed, but not deployed to the AppStore yet).

**Comment by mykola-mokhnach** [comment]
A fixed iOS release has been recently deployed to AppStore. Could you please update Wire and check if it works for you?

**Comment by avently** [comment]
No, it doesn't work. Checked yesterday. The release was updated two or three days ago, right? If so, here is the result:
I called to iPhone. When iPhone accept the call my app was crashed. I repeated but connection wasn't established. Then iPhone called to me. After I accepted the call call just disappeared and I saw chat window. 
Sorry for bad news

**Comment by mykola-mokhnach** [comment]
Is the version of iOS build equal to 2.32.2795? If yes then could you please contact our customer support and provide more info about your device and the crash, so we could investigate the problem and make Wire better?
Thanks for you assistance.

@david-wire FYI

**Comment by avently** [comment]
[wire.txt](https://github.com/wireapp/wire-android/files/836488/wire.txt)
This is the log. 
If you have iPhone you can call me and we will see what's happening. I can't ask my friend to do this tests when you want new information. He is not an IT guy. 
P.S. I already wrote a request for the support. Take a look at request number 32457. It's my mail from wire account. You can find me there and write.

**Comment by mykola-mokhnach** [comment]
That's great 👍 . We appreciate your feedback. I'll forward the crash report directly to the developers, so they can have closer look.

**Comment by RebelCoderRU** [comment]
I have to say Audio/Video calls are unusable last 2 weeks or so.

**Comment by avently** [comment]
Strange thing is nobody is trying to fix it. I have followed many repos but there are no commits related to calls. It is one of the main features but we can't use it and nobody cares.

**Comment by licensecart** [comment]
We've still got issues with the calls not sure if it's the MacOS / Windows or iOS versions but neither party can pick up a call.

**Comment by Simplenuity** [comment]
Also Linux and Android versions are affected. I think it was over a week ago that I was able to successfully establish an audio or video call. Meanwhile even messages are not getting delivered and notified reliably anymore :(

Are there some major infrastructure problems going on? Beside the bugs in the clients...

**Comment by avently** [comment]
Today I had been calling to iPhone and sound was amazing. No echoes, no big ping, no problems except one. iPhone can't call me (I didn't see even a message that looks like "user called you"). Once my call wasn't showed on iPhone side (but I'm not 100% sure about that). 
This is really cool. Thank you for that. 
P.S. iPhone app was updated via app store and I have a version from GitHub for Android. 

I think we can close the issue once the other guys will report about their successful situation.

**Comment by mykola-mokhnach** [comment]
Thanks for the feedback @avently . We are working hard to improve calling quality and to make it as secure as possible, so there might be changes in every new release.
