### ISSUE TITLE
Why not add sms?

### ISSUE THREAD

**Issue by Kommynct** [wireapp/wire-android#698]
Currently wire does everything I need, and does it well.

I'd like to replace hangouts on my phone with it for everything, but it's missing SMS, which is a crucial feature for me. Implementation of sms or RCS would make this a gold standard in a chat app as far as i'm concerned, there would be no competition. #92 way back when addressed this, and was a great writeup, but was closed.

Is it really necessary to close the issue, and not leave it open as a possibility? I repost this now because its been 7 months, and the app is pretty rock-solid now.

**Comment by salmonellad** [comment]
Legacy sms texting is tired, outdated, insecure, and needs to be left on an iceflow to die.

😛

XMPP & SIP are here to stay

**Comment by anatoli26** [comment]
Agree with @salmonellad. If you want SMS, just use the default app for that, why to mix it into completely unrelated app (and I had problems with that on Signal when it was sending messages to a Signal contact via SMS)? Wire priority is security and privacy, SMS is just the complete opposite. My last use of SMS was a couple of years ago. You'll probably have to use both whatsapp and wire for some time, before wire gets wide adoption.

Also, don't forget that adding features make a project more complex and this makes it more error-prone. So if something is almost unrelated to a security-related project, I would prefer not adding it for keeping it simple.

**Comment by that1communist** [comment]
While I agree that SMS should die, I think it is irrefutable that SMS and rcs will live on no matter what this project does, as for why insert it into this, I am stuck with insecure apps installed because of wires lack of this feature, and SMS or rcs could be made to be end to end encrypted if wire learns to detect itself. 

And it's also just inconvenient to have multiple messaging apps, I mean yeah there's still development to be done, don't get me wrong, but adding this feature would be very helpful for some people.

**Comment by WildYorkies** [comment]
@that1communist 

> I am stuck with insecure apps installed because of wires lack of this feature

SMS, by definition, is insecure. It's about the protocol, not just the app.

**Comment by nuzzar** [comment]
TBH, I don't care about SMS either. What I want is the ability to block SMS spam number without the need to add it as contact like in signal and opening the damn message. The only good app that do this correctly that I know of is facebook messenger. And I certainly prefer an open source project over facebook to handle my SMS. So it would be a plus for me if wire can handle this as well.

**Comment by darkbluelight** [comment]
Have a look here: https://silence.im/

**Comment by Limero** [comment]
I totally agree that basic SMS support should be implemented. I currently have a regular messages app installed only for verification codes and occasional messages.

Another reason is that it's WAY easier to get new people to replace their regular messages app with Wire than for them to install "just another messaging app". It could also result in projects like CopperheadOS making Wire their default messaging app.

**Comment by Qluxzz** [comment]
Since Hangouts is now removing SMS support I also stand behind this idea. An app that combines both SMS and IMs (like Hangouts did), would be the ultimate messaging app.

**Comment by daebb** [comment]
@Limero Totally agree. While I, personally, like to keep my SMS separated from my messengers, it would be a handy feature to have (of course you should be able to toggle it on and off) and would certainly stand out if it's implemented as intuitive and smooth as the rest of Wire is already.

**Comment by 2114L3** [comment]
while SMS is not secure and is against all that wire as created. it would make it easier to talk family into using wire if it did SMS now that hangouts is giving it the flick. putting SMS would only be to get wire in front of more people. likely the same reason apple and google integrated sms into theirs.

**Comment by makingthematrix** [comment]
I think we can safely close this issue. We don't plan to add sms.
