### ISSUE TITLE
Contextual reply/forward

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-android#704]
Hey guys,

it would be cool to have some kind of contextual reply. Like the telegram app for example does. 

You click on the message you want to reply/forward and after that a new dialog is showing up with the following otions:
-Reply
-Forward
-Cancel (or without it)

After you did choose Reply, the original message is kind of cited (when too long, shortened) above the new text field for typing the reply. When you send your new message: you have the cited block and underneath your new reply.

After you did choose Forward, you get redirected to your chat-list. After choosing the one where you want to forward your message you land in the chat and can write your stuff like in the reply-action and finally you have your cited block with an underlying new contextual text.

I hope my feature-request is clear and you have already something similar, please remove this one.
cheers,
bg

EDIT: Forgot something important. When you click on the cited block, your reading-position in the chat gets redirected to the original entry.. So if you have a group-chat and somebody cites you from 2 days ago, you can easily go back to the original entry by clicking on it. I think this is very important as well, because it can organize big chats quite easy. 🙂

**Comment by makingthematrix** [comment]
I think we can safely close this issue now. We implemented both "Reply" and "Share" (i.e. "forward") functionalities some time ago.
