### ISSUE TITLE
Favorite chats

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-android#722]
I didn't found another issue about it:
When selecting the chat in the chatlist please add an option to "favorite" it. With an increasing list of chats I want to access the important ones quickly, by finding them always at the same position instead of searching for them in the chat-list-history.

And I guess the feature wouldn't be a big implemention, but can improve the app-experience quite a lot (at least for people who have lots of people and thus chats).

---
And an offtopic question: do you guys(wire devs) have charts(or other visualizations) how your user-base increased over the last years? Because I think you have already quite some impressing piece of software, which I just got in touch with just a few months ago. 
And I'm really looking forward to the release of your open server! 🙂

**Comment by makingthematrix** [comment]
This feature was implemented in https://github.com/wireapp/wire-android/pull/2344
