### ISSUE TITLE
Some pictures don't load

### ISSUE THREAD

**Issue by levinus** [wireapp/wire-android#724]
Hi,
I recently recognized (more than one time) that some images that are sent over wire in a group chat just don't load on the recievers side. They just stay in the themes color not even a sign of loading is shown. Its not possible to save them via a long click (see attached image, toast translates to "File could not be saved").
All recievers in the group chat can't load the image.
In the recent case (debug log attached) 3 images were sent, the first one from person A wasn't loaded, the second one from person B was fine and the thirt, again from person A (re-try) didn't load either. Could this be somthing on the senders side?
I (one of the recievers) am on a Nexus 5X with Android 7.1, the sender is on a Sony Xperia Z1 with CyanogenMod (I have to look the version up) with GApps installed. 
I don't think that this is a duplicate of #612 or #220 because the workaround from 612 does not work (same behaviour after a complete restart of the app) and the blue loading bar doesn't show up.

[wire_debug_report.txt](https://github.com/wireapp/wire-android/files/852409/wire_debug_report.txt)
![photo_2017-03-18_13-34-00](https://cloud.githubusercontent.com/assets/12646813/24072028/99fd0936-0bdf-11e7-81fa-4b4c40559be2.jpg)

**Comment by levinus** [comment]
Issue on the sender side. Solved. If those problems persist I will open a new issue with a report from the sender side.

**Comment by KyleGospo** [comment]
How did you solve this? I am experiencing the same issue, but it's also affecting contact images and my own account image.

**Comment by levinus** [comment]
The problem was on the sender side. The senders phone was on mobile data and didn't send the pics really to the wire servers. Solved by resending in a WiFi network. I think your issue is not the same. Please look at #612 or #220 if your problem is the same as the one described there. If not, create a new issue with a log.
