### ISSUE TITLE
Encrypting local data on phones?

### ISSUE THREAD

**Issue by forteller** [wireapp/wire-android#737]
There's a great website over on https://www.securemessagingapps.com/ which compares different secure chat services. In its grid there's one thing that's left blank because they haven't found any information about it:

Does the app encrypt data on the device? (iOS and Android only)

Please provide some info on this on the website, for example on https://wire.com/en/privacy/

Thanks!

**Comment by raphaelrobert** [comment]
This is explained in the Wire Security Whitepaper in section 7.1.

**Comment by forteller** [comment]
Thanks, @raphaelrobert! Still important enough to be mentioned in a more accessible place, perhaps?

For others who might find this thread in search of this info at a later time. Here's the Whitepaper: https://wire.com/resource/Wire%20Security%20Whitepaper/download/

**Comment by raphaelrobert** [comment]
Thanks! For now the whitepapers is where explain things in more detail.

**Comment by forteller** [comment]
I sent the info over to https://www.securemessagingapps.com/ and now it's updated :)

**Comment by raphaelrobert** [comment]
Many thanks!
