### ISSUE TITLE
Import contacts from address book

### ISSUE THREAD

**Issue by forteller** [wireapp/wire-android#749]
I think it's great that Wire does not demand access to the phones address book. But I would find it very helpful if I could choose for Wire to scan my address book to other find people who use Wire and let me select who to connect with.

It should also explicitly state before I choose to do this that the content of my address book will not be saved on the Wire servers after the search is over, so that more people will feel safe enough to use this option.

**Comment by Strit** [comment]
WIre already does this on my Android phone. If you have the "Share Contacts" set to on. That option also clearly states that no info will be shared in any way.

**Comment by forteller** [comment]
Ah, yes. I didn't see that. Thanks!
