### ISSUE TITLE
Allow use of chat while been in call

### ISSUE THREAD

**Issue by avently** [wireapp/wire-android#750]
For now you can't use chat when you are talking with somebody. I think we should have a way to use the chat for all features except audio message. 
Interface needs to have a button which hides call activity and then shows the activity back when it's needed.

**Comment by theincogtion** [comment]
By the way: In Windows it is possible to chat but not in Android :(

**Comment by mandreyel** [comment]
+1

This can be rather annoying (e.g. when sharing a picture being discussed in a call) and seems like an arbitrary restriction. Is there any specific reason this feature is not implemented?

**Comment by tariq-chameleon** [comment]
Very often I find myself willing to clarify myself to the person I am in voice-chat with using a text/picture/link/video/local file but I am not being able to do that unless I go to my desktop machine and use the desktop version.

**Comment by someoneEsle** [comment]
Hey everyone! We just pushed a beta to the play store that adds this functionality. Let us know if you find any bugs!
