### ISSUE TITLE
Add to Aptoide (Android app store)

### ISSUE THREAD

**Issue by forteller** [wireapp/wire-android#752]
[Aptoide](http://www.aptoide.com/) is an app store for Android where anyone can set up their own repository and publish/update apps. Aptoide itself is open source, but it allows any type of apps.

If you don't publish Wire there yourself, someone else is sure to do it instead, and that's not very secure. An official Wire repository would be most appreciated. Thanks!

**Comment by makingthematrix** [comment]
The topic of putting Wire Android on other platforms than Google Play Store comes back every few months. We agree it would be great to do that but we don't have enough time and energy to handle this. After a lot of discussion we decided that we want to focus on Google Play Store only for near future.
