### ISSUE TITLE
Are conversations with Otto the bot private?

### ISSUE THREAD

**Issue by patrickwelker** [wireapp/wire-android#762]
I just wondered if you gather any data from Otto the Bot conversations? My better half started to send herself passwords and other personal stuff via Otto. I just wanted to confirm that this is not the best idea.

**Comment by mykola-mokhnach** [comment]
The bot immediately deletes all the received and decrypted strings on his side. It only uses them to generate reply if needed. Also we don't keep any logs or anything, which may affect your privacy in dialog with bot.

**Comment by ImAnnoying2** [comment]
Why not close this issue if the question has been answered?
