### ISSUE TITLE
Annoying behavior when sharing to wire

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#764]
Nexus 5X, Android 7+, my keyboard is Gboard

- Open gallery
- Choose an image, hit share
- Share to Wire
- Use the keyboard to type someone's name, and select them
- At this point the bottom right corner of the keyboard shows a little arrow where it usually displays the Enter button: this arrow is literally **SCREAMING** "Tap me to send", but when you click it _nothing happens_ :cry: :cry: :cry: . I think it would be immensely helpful if you could fix this tiny little bug and make the arrow actually send the message.
Thanks!

**Comment by bjoernherbig** [comment]
It is indeed screaming "Tap me to send". Screaming was quite loud, should be fixed soon ;)

**Comment by bjoernherbig** [comment]
fixed in #766
