### ISSUE TITLE
Make "Share contacts" an opt-in feature rather than opt-out

### ISSUE THREAD

**Issue by ruppalsingh** [wireapp/wire-android#779]
Wire has been making tremendous progress of late. I was hard pressed to give it another chance. I signed up via email on the website, installed the application on my phone, logged in, skipped inputting my phone number... and immediately after that, Wire proceeded to scan my phonebook and show me contacts which are already signed up on Wire without any input from me.

I had no choice to stop the process, and nor was my consent taken. A lot of privacy-minded folks would be taken aback, as was I and another friend of mine.

My suggestion is to make this
* an opt-in feature, or,
* at the very least, have a dialogue on first install asking if the user would be OK with a phonebook scan and an option to skip it -- similar to the way Wire currently asks you to optionally link your phone number or skip it.

**Comment by 2114L3** [comment]
android v6 should prompt for contacts permission as all perms are opt-in with google.

please be the champion of privacy and ask first.
_(same with debug telemetry)_

**Comment by Larx** [comment]
I also second that. I just clicked away the Android permission thing as it seemed normal to me that a communication app would like access to my contacts.

What I did not expect was that Wire would then upload my contacts without any further question. This is definitely something an app with selling point privacy should definitely not do.

**Comment by fichtennadel** [comment]
I second that, too. 

Some of us are stuck with Android 5 (like me, using a company owned mobile phone ...) and opt-in would be a real step forward for those reluctant to share their contacts or reluctant to expose their availability on Wire. Currently that's a deal breaker for me. Opt-in for address book upload would make me switch to Wire.

It would be nice to hear if this feature is on the roadmap and if yes, when we could expect it.

**Comment by someoneEsle** [comment]
Hi, sharing contacts with Wire is already opt-in by default. On Android 5 you have to accept the permission to give the app access to contacts upon installing, but that is a limitation of Android -- you have to accept all the permissions upon installing.
If you install the app on an Android 5 (which I just did on a Nexus 4), then when you go into Wire's contacts list you will get a warning message asking you whether or not you want to share your contacts with Wire. Also, at any point you can go into Settings>Options and enable/disable the sharing of contacts.
Let me know if this clarifies the issue :)

**Comment by fichtennadel** [comment]
Thanks for clarifying this, worked for me as described. 
Maybe you could state this behaviour more clearly in the docs/FAQ.

**Comment by someoneEsle** [comment]
@fichtennadel We have updated our FAQ :) https://support.wire.com/hc/en-us/articles/213572329--What-do-the-various-permissions-on-Android-do-
