### ISSUE TITLE
Active call still shown as calling

### ISSUE THREAD

**Issue by theincogtion** [wireapp/wire-android#780]
My phone partner also hand Android 6 and we had both the same behavior.
If a call comes in and I anwsered it, the call is still shown as calling and not as "active"
We could both talk but if I touched again an "answering" the connection terminates.
![screenshot_20170408-203326](https://cloud.githubusercontent.com/assets/10852327/24832407/cb62e366-1caf-11e7-8d88-1e37a2debaf1.png)

The screenshot is taken during the call.

**Comment by mykola-mokhnach** [comment]
Could you please provide more detailed steps to reproduce? As far as I can understand you are confused by the incoming call system notification, which is not replaced after the call has been accepted from the overlay - correct?

It would be also useful to know the phone model and Wire version

**Comment by theincogtion** [comment]
>  As far as I can understand you are confused by the incoming call system notification, which is not replaced after the call has been accepted from the overlay - correct?

Correct!

> `Could you please provide more detailed steps to reproduce? 
Call somebody on an Android Phone, thats pretty all.

> It would be also useful to know the phone model and Wire version
Wire from Google Play Store 2.31.324
My phone is a BQ Aquaris M5
His phone is a Motorola Moto G 2014
Both with Android 6.0.1
Motorola und BQ are both very close to stock android,

`

**Comment by makingthematrix** [comment]
The notifications were reimplemented and there were many changes to the calling functionality. I think I can close this ticket now.
