### ISSUE TITLE
See my favorited (hearted) messages in a conversation

### ISSUE THREAD

**Issue by forteller** [wireapp/wire-android#787]
The ability to heart messages seems a bit underutilized at the moment. It's nice to give a "thumbs up", but I find it very intuitive that the hearts should also function sort of like a favorite/bookmark button. A way to see just the messages that you've hearted in each separate chat/thread would IMHO be very useful and nice.

**Comment by someoneEsle** [comment]
duplicate of #634

**Comment by ImAnnoying2** [comment]
Please close this duplicate.
