### ISSUE TITLE
Add a possibility to save received images (photos) to a memory like in Signal, Telegram or other messengers

### ISSUE THREAD

**Issue by ghsrcgh** [wireapp/wire-android#794]
Please, add a possibility to save received images (photos) to a memory like in Signal, Telegram or other messengers

**Comment by mykola-mokhnach** [comment]
You can save an image by long tapping it and selecting Save. Would you like something else to be implemented?

**Comment by ghsrcgh** [comment]
I have no this option, tried a lot of times, before created ticket.
I tried to see it with all access rights (restricted) removed. Then I had enabled access to the Memory and tried again. Nothing available.

**Comment by mykola-mokhnach** [comment]
Could you please provide a screenshot of the view, where you expect to see the option?

**Comment by ghsrcgh** [comment]
I checked again and understand the issue.
1. There is no possibility to save an image, if it is opened on a full screen. You may tap so long as you want, but nothing appears. I'm awaiting a possibility to save like it made in Telegram or Signal (there is a ":" menu or Save icon). It is obviously for user and working well (understandable usecase). Anyway, I want to have a possibility to save from a full screen view.
2. If you long taping on a preview, yes, menu appears and I able to select a "Save".

**Comment by makingthematrix** [comment]
I think this was a bug that was fixed a long time ago. I will close this ticket now.
