### ISSUE TITLE
Add a possibility to configure notifications data: show message text, show author

### ISSUE THREAD

**Issue by ghsrcgh** [wireapp/wire-android#798]
Add a possibility to configure notifications data: show message text, show author, like it is made in Signal or Telegram.

Notification:
* Show message preview - on/off
* Show author name - on/off

In addition: please review to have no sensitive data sent through push-mechanisms without encryption. I hope it is send signals only, no any meta-information, etc.

**Comment by ghsrcgh** [comment]
This is really required feature, because of the privacy. Even a common messengers like Whatsapp, Viber (and of course Signal, Telegram) have these options... But Wire (secure messenger) - not.

**Comment by makingthematrix** [comment]
Notifications are now configured in Android, with notifications channels. We don't plan any more changes to this functionality.
