### ISSUE TITLE
Names switched in chat

### ISSUE THREAD

**Issue by ConorIA** [wireapp/wire-android#799]
Something very odd happened today. I was writing my wife, but for some reason all of my messages appeared on her phone as though she'd sent them and vice versa. 

Here is a shot from my phone (correct names):
![tmp_16199-point blur_apr162017_2133151072464415](https://cloud.githubusercontent.com/assets/870746/25076254/0431ae5a-22ed-11e7-8e08-824bbec37b6c.jpg)

And from hers:
![tmp_16199-point blur_apr162017_213241729972820](https://cloud.githubusercontent.com/assets/870746/25076257/095d4722-22ed-11e7-8c5e-cd92458a14c1.jpg)

Notice that the problem solved itself by the time the last meaaage was sent. Still very odd.

**Comment by mykola-mokhnach** [comment]
@ConorIA Could you please try to reproduce the described issue with debug logging enabled (like it is described in the issues reporting template) and send the collected log to our customer support?

**Comment by ConorIA** [comment]
@mykola-mokhnach, I've been using Wire for months, and that was the first time I saw this happen. I don't expect to be able to reproduce it. I'm thinking this was a once-off. It eventually corrected itself anyway. If it happens again, I'll try to get logs and will re-open this.
