### ISSUE TITLE
Unable to build on android studio 2.2 

### ISSUE THREAD

**Issue by Himanshu4003** [wireapp/wire-android#8]
I am getting new build issue for wire-android  : 

``` java
Error:Unable to find method 'org.gradle.api.tasks.scala.ScalaCompileOptions.getForce()Ljava/lang/String;'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
````

i am using android studio 2.2 Preview 1

**Comment by Himanshu4003** [comment]
Now i try with Android studio 2.0 , It give me following error 

```` Java
Error:Execution failed for task ':wire-core:prepareComKoushikduttaAsyncAndroidasync218Library'.
> Could not expand ZIP '/Users/eb/.gradle/caches/modules-2/files-2.1/com.koushikdutta.async/androidasync/2.1.8/931767d6b456957e2b0efb582515e6cf4a5c4e1a/androidasync-2.1.8.aar'.

````

**Comment by zbsz** [comment]
When you first open the project in Android Studio it asks you to upgrade android plugin.
Important: don't allow that. We use slightly customized version 1.5.0 (with Scala support).
You will also want to install Scala plugin in Android Studio to edit some classes.

**Comment by Himanshu4003** [comment]
Now it's seem to build with 1.5.0 but getting following Error : 

```` Java

advice defined in com.googlecode.mp4parser.RequiresParseDetailAspect has not been applied [Xlint:adviceDidNotMatch]
advice defined in hugo.weaving.internal.Hugo has not been applied [Xlint:adviceDidNotMatch]
Error:PowerManager.ACQUIRE_CAUSES_WAKEUP
                   ^
/Users/eb/Documents/wireApp/wire-android/app/src/main/scala/com/waz/zclient/GlobalCallingController.scala
Error:(120) value SCREEN_BRIGHT_WAKE_LOCK in object PowerManager is deprecated: see corresponding Javadoc for more information.
Error:(120) value FULL_WAKE_LOCK in object PowerManager is deprecated: see corresponding Javadoc for more information.
Error:PowerManager.ACQUIRE_CAUSES_WAKEUP
                                                          ^
  private val initialsFontColor = getResources.getColor(R.color.chathead__user_initials__font_color);
                                               ^
  private val iconOverlayColor = getResources.getColor(R.color.chathead__glyph__overlay_color)
                                              ^
  private val grayScaleColor = getContext.getResources.getColor(R.color.chathead__non_connected__color)
                                                       ^
/Users/eb/Documents/wireApp/wire-android/app/src/main/scala/com/waz/zclient/views/chathead/ChatheadView.scala
Error:(54) method getColor in class Resources is deprecated: see corresponding Javadoc for more information.
Error:(55) method getColor in class Resources is deprecated: see corresponding Javadoc for more information.
Error:(56) method getColor in class Resources is deprecated: see corresponding Javadoc for more information.
Error:(57) method getColor in class Resources is deprecated: see corresponding Javadoc for more information.
  private val overlayColor = getResources.getColor(R.color.text__secondary_light)
                                          ^
6 warnings found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

````

**Comment by zbsz** [comment]
Those are just warnings, ignore them. 
As usual with Android, we are forced to use deprecated APIs to support older Android versions. In java code those warnings can be easily suppressed with annotation. But Scala compiler doesn't have this option, it always prints warnings when deprecated methods are used in Scala code. 
We would need to completely disable deprecation warnings in Scala compiler, and we don't want to do that, as we still want to get warnings for deprecated language features.

**Comment by Himanshu4003** [comment]
Thats's fine , But now i am getting below issue : 

When i added zmessaging-android.aar in main app build.gradle it give me below Error : 

```` Java

:app:processAvsDebugResources FAILED
Error:Execution failed for task ':app:processAvsDebugResources'.
> Error: more than one library with package name 'com.waz.zms'
Information:BUILD FAILED

`````

**Comment by Himanshu4003** [comment]
i can see it's happen due to conflict of zmessaging-android-macrosupport-2.0.jar and zmessaging-android.aar , One more thing i am unable to find any gradle dependancy  that define zmessaging-android-macrosupport-2.0.jar .

**Comment by zbsz** [comment]
This error is shown because two versions of sync engine (`zmessaging`) library are included, one of them is your aar and second defined in dependencies, fetched from our bintray.
`zmessaging-android-macrosupport-2.0` normally is specified in `zmessaging-android` pom, together with two other test dependencies (`testutils` and `actors-core`), `zmessaging` also specifies couple other libraries that are pulled in as transitive dependencies, that's why we suggest to not include custom `zmessaging` aar directly, but publish it to local maven repo with `sbt publishM2`, once you  do that, you can just change `zMessaging..Version` in `build.gradle`.

If you really want to use custom aar file directly, then you will need to add several dependencies from `zmessaging` pom file into client build setup, take a look at dependencies list in pom:
https://dl.bintray.com/wire-android/releases/com/wire/zmessaging-android/75.0.277/:zmessaging-android-75.0.277.pom

`zmessaging-android-macrosupport-2.0.jar` can be compiled from sync library project using this command: `sbt macrosupport/package`

**Comment by Shubham1209mathur** [comment]
1) Manually download Gradle 3.3 binary (direct link: https://services.gradle.org/distributions/gradle-3.3-bin.zip)

2) Open your android studio root directory, and extract the zip to the gradle folder (for example in my Debian machine the full path is /opt/android-studio/gradle/gradle-3.3)

3) Open Android Studio, go to File->Settings->Build, Exectution, Deployment->Gradle and set "Gradle home" to point your new gradle-3.3 folder.

4) Sync and you are ready to go!

I hope that helps ;)
