### ISSUE TITLE
Add a possibility to delete history (chat log), but not a conversation at all

### ISSUE THREAD

**Issue by ghsrcgh** [wireapp/wire-android#800]
Add a possibility to delete history (chat log) (better - securely wipe it), but not a conversation at all, i.e. contact name does not disappear from a contact list, and when you are opening it, you just see a an empty chat, where you can start with the first message.

**Comment by mykola-mokhnach** [comment]
It actually works this way. You can still find the deleted conversation using search function and continue sending messages there
