### ISSUE TITLE
New messages: status notification canceled after reading one of them

### ISSUE THREAD

**Issue by theincogtion** [wireapp/wire-android#802]
If I get a new message in wire it is shown in the status bar on android.
This also happens if 2 or more messages are unread.
If I read one of them the notification in the statusbar about the unread messages disappears.
I often forget to read the other one because Wire does not show unread messages for me.

**Comment by makingthematrix** [comment]
Hi,
I'm going to close this issue. We had a lot of changes over time to the notifications feature. Please open a new ticket if this is still an issue.
