### ISSUE TITLE
Counter-intuitive behavior when sketching

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#816]
## The problem

- open sketch
- draw an emoji
- tap a color in the top bar, as in "now I want to draw something myself"
- attempt to draw something --> a new emoji appears instead

## Environment

* Wire version that exhibits the issue: 2.31.325
* Android OS version used to run Wire: stock 7.1.2

**Comment by red-avtovo** [comment]
Actually, color is not attached to drawing that much. You should choose a drawing tool back, before changing the color

**Comment by someoneEsle** [comment]
Right, but I think that is not what most people would expect. If I tap on a color, what I'm thinking is "I want to draw with this color". If you want the user to go back to the drawing tool in order to change the color, then the top bar with the color should not be visible when the user is using emojis (though I would argue that this is not a good solution, and I would rather have the brush tool selected automatically when I tap a color).
