### ISSUE TITLE
[Feature] Add the possibility to delete/unfriend contact(s)

### ISSUE THREAD

**Issue by vadimvera** [wireapp/wire-android#818]
It would be nice to have the option to **delete** a contact that no longer uses the application (or for some other reason). For instance, nowadays I have 4/5 people that I invited some time ago but for some reason they didn't want to keep using Wire...but still they always show up in the contact's list.

I know there is an `Archive` functionality that hides contacts (or puts them "somewhere" else), but if you know for sure that you are not going to be in communication with a particular contact, it would be nice to **delete** it.

Another scenario I can think of right now is, if you _accept_ someone by mistake and later on it turns out he/she wasn't who you think he/she should be — the `Block` option is kind of weird in that case. In the end, the "deleted" contact must have to add you again in order to communicate with.

> I know this is not "only" related with Android, but a system-wide option. I just didn't know where to put it 😄.

**Comment by forteller** [comment]
Right click in the web app or drag the name to the right in the mobile app and there's a "delete" option there. I've never used it though, so I don't know for sure what it does, but I'm guessing it does what you want it to :)

**Comment by vadimvera** [comment]
I know there is that, but what I meant was to have the ability to *unfriend (and hence delete) from my list a contact so I would need to accept a new request from he/she again in order to establish any communication(s)*.

The actual "delete" option only clears out the conversation and remove it from the "frequent" list. It's like if you have never talked to that contact so you need to start a new conversation ‒in case you want to-
 since that contact won't appear in the "frequent" list.

**Comment by forteller** [comment]
Aha, now I see. Sorry, and thanks :)

**Comment by forteller** [comment]
Why was this closed with no resolution or explanation? It's not my issue, but it seems to me like @vadimvera has a point, no?

**Comment by vadimvera** [comment]
Well, they have a problem in any case. Let's say, I delete the account and sign-up several times — always selecting the same username/handle. All my friends would have the same "me" as many times as I delete the account and I sign-up, which is what's happening right now.

You can "archive" them all but they are still there. This can make it worst, because you might want to actually delete the conversation (clearing the conversation and removing it from the "frequent" list); then all of them will be in the "archive" list...so what's the one? You can "hide away" the issue by restricting the use of usernames/handles (they can be selected once), but that would be worst, IMO.

Wire should have the option to unfriend, or at least, clean-up the non-existent user(s).
