### ISSUE TITLE
Download failed when trying to access a shared file

### ISSUE THREAD

**Issue by MrCustomizer** [wireapp/wire-android#826]
## The problem

When I try to open a shared PDF file in a group chat with the Android client, I get a "Download failed" error. Downloading the same file in the desktop (Linux) and web app works.

## Environment

* Wire version that exhibits the issue:2.31.325
* Android OS version used to run Wire: 7.1.2 and probably 4.2 (the phones of my buddy is a Fairphone, 1st generation)
* Is this a custom firmware or a stock one: 7.1.2 is Lineage OS, 4.2 is the stock ROM of the Fairphone
* Mobile phone model/manufacturer: Samsung Galaxy S4 Mini and Fairphone 1
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): WLAN

## Details

Steps to reproduce this bug: Share a PDF file in a group chat and try to open it.

Please tell me, if you need further information.

**Comment by MrCustomizer** [comment]
Addition: The third guy in our chat could download the file. I'm not able to try the download again, as it is still marked with "Download failed" and there doesn't seem to be an option to retry.

**Comment by rbu** [comment]
I can't view or download any shared files either, both in group chats and personal chats. This is on Android 7.1.1.

**Comment by makingthematrix** [comment]
This functionality was rewritten. I think I can close this issue now.
