### ISSUE TITLE
The call is still active after it is ended, when screen sharing

### ISSUE THREAD

**Issue by Asuanin** [wireapp/wire-android#828]
I tested call betwen Adroid phone and Linux desktop, when screen sharing, and after end call, it is still active on Android and buttons and return has any reaction, help only kill process

Android: dial linux user
Linux: accept call and screen sharing
Android: not rescieve any video and beep sound more 10 second
Linux: call is ended
Android: call still active, time run and buttons and return has any reaction

Phone:
Lenovo P70A
Android 4.4.4 (stock rom)
Nova Launcher
Wire 2.31.325

PC:
Ubuntu 16.04.2 LTS
kernel 4.4.0-72 x86_64
LXDE, 4 virtual desktops
Wire 2.13.2721

**Comment by mykola-mokhnach** [comment]
Please move the issue to https://github.com/wireapp/wire-desktop/issues, since it's a problem in web client, rather than Android one.
