### ISSUE TITLE
Request:  Allow sending messages during video calls

### ISSUE THREAD

**Issue by axaxs** [wireapp/wire-android#829]
When in video calls(and perhaps calls also, I haven't tested), it would be nice to be able to still send messages.  I often want to send messages or files to the person I'm speaking with, but there doesn't seem to be a way to do that.

**Comment by alaubus** [comment]
It's also not possible to send messages during calls. It would be very useful to have a button to show the text conversation while speaking.

**Comment by someoneEsle** [comment]
Hey everyone! We just pushed a beta to the play store that adds this functionality. Let us know if you find any bugs!
