### ISSUE TITLE
Dark Theme not available on Tablet

### ISSUE THREAD

**Issue by alexleonard** [wireapp/wire-android#836]
## The problem

On my Sony Z3 Phone in Options > By Popular Demand, I have an option to enable Dark Theme :+1: 

On my Sony Z3 Tablet Compact, this option is not available :(

## Environment

* Wire version that exhibits the issue: latest
* Last Wire version that did not exhibit the issue (if applicable): has been like this since I started using wire say 4 months ago
* Android OS version used to run Wire: 5.1.1
* Is this a custom firmware or a stock one: stock sony
* Mobile phone model/manufacturer: Sony Z3 Tablet Compact
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi

## Details

I can also confirm the dark theme is not available on a Samsung Galaxy Tab S2 running Android 6.0.1.

**Comment by makingthematrix** [comment]
I guess we never really came around to look at this issue. Sorry. We don't officially support tablets anymore. The additional work necessary for that is just too much for our small team...  Is the problem still happening?

**Comment by alexleonard** [comment]
Hi @makingthematrix 

I completely forgot I'd added this issue. I can't actually check it as I no longer have a tablet!
