### ISSUE TITLE
Message delivery is unreliable

### ISSUE THREAD

**Issue by rbu** [wireapp/wire-android#837]
## The problem

We have a group chat of > 2 people. Messages are not received by everyone.

## Environment

* Wire version that exhibits the issue: 2.31.325
* Android OS version used to run Wire: 7.1.1
* Is this a custom firmware or a stock one: LineageOS
* Mobile phone model/manufacturer: Google Nexus 5
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): 4g/Wifi

## Details

I have been participating in a group chat and have missed messages. Even after a restart of Wire, they have not appeared. This may have been during a network change (wifi to data). I cannot reliably reproduce the error with new messages, but the old messages reliably do not show up.

**Comment by bastoGrande** [comment]
It is almost the same for me, but I'm not using lineageos or am aware that any of my contacts is using it. 

But! Sometimes, I receive messages just when I restart wire, or I don't get notified of new messages by android. On the other hand I think I didn't missed any message completely yet.. 

OS: Android 5.1 (rooted by [default](https://code.fairphone.com/projects/fp-osos/)) 
No Google services installed... (could this be the problem?)

**Comment by dscotese** [comment]
I would like to propose that a problem such as this one MAY be solved without code changes, and if it really can be solved that way, it will be because we have more information about it.  I haven't gotten the app yet, but there may be a feature that allows you two to provide more information that comes from the app logs.

**Comment by makingthematrix** [comment]
We don't support Lineage OS and devices without Google Play Services. Sorry.
