### ISSUE TITLE
emoji appears as black box under linux

### ISSUE THREAD

**Issue by 2114L3** [wireapp/wire-android#838]
## The problem

when opening an existing conversation in wire-2.13.2741-x86_64.AppImage where the conv between to mobiles included an emoji, the said emoji sent appears in the linux chat feed as a black outlined, white filled, small rectangle

android mobiles where on latest wire update

## Image
![screenshot_2017-05-04_20-11-39](https://cloud.githubusercontent.com/assets/6963390/25699285/f1a37904-3105-11e7-8ced-63edf2658fcf.png)

this problem maybe unrelated to the android application, and specifically to the linux appimage

**Comment by 2114L3** [comment]
issue doesnt appear on the android app. 
closing and checking desktop app issues

**Comment by mykola-mokhnach** [comment]
This might be related to https://github.com/wireapp/wire-android/issues/782
Means if the particular emoji charcode is supported in the default font used in Linux then it will be visible. Otherwise not.

**Comment by 2114L3** [comment]
i've opened
https://github.com/wireapp/wire-desktop/issues/622

will test with other emojis on your note

curious if appimage is able to include fonts to resolve issues of it being absent as this appears to be a dependency for correct display.
