### ISSUE TITLE
Auto-scroll to end when accidentally activating reply box frustrating

### ISSUE THREAD

**Issue by alexleonard** [wireapp/wire-android#857]
## The problem

In big group chats it often happens that a few hundred messages will be added whilst I'm doing something else. When I want to catch up with the chat, it's very easy to accidentally tap into the reply box whilst scrolling through. Of course as soon as the reply box is accidentally activated the conversation thread automatically scrolls all the way to the end.

I understand the thinking behind this functionality (if you activate reply box, it might be useful to be seeing the most recent message to reply to), but as it can be quite easy to accidentally activate the reply box perhaps it would make more sense to have an explicit action to jump to the last message.

EG: if you activate the reply input when mid-thread a 'Jump to end' button is revealed. This button would not appear if you're already at the end of the thread.

It might also help to have a stronger visual separation of the reply area and the message thread above.

## Environment

* Wire version that exhibits the issue: 2.31.325
* Last Wire version that did not exhibit the issue (if applicable):
* Android OS version used to run Wire: 6.0.1
* Is this a custom firmware or a stock one: stock
* Mobile phone model/manufacturer: Sony Xperia Z3
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): n/a

**Comment by someoneEsle** [comment]
duplicate #507
you can add your scenario to my issue (and vote it up :smile: ) as another reason to avoid this behavior
