### ISSUE TITLE
Add TLS 1.2 support on Android 4.1+

### ISSUE THREAD

**Issue by Paviluf** [wireapp/wire-android#870]
As a follow up from https://github.com/wireapp/wire-android/issues/518 , it seem that it's totally possible to use TLS 1.2 on phone with Android 4.1+

https://github.com/square/okhttp/issues/2372#issuecomment-244807676

**Comment by darkbluelight** [comment]
Millions of users that are on Android 4.1+ are not able to use Wire at the moment cause of this design flaw ! Signal on the other side has managed to serve all those 4.1+ users with pictures...

**Comment by david-wire** [comment]
@Paviluf We have released an update, version 2.33.336. Please check if this media / image issue you mentioned in #518 is solved with that version.

**Comment by ganone** [comment]
@david-wire Negative, I have tried the latest version, still no media stuff received.

**Comment by Paviluf** [comment]
@david-wire thanks for trying to make it work ! Unfortunately, as @ganone says it still doesn't work :(

**Comment by darkbluelight** [comment]
Still negative, still no pictures, still not usable on Android 4.4.4. thanks anyway for your efforts so far.

**Comment by DrAxelbauer** [comment]
Maybe the work-around posted here #830 is helping you on Android 4.1...It is working ion my Android 4.2.2 phone! Images are loaded....give it a shot!

**Comment by Paviluf** [comment]
@david-wire any news or something to test ?

**Comment by makingthematrix** [comment]
As we don't support Android 4.x anymore, I think I can safely close this issue.
