### ISSUE TITLE
Glitch when opening timed picture

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#875]
## The problem

1. set timer to 1 day
2. send picture
3. tap on the picture you just sent
4. the "view photo" mode displays the picture you just sent for half a second, and then skips to the next picture

## Environment

* Wire version that exhibits the issue: 2.32.330
* Last Wire version that did not exhibit the issue (if applicable): it was before the new viewing mode for pictures was introduced
* Android OS version used to run Wire: stock 7.1.2
* Mobile phone model/manufacturer: Nexus 5X

**Comment by someoneEsle** [comment]
Update: this issue has only partly been solved in the most recent version.
In fact, if you do the following...

1. set timer to 1 day
2. send picture X
3. set timer to off
4. send picture Y
5. open picture Y
6. swipe back to see picture X --> picture X is not shown. Whatever picture was sent before X is shown instead.

**Comment by mykola-mokhnach** [comment]
Swipe to see the next/previous picture is disabled for timed picture previews. One can only swipe for non-timed picture previews.
