### ISSUE TITLE
Audio or video call not functionning when using a VPN

### ISSUE THREAD

**Issue by repsorp** [wireapp/wire-android#877]
## The problem

Audio or video call not functionning when using a VPN

## Environment

* Wire version: 2.32.330
* Android OS version: 7.1.2
* Mobile phone model/manufacturer: LGE bullhead | Nexus 5X | google | N2G47O
* Mobile network type: Wi-fi
* VPN: OpenVPN for Android
https://github.com/schwabe/ics-openvpn

## Details

- Trying to make an audio or video call with Wire
- Everything's looking normal on my side (ringing sound, front camera activated)
- Nothing occurs on the other side (not any incoming call signal)

## Link to Debug logs

Transmitted by e-mail to support@wire.com

**Comment by red-avtovo** [comment]
We already have a fix for that. So, no worries, just wait a little bit for the next release
