### ISSUE TITLE
SSL handshake failure on Android 7.0

### ISSUE THREAD

**Issue by romano21A** [wireapp/wire-android#878]
I can't recieve any pictures due to an SSLHandshakeException (see [debug log](https://gist.github.com/romano21A/d79a672cf42f34042f4ee6eca7e1d308)).
After searching a bit I found a few posts ([post 1](https://stackoverflow.com/questions/39133437/sslhandshakeexception-handshake-failed-on-android-n-7-0) [post 2](https://community.letsencrypt.org/t/warning-android-7-0-clients-not-browsers-can-only-use-curve-prime256v1/23212)), saying that Android 7.0 only supports one elliptic curve, which is probably the problem here.

* Wire version that exhibits the issue: 2.32.330
* Android OS version used to run Wire: 7.0
* Is this a custom firmware or a stock one: stock
* Mobile phone model/manufacturer: Lenovo Moto G4+
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): mobile networks and Wi-Fi

**Comment by red-avtovo** [comment]
Hi @romano21A. That you for your feedback!
Could you provide the Google Play Service version, please?

**Comment by romano21A** [comment]
It should be 11.0.45 (438-155874144)

**Comment by SafariLeader** [comment]
I have the same problem since upgrading to 2.32.335. I already sent a bug report to support.

    Wire version that exhibits the issue: 2.32.335
    Android OS version used to run Wire: 7.1
    Is this a custom firmware or a stock one: LineageOS    
    Mobile phone model/manufacturer: Oneplus 2
    Mobile network type (EDGE/LTE/Wi-Fi/Offline): mobile networks and Wi-Fi

**Comment by romano21A** [comment]
@SafariLeader If my theory is correct, that this is caused by the missing elliptic curve in Android 7.0, then your bug would be a different one, as this is fixed in Android 7.1 and later.
Your bug might be related to these ones though: #826 #518

**Comment by mykola-mokhnach** [comment]
@romano21A Can you please update Wire and Google Play Services to the recent available versions and verify whether the issue is fixed?

**Comment by romano21A** [comment]
Yes, the issue is fixed. Thank you!
