### ISSUE TITLE
Recorded timed video appears in Gallery

### ISSUE THREAD

**Issue by SafariLeader** [wireapp/wire-android#882]
## The problem

Wire saves videos which are recorded as "timed video" from the app itself.

## Environment

* Wire version that exhibits the issue: 2.32.330
* Android OS version used to run Wire: 7.1.2
* Is this a custom firmware or a stock one: LineageOS
* Mobile phone model/manufacturer: Oneplus Two
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/Wi-Fi

## Details

When recording timed video from the Wire app itself, the video will later appear in the gallery app in the "WIRE_MEDIA" folder. It seems as if wire saves the timed video, which should either be an option to be enabled by the user if wanted or it should be disabled completely. I can not say with certainty that this happens 100% of the time, but in my opinion this should never be the case, that wire saves something that is timed.

**Comment by red-avtovo** [comment]
Thank you for your feedback. We are looking on it

**Comment by SafariLeader** [comment]
Thank you very much. I was trying very hard to replicate this behaviour, but unfortunately I was not able to force it. For me it happened very rarely in the past and it might be hard for you guys to track this. Nevertheless, it might be something to keep an eye on. I will send a debug log once it happens again for me.

**Comment by mykola-mokhnach** [comment]
@SafariLeader Please get the recent release from Play Store. The issue should be fixed there
