### ISSUE TITLE
Video cropping/compressing in source code

### ISSUE THREAD

**Issue by nominalista** [wireapp/wire-android#885]
Because video compressing is not build in feature of Android SDK, I was wondering how it is done in Wire code, but unfortunately it is quite hard to find it. 

Where can I find parts responsible for cropping and/or compressing video before sending in conversation? Is it applicable to another application?

**Comment by Gardosen** [comment]
this question is now nearly 3 years old and was not answered in that time, neither there was another attempt to get an answer.

i close this now, as i think the question is probably redundant.

Kind regards
Marco from the Android Team
