### ISSUE TITLE
No real image fullscreen preview and zoom

### ISSUE THREAD

**Issue by fungs** [wireapp/wire-android#888]
## The problem

Images cannot be opened in a frame-less fullscreen mode (same in the browser, if fact, when clicking on the image, it becomes smaller). On Android phones, image zoom using figure gesture is not working. My contacts complain about this missing feature compared to other messengers.

## Environment

* Current version 2.32.330
* Android OS 5-7 official firmwares

**Comment by fungs** [comment]
I have to correct, sometimes the zoom works, sometimes it doesn't, sometimes, it is really slow.

**Comment by fungs** [comment]
Fullscreen would be an enhancement.
Faulty zooming I would consider a bug.

**Comment by red-avtovo** [comment]
Is zooming not working for small images only?

**Comment by fungs** [comment]
I don't see differences between image sizes. Maybe it is for high resolution images, that the zooming takes too much computation time and gets stuck? I see this on a brand new Android 7.1 device as well.

**Comment by red-avtovo** [comment]
Can you post a non-zoomable image here to test that on other builds?

**Comment by fungs** [comment]
I'll see if I can find one (not today, though). I got told by my contacts who are using wire the first time, that they cannot zoom images before I tested myself, so it must be more common. Take a couple of high-resolution images, and post them in a chat, then click to get into the image preview mode and slide left right to switch between images and try to zoom in into images from time to time.

**Comment by daebb** [comment]
For me, zooming does not work with any image I send, neither high-res-ones nor with sketches I made from scratch in Wire. This wasn’t the case before the last update(s?) as far as I remember. I’m currently on version 2.34.338 of Wire (HTC One M7, Android 5.0.2).

Here’s a ![comic](https://user-images.githubusercontent.com/5122909/26908432-f1c7f1b6-4bfa-11e7-9553-7b09fdc24864.png) I sent myself for testing that can not be zoomed, although I suppose it doesn’t really make a difference as no image can be zoomed in my case.

**Comment by mandreyel** [comment]
Can confirm, zooming doesn't work at all (for me anyway). It would be nice if this were fixed, it's an oft used feature.

**Comment by someoneEsle** [comment]
@mandreyel what phone are you using? Seems like it's affecting only some phones, because it works on many phones I tried..

**Comment by juliss95** [comment]
On my phone, zooming and rotating images has never worked and i'm already using Wire for more than a year on a daily basis. 

My phone is a Xiaomi Mi2S

**Comment by makingthematrix** [comment]
This functionality was rewritten. I used the picture provided by @daebb to confirm that zooming works. I'll close the ticket. Please reopen if anything like this happens again.

**Comment by fungs** [comment]
Great, now that you mention, zooming seems to work better now (2020) ;)
