### ISSUE TITLE
Keyboard doesn't come out when first opening a conversation after app launch

### ISSUE THREAD

**Issue by WildYorkies** [wireapp/wire-android#895]
## The problem

When first opening the app, when you click on a conversation, the keyboard does not load up. When you go back and click again, it shows up. 

## Environment

* Wire version that exhibits the issue: 2.33.335
* Last Wire version that did not exhibit the issue (if applicable): The previous version
* Android OS version used to run Wire: 6.0
* Is this a custom firmware or a stock one: stock
* Mobile phone model/manufacturer: Moto G 3rd gen
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi

## Details

* Launch app
* Click on conversation
* Notice that keyboard doesn't open, you only can see the conversation contents
* exit this view
* click on the same conversation or a different one
* Notice that the keyboard is open now

**Comment by bjoernherbig** [comment]
Thanks for reporting. Just to clarify: do you mean the entry field or the keyboard?

**Comment by WildYorkies** [comment]
@bjoernherbig It was the whole apparatus. The whole keyboard. 

This issue seems to be fixed with Wire Version 2.33.336
