### ISSUE TITLE
A problem occurred evaluating project ':app'

### ISSUE THREAD

**Issue by wilbyang** [wireapp/wire-android#9]
When I import the project from github into Android Studio (2.1.2), there is an error saying A problem occurred evaluating project ':app'.

**Comment by clm2733227** [comment]
me too.here's the code.
`    if (keepSpecsMap.remove("activity") != null) {
        println "KEEP_SPECS patched: removed 'activity' root"
    } else {
        println "Failed to patch KEEP_SPECS: no 'activity' root found"
    }`

**Comment by clm2733227** [comment]
me too.
occurred in these lines.
`    
    if (keepSpecsMap.remove("activity") != null) {
        println "KEEP_SPECS patched: removed 'activity' root"
    } else {
        println "Failed to patch KEEP_SPECS: no 'activity' root found"
    }
`

**Comment by zbsz** [comment]
Did you allow Android Studio to upgrade project to new android gradle plugin?
We use slightly customized version 1.5.0 (with Scala support). So make sure not to upgrade it.
