### ISSUE TITLE
App is too "bloated" for systems with lower specs, resulting on very poor UX for those users

### ISSUE THREAD

**Issue by notnsane** [wireapp/wire-android#90]
While the app "just works" on a modern phone with at least 1 GB RAM and 2 cores, older phones with 1 core and less RAM (512 MB) have a _very_ poor experience, and there are plenty of devices with 4.4+ systems and those hardware specs.

Overall, the whole app UI lags, the messages are shown with a 1 second lag (or more)...

Using a picture in high resolution and expanding it to the whole app background AND showing a UI with transparency on top of it would kill most phones. It's nice, but I'm sure we can use a texture and expanding it like Whatsapp or Telegram does.

I suggest either either developing a "barebones" UI or at least let us use a solid color (or no colors) for the background, and also an option to disable all animations. Anything to make the UI more responsive, currently we have to use the app "as it is" and it provides a very bad UX for that kind of hardware.

**Comment by someoneEsle** [comment]
I agree, the app looks really nice but on slower devices (i.e. like 50%) it does not perform particularly well. However I don't think that adding more options (like turning off animations and stuff like that) would result in a better UX -- too many options usually just confuse the users. I think it would be good to reduce the overall amount of animations, and maybe investigate some more efficient ways to animate stuff. Alternatively, it may be worth turning off by default some animations for devices that run older versions of android. Though as technology evolves, this problem will disappear entirely (unless Wire becomes heavier)

**Comment by bjoernherbig** [comment]
We are constantly improving memory usage and performance. A "barebone" version is currently not planned.
