### ISSUE TITLE
'Could not expand ZIP' error during build

### ISSUE THREAD

**Issue by cyb3rwr3ck** [wireapp/wire-android#904]
## The problem

I am unable to gradlew the project. 
During `./gradlew assembleProdRelease` the build fails with the following exception (jdk version afterwards): 

```
[...]

Execution failed for task ':wire-ui:compileReleaseJavaWithJavac'.
Could not expand ZIP '[snip] wire-android/wire-ui/build/intermediates/exploded-aar/com.wire/zmessaging-android/100.2.366/jars/classes.jar'.

[...]

 $ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
````

## Environment

* Latest github version
* Linux Mint 18.1

**Comment by hub-ch-NetE1** [comment]
Hello,
@cyb3rwr3ck you can try again 
Follow instruction here https://github.com/wireapp/wire-android/issues/1892 further.

**Comment by Gardosen** [comment]
as there was no response. for nearly. 1year i will close this as solved.

Kind regards
Marco from the Android Team
