### ISSUE TITLE
Tablet tries to complete call when tablet wakes up from sleep

### ISSUE THREAD

**Issue by msbentley** [wireapp/wire-android#909]
## The problem

When I call (in this case using a desktop) to a tablet which is sleeping (disconnected from wifi), Wire on the tablet tries to call me back as soon as it wakes up and connects to wifi, causing great confusion!

## Environment

* Wire version that exhibits the issue: All versions to date (current version installed)
* Last Wire version that did not exhibit the issue (if applicable): N/A (all versions)
* Android OS version used to run Wire: 4.4
* Is this a custom firmware or a stock one: stock Samsung
* Mobile phone model/manufacturer: Samsung Galaxy Pro
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): WiFi only

**Comment by mykola-mokhnach** [comment]
The problem should be fixed in the upcoming release

**Comment by makingthematrix** [comment]
I guess I can close this ticket at last :)
