### ISSUE TITLE
SMS support/fallback

### ISSUE THREAD

**Issue by michbert** [wireapp/wire-android#92]
Hi all,

I know this is very much against the 'always encrypted' concept, however in most cases people still prefer communicating unencrypted over not being able to reach someone at all. In that sense I'd say what most want is rather 'always encrypted when technically possible'.

Of course there is always the possibility to use another app as a fallback, however I see a difference between potentially the only messaging app I ever use to reach everyone and yet another (maybe even the best) closed messaging app where I can only reach a few people.

Maybe there are quite a lot of people, who don't mind installing and having to switch between a multitude of different messengers, but then these guys are not the problem to get on board. Others (like me) are not happy with that and ideally want to have just a single app for all their chats and specifically their whole chat history in just one place.

Currently I use Signal as my sole messenger, since it's the only open source IM that acts as a SMS client as well. Even though virtually no one uses Signal (and that's perhaps more than current wire users) I can still use it to reach basically everybody. And I don't have to think whether I can somehow communicate encrypted with that person before starting to write. 

The problem though is that Signal has quite some issues. No multi device support (yet), only connecting via phone number, no video, mediocre audio, etc... and that it doesn't seem like going to change much soon. Wire does much of it much better, but cannot replace Signal for me. So I was wondering what you guys generally think about supporting SMS? 

Ideally SMS support should not be just having the app on one phone sending and receiving SMS, but rather syncing received messages between your devices and allow to use one of your phones as proxy to send SMS from all your devices as well. Which would be a great premium feature, if wire should ever want make some revenue. In fact mySMS (www.mysms.com) already does this, though unfortunately not without storing all your data on their servers...

Last but not least it's not necessarily all about SMS, if we hopefully ever have some open protocol(s) being used more widely for messaging, a closed messenger that can easily integrate another protocol as a fallback, but also adds nice features on top could probably be very popular...

What are your thoughts?

**Comment by david-wire** [comment]
Hello, thanks for the very detailed feedback and the suggestion (and apologies for the delay in responding). We do get your point, however, there are no plans to add SMS support or other alternatives. 
Thank you for taking the time to send us your comments, and please feel free to contact us again if you have additional questions.
