### ISSUE TITLE
SMS_write_Permission ?!

### ISSUE THREAD

**Issue by iddno** [wireapp/wire-android#927]
I don't know where to watch for that problem, i checked the FAQ but there is the SMS WRITE PERMISSION not listed at all. So I ask here then. 

Besides the massive battery drain problem the latest version has, at least on devices without google services and using websocket etc. 

There is onething I can not understand and I wanna have an explanation for this if possible. 

Why does the android wire app need/want SMS_WRITE_PERMISSION? I don't care at the end because I block it anyways, but the important part is, sms_read permission didnt't ask for permission once, as the WRITE permission asks for it regulary for no reason at all, it just seems random too.
So that looks a little strange in my eyes. 

![sms_write_permission](https://user-images.githubusercontent.com/23586679/27039512-73d1fcc4-4f8e-11e7-9d10-d0e574b408c4.png)

**Comment by red-avtovo** [comment]
Hello @iddno! Thank you for your feedback!
You can find all permissions, that Wire requests from user at [AndroidManifest file](https://github.com/wireapp/wire-android/blob/master/app/src/main/AndroidManifest.xml)

**Comment by iddno** [comment]
Erm.. actually there is nothing to be found about SMS WRITE PERMISSION! So why is this closed so fast? Just show me that particular line which states something about SMS write permission because all I see there about SMS is this:

    <activity android:name="com.waz.zclient.SMSCodeReceiverActivity"

And the "uses-permission" part doesn't show ANYTHING about SMS at all.. so?!
