### ISSUE TITLE
Deleting image from gallery makes wire's preview go gray

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#932]
## The problem

1. open a conversation
2. send picture X
3. go to the gallery and delete picture X
4. now wire shows an empty placeholder where picture X used to be

## Environment

* Wire version that exhibits the issue: 2.35.339
* Android OS version used to run Wire: stock android 7.1.2
* Mobile phone model/manufacturer: Nexus 5X

**Comment by kmark** [comment]
I can confirm this. Galaxy S7 edge on Android 7.0. It's very annoying. I'm guessing it knows the image was sent from the same device so it tries to use the local copy. When the local copy no longer exists it should pull down the copy on the server. If I open up say the web client it'll download the images I sent from my other device just fine as it's never depending on a local file. This seems to apply at the very least to images. Not sure about other file types.

**Comment by matpk1990** [comment]
Annoying bug, please fix it.

**Comment by lucilacaranza** [comment]
Zendesk ticket #[61377](https://wearezeta.zendesk.com/agent/tickets/61377) has been linked to this issue.

**Comment by lucilacaranza** [comment]
Zendesk ticket #[59821](https://wearezeta.zendesk.com/agent/tickets/59821) has been linked to this issue.

**Comment by lucilacaranza** [comment]
Zendesk ticket #[58987](https://wearezeta.zendesk.com/agent/tickets/58987) has been linked to this issue.

**Comment by Larx** [comment]
What do those new links to Zendesk mean? Is this annoying problem being worked on?

**Comment by makingthematrix** [comment]
This functionality was rewritten. I can't reproduce the bug anymore. I'll close the ticket - please reopen if anything liek this happens again.
