### ISSUE TITLE
Images are being forwarded as files

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#933]
## The problem

1. open a conversation
2. take a picture
3. send it
4. forward it to someone else
5. the image is forwarded as a file, and it is not displayed as pictures usually are

## Environment

* Wire version that exhibits the issue: 2.35.339
* Android OS version used to run Wire: stock android 7.1.2
* Mobile phone model/manufacturer: nexus 5X

**Comment by makingthematrix** [comment]
I guess this was fixed with the new assets functionality.
