### ISSUE TITLE
Incorrect behavior brings user back to unarchived conversations

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#934]
## The problem

1. open archive
2. open a conversation
3. swipe back to go to the conversations list
4. wire takes you back to the list of unarchived conversations, instead of bringing you back to the archived ones

similar bug
1. open archive
2. swipe a conversation to open the "quick menu"
3. don't tap any icon, just tap somewhere on the screen
4. wire takes you back to the list of unarchived conversations, instead of bringing you back to the archived ones

## Environment

* Wire version that exhibits the issue: 2.35.339
* Android OS version used to run Wire: stock android 7.1.2
* Mobile phone model/manufacturer: Nexus 5X

**Comment by mykola-mokhnach** [comment]
It's by design, since selecting a conversation from the list of archived conversations automatically unarchives it

**Comment by someoneEsle** [comment]
Ohhhh I see. Then only the second bug should be considered a real bug. (by the way, I'm not sure most people want their conversations unarchived just because they have opened them)
