### ISSUE TITLE
Enhancement proposal: third state "indirectly verified", besides "verified" and "not verified"

### ISSUE THREAD

**Issue by pi-xel** [wireapp/wire-android#937]
Hello,

As the title says, I would like to propose a third state of verification, besides "verified" and "not verified" that is somewhere in between regarding security.

Use cases:

1. Alice, Bob and Carlos start a group conversation. Alice has exchanged fingerprints with Bob and Bob with Carlos, but Alice not with Carlos. Right now, Alice sees Carlos as "not verified" and also Carlos sees Alice as "not verified". With the third state, Alice would see Carlos as "indirectly verified via Bob" and Carlos would see Alice as "indirectly verified via Bob", which would indicate a higher level of security compared to "not verified" and would remove the requirement that everyone compares fingerprints with everyone else in a group.

2. Alice and Bob have exchanged fingerprints and are thus mutually "verified". Then Bob starts using a new device, such that he becomes "not verified" for Alice and sees Alice as "not verified" from the new device. Then Bob compares fingerprints between the new and old device, such that new and old device are both "verified". Thereafter, Alice sees Bob and his new device as "indirectly verified via Bob (old device)" and Bob sees Alice on the new device as "indirectly verified via Bob (old device)".

Please give me your thoughts on this idea.

Best regards,
pi-xel

**Comment by Gardosen** [comment]
there is a similiar proposal which i have forwarded to the discussion board of the developers. there for i close this one here now.

Kind regards
Marco from the Android Team
