### ISSUE TITLE
No "received" status for messages in new groups

### ISSUE THREAD

**Issue by Awerick** [wireapp/wire-android#943]
## Problem/How to reproduce it
 *  Create a _new_ group with the Android App (_edit:_ or with the Linux Desktop App).
 *  Send a message (and verify that it was received by the other participant(s)).
 *  **Actual behavior:** Message still only shows "Send" status.
 *  **Expected behavior:** Status should change to "Received".

(Strange: For some of the new groups the Desktop (Linux) App shows a "Received" status – but only for the _first message_, not for any subsequent messages.)

(I could only reproduce this issue for a new _group_, not for a _one-to-one conversation_ with a new contact.)

## Environment
* Wire 2.35.339
* Android 6.0.1, Custom ROM
* Wifi as well as Mobile Internet

**Comment by Awerick** [comment]
Now the problem also occurs in _old_ groups – no "received" status is shown despite the message sent and received.

**Comment by pia-wire** [comment]
This is intended behaviour. We don't show the "delivered" status in groups because we can't show who received the message. Group messages are always on "sent" only.

**Comment by makingthematrix** [comment]
"Sent" and "Delivered" should work correctly now, and read receipts are available since https://github.com/wireapp/wire-android/pull/1894.
Please reopen if the problem occurs again.
