### ISSUE TITLE
Unread message after sending video

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#965]
## The problem

1. open conversation with A
2. send video
3. go back to conversations list
4. conv. A has one unread message (which is not true)

## Environment

* Wire version that exhibits the issue: 2.36.342
* Android OS version used to run Wire: stock android 7.1.2
* Mobile phone model/manufacturer: Nexus 5X

**Comment by red-avtovo** [comment]
Hi @someoneEsle. Thank you very much for your report!

**Comment by red-avtovo** [comment]
Hey @someoneEsle. Is this issue still reproducible for you? I can't reproduce it on latest ```2.37.349``` client

**Comment by someoneEsle** [comment]
Looks fixed. However I do still have some other issues related to the unread count, but I'll close this one

**Comment by someoneEsle** [comment]
I just had this issue again.
