### ISSUE TITLE
vibration recorded at start of audio messages

### ISSUE THREAD

**Issue by davidak** [wireapp/wire-android#970]
## The problem

When i hold the record button to record an audio message, the phone vibrates once. This vibration is recorded on the start of every message.

[recording.m4a.zip](https://github.com/wireapp/wire-android/files/1113527/recording.m4a.zip)

## Environment

* Wire version that exhibits the issue: 2.36.343
* Last Wire version that did not exhibit the issue (if applicable): -
* Android OS version used to run Wire: Fairphone Open OS 17.04 (based on Android 5.1, without Google Play Serrvices)
* Is this a custom firmware or a stock one: alternative OS from manufacturer
* Mobile phone model/manufacturer: Fairphone 2
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/Wifi

## Details

I have this issue with my Fairphone, but my friend with a Samsung Galaxy Note 4 don't has it. His don't vibrate at all when recording audio messages.

## Link to Debug logs

https://gist.github.com/davidak/eb86c0075ce720272bd345fa4a7d3b1a

**Comment by jspittka** [comment]
Thanks for reporting this problem. We tried to make sure that we avoid recording the notifications but Android hardware differs quite a bit. It is possible that we missed this specific scenario.

**Comment by davidak** [comment]
It don't vibrate in the latest version. That solves this problem.
