### ISSUE TITLE
[Enhancement] Audio-messages bigger than 25Mb are lost

### ISSUE THREAD

**Issue by ronidee** [wireapp/wire-android#972]
After recording a 25mb+ audio-message, the message is lost. 
Then the user has to repeat everything he just said in two separated messages.

### Please implement one of these functionalities: 

a) automatically stop the recording/notify the user
b) split the recording into several files and send them
c) increase the maximum size
d) add an option to increase compression/decrease quality.

Thank you very much

**Comment by someoneEsle** [comment]
duplicate of #508, please upvote that ticket and comment there if needed :)

**Comment by ronidee** [comment]
Ah, I'm sorry. I searched for this issue but didn't find it, that's.
