### ISSUE TITLE
Nothing happens when sending video recorded from within Wire

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#973]
## The problem
I can reproduce this bug consistently, but it may depend on my phone model.

1. open a conversation
2. tap button to record video
3. record something
4. send
5. nothing happens, the video was not sent, the app doesn't crash, no placeholder, nothing.

## Environment

* Wire version that exhibits the issue: 2.36.343
* Android OS version used to run Wire: stock android 7.1.2
* Mobile phone model/manufacturer: Nexus 5X

**Comment by someoneEsle** [comment]
While fixing this, maybe keep an eye on #430, might be related

**Comment by davidak** [comment]
I have the same issue, also with photos.

## Environment

* Wire version that exhibits the issue: 2.36.343
* Last Wire version that did not exhibit the issue (if applicable): -
* Android OS version used to run Wire: Fairphone Open OS 17.04 (based on Android 5.1, without Google Play Serrvices)
* Is this a custom firmware or a stock one: alternative OS from manufacturer
* Mobile phone model/manufacturer: Fairphone 2
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/Wifi

**Comment by ronidee** [comment]
This _could_ also be related to issue #950 (Audio and textmessages are not being sent/just disappear).

**Comment by orangesunny** [comment]
I am unable to send the video too, doesn’t matter if recorded in Wire or another app, Wi-Fi or mobile network. No error message, nothing.

Samsung Galaxy S9+, Android 8 and 9, all versions of Wire through the last year.

**Comment by makingthematrix** [comment]
This whole functionality of handling assets (photos, videos, audio recordings...) was rewritten. We also improved the reliability of sending data. @orangesunny, can you say if this is still happening to you?
