### ISSUE TITLE
Audio recording over 25 MB lost forever

### ISSUE THREAD

**Issue by davidak** [wireapp/wire-android#974]
## The problem

![25mb](https://user-images.githubusercontent.com/91113/27764357-c59ade78-5e97-11e7-981d-ff31a2ce16e6.jpg)

## Environment

* Wire version that exhibits the issue: 2.36.343
* Last Wire version that did not exhibit the issue (if applicable): -
* Android OS version used to run Wire: Fairphone Open OS 17.04 (based on Android 5.1, without Google Play Serrvices)
* Is this a custom firmware or a stock one: alternative OS from manufacturer
* Mobile phone model/manufacturer: Fairphone 2
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/Wifi

## Details

1. explain an alternative to the current corrupted system (~8m audio recording)
2. try to send it
3. get error message
4. recording lost forever

**Comment by someoneEsle** [comment]
duplicate of # #508. Please go to #508 and upvote it, so that the developers will give it higher priority! :)

**Comment by davidak** [comment]
@someoneEsle Thanks.
