### ISSUE TITLE
Sound very low when video calling

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#975]
Caller (my phone): Nexus 5X, Android 7.1.2, Wire 2.36.343. On very good WiFi
phone being called: Samsung S7, Android 6.something, not sure about their Wire version I think it is either 2.36.343 or a slightly earlier version. On average 4G.

1. My phone video called the other device
2. For the first 10 seconds or so, the audio is fine on my end
3. After a little while, the audio becomes really low and barely audible (even if I turn up the volume of my phone, it is very hard to hear). The audio stays super low for the rest of the call. I'm not sure whether the problem is with my phone or my friend's phone, but I've tried calling them several times and this is a consistent behavior.

**Comment by makingthematrix** [comment]
There were a lot of changes and as far as I know there are currently no issues with loudness during video calls. I'll close this ticket. Please reopen if the problem appears again.
