### ISSUE TITLE
How do I build Client android app

### ISSUE THREAD

**Issue by Tyriod** [wireapp/wire-android#985]
## The problem

I tried building a client app but the gradle says the Ant based compiler for scala is deprecated. The app actually builds but it affects the function of the app. How do I rectify this issue please.

**Comment by Tyriod** [comment]
Can someone reply me please?

**Comment by ronidee** [comment]
The more details you provide how to reproduce the error, the easier it is to help you.
However, I had the same issue and found a solution by searching for the error-message.
Check out the issue I opened: #942

**Comment by ArchiveBase** [comment]
duplicate of https://github.com/wireapp/wire-android/issues/583

**Comment by marcoconti83** [comment]
Thanks to @ArchiveBase for linking the duplicate issue. @Tyriod is this still a problem?

**Comment by NetE1** [comment]
AVS issue also solved https://github.com/wireapp/wire-android/issues/1892 @Tyriod if you intend to build.

**Comment by marcoconti83** [comment]
Hi @Tyriod ,
The app will build, regardless of that "gradle says the Ant based compiler for scala is deprecated". Ignore that error and try to build again now, it should work.

Thanks @NetE1 for bumping this ticket.
