### ISSUE TITLE
Deleted conversations are being archived not deleted

### ISSUE THREAD

**Issue by revpp** [wireapp/wire-android#997]
It's impossible to delete conversions because they are being automatically archived not deleted. When attempting deletion from archived section, nothing happens it stays there (sometimes content of conversations is emptied but more often stays intact in archived messages).

**Comment by bfqrst** [comment]
Thanks for opening @revpp ! I can confirm this behavior on a Nexus 6P, Android 7.1.2, Patch Level July 5th. Wire version being 2.36.343 but it did occur in previous versions as well.

Thanks for having a look
Cheers
Ralph

**Comment by vadimvera** [comment]
And the same applies for groups. If you create (or get invited to) one, by the time you want to "get out" you can't simply do that.

The conversation is removed and "archived"; then you navigate to the "archive" list, tap in the group again...and you are in!

**Comment by tokariu** [comment]
This Bug is driving me nuts since the beginning of Wire. In my general understanding "delete" should completely delete a conversation and not archive it at all. It's 2017 and there is still no bulletproof way to get rid of obsolete conversations.

**Comment by t-aus-m** [comment]
10 months in and the issue still persists. Any news from the developer side of things?

**Comment by reno-a** [comment]
For us too, group appear in archive, but we can not delete it.

[Wire version 3.10.442 / LineageOS 14.1]

**Comment by lucilacaranza** [comment]
Zendesk ticket #[62111](https://wearezeta.zendesk.com/agent/tickets/62111) has been linked to this issue.

**Comment by reno-a** [comment]
Hello @lucilacaranza, 
Can't connect

**Comment by lucilacaranza** [comment]
*Comment made from Zendesk by Lucila Caranza on 2018-07-02 at 12:01:*

<blockquote><div class="zd-comment">Hey there,<br><br>Good news, this bug has been fixed on version 6.12 :)<br><br>Please update and let us know if you have any issues.<br><br>Thanks,<br>

<span class="collapse-signature"></span><div class="signature"><p dir="auto">Lucy Portman<br>
Wire Support</p></div>
</div></blockquote>
